---
title:                                  MsDropdown
title_extention:                        Integrated Dropdown Generator Module for J1 Template
tagline:                                User Guide for J1 Template

date:                                   2022-08-14
#last_modified:                         2023-01-01

description: >
                                        MsDropdown is a lightweight jQuery library for Template
                                        to enable the use of images (or icons) for HTML select
                                        based dropdown menus for J1 Theme. MsDropdown helps to make
                                        menu entries better understandable, and eye-minded.
                                        Additional menu icons can support a lot understanding
                                        what is behind.
keywords: >
                                        Jekyll, JekyllOne, Theme, User Guide, Module, HTML, Dropdown,
                                        MsDropdown, Manual

categories:                             [ Manual, Module ]
tags:                                   [ Dropdown, MsDropdown ]

image:
  path:                                 /assets/image/module/attic/menu-1280x1000.jpg
  width:                                1920
  height:                               1280

tts:                                    true
comments:                               false
exclude_from_search:                    false
regenerate:                             false
permalink:                              /pages/public/manuals/modules/msdropdown/

resources:                              []
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/module/attic/menu-1280x1000.jpg
          alt:                          menu-1280x1000.jpg
          title:                        Manuals
          tagline:                      MsDropdown
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CAUTION: This page is under construction. An updated version will be
available soon.

MsDropdown is a lightweight jQuery library to enable the use of images (or
icons) for HTML `<select>` based dropdown menus. The HTML standard does *not*
support the use of images or icons in menu/dropdown lists. MsDropdown helps
to make menu entries better understandable, and eye-minded. Additional menu
icons can support understanding what is behind a lot.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== MsDropdown API

lorem:sentences[5]

include::{documentdir}/msdropdown_properties.asciidoc[]

include::{documentdir}/msdropdown_api.asciidoc[]
