---
title:                                  Manual
tagline:                                range slider
date:                                   2022-02-20 00:00:00
description: >
                                        Welcome to the preview page focussing on the Range Slider
                                        module.
keywords: >
                                        previewer, tool, preview, overview, images, jquery, plugin,
                                        Slider, RangeSlider, noUiSlider,
                                        opensource, free, load, download, start, starter, example,
                                        high, easy, use, secure, encrypt, standard, popular,
                                        generate, develop, create, learn, distribute, publish, deploy,
                                        beginner, advanced, expert, student, learner, writer, reader, visitor
                                        framework, toolkit, integration, extension, module, api,
                                        dynamic, static, generator, client, server, internet, local, localhost
                                        page, web, website, webdesign, material, design, responsive,
                                        javascript, nodejs, ruby, windows, linux, osx, mac, os,
                                        http, https, html, html5, css, scss, style,
                                        browser, firefox, chrome, edge, opera, safari,
                                        configuration, generator, navigation, menu, dropdown, fab, action, button
                                        application, interface, provider, api, repository,
                                        cookie, language, translation, gdpr, dsgvo, privacy,
                                        asciidoc, aciidoctor, bootstrap, jekyll, liquid,
                                        hyvor, disqus, git, github, netlify, heroku, apple, microsoft,
                                        provider, service, internet, support,
                                        google, analytics, advertising, search, console, silverlight, score,
                                        j1, template, jekyllone, comment

categories:                             [ Previewer ]
tags:                                   [ Modules, Slider, RangeSlider ]

comments:                               false
fab_menu_id:                            page_ctrl

permalink:                              /pages/public/previewer/range-slider/
regenerate:                             false
compress:                               false

resources:                              [ clipboard, rangeslider, rouge ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       https://unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:noui-slider--documentation:            https://refreshless.com/nouislider/


//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// See: https://materializecss.com/range.html
// See: https://refreshless.com/nouislider/

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

The Javascript tool _nouiSlider_ is a 3rd party plugin fully integrated into
the J1 Template by the module `rangeslider`. Read the following sections on
using the module for your web pages.

TIP: For all possible slider configurations, see __noUiSlider__'s official
link:{noui-slider--documentation}[documentation, {browser-window--new}]
to see a variety of more slider options available.

== Asciidoc Markup

J1 Template provides an Asciidoc Extension `range_slider::` to integrate
configured range sliders by Asciidoc Markup into your web pages. The
extension is easy to use as only two parameters are required:

* slider `ID`
* additional `CSS classes` (if required)

[source, no_template, role="noclip"]
----
range_slider::slider_id[]
range_slider::slider_id[role="additional CSS classes"]
----

== HTML Markup

Alternatively, a range slider can also be noted using HTML markups. Even
in the case of notation via HTML, all configured parameters are applied
when the module is initialized.

NOTE: Remember that for HTML code placed in an (Asciidoc) page, the code
has to be enclosed in a *pass-through* block, delimited by four plus
signs (++++).

[source, no_template, role="noclip"]
----
<div id="slider" class="range-slider"></div>
----

== Page configuration

The module `rangeslider` is resource record of type *ondemand* and only
available with a page if the module is explicitly requested.

.J1 Page Configuration (Frontmatter)
[source, no_template, role="noclip"]
----
---
title:                                  <your title>
tagline:                                <your tagline>
...
resources:                              [ rangeslider ] <1>
resource_options:
  <your options>
---
----
<1> The module `rangeslider` needs to be given with the record *resources*
as the resource in only available on demand.

== Resource configuration

.Resource record for the module rangeSlider (`resources.yml`)
[source, no_template, role="noclip"]
----
# ----------------------------------------------------------------------------
# Range Slider, based on the JS implementation of the noUiSlider API
# See: https://github.com/leongersen/noUiSlider
#
- name:                               rangeSlider
  resource:
    enabled:                          true

    id:                               rangeslider
    comment:                          module rangeSlider
    region:                           head
    layout:                           [ page, post, collection, raw ]
    required:                         ondemand
    preload:                          false
    script_load:                      defer
    dependencies:                     false
    pass_init_data:                   false
    data:
      css:                            [ modules/rangeSlider/css/theme/uno/nouislider ]
      files:                          [ adapter/js/rangeSlider.js ]
      js:                             [ modules/rangeSlider/js/nouislider ]
      init_function:                  [ j1.adapter.rangeSlider.init ]
----

== Module configuration

Before range sliders are used with your websites, all sliders must be set up
via the module's user configuration. The range sliders used can be configured
below the `sliders` key in the `rangeSlider.yml` configuration file located
in the folder `~/_data/modules`.

.J1 Module Configuration (`rangeSlider.yml`, excerpt)
[source, no_template, role="noclip"]
----
# ------------------------------------------------------------------------------
# ~/_data/modules/rangeSlider.yml
# User Configuration of the Range Slider Module
#
# Product/Info:
# https://jekyll.one
#
# Copyright (C) 2022 Juergen Adams
#
# J1 Template is licensed under the MIT License.
# See: https://github.com/jekyll-one-org/J1 Template/blob/master/LICENSE
#
# ------------------------------------------------------------------------------

...

  sliders:

    # --------------------------------------------------------------------------
    # example slider
    #
    - slider:
        enabled:                        true
        id:                             example_slider_asciidoc

        options:
          title:                        "Title of the Example Slider"
          label:                        "Example Slider, range: [5,50], start at: 25, step: 5"
          start:                        25
          step:                         5
          range:
            min:                        5
            max:                        50

    # --------------------------------------------------------------------------
    # example slider (controled)
    #
    - slider:
        enabled:                        true
        id:                             example_slider_html

        options:
          title:                        "Title of the Example Slider (controlled)"
          label:                        "Example Slider, range: [5,50], start at: 25, step: 5"
          start:                        25
          step:                         5
          range:
            min:                        5
            max:                        50

----

== Examples

The following examples show identical sliders but in *different* configurations.
Once noted using the built-in Asciidoc extension, the other uses native HTML
markup. The example using <<HTML Markup>> is a bit more complex as Javascript
is used to control the slider (reset button).

WARNING: Do not use the *identical* slider *ids* on the same page. Duplicate
ids on the same page will cause the module initialization to fail and result
in *no* sliders being usable.

=== Asciidoc Markup

The slider's notation using Asciidoc may be completely sufficient for
simple user interfaces. Remember that evaluating the slider's values requires
always a *Javascript* interface to react to the values changed by the slider.

[[module-configuration-asciidoc]]
==== Module configuration

[source, no_template]
----
# ------------------------------------------------------------------------------
# Example Slider
#
- slider:
    enabled:                        true
    id:                             example_slider_asciidoc

    options:
      title:                        "Title of the Example Slider"
      label:                        "Example Slider, range: [5,50], start at: 25, step: 5"
      start:                        25
      step:                         5
      range:
        min:                        5
        max:                        50
----

[[markup-asciidoc]]
==== Markup

[source, no_template]
----
range_slider::example_slider_asciidoc[role="mt-5 mb-5"]
----

[[rendered-slider-asiidoc]]
==== Rendered Slider

See the rendered slider below (ID: `example_slider_asciidoc`) based on the
Asciidoc Markup using the extension `range_slider::`:

range_slider::example_slider_asciidoc[role="mt-5 mb-6"]

=== HTML Markup

The slider's notation using Asciidoc is sufficient for simple user interfaces.
For more complex user interfaces it is recommended to use HTML markups. The
following example implements a slider and a control button to reset the
slider to the *defaults* value.

[[module-configuration-html]]
==== Module configuration

[source, no_template]
----
# --------------------------------------------------------------------------
# example slider (controlled)
#
- slider:
    enabled:                        true
    id:                             example_slider_html

    options:
      title:                        "Title of the Example Slider (controlled)"
      label:                        "Example Slider, range: [5,50], start at: 25, step: 5"
      start:                        25
      step:                         5
      range:
        min:                        5
        max:                        50
        max:                        50
----

[[markup-html]]
==== Markup

[source, html]
----
<div id="example_slider_html" class="range-slider mt-5 mb-5"></div>

<button type="button" name="reset-example-defaults"
  class="btn btn-flex btn-primary mt-3"
  aria-label="Reset Button"
  style="min-width: 12rem">
  <i class="mdi mdi-close mdi-24px mr-1"></i>
  Reset Slider
</button>
----

[source, js]
----
<script>
  $(function() {
    var dependencies_met_controlled_slider_finished = setInterval(function() {
      if (j1.adapter.rangeSlider.getState() == 'finished') {
        var controlledSlider = document.getElementById('example_slider_control');
        clearInterval(dependencies_met_controlled_slider_finished);
        controlledSlider.noUiSlider.on('update', function (values, handle) {
          console.log('Current value of the example slider: ' + values[handle]);
        });
        $('button[name="reset-example-defaults"]').on('click', function (e) {
          var default_value = 25;
          console.log('Reset the example slider value to: ' + default_value);
          controlledSlider.noUiSlider.set(default_value);
        });
      } // END if rangeSlider.getState()
    }, 25); // End interval dependencies_met_controlled_slider_finished
  }); // END document ready
</script>
----

[[rendered-slider-html]]
==== Rendered Slider

Find  the rendered slider below (ID: `example_slider_html`) based on the
HTML Markups from above. Additional, a Javascript is used to control (reset)
the slider. Click the button *RESET SLIDER* to reset the slider to the default
value.

TIP: You can monitor the changes on the slider using the *development* console
of your browser.

++++
<div id="example_slider_html" class="range-slider mt-5 mb-5"></div>

<button type="button" name="reset-example-defaults"
  class="btn btn-flex btn-primary mt-3"
  aria-label="Reset Button"
  style="min-width: 12rem">
  <i class="mdi mdi-close mdi-24px mr-1"></i>
  Reset Slider
</button>
++++

++++
<script>
  $(function() {
    var dependencies_met_controlled_slider_finished = setInterval(function() {
      if (j1.adapter.rangeSlider.getState() == 'finished') {
        var controlledSlider = document.getElementById('example_slider_html');
        clearInterval(dependencies_met_controlled_slider_finished);
        controlledSlider.noUiSlider.on('update', function (values, handle) {
          console.log('Current value of the example slider: ' + values[handle]);
        });
        $('button[name="reset-example-defaults"]').on('click', function (e) {
          var default_value = 25;
          console.log('Reset the example slider value to: ' + default_value);
          controlledSlider.noUiSlider.set(default_value);
        });
      } // END if rangeSlider.getState()
    }, 25); // End interval dependencies_met_controlled_slider_finished
  }); // END document ready
</script>
++++


/////
== noUiSlider API

=== Getting slider values

noUiSlider has an API with two simple methods: .get() and .set(). To get
the current slider value:

.Example
[source, js, role="noclip"]
----
  var slider    = document.getElementById('slider');
  var sliderVal = slider.noUiSlider.get();
----

For one-handle sliders, calling `.get()` will return the value as a `string`.
For multi-handle sliders, an `array['string', 'string', ...]` will be returned.
Use .`get(true)` to get the slider values without formatting applied (as a
number or array[number, number, ...]).

=== Setting slider values

If a slider is configured to use one handle, its current value can be changed
using the `.set()` method. For sliders with multiple handles, pass an array.

One-handled sliders will also accept arrays. Within an array, any position
can be set to null to leave a handle unchanged.

noUiSlider will always limit values to the slider range. To set a single slider
handle, the `setHandle` method can be used. This method accepts a zero-indexed
handle number, a value and optionally a 'fire set event' boolean. Passing
`null` as the value to setHandle will leave the handle unchanged.

Both the set and setHandle methods have an exactInput argument, which can
be used to ignore the stepping configured for the slider.
To return to the initial slider values, the `.reset()` method can be used.
This will only reset the slider values.

.Examples
[source, js, role="noclip"]
----
var slider = document.getElementById('slider');

noUiSlider.create(slider, /* { options } */);

// Set one handled slider
slider.noUiSlider.set(10);
slider.noUiSlider.set([150]);

// Set the upper handle on a slider with two handles,
// don't change the lower one
slider.noUiSlider.set([null, 14]);

// On a slider with three handles,
// set the third to 12 (the handleNumber is 0-indexed),
// fire the set event (default true),
// Don't ignore stepping on the slider (default false)
slider.noUiSlider.setHandle(2, 12, true, true);

// Set both slider handles on a slider with two handles
slider.noUiSlider.set([13.2, 15.7]);

// Set both slider handles on a slider with two handles,
// fire the set event (default true)
// Ignore stepping on the slider (default false)
slider.noUiSlider.set([13.2, 15.7], true, true);

// Return to the 'start' values
// Does NOT reset any other slider properties
slider.noUiSlider.reset();
----

=== Events

noUiSlider offers several ways to listen to interaction: `update`, `change`,
`set`, `slide` and `drag`. These events can all be used at the same time.
There are also the `start` and `end` events, that fire when a drag is
started or ended.

Events always fire in the following order:

`start` > `slide` > `drag` > `update` > `change` > `set` > `end`

noUiSlider uses a custom binding model with support for namespaces. There are
two methods, `.on(eventName, callback)` and `.off(eventName)`. Events can be
namespaced by appending a period ('.') and an identifier to the event name.

Nested namespaces ('slide.something.else') are not supported, and are threated
as a single namespace (so '.a.b' isn't related to '.a').

Values is an array containing the current slider values, with formatting
applied. handle is the index of the handle that caused the event, starting
at zero. `values[handle]` gives the value for the handle that triggered the
event.

// unencoded contains the slider values without any formatting.

For all events, this is set to the current slider's API, containing (among
others) the `.get()` and `.set()` methods. The Slider API is also available
as the sixth argument to all events.

.Examples
[source, js, role="noclip"]
----
function doSomething(values, handle, unencoded, tap, positions, noUiSlider) {
  // values: Current slider values (array);
  // handle: Handle that caused the event (number);
  // unencoded: Slider values without formatting (array);
  // tap: Event was caused by the user tapping the slider (boolean);
  // positions: Left offset of the handles (array);
  // noUiSlider: slider public Api (noUiSlider);
}

// Binding signature
slider.noUiSlider.on(eventName, doSomething);

// Binding namespaced events
slider.noUiSlider.on('set.one', function () { });
slider.noUiSlider.on('change.one', function () { });

// Remove all events in the 'one' namespace.
slider.noUiSlider.off('.one');

// Remove all events
slider.noUiSlider.off();

// Remove all 'change' events in any namespace.
slider.noUiSlider.off('change');
----
/////

/////
=== HTML5 Range Input

// See: https://www.w3schools.com/tags/att_input_type_range.asp

The `<input type="range">` defines a control for entering a number whose exact
value is not important (like a slider control).

Default range is 0 to 100. However, you can set restrictions on what numbers
are accepted with the attributes below.

* max - specifies the maximum value allowed
* min - specifies the minimum value allowed
* step - specifies the legal number intervals
* value - Specifies the default value

TIP: Always add the <label> tag for best accessibility practices!

.HTML Markup
[source, html, role="noclip"]
----
  <form action="#">
      <input type="range" id="input-slider" min="0" max="100" />
  </form>
----

++++
<div class="row mt-5 mb-5">

  <div class="col-md-6 ml-1">
    <form action="#">
      <input type="range" id="input-slider" min="0" max="100" />
    </form>
  </div>

</div>
++++
/////
