---
title:                                  J1 Masonry
tagline:                                Preview
date:                                   2020-11-03 00:00:00
description: >
                                        J1 Template implements the Masonry module based on the Javascript
                                        library Masonry, a popular grid layout library by David DeSandro.
                                        The masonry or the Pinterest-style layout is a popular choice for
                                        aesthetically pleasing images of varying sizes.

categories:                             [ Previewer ]
tags:                                   [ Masonry, Example ]

comments:                               false
fab_menu_id:                            open_toc
scrollbar:                              false
regenerate:                             false
permalink:                              /pages/public/previewer/masonry/

resources:                              [
                                          animate, clipboard, justifiedGallery,
                                          lightbox, lightGallery, masonry,
                                          rouge, slick
                                        ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/hayden-mills-2.jpg
          alt:                          Photo by Hayden Mills on Unsplash
          badge:
            type:                       unsplash
            author:                     Hayden Mills
            href:                       https://unsplash.com/@haydmills
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The tecnical term *Masonry* is used in web development to refer to a *grid*
layout system for arranging elements on a webpage. The masonry layout, also
known as the **Pinterest**-style layout, is a popular choice for displaying
images of varying sizes aesthetically pleasingly.

[role="mb-4"]
J1 Masonry is based on the popular JavaScript library _Masonry_, which enables
the creation of responsive, dynamic grid layouts of *large* groups of content.
It uses a unique algorithm to arrange elements vertically, then horizontally
in the grid. The result is a visually appealing layout that works well with
images and other content of varying sizes. The Masonry module  is easy to use
and can be added to a webpage with just a few lines. The module provides a
flexible configuration that allows developers to customize the layout, adjust
the column width and gutter size, and add animations and other effects.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
== Responsive Carousel

A carousel may be an alternative for a masonry-styled grid to display groups
of posts, articles, or images in quite a compact way. The negative aspect of
using sliders on larger groups of elements is the limited number of elements
displayed on a slideshow. Sliders are typically used for so-called featured
content to show *specific* elements the website visitors should find on a
most top position of your homepage as an eye-catcher.

.Collection carousel (Biography)
slick::collection_carousel_biography[role="mb-4"]


== Grid on Collections

The J1 Masonry `collections grid` pulls content from a specific collection.
All grids for collections display the *articles* a collection contains.
Additionally, the article title and the (first) tag of an article are shown.
All Masonry grids for the J1 Theme can be easily customized in various ways,
such as changing the number of posts displayed, the masonry speed, and other
options.

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::collection_biography[]
----

.Collection Grid + No Preview + No Gutters (Biography)
masonry::collection_biography[role="mb-3"]

.Configuration settings (YAML)
[source, yaml, role="noclip mt-4 mb-4"]
----
# ------------------------------------------------------------------------------
# Collection Biography
#
- grid:
  enabled:                          true

  id:                               collection_biography
  type:                             collection
  collection:                       biography
  image_styles:                     img-fluid
  image_height:                     470px
  image_width:                      400px
  preview:                          false
  gutters:                          false

  # ----------------------------------------------------------------------------
  # Masonry options
  #
  options:
    originTop:                      true
    originLeft:                     true
    initLayout:                     true
    percentPosition:                true
----

.Collection Grid + Preview + Gutters (Fantasy)
masonry::collection_fantasy[role="mb-3"]

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::collection_fantasy[]
----

.Configuration settings (YAML)
[source, yaml, role="noclip mt-4 mb-4"]
----
# ------------------------------------------------------------------------------
# Collection Biography
#
- grid:
  enabled:                          true

  id:                               collection_fantasy
  type:                             collection
  collection:                       fantasy
  image_styles:                     img-fluid
  image_height:                     470px
  image_width:                      400px
  preview:                          true
  gutters:                          true

  # ----------------------------------------------------------------------------
  # Masonry options
  #
  options:
    originTop:                      true
    originLeft:                     true
    initLayout:                     true
    percentPosition:                true
----


== Grid on Posts

J1 Masonry `posts grid` pull content from a specific category. All Grids for
posts display the post category, the post title, the author and date. All
Masonry grids for the J1 Theme can be easily customized in various ways, such
as changing the number of posts displayed, the masonry speed, and other
options.

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::post_series_example[]
----

.Post Grid + Gutters (Life)
masonry::post_series_example[role="mb-4"]

.Configuration settings (YAML)
[source, yaml, role="noclip mt-4 mb-4"]
----
# --------------------------------------------------------------------------
# Post Series
#
- grid:
  enabled:                          true

  id:                               post_series_example
  type:                             post
  group:                            Life
  image_styles:                     img-fluid
  image_height:                     300px
  gutters:                          true

  # ------------------------------------------------------------------------
  # Masonry options
  #
  options:
    originTop:                      true
    originLeft:                     true
    initLayout:                     true
    percentPosition:                true
----


NOTE: The J1 Masonry module supports a series of posts out of the box. If the
grid type of `post-series` is given, all posts of a group (series) are
generated automatically as Bootstrap Cards of type *post*.

[role="mb-4"]
The Masonry Javascript module has become a go-to library for web developers
who need to create dynamic grid layouts, especially for websites that showcase
many images or other visual content like post series for example.


== Grid on Images

J1 Masonry is a great tool to create dynamic image galleries. Image galleries
are popular on many websites, and masonry can be a useful tool for creating
dynamic and visually appealing galleries. By using masonry, you can create a
gallery that displays images of different sizes in an aesthetically pleasing
and functional way.

=== Bootstrap Cards

Bootstrap cards are a popular component of the Bootstrap front-end framework
that provides a flexible and customizable way to display content on a website.
A card is a container for content that can be styled and arranged in various
ways to suit the website's needs.

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::card_example[]
----

.Image Cards + Lightbox + Gutters + Captions
masonry::card_example[role="mb-4"]

.Configuration settings (YAML)
[source, yaml, role="noclip mt-4 mb-4"]
----
# --------------------------------------------------------------------------
# Image Cards + Lightbox + Gutters + Captions
#
- grid:
  enabled:                          true

  id:                               card_example
  type:                             card
  image_base_path:                  /assets/images/modules/gallery/mega_cities
  image_styles:                     img-fluid img-object--cover g-height-300
  lightbox:                         true
  gutters:                          true

  # ------------------------------------------------------------------------
  # Captions
  #
  caption:
    enabled:                        true
    position:                       bottom

  # ------------------------------------------------------------------------
  # Masonry options
  #
  options:
    originTop:                      true
    originLeft:                     true
    initLayout:                     true
    percentPosition:                true

  # ------------------------------------------------------------------------
  # Images
  #
  images:

    - image:                        # image 1
      file:                         denys-nevozhai-1_b.jpg
      caption:                      Man posing at the rooftop of Jin Mao Tower Shanghai - China

      ...
----

=== Images

Using an image gallery to display images of different sizes can be challenging,
resulting in an uneven or unbalanced layout. However, this is where masonry
can be particularly useful.

==== Base Grid

Masonry uses a dynamic grid system to position images to create a visually
appealing and balanced layout. A dynamic grid system means you can display
images of different sizes without worrying about them looking out of place
or disrupting the overall flow of the gallery.

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::image_grid_base_example[]
----

.Image Grid + No Lightbox + No Gutters + No Captions
masonry::image_grid_base_example[role="mb-4"]

.Configuration settings (YAML)
[source, yaml, role="noclip mt-4 mb-4"]
----
# --------------------------------------------------------------------------
# Image Grid + No Lightbox + No Gutters + No Captions
#
- grid:
  enabled:                          true

  id:                               image_grid_base_example
  type:                             image
  image_base_path:                  /assets/images/modules/gallery/mega_cities
  image_styles:                     img-fluid
  lightbox:                         false
  gutters:                          false

  # ------------------------------------------------------------------------
  # Captions
  #
  caption:
    enabled:                        false
    position:                       bottom

  # ------------------------------------------------------------------------
  # Masonry options
  #
  options:
    originTop:                      true
    originLeft:                     true
    initLayout:                     true
    percentPosition:                true

  # ------------------------------------------------------------------------
  # Images
  #
  images:

    - image:                        # image 1
      file:                         denys-nevozhai-1_b.jpg
      caption:                      Man posing at the rooftop of Jin Mao Tower Shanghai - China

      ...
----

==== Full Grid

The full grid is using additonally a so-called *lightbox*. A lightbox is a
helper which displays enlarged, almost screen-filling versions of images
(or videos) while dimming the remainder of the page. The technique,
introduced by Lightbox V2, gained widespread popularity thanks to its simple
style. The term *lightbox* has been employed since then for Javascript
libraries to support such functionality.

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::image_grid_full_example[]
----

A lightbox supports single images and image groups (image sets). Click on the
images below to see how a Lightbox manages a group of images shown in your
grid.

.Image Grid + Gutters + Lightbox + Captions
masonry::image_grid_full_example[role="mb-4"]

.Configuration settings (YAML)
[source, yaml, role="noclip mt-4 mb-4"]
----
# --------------------------------------------------------------------------
# Image Grid + Lightbox + Gutters + Captions
#
- grid:
  enabled:                          true

  id:                               image_grid_full_example
  type:                             image
  image_base_path:                  /assets/images/modules/gallery/mega_cities
  image_styles:                     img-fluid
  lightbox:                         true
  gutters:                          true

  # ------------------------------------------------------------------------
  # Captions
  #
  caption:
    enabled:                        true
    position:                       bottom

  # ------------------------------------------------------------------------
  # Masonry options
  #
  options:
    originTop:                      true
    originLeft:                     true
    initLayout:                     true
    percentPosition:                true

  # ------------------------------------------------------------------------
  # Images
  #
  images:

    - image:                        # image 1
      file:                         denys-nevozhai-1_b.jpg
      caption:                      Man posing at the rooftop of Jin Mao Tower Shanghai - China

      ...
----

NOTE: The lightbox placed on Masonry Grids is _Lightbox V2_, the classic
lightbox widely used on the Internet.

////
==== Full Grid + Filters

The CSS3 filter property provides a range of image filters that allow you
to apply various visual effects to images using only CSS. These filters can
alter the appearance of images by adjusting colors, blurring or sharpening,
adding gradients, and more.

NOTE: Find available CSS Image Filters in section <<CSS3 Filter Functions>>.

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::image_grid_full_example_filters[]
----

.Image Grid + Gutters + Lightbox + Captions + Filters
masonry::image_grid_full_example_filters[role="mb-4"]

.Configuration settings (YAML)
[source, yaml, role="noclip mb-4"]
----
# --------------------------------------------------------------------------
# Image Grid + Lightbox + Gutters + Captions
#
- grid:
  enabled:                          true

  id:                               image_grid_full_example
  type:                             image
  image_base_path:                  /assets/images/modules/gallery/mega_cities
  image_styles:                     img-fluid
  lightbox:                         true
  gutters:                          true

  # ------------------------------------------------------------------------
  # Captions
  #
  caption:
    enabled:                        true
    position:                       bottom

  # ------------------------------------------------------------------------
  # CSS filter options (Sepia)
  #
  filters:
    enabled:                        true
    grayscale:                      0.8
    contrast:                       0.8
    brightness:                     0.7
    sepia:                          1

  # ------------------------------------------------------------------------
  # Masonry options
  #
  options:
    originTop:                      true
    originLeft:                     true
    initLayout:                     true
    percentPosition:                true

  # ------------------------------------------------------------------------
  # Images
  #
  images:

    - image:                        # image 1
      file:                         denys-nevozhai-1_b.jpg
      caption:                      Man posing at the rooftop of Jin Mao Tower Shanghai - China

      ...
----
////

////
[role="mt-5"]
== CSS3 Filter Functions

// See: https://developer.mozilla.org/en-US/docs/Web/CSS/filter#filter_functions

The filter property is specified as none or one or more of the functions
listed below. If the parameter for any function is invalid, the function
returns none. Except where noted, the functions that take a value expressed
with a percent sign (as in 34%) also accept the value expressed as decimal
(as in 0.34).

=== blur()

The blur() function applies a Gaussian blur to the input image. The value
of radius defines the value of the standard deviation to the Gaussian
function, or how many pixels on the screen blend into each other, so a
larger value will create more blur. The initial value for interpolation is 0.
The parameter is specified as a CSS length, but does not accept percentage
values.

.Examples
[source, css]
----
filter: blur(5)
filter: blur(50)
----

=== brightness()

The brightness() function applies a linear multiplier to the input image,
making it appear more or less bright. A value of 0% will create an image
that is completely black. A value of 100% leaves the input unchanged. Other
values are linear multipliers on the effect. Values of an amount over 100%
are allowed, providing brighter results. The initial value for interpolation
is 1.

.Examples
[source, css]
----
filter: brightness(1)
filter: brightness(0.3)
----

=== contrast()

The contrast() function adjusts the contrast of the input image. A value
of 0% will create an image that is completely gray. A value of 100% leaves
the input unchanged. Values of an amount over 100% are allowed, providing
results with more contrast. The initial value for interpolation is 1.

.Examples
[source, css]
----
filter: contrast(2)
----

=== grayscale()

The grayscale() function converts the input image to grayscale. The value
of amount defines the proportion of the conversion. A value of 100% is
completely grayscale. A value of 0% leaves the input unchanged. Values
between 0% and 100% are linear multipliers on the effect. The initial value
for interpolation is 0.

.Examples
[source, css]
----
filter: grayscale(1)
filter: grayscale(0.5)
----

=== hue-rotate()

The hue-rotate() function applies a hue rotation on the input image. The value
of angle defines the number of degrees around the color circle the input
samples will be adjusted. A value of 0deg leaves the input unchanged. The initial value for interpolation is 0. Though there is no maximum value; the effect of values above 360deg wraps around.

.Examples
[source, css]
----
filter: hue-rotate(90)
----

=== invert()

The invert() function inverts the samples in the input image. The value of
amount defines the proportion of the conversion. A value of 100% is completely
inverted. A value of 0% leaves the input unchanged. Values between 0% and 100%
are linear multipliers on the effect. The initial value for interpolation is 0.

.Examples
[source, css]
----
filter: invert(100%)
filter: invert(1)
filter: invert(0.6)
----

=== opacity()

The opacity() function applies transparency to the samples in the input image.
The value of amount defines the proportion of the conversion. A value of 0%
is completely transparent. A value of 100% leaves the input unchanged. Values
between 0% and 100% are linear multipliers on the effect. This is equivalent
to multiplying the input image samples by amount. The initial value for
interpolation is 1. This function is similar to the more established opacity
property; the difference is that with filters, some browsers provide hardware
acceleration for better performance.

.Examples
[source, css]
----
filter: opacity(1)
filter: opacity(0.5)
----

=== saturate()

The saturate() function saturates the input image. The value of amount
defines the proportion of the conversion. A value of 0% is completely
un-saturated. A value of 100% leaves the input unchanged. Other values are
linear multipliers on the effect. Values of amount over 100% are allowed,
providing super-saturated results. The initial value for interpolation is 1.

[source, css]
----
filter: saturate(200%)
----

.Examples
=== sepia()

The sepia() function converts the input image to sepia. The value of amount
defines the proportion of the conversion. A value of 100% is completely sepia.
A value of 0% leaves the input unchanged. Values between 0% and 100% are
linear multipliers on the effect. The initial value for interpolation is 0.

[source, css]
----
filter: sepia(1)
filter: sepia(0.5)
----

=== Combining functions

You may combine any number of functions to manipulate the rendering. The
following example enhances the contrast and brightness of the image:

.Example
[source, css]
----
filter: grayscale(0.5) sepia(0.5)
----


[role="mt-5"]
== Justified Gallery

[role="mb-4"]
As an alternative to grids on image contents arranged by Masonry, the module
*JustifiedGallery* can be used to display photos in a masonry-styled image
gallery. link:{url-justified-gallery--home}[JustifiedGallery, {browser-window--new}]
is a great _jQuery_ Plugin to create responsive, infinite, and high-quality
justified image galleries.

.Masonry Layout of JustifiedGallery
gallery::jg_customizer[role="mb-4"]

Digital image content, pictures or videos, are easy to make. Today, every
mobile has a camera. Presenting a bunch of photos or videos is done very
easily by using *Justified Gallery*. Videos created by a digicam or a mobile
can be played by J1 Theme using the HTML5 Video support. Present
videos you have made at it’s best.

TIP: Find more on how to present video content using *JustifiedGallery* on the example
page link:{url-roundtrip--present-videos}[Present Videos, {browser-window--new}].
////
