---
title:                                  Rouge
tagline:                                Highlighter Themes
date:                                   2022-12-08 00:00:00
description: >
                                        Rouge is a pure Ruby library for syntax highlighting
                                        and is fully supported by Jekyll. The library is
                                        integrated with the J1 Theme and supports 100+ script
                                        and programming languages. Multiple styles are available
                                        to customize the highlighter Rouge for light or dark
                                        J1 Themes.

categories:                             [ Previewer ]
tags:                                   [ Highlighter, Rouge ]

image:
  path:                                 /assets/images/modules/attics/jessica-ruscello-1920x1280.jpg
  width:                                1920
  height:                               1280
  alt:                                  Photo by Jessica Ruscello Unsplash

scrollbar:                              false
fab_menu_id:                            page_ctrl

permalink:                              /pages/public/previewer/rouge/
regenerate:                             false

resources:                              [ animate, clipboard, rouge ]
resource_options:
  - toccer:
      collapseDepth:                    3
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/jessica-ruscello-1920x1280.jpg
          alt:                          Photo by Jessica Ruscello Unsplash
          badge:
            type:                       unsplash
            author:                     Jessica Ruscello
            href:                       https://unsplash.com/@jruscello
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
// :source-highlighter: rouge
// https://dzone.com/articles/awesome-asciidoctor-highlight-lines-in-source-code
//
:rouge-line-class: line
:rouge-line-id: X%i


//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Rouge is a pure Ruby library for syntax highlighting and is fully supported
by Jekyll. The library is integrated with the J1 Theme and supports 100+
script and programming languages. Multiple styles are available to customize
the highlighter for light or dark J1 Themes.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="dropcap"]
== Styles selector

For the default theme `Uno` of J1 Theme, the following _Rouge_ themes
are used:

* light: `uno.light` (based on the style `github`)
* dark:  `uno.dark`  (based on the style `gruvbox`)

NOTE: The default styles used for J1 Theme can be configured with the
global template configuration file `~/_data/j1_config.yml`.

Make a selection from the select button below to preview a style for the
Rouge Syntax Highlighter.

++++
<div class="btn-group" role="group" aria-label="Button to select a style">
  <!-- See: https://stackoverflow.com/questions/47242702/force-bootstrap-dropdown-menu-to-always-display-at-the-bottom-and-allow-it-go-of -->
  <!-- NOTE: control the behaviour of popper.js for positioning -->
  <!-- NOTE: set attribute data-flip="false" to open the SELECT list at the BOTTOM of the BUTTON -->
  <button id="btnGroupThemesDropdown"
    class="btn btn-primary btn-raised btn-flex btn-lg dropdown-toggle"
    data-flip="false" type="button"
    data-bs-toggle="dropdown"
    data-bs-target="#navbarDropdown"
    aria-haspopup="true"
    aria-expanded="false">
    Select a style <span class="caret ml-2"></span>
  </button>
  <ul class="dropdown-menu scrollable-menu" role="menu" aria-labelledby="btnGroupThemesDropdown">
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('uno.light')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>uno.light</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('uno.dark')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>uno.dark</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('base16')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>base16</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('base16.dark')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>base16.dark</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('base16.light')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>base16.light</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('base16.monokai')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>base16.monokai</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('base16.monokai.dark')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>base16.monokai.dark</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('base16.monokai.light')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>base16.monokai.light</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('base16.solarized')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>base16.solarized</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('base16.solarized.dark')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>base16.solarized.dark</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('base16.solarized.light')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>base16.solarized.light</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('colorful')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>colorful</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('github')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>github</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('gruvbox')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>gruvbox</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('gruvbox.light')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>gruvbox.light</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('igorpro')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>igorpro</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('molokai')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>molokai</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('monokai')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>monokai</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('monokai.sublime')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>monokai.sublime</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('pastie')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>pastie</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('thankful_eyes')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>thankful_eyes</a></li>
    <li><a class="dropdown-item" href="#void"  onclick="j1.adapter.rouge.reaplyStyles('tulip')"> <i class="mdi mdi-view-quilt mdi-18px mr-2" style="color: #9E9E9E"></i>tulip</a></li>
  </ul>
</div>
<div id="selected" class="mt-3 mb-5"></div>
++++

=== Language examples

Find a selected number languages (code blocks) and their highlightning using
a selected theme.

include::{documentdir}/rouge/100_language_examples.asciidoc[]

== Rouge attributes

You can further customize the source block output with additional Rouge
attributes.

include::{tabledir}/rouge/200_rouge_attributes.asciidoc[]

== Supported languages

Here the list of the (current of Feb, 2022) supported languages and lexers
(language highlighters).

include::{tabledir}/rouge/300_supported_languages.asciidoc[]
