---
title:                                  Google Adsense
tagline:                                Preview  Advertising
date:                                   2023-05-19 00:00:00 +100
description: >
                                        AdSense is an advertising platform provided by Google,
                                        fully integrated into J1 Template for easy use, that
                                        allows website owners and content creators to earn
                                        money by displaying targeted advertisements on their
                                        online properties.
keywords: >
                                        Jekyll, Theme, JekyllOne, Info, Preview, Google, Adsense

categories:                             [ Manual ]
tags:                                   [ Cheatsheet, Adsense ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/eleni-afiontzi.jpg
  width:                                1920
  height:                               1280
  alt:                                  Photo by Eleni Afiontzi on Unsplash

regenerate:                             false
permalink:                              /pages/public/previewer/gad/

resources:                              [ advertising, animate, clipboard, rouge ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/eleni-afiontzi.jpg
          alt:                          Photo by Eleni Afiontzi on Unsplash
          badge:
            type:                       unsplash
            author:                     Eleni Afiontzi
            href:                       https://unsplash.com/de/@eleniafiontzi
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="dropcap"]
AdSense is an advertising platform provided by Google that allows website
owners and content creators to earn money by displaying targeted advertisements
on their online properties. It is one of the most popular and widely used
advertising networks on the internet.

NOTE: It's important to note that AdSense has policies and guidelines that
publishers must adhere to. Violations of these policies can lead to penalties
or even account suspension. Publishers need to ensure that their content and
website comply with the AdSense program policies to maintain their
eligibility for the program.

[role="mt-5"]
== Benefits using AdSense

With AdSense, website owners can participate in the program to monetize
their websites, blogs, or YouTube channels. AdSense provides a way for
publishers to generate revenue by displaying relevant ads matched to their
site's content or videos When a visitor clicks on an ad displayed through
AdSense, the website owner earns a portion of the revenue generated from
that click. The amount earned per click can vary depending on factors such
as the advertiser's bid, the ad's keywords' competitiveness, and the
website's overall performance.

AdSense uses contextual targeting to display ads relevant to the website's
content. Using the service means that the ads are tailored to match the
interests of the visitors, increasing the likelihood of clicks and conversions
for advertisers. Google handles the entire ad selection, delivery, and
payment process, making it a convenient solution for website owners who
want to monetize their online presence. AdSense also provides various
customization options, allowing publishers to control the appearance and
placement of ads on their websites.

[role="mt-5"]
== J1 Integration

To make the implementation of _Google Adsense_ as easy as possible,
J1 Template integrates all required scripts with the *Advertising* module.
First, find examples of how *Google Ads* are integrated into a *page*.

=== Examples

A common type for *Google Ads* is the type `in-article`.

gad::ad_7522184684["mt-4 mb-4"]

A common type for *Google Ads* is the type `in-article`.

gad::ad_7522184684_2["mt-4 mb-4"]

[role="mt-4"]
=== Setup

Setting up the *Advertising* requires to *enable* the module on every page
by requesting the *module* to be loaded by the `resources` record. Add the
*id* of the module `advertising` to enable the processing the ads you have
configured.

.Frontmatter settings (resources)
[source, yaml, role="noclip"]
----
title:                                  Google Adsense
tagline:                                Preview  Advertising

...

resources:                              [ advertising, animate, clipboard, rouge ]

...
----

lorem:sentences[5]

[role="mt-4"]
=== Asciidoc Extension

Making ads on a page easier, the Asciidoc Extention `gad::` supports you in
placing a container into your source code. While your page is being processed
by _Jekyll_, the module places a `<div>` element and fills in on module
*initialization*.

[source, bash, role="noclip"]
----
gad::ad_id[role="additional container classes"]
----

.Example
[source, bash, role="noclip"]
----
gad::ad_7522184684["mt-4 mb-4"]
----

The *HTML code* generated for an ad (id `ad_7522184684`) looks like so:

.Generated HTML code
[source, html, role="noclip"]
----
<div id="ad_7522184684" class="gad-container mb-5">
  <ins id="ins_ad_7522184684"
    class="adsbygoogle"
    style="display:block; text-align:center;"
    data-ad-test="on"
    data-ad-layout="in-article"
    data-ad-format="fluid"
    data-ad-client="<your-publisher-id>"
    data-ad-slot="7522184684">
  </ins>
</div>
----

NOTE: On module *initialization*, all `<div>` elements get registered with
*Google AdSense* to fill the *container* by active advertising.

[role="mt-5"]
== Module Configuration

The module configuration requires first to set your `publisherID` *globally*
to register a page with *Google AdSense*. In a second step, all *ads*
(ad blocks, slot ids) registered with your AdSense account are to be defined.

[source, yaml, role="noclip"]
----
# ------------------------------------------------------------------------------
# User settings
#
settings:
  enabled:                              true

  google:
    publisherID:                        <your-publisher-id>
    autoHideOnUnfilled:                 false
    addBorderOnUnfilled:                true

  # ----------------------------------------------------------------------------
  # All advertising container/ad available
  # ----------------------------------------------------------------------------
  ads:

    # ------------------------------------------------------------------------
    # Ad on slot id "7522184684"
    #
    - ad:

      # container settings
      # ----------------------------------------------------------------------
      enabled:                        true

      id:                             ad_7522184684
      layout:                         home

      # ad properties
      # ----------------------------------------------------------------------
      publisherID:                    <your-publisher-id>
      test:                           "on"
      styles:                         "display:block; text-align:center;"
      slot:                           7522184684
      ad_layout:                      in-article
      format:                         fluid

      # ------------------------------------------------------------------------
      # Ad on slot id "7522184684"
      #
      - ad:

        # container settings
        # ----------------------------------------------------------------------
        enabled:                        true

        id:                             ad_7522184684
        layout:                         page

        # ad properties
        # ----------------------------------------------------------------------
        publisherID:                    ca-pub-3885670015316130
        test:                           "on"
        styles:                         "display:block; text-align:center;"
        slot:                           7522184684
        ad_layout:                      in-article
        format:                         fluid

      # ------------------------------------------------------------------------
      # Ad on slot id "7522184684" #2
      #
      - ad:

        # container settings
        # ----------------------------------------------------------------------
        enabled:                        true

        id:                             ad_7522184684_2
        layout:                         page

        # ad properties
        # ----------------------------------------------------------------------
        publisherID:                    ca-pub-3885670015316130
        test:                           "on"
        styles:                         "display:block; text-align:center;"
        slot:                           7522184684
        ad_layout:                      in-article
        format:                         fluid
----

NOTE: You can define the same ad block (slot id) multiple times, but a unique
`id` has to be configured each ad block.

[role="mt-4"]
=== Properties

Find all property settings for ad blocks below.

.Property settings
[cols="2a, 2a, 3a, 5a", options="header", width="100%", role="rtable mt-3 mb-5"]
|===
|Prperty |Values |Default |Description

|`styles`
|string
|none
|Defines the CSS styles applied on an specific advertising. Contains *CSS*
classes separated by an colon (`;`). Taken from the ad-code generated
by Adsense. +
Example: `display:block; text-align:center;`.

|`publisherID`
|string
|ca-pub-number\|pub-number
|Defines the publisher id used for an advertising. *Current* accounts at
Adsense using the format of `ca-pub-1234567890123456` (fake id).

|`format`
|string
|none
|Enables **auto**-format settings. Taken from the ad-code generated
by Adsense. +
Example: `fluid`.

|`ad_layout`
|string
|none
|Specifies the layout of the *ad*. Taken from the ad-code generated
by Adsense. +
Example: `in-article`.

|`test`
|string (on\|off)
|off
|For testing only. If `test` is enabled (`on`), clicks and impressions
*not* recorded by the service and advertisers are *not* charged. If tests
are done on *localhost*, property `test` must set to `on`.

|===
