---
title:                                  J1 Masonry
tagline:                                Preview
date:                                   2020-11-03 00:00:00
description: >
                                        The term masonry is commonly used in web development to
                                        refer to a grid layout system for arranging elements on a webpage.
                                        The masonry layout, also known as the Pinterest-style layout, is
                                        a popular choice for displaying images of varying sizes aesthetically
                                        pleasingly.

categories:                             [ Previewer ]
tags:                                   [ Masonry, Example ]

comments:                               false
fab_menu_id:                            open_toc
scrollbar:                              false
regenerate:                             false
permalink:                              /pages/public/previewer/masonry/

resources:                              [
                                          clipboard, lightbox, masonry,
                                          rouge, slick
                                        ]
resource_options:
  - attic:
      padding_top:                      600
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/hayden-mills-2.jpg
          alt:                          Photo by Hayden Mills on Unsplash
          badge:
            type:                       unsplash
            author:                     Hayden Mills
            href:                       https://unsplash.com/@haydmills
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The recnical term *Masonry* is used in web development to refer to a *grid
layout* system for arranging elements on a webpage. The masonry layout, also
known as the **Pinterest**-style layout, is a popular choice for displaying
images of varying sizes aesthetically pleasingly.

J1 Masonry is based on the popular JavaScript library _Masonry_ that enables
the creation of responsive, dynamic grid layouts. It uses a unique algorithm
to arrange elements vertically, then horizontally in the grid. The result is
a visually appealing layout that works well with images and other content of
varying sizes.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
== Masonry Grid on Posts

J1 Masonry is easy to use and can be added to a webpage with just a few
lines. The module provides a flexible configuration that allows developers
to customize the layout, adjust the column width and gutter size, and add
animations and other effects.

[role="mb-4"]
J1 Masonry posts grid pull content from a specific category. All Grids for posts
display the post category, the post title, the author and date. All Masonry
Grids for the J1 Theme can be easily customized in various ways, such as
changing the number of posts displayed, the masonry speed, and other options.

.Asciidoc configuration
[source, config, role="noclip mb-3"]
----
masonry::post_series_grid[]
----

.Masonry Post Grid
masonry::post_series_grid[role="mb-4"]

NOTE: The J1 Masonry module supports a series of posts out of the box. If the
grid type of `post-series` is given, all posts of a group (series) are
generated automatically as Bootstrap Cards of type *post*.

[role="mb-4"]
The Masonry Javascript module has become a go-to library for web developers
who need to create dynamic grid layouts, especially for websites that showcase
many images or other visual content like post series for example.


== Masonry Grid on Images

J1 Masonry is a great tool to create dynamic image galleries. Image galleries
are popular on many websites, and masonry can be a useful tool for creating
dynamic and visually appealing galleries. By using masonry, you can create a
gallery that displays images of different sizes in an aesthetically pleasing
and functional way.

=== Bootstrap Image Cards

Bootstrap cards are a popular component of the Bootstrap front-end framework
that provides a flexible and customizable way to display content on a website.
A card is a container for content that can be styled and arranged in various
ways to suit the website's needs.

.Asciidoc configuration
[source, config, role="noclip mb-3"]
----
masonry::bs_image_cards_example[role="mb-4"]
----

.BS Image Cards + Lightbox
masonry::bs_image_cards_example[role="mb-4"]


=== Grid on Images in different sizes

Using an image gallery to display images of different sizes can be challenging,
resulting in an uneven or unbalanced layout. However, this is where masonry
can be particularly useful.

==== Base Image Grid

Masonry uses a dynamic grid system to position images to create a visually
appealing and balanced layout. A dynamic grid system means you can display
images of different sizes without worrying about them looking out of place
or disrupting the overall flow of the gallery.

.Asciidoc configuration
[source, config, role="noclip mb-3"]
----
masonry::image_grid_example[role="mb-4"]
----

.Image Grid
masonry::image_grid_example[role="mb-4"]

==== Image Grid + Lightbox

A Lightbox is, in general, a helper which displays enlarged, almost
screen-filling versions of images (or videos) while dimming the remainder
of the page. The technique, introduced by Lightbox2, gained widespread
popularity thanks to its simple style. The term *lightbox* has been employed
since then for Javascript libraries to support such functionality.

.Asciidoc configuration
[source, config, role="noclip mb-3"]
----
masonry::image_grid_lightbox_example[role="mb-4"]
----

.Image Grid
masonry::image_grid_lightbox_example[role="mb-4"]

A lightbox supports image groups (image sets). Click on the images below to
see how a Lightbox manages a group of images.

NOTE: The default lightbox for Masonry Grids is _Lightbox2_, the classic
lightbox widely used on the Internet.
