---
title:                                  Image
title_extention:                        J1 Image Apps
tagline:                                J1 Image Apps

date:                                   2020-11-03
#last_modified:                         2023-01-01

description: >
                                        The image modules supported by J1 Template offer valuable
                                        features based on powerful Open Source libraries like
                                        Masterslider, lightGallery, or Justified Gallery for high-end,
                                        masonry-styled preview maps.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        image, lightbox, carousel, slider, gallery,
                                        masterslider, lightgallery, justifiedgallery

categories:                             [ Roundtrip ]
tags:                                   [ Module, Lightbox, Image, Slider ]

image:
  path:                                 /assets/image/module/attic/1920x1280/quino-al-2.jpg
  width:                                1920
  height:                               1280

compress:                               true
regenerate:                             false
permalink:                              /pages/public/tour/image_data/

resources:                              [
                                          gallery, lightbox, lightgallery,
                                          masonry, photoswipejs, swiperjs
#                                         videojs, vimeo-player
                                        ]
resource_options:
  - toccer:
      collapseDepth:                    3
  - attic:
      slides:
        - url:                          /assets/image/module/attic/1920x1280/quino-al-2.jpg
          alt:                          Photo by Quino Al Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Quino Al Angel
            href:                       //unsplash.com/@quinoal
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:time-num--string:                      10-15
:time-en--string:                       Minutes
:time-en--description:                  to read
:time-de--string:                       Minuten
:time-de--description:                  Lesezeit

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Welcome to the preview page focussing on image modules. This page shows
all of the powerful features of the J1 Template to manage your image-based
content using lightboxes, carousels, sliders, grids, and galleries.

The image-related modules of the J1 Template offer a wide range of complex
functionality based on powerful Open Source libraries like Lightbox Version 2,
lightGallery Version 2, Slick Slider, Master Slider, or Masonry and
Justified-Gallery to create masonry-styled preview maps.

[subs=attributes]
++++
<div class="video-title">
  <i class="mdib mdib-clock-outline mdib-24px mr-2"></i>
  {time-num--string} {time-en--string} {time-en--description}
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
// [role="notranslate"]
[role="mt-5"]
== Lightboxes

A lightbox is a helper which displays enlarged, almost screen-filling versions
of images while dimming the remainder of the page. The technique, introduced
by Lightbox Version 2, gained widespread popularity thanks to its simple style.
The term *lightbox* has been employed since then for Javascript libraries to
support such functionality.

For J1 Template, different lightbox modules are available:

* Lightbox Version 2 (default)
* lightGallery Version 2 (optional)
* Slick Lightbox (optional, currently for Slick Carousels only)

The *default* tool employed by J1 Template is Lightbox V2, a Javascript
library written by _Lokesh Dhakar_ free to use for private or business
websites. For more complex use cases, like a thumbnail gallery preview or
video support, *lightGallery* can be used alternatively.

[CAUTION]
====
lightGallery is *free* to use based on a GPLv3 license for *non-business*
websites. If you have plans to use this lightbox for your business or on a
commercial site, you need to subscribe a so-called *Commercial License*. Find
more on the *paid* solution on the page:
https://www.lightgalleryjs.com/license[lightGallery license, {browser-window--new}].
====

All lightboxes are fully integrated to be used as standalone modules or
used as helpers *under-the-hood* by other modules focussing on image-data
like gallerys or carousels.

[TIP]
====
For details of the default lightbox of J1 Template, see the documentation
under the link:{url-j1-docs--lightbox-module}[Lightbox module, {browser-window--new}].
====

[role="mt-5"]
=== Lightboxes

Find below an example of using the the default lightbox used for standalone
images. See how individual images are linked.

.Lightbox for standalone images
lightbox::example-standalone[800, {data-images-lightbox--standalone}, role="mt-4 mb-5"]

The J1 lightbox module supports groups of images as well. Click on the image
group below to see how a group is managed.

.Lightbox for grouped images
lightbox::example-group[395, {data-images-lightbox--group}, group, role="mt-4 mb-4 wm-800"]


[role="mt-5"]
=== lightGallery

lightGallery provides more complex image data functions than the default
lightbox. The module supports a gallery-style thumbnail preview plus image
resizing, a download dialog, sharing provider support, and more helpful.
Check what lightGallery can do this by the following example.

.Gallery + lightGallery
gallery::jg_old_times[role="mt-4 mb-4"]

.lightGallery - Gallery or Lightbox
[NOTE]
====
The name lightGallery implies a sort of a gallery, but the library is a
*lightbox*, and provides enhannced functionality on image-based data rather
than enlarged displaying of images.
====

[role="mt-5"]
== J1 Slider

J1 Slider is based on *SwiperJS* in version *1.2.0* (January 7, 2025). The
slider is a powerful tool to create fully responsive and touch-enabled
slideshows.

[role="mt-4"]
=== Text Sliders

Swipers are typically used for displaying images. Still, the implementation
for the J1 Template supports a lot more sources to be displayed as a slide
show -- simple text for example.

[TIP]
====
Text sliders can be placed like banners on a page's section. For text sliders,
different animations are available.
====

[role="mt-4"]
==== Base Text Slider

Important statements or topics can be placed on top of an article or
a paragraph to give them better visibility. In one line, you can present
many facts to know animated for the reader's attention within a single
line.

.Base Text Swiper
swiper::swiper_text_base[role="mt-4 mb-5"]


[role="mt-4"]
==== Parallax Text Slider

A more emphasized type of text-based slide is a *parallax* text slider. If you
want to focus the meaning, this kind of a slide show may be interesting.
Image-based slide may draw off the reader's attention from the text. Therefore,
a pure text-based presentation may a better choice.

.Extended Text Swiper · Parallax
swiper::swiper_text_parallax[role="mt-4 mb-5"]


[role="mt-5"]
=== Image Slider

Slider (or carousels) are mostly used for pictures data to animate images
as a series. Find with the following some examples of how to use a carousel
for your image data.

A simple image show is useful, for example, as an animated (or not animated)
banner presenting exciting things about your site or the products offered.

[role="mt-4"]
==== One Slide Slider + Pagination

The build-in slider module *SwiperJS* supports multiple and single image
shows. Here you find an example of a single image slide show with controls
enabled to browse all images back and forth. An indicator below the slider
shows how many images the show contains.

.Image Slider · Full-width + Pagination
swiper::swiper_image_base_full_width_pagination[role="mt-3 mb-4"]

[role="mt-4"]
==== Image Slider + Lightbox

Sliders are used for an exceptionally compact form of image galleries. This
example shows some pictures having individual caption text and supports
a lightbox to enlarge images full size.

.Image Slider + Lightbox
swiper::swiper_image_base_captions[role="mt-4 mb-4"]

The J1 module lightbox is a simple Lightbox but offers a bunch of impressive
features for displaying images. For example, the lightbox can display all
images as a group. If one picture is opened in the lightbox, others are
browsed by easy-to-use control buttons.

[role="mt-5"]
=== Extendend Image Swipers

Layouts in terms of J1 Template for SwiperJS are *transformations* of a Swiper.
A *layout* is used to rebuild it for a more complex visual *presentation* for
the Swiper's slides. The Layout of a swiper can improve the *useability* or
make the *presentation* of a slideshow more *interesting*.

[role="mt-4"]
[[image_thumbs_top_bottom]]
==== Layout Thumb Top|Bottom

To give the users a more *visual* control over a slideshow, Swiper sliders
can provide *UI elements* by placing minified images or text elements (thumbs)
side-by-side (on the left|right), or at the bottom|top of a swiper. Find below
examples how to control such sliders' by a thumb (slave) silder.

[role="mt-4 mb-4"]
[TIP]
====
This Layout creates best results for high-quality images for websites mainly
used on *desktop* computers.
====

This Thumb Slider uses minified images that are placed to control the (main)
slider at the *top* or the *bottom*. This swiper type creates a thumbed Swiper
that uses *two lanes*, which takes up a *lot of space* but can render the
sliders' images *optimally*.

.Extendend Swiper · Layout Thumb Top
swiper::thumb_slider_top[role="mb-5"]


// [role="mt-5"]
// [[image_thumbs_right_left]]
// ==== Layout Thumb Right|Left

// A more **mobile**-friendly version of a Thunb slider is created by placing the
// minified images for the slider side-by-side on the *right* or the *left*. This
// swiper use just a *single lane* in the page, but *minifies* the presented images
// as required for the lane *heigth* specified.

// [role="mb-5"]
// [TIP]
// ====
// Adding a *Lightbox* to a *single-lane* swiper allows users to *enlarge* the
// presented *images*.
// ====


[role="mt-5"]
==== Layout Neighbor

A slideshow typically presents a larger number of slides, which requires a
sort of navigation. The effect *neighbors* accompanies the *active slide* by
their *neighbors* on the left and right as *previews*. The neighbor on the
*left* acts like a *previous button* and scrolls the slides *backward*. The
neighbor on the *right* acts like a *next button* and scrolls the slides
*forward*.

[role="mb-5"]
[TIP]
====
The *effect* transforms a slider into a quite *compact* presentation that does
*not* require any (additional) *navigation* elements.
====

.Extendend Swiper · Layout Neighbor
swiper::neighbor_slider[role="mb-5"]


[role="mt-5"]
==== Layout Panorama

The layout panaorama presents available slides of a slider as a group. The
group is displayed in a virtual, circular viewing angle. 

[role="mb-5"]
[TIP]
====
The effect is great for slides connected in terms of content to give the user
a panoramic view impression.
====

.Extendend Swiper · Layout Panorama
swiper::swiper_image_panorama[role="mt-4 mb-5"]


[role="mt-5"]
== Masonry Gallery

Masonry for J1 is a great tool to create dynamic image galleries. Image
galleries are popular on many websites, and masonry can be a useful tool for
creating dynamic galleries.

By using the Masonry module, you can create a gallery that displays images of
different sizes in an aesthetically pleasing and functional way.

.Grid of Images
masonry::image_fixed_height_lb[role="mt-4 mb-5"]

.More about Masonry
[TIP]
====
Find more on how the Masonry module can be used on the
link:{url-j1-masonry-previewer}[Masonry Preview, {browser-window--new}] page.
====


[role="mt-5"]
== Justified Gallery

link:{url-justified-gallery--home}[JustifiedGallery, {browser-window--new}]
is a great _jQuery_ Plugin to create responsive, infinite, and high-quality
justified image galleries. J1 Template combines the Gallery with the lightboxes
supported to enlarge the images of a gallery. See the gallery in action; and
for sure, all that you see is even responsive. Change the size of your current
browser window, by width or height to see what will happen!

[role="mb-4"]
Pictures you've made are typically not even in size. Images may have the
same size (resolution), but some are orientated landscapes, or others
may be portraits. For that reason, a more powerful gallery is needed to create
so-called justified views. J1 Gallery is based on Justified Gallery to create
so-called masonry grid layouts.

It works by placing elements in an optimal position based on available
horizontal and vertical space. Sort of like mason fitting stones in a wall.
For sure, you'll have seen it in action all over the Internet.

.Gallery of Images + lightGaller
gallery::jg_mega_cities[role="mt-4 mb-4"]


[role="mt-5"]
== What next

I hope, you've enjoyed exploring the possibilities J1 offers for managing
and displaying digital image content. But much, much more can the J1 do for
your web.

The J1 Template support playing audio and video on web pages by using the
HTML5 audio and video support, the new standard of HTML. HTML5 implements a
pure HTML way to show play audio or playing video on the web. Modern browsers
support the audio tag `<audio>` and the video tag `<video>` for the HTML5
standard.

The previous proprietary de facto standard software like a Flash Player,
Quicktime, or Silverlight is no longer needed as the Theme JekyllOne provides
HTML5 video for local content and from online sources on the Internet.

[role="mb-7"]
Incredible? See the next example page link:{url-tour--audio_data}[Audio Player].
