---
title:                                  Swiper V11
title_extention:                        API
tagline:                                Programming Interface

date:                                   2026-05-16
#last_modified:                         2026-01-01

description: >
                                        Swiper is the free and most modern mobile touch
                                        slider with hardware accelerated transitions and
                                        amazing native behavior. It is intended to be
                                        used in mobile websites, mobile web apps, and
                                        mobile native/hybrid apps.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        mobile, sites, static, jamstack, bootstrap, touch,
                                        image, slider, swiper

categories:                             [ Manual ]
tags:                                   [ Module, Slider, Swiper ]

image:
  path:                                 /assets/image/module/attic/1920x1280/teemu-paananen.jpg
  width:                                1920
  height:                               1280

compress:                               true
regenerate:                             true
permalink:                              /pages/public/manual/module/carousel/swiper/

resources:                              [
                                          gallery, lightbox3,
                                          photoswipejs, swiperjs
                                        ]
resource_options:
  - toccer:
      collapseDepth:                    2
  - attic:
      slides:
        - url:                          /assets/image/module/attic/1920x1280/teemu-paananen.jpg
          alt:                          Photo by Teemu Paananen on Unsplash
          badge:
            type:                       unsplash
            author:                     Teemu Paananen
            href:                       //unsplash.com/@xteemu
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Attribute settings for page content control (e.g includes)
//
:includedir:                            _includes
:tabledir:                              _includes/tables
:documentdir:                           _includes/documents

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:time-num--string:                      15-60
:time-en--string:                       Minutes
:time-en--description:                  to read
:time-de--string:                       Minuten
:time-de--description:                  Lesezeit

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// https://swiperjs.com/swiper-api
// -----------------------------------------------------------------------------
[role="dropcap"]
Swiper is the free and most modern mobile touch slider with hardware
accelerated transitions and amazing native behavior. It is intended to be
used in mobile websites, mobile web apps, and mobile native/hybrid apps.

In the J1 Template, Swiper is the *carousel engine* behind every slider on
your page. It is used together with link:{site.baseurl}/pages/public/manual/module/photoswipe5/photoswipe/[PhotoSwipe]
to provide an optional *lightbox*, so visitors can not only swipe through
your slides but also open each slide in a large overlay view. You can use
Swiper on its own, of course, if you do not need the lightbox feature.

[NOTE]
====
The Swiper API documentation pages are based on Swiper version *v11.2.x*
for the current J1 template version 2026.x. The idea of providing this
documentation is *not* to simply copy the original Swiper pages as
duplicates. For better readability and usability, all pages are
restructured and enhanced by code examples or improved description texts.

// The documentation pages for the J1 Template project will be used for the
// **AI**-based **chat client** (*planned* for 4th quarter of 2025). The agent
// will be trained by all available documentation pages of the Template system
// to give users an easy-to-use source for using the J1 Template to create
// websites for their needs.
====


// Include sub-documents
// -----------------------------------------------------------------------------

include::{documentdir}/000_swiper_api_intro.asciidoc[]
// include::{documentdir}/100_swiper_parameters.asciidoc[]
// include::{documentdir}/110_swiper_properties.asciidoc[]

// include::{documentdir}/120_swiper_methods.asciidoc[]
// include::{documentdir}/130_swiper_events.asciidoc[]
include::{documentdir}/140_swiper_modules.asciidoc[]




