---
title:                                  HTML Audio
title_extention:                        Embed Audio files
tagline:                                Embed Audio files

date:                                   2024-04-16
#last_modified:                         2024-01-01

description: >
                                        HTML 5 has brought sanity to audio support in the browser
                                        by adding the audio tag element and by introducing several
                                        standard audio formats.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap, html, html5,
                                        asciidoctor, audio

categories:                             [ Plugins ]
tags:                                   [ Asciidoctor, Audio ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/alexey-ruban.jpg
  width:                                1920
  height:                               1280

tts:                                    true
comments:                               false
exclude_from_search:                    false
regenerate:                             false
personalization:                        true
permalink:                              /pages/public/manuals/plugins/audio_video/html_audio/

resources:                              []
resource_options:
  - toccer:
      collapseDepth:                    2
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/alexey-ruban.jpg
          alt:                          Photo by Alexey Ruban on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexey Ruban
            href:                       //unsplash.com/de/@intelligenciya
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-j1-jupyter-notebooks--where-to-go: /pages/public/jupyter/where-to-go/

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// See: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs
//
The block audio macro enables you to embed audio streams into your
documents. Using the macro, embed self-hosted audio files or audio sources
from the Internet are supported.

mdi:clock-time-five-outline[24px, md-gray mt-4 mb-5 mr-2]
*5-10 Minutes* to read


[role="mt-5"]
== Asciidoc Macro `audio::`

The block audio macro enables you to embed audio streams into your
documents. Using the macro, embed self-hosted audio files or audio sources
from the Internet are supported.

[role="mt-5"]
=== Syntax

The audio formats the macro supports is given by the formats supported by
the browser. HTML 5 has brought sanity to audio support in the browser by
adding a dedicated audio tag element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio[`<audio>`, {browser-window--new}]
and by introducing several standard audio formats, widely supported across
all modern browsers.

For a canonical list of supported web audio formats and their interaction
with modern browsers, see the
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility[Mozilla Developer Supported Media Formats, {browser-window--new}]
documentation.

.Basic audio file include
[source, js]
----
audio::ocean-waves.wav[]
----

You can control the audio settings using additional attributes on the
macro. For instance, you can offset the start time of playback using the
`start` attribute and enable autoplay using the `autoplay` option.

.Set attributes for local audio playback
[source, js]
----
audio::ocean-waves.wav[start=60,opts=autoplay]
----

You can include a caption above the audio using the title attribute.

.Add a caption to the audio
[source, js]
----
.Take a zen moment
audio::ocean-waves.wav[]
----


[role="mt-5"]
=== Attributes

To control the audio, following attributes are available.

[cols="2a,3a,7a", width="100%", options="header", role="rtable mt-5 mb-5"]
|===
|Attribute |Value\|s |Example

|`title`
|User defined text
|`.Ocean waves`

|`start`
|User-defined playback start time in seconds.
|`start=30`

|`end`
|User-defined playback end time in seconds.
|`end=90`

|`options` (*opts*)
|`autoplay`, `loop`, `controls`, `nocontrols`
|`opts="autoplay,loop"`

[NOTE]
====
The *controls* value is *enabled* by default.
====

|===


[role="mt-5"]
== HTML `<audio>` element

The HTML video element `<audio>` embeds a media player which supports
audio playback into the document.

[role="mt-4"]
=== Events
// See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

[cols="4a,8a", width="100%", options="header", role="rtable mt-4 mb-4"]
|===
|Event Name |Fired When

|https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode/audioprocess_event[`audioprocess`, {browser-window--new}]
|The input buffer of a
https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode[`ScriptProcessorNode`, {browser-window--new}]
is ready to be processed.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplay_event[`canplay`, {browser-window--new}]
|The browser can play the media, but estimates that not enough data
has been loaded to play the media up to its end without having to stop
for further buffering of content.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplaythrough_event[`canplaythrough`], {browser-window--new}]
|The browser estimates it can play the media up to its end without
stopping for content buffering.

|https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/complete_event[`complete`, {browser-window--new}]
|The rendering of an
https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext[`OfflineAudioContext`, {browser-window--new}]
is terminated.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/durationchange_event[`durationchange`, {browser-window--new}]
|The `duration` attribute has been updated.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/emptied_event[`emptied`, {browser-window--new}]
|The media has become empty; for example, this event is sent if the
media has already been loaded (or partially loaded), and the
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/load[`HTMLMediaElement.load`, {browser-window--new}]
method is called to reload it.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/ended_event[`ended`, {browser-window--new}]
|Playback has stopped because the end of the media was reached.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadeddata_event[`loadeddata`, {browser-window--new}]
|The first frame of the media has finished loading.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadedmetadata_event[`loadedmetadata`, {browser-window--new}]
|The metadata has been loaded.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadstart_event[`loadstart`, {browser-window--new}]
|Fired when the browser has started to load the resource.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/pause_event[`pause`, {browser-window--new}]
|Playback has been paused.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play_event[`play`, {browser-window--new}]
|Playback has begun.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playing_event[`playing`, {browser-window--new}]
|Playback is ready to start after having been paused or delayed due to
lack of data.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/ratechange_event[`ratechange`, {browser-window--new}]
|The playback rate has changed.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/seeked_event[`seeked`, {browser-window--new}]
|A _seek_ operation completed.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/seeking_event[`seeking`, {browser-window--new}]
|A _seek_ operation began.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/stalled_event[`stalled`, {browser-window--new}]
|The user agent is trying to fetch media data, but data is unexpectedly
not forthcoming.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/suspend_event[`suspend`, {browser-window--new}]
|Media data loading has been suspended.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/timeupdate_event[`timeupdate`, {browser-window--new}]
|The time indicated by the `currentTime` attribute has been updated.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volumechange_event[`volumechange`, {browser-window--new}]
|The volume has changed.

|https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/waiting_event[`waiting`, {browser-window--new}]
|Playback has stopped because of a temporary lack of data

|===

[role="mt-4"]
=== Codecs

The list below denotes the codecs most commonly used on the web and which
file types support them. If you only need to know which codecs are possible,
this is for you.

Individual browsers *may or may not* choose to support all of these codecs,
and their support for which container types can use them may also vary.
In addition, browsers may support additional codecs not included on this
list.

[cols="2a,3a,7a", width="100%", options="header", role="rtable mt-5 mb-7"]
|===
|Codec name |Full name |Container support

|https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#aac_advanced_audio_coding[AAC, {browser-window--new}]
|Advanced Audio Coding
|
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#mpeg-4_mp4[MP4, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#adts[ADTS, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#3gp[3GP, {browser-window--new}]

|https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#alac_apple_lossless_audio_codec[ALAC, {browser-window--new}]
|Apple Lossless Audio Codec
|
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#mpeg-4_mp4[MP4, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#quicktime[QuickTime, {browser-window--new}] (MOV)

|https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#amr_adaptive_multi-rate[AMR, {browser-window--new}]
|Adaptive Multi-Rate
|
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#3gp[3GP, {browser-window--new}]

|https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#flac_free_lossless_audio_codec[FLAC, {browser-window--new}]
|Free Lossless Audio Codec
|
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#mpeg-4_mp4[MP4, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#ogg[Ogg, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#flac[FLAC, {browser-window--new}]

|https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#g.711_pulse_code_modulation_of_voice_frequencies[G.711, {browser-window--new}]
|Pulse Code Modulation (PCM) of Voice Frequencies
|
https://developer.mozilla.org/en-US/docs/Glossary/RTP[RTP, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API[WebRTC, {browser-window--new}]

|https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#g.722_64_kbps_7_khz_audio_coding[G.722, {browser-window--new}]
|7 kHz Audio Coding Within 64 kbps (https://developer.mozilla.org/en-US/docs/Glossary/VoIP[VoIP, {browser-window--new}])
|
https://developer.mozilla.org/en-US/docs/Glossary/RTP[RTP, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API[WebRTC, {browser-window--new}]

|https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#mp3_mpeg-1_audio_layer_iii[MP3, {browser-window--new}]
|MPEG-1 Audio Layer III
|
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#mpeg-4_mp4[MP4, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#adts[ADTS, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#mpeg[MPEG, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#3gp[3GP, {browser-window--new}]

When MPEG-1 Audio Layer III codec data is stored in an MPEG file, and
there is no video track on the file, the file is typically referred to
as an MP3 file, even though it's still an MPEG format file.

|https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#opus[Opus, {browser-window--new}]
|Opus
|
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#webm[WebM, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#mpeg-4_mp4[MP4, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#ogg[Ogg, {browser-window--new}]

|https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#vorbis[Vorbis, {browser-window--new}]
|Vorbis
|
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#webm[WebM, {browser-window--new}],
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#ogg[Ogg, {browser-window--new}]

|===
