---
title:                                  Amplitude
title_extention:                        Custom Audio players
tagline:                                Custom Audio Players

date:                                   2024-04-17
#last_modified:                         2024-01-01

description: >
                                        Amplitude is a JavaScript library to control the design of audio media
                                        elements on web pages. The concept allows designers to fully control the
                                        look and feel of audio players without deep scripting knowledge.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap, html, html5, audio,
                                        Amplitude

categories:                             [ Testpage ]
tags:                                   [ Audio. Amplitude ]

image:
  path:                                 /assets/images/icons/videojs/videojs-poster.png
  width:                                1920
  height:                               1280

regenerate:                             false
personalization:                        true
permalink:                              /pages/public/amplitude_tester/

resources:                              [ amplitude-js ]
resource_options:
  - toccer:
      collapseDepth:                    2
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/alexey-ruban.jpg
          alt:                          Photo by Alexey Ruban on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexey Ruban
            href:                       //unsplash.com/de/@intelligenciya
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// See: https://521dimensions.com/open-source/amplitudejs/docs
// See: https://github.com/mediaelement/mediaelement-plugins
// See: https://github.com/serversideup/amplitudejs/

[role="dropcap"]
The audio tag in HTML5 is a great way to add audio media to web pages.
However, the browser fully controls the audio playback interface, which
can limit or even break a page's design if audio media is used.

AmplitudeJS for the J1 Template offers a straightforward solution for web
developers. It allows them to easily customize the appearance of their audio
players without the need for complex scripting. By leveraging J1 Template
and Amplitude's API, web designers can craft unique interfaces that define
the visual and functional aspects of a player's audio control elements.


mdi:clock-time-five-outline[24px, md-gray mr-2]
*5 Minutes* to read

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-4"]
The J1 Template implements custom players based on the (default) theme Uno.
The color scheme used matches the look and feel of the template to preserve
the page design.

Three types of AmplitudeJS players are build-in for the J1 template system:

* Single Song Player
* Flat Player (the default audio plaayer)
* Expanded Player

[role="mt-4"]
[NOTE]
====
Amplitude players for the J1 Template are mobile-friendly. Instead of
clicking on the appropriate elements, touch events are applied to all
mobile devices.
====


[role="mt-5"]
== Single Song Player

Balla Balla ..

.Dance Floor 路 Royalty Free Music
amplitude::free_disco_single_song[role="mt-3 mb-5"]


[role="mt-5"]
== Flat Player

Balla Balla ..

.Dance Floor 路 Royalty Free Music
amplitude::free_disco_flat[role="mt-3 mb-5"]


[role="mt-5"]
== Expanded Player

Bla, bla ...

.Dance Floor 路 Royalty Free Music
amplitude::free_disco_expanded[role="mt-3 mb-5"]

// .Pop Music 路 Royalty Free Music
// amplitude::free_pop[role="mt-3 mb-5"]

[role="mt-5"]
== Player configuration

lorem:sentences[5]

[role="mt-4"]
=== Macro `amplitude::`

lorem:sentences[7]

[role="mt-4"]
=== Module settings

[role="mb-7"]
lorem:sentences[7]
