---
title:                                  Tester
tagline:                                Universal Icon Picker
date:                                   2023-05-20 00:00:00
description: >
                                        Welcome to the preview page focussing on the image module. This page
                                        shows some valuable features of the J1 Theme to manage your image-based
                                        content using lightboxes, carousels (slider), and galleries.

categories:                             [ Testpages ]
tags:                                   [ Example ]

comments:                               false
fab_menu_id:                            open_toc

permalink:                              /pages/public/learn/ui-picker/
regenerate:                             false

resources:                              [ animate, clipboard, rouge, lightbox, uipicker ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       https://unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Icon Picker

++++

<!-- Styles -->
<!-- base | always include -->
<!-- link rel="stylesheet" type="text/css" href="https://unpkg.com/@fonticonpicker/fonticonpicker/dist/css/base/jquery.fonticonpicker.min.css" -->
<link rel="stylesheet" type="text/css" href="/assets/themes/j1/modules/universal-icon-picker/assets/css/fonticonpicker/fonticonpicker.css">

<!-- default grey-theme -->
<!-- link rel="stylesheet" type="text/css" href="https://unpkg.com/@fonticonpicker/fonticonpicker/dist/css/themes/grey-theme/jquery.fonticonpicker.grey.min.css" -->

<!-- optional themes | no need to include default theme -->
<!-- link rel="stylesheet" type="text/css" href="https://unpkg.com/@fonticonpicker/fonticonpicker/dist/css/themes/bootstrap-theme/jquery.fonticonpicker.bootstrap.min.css" -->
<!-- link rel="stylesheet" type="text/css" href="https://unpkg.com/@fonticonpicker/fonticonpicker/dist/css/themes/dark-grey-theme/jquery.fonticonpicker.darkgrey.min.css" -->
<!-- link rel="stylesheet" type="text/css" href="https://unpkg.com/@fonticonpicker/fonticonpicker/dist/css/themes/inverted-theme/jquery.fonticonpicker.inverted.min.css" -->

<!-- Scripts -->
<script type="text/javascript" src="https://unpkg.com/@fonticonpicker/fonticonpicker/dist/js/jquery.fonticonpicker.min.js"></script>

  <!-- script src="/assets/themes/j1/modules/universal-icon-picker/assets/js/universal-icon-picker.js"></script -->
<button id="selector" title="Open the icon picker">Click to open</button>
<p class="mt-3"> Selected Icon </p>
<div id="output" class="output-icon mt-3 mb-5"></div>

++++

++++
<script>

  document.addEventListener('DOMContentLoaded', function(event) {

    // const options = {
    //     iconLibraries: [
    //         'happy-icons.min.json',
    //         'font-awesome.min.json'
    //     ],
    //     iconLibrariesCss: [
    //         'happy-icons.min.css',
    //         'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css'
    //     ],
    //     resetSelector: '#uip-reset-btn',
    //     onSelect: function(jsonIconData) {
    //         document.getElementById('output-icon').innerHTML = jsonIconData.iconMarkup;
    //         console.log(jsonIconData);
    //     },
    //     onReset: function() {
    //         document.getElementById('output-icon').innerHTML = '';
    //     }
    // }

    var uip = new UniversalIconPicker('#selector', {
      iconLibraries: [
          'font-awesome.min.json',
          'mdi-icons.min.json'
      ],
      iconLibrariesCss: [
          'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css',
          'https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/7.2.96/css/materialdesignicons.min.css'
      ],
      onSelect: function(jsonIconData) {
          document.getElementById('output').innerHTML = jsonIconData.iconMarkup;
          console.log(jsonIconData);
      }
    });

  });

</script>
++++
