---
title:                                  WebWhiz
title_extention:                        ChatGPT Client for J1 Template
tagline:                                ChatGPT Client

date:                                   2023-01-01
#last_modified:                         2023-01-01

description: >
                                        Welcome to the info pages of J1 Template. A good decision
                                        to get on that page first. Certainly, there is no better
                                        place to learn what J1 Template can do and what pages are
                                        available to experience more.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap

categories:                             [ Info ]
tags:                                   [ Introduction ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/brigitta-schneiter.jpg
  width:                                1920
  height:                               1280

fab_menu_id:                            open_toc
regenerate:                             false
permalink:                              /pages/public/learn/web_whiz/

resources:                              [ animate, rouge ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/brigitta-schneiter.jpg
          alt:                          Photo by Brigitta Schneiter on Unsplash
          badge:
            type:                       unsplash
            author:                     Brigitta Schneiter
            href:                       https://unsplash.com/de/@brisch27
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-j1--jekyll-collections:            /pages/public/learn/bookshelf/jekyll_collections/
:url-j1--cheatsheet-template:           https://jekyll.one/pages/public/tools/cheatsheet/j1/
:url-j1--cheatsheet-yaml:               https://jekyll.one/pages/public/tools/cheatsheet/yaml/
:url-j1--tutorial-j1-in-a-day:          https://jekyll.one/pages/public/learn/kickstart/web_in_a_day/meet_and_greet/
:url-j1--tutorial-learning-seo:         https://jekyll.one/pages/public/learn/kickstart/learning_seo/what_seo_is/

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Welcome to the learning pages of the J1 Template. A good decision to
get on that page first. Certainly, there is no better place to start learning
what the J1 Template can do and what pages are available to experience more.

mdi:clock-time-five-outline[24px, md-gray mr-2]
*3 Minutes* to read

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Chat Interface

Embedded Chat Interface (No Launcher). The Chat interface is permanently
displayed on your web page without a launcher icon.
