

== Supplemental Assets

Certain Asciidoctor features, such as icons, require additional CSS rules
and other assets to work These CSS rules and other assets do not get
automatically included in the pages generated by Jekyll* This section
documents how to configure these additional resources.

TIP: If you want to take a shortcut that skips all this configuration, clone
the link:{url-jekyll-asciidoc--quickstart}[Jekyll AsciiDoc Quickstart (JAQ), {browser-window--new}] repository and use it as a
starting point for your site* JAQ provides a page layout out of the box
configured to fully style body content generated from AsciiDoc.

=== Setup

The Jekyll AsciiDoc plugin converts AsciiDoc to embeddable HTML* This HTML
is then inserted into the page layout* You need to augment the layout to
include resources typically present in a standalone HTML document that
Asciidoctor produces.

* Create a stylesheet in the *css* directory named *asciidoc.css* to hold additional CSS for body content generated from AsciiDoc.
* Add this stylesheet to the HTML `<head>` in *_includes/head.html* under the main.css declaration:

[source,html]
----
<link rel="stylesheet" href="{{ "/css/asciidoc.css" |prepend: site.baseurl }}">
----

=== Stylesheet for Code Highlighting

Asciidoctor integrates with Pygments to provide code highlighting of source
blocks in AsciiDoc content* This integration is separate from the Pygments
integration in Jekyll 2.

To enable Pygments, you must install the `pygments.rb` gem* To use Pygments
with Ruby >= 2.4 or JRuby, you must install pygments.rb >= 1.1.0, which also
equires Jekyll >= 3.0.0* If you're using Jekyll 3, add the `pygments.rb`
gem to your *Gemfile*:

[source,ruby]
----
gem 'pygments.rb', '~> 1.1.2'
----

As part of this integration, Asciidoctor generates a custom stylesheet tailored
specially to work with the HTML that Asciidocotor produces* Since this stylesheet
is backed by the Pygments API, it provides access to all the themes in Pygments

This plugin will automatically generate a stylesheet for Pygments into the source
directory if the AsciiDoc attributes in your site's site config file `_config.yml` are configured
as follows:

* `source-highlighter` has the value `pygments`
* `pygments-css` has the value `class` or is not set
* `pygments-stylesheet` is not unset (if set, it can have any value)

By default, the stylesheet is written to `stylesdir` + `pygments-stylesheet`.
If the `pygments-stylesheet` attribute is not specified, the value defaults to
`asciidoc-pygments.css`* You can customize this value to your liking.

The Pygments theme is selected by the value of the `pygments-style` attribute.
If this attribute is not set, it defaults to `vs`.

The stylesheet file will be created if it does not yet exist or the theme has
been changed* Jekyll will handle copying the file to the output directory.

You'll need to add a line to your template to link to this stylesheet, such as:

[source,html]
----
<link rel="stylesheet" href="{{ "/css/asciidoc-pygments.css" |prepend: site.baseurl }}">
----

To disable this feature, either set the `pygments-css` to `style` (to enable
inline styles) or unset the `pygments-stylesheet` attribute in your site's
site config file `_config.yml`.

NOTE: It may still be necessary to make some tweaks to your site's stylesheet
to accomodate this integration.

=== Font-based Admonition and Inline Icons

To enable font-based admonition and inline icons, you first need to add Font Awesome to *_includes/head.html* file under the asciidoc.css declaration:

[source,html]
----
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
----

NOTE: You can also link to a local copy of Font Awesome.

Next, you need to add the following CSS rules from the default Asciidoctor
stylesheet to the *css/asciidoc.css* file:

[source,css]
----
span.icon>.fa {
  cursor: default;
}
.admonitionblock td.icon {
  text-align: center;
  width: 80px;
}
.admonitionblock td.icon [class^="fa icon-"] {
  font-size: 2.5em;
  text-shadow: 1px 1px 2px rgba(0,0,0,.5);
  cursor: default;
}
.admonitionblock td.icon .icon-note:before {
  content: "\f05a";
  color: #19407c;
}
.admonitionblock td.icon .icon-tip:before {
  content: "\f0eb";
  text-shadow: 1px 1px 2px rgba(155,155,0,.8);
  color: #111;
}
.admonitionblock td.icon .icon-warning:before {
  content: "\f071";
  color: #bf6900;
}
.admonitionblock td.icon .icon-caution:before {
  content: "\f06d";
  color: #bf3400;
}
.admonitionblock td.icon .icon-important:before {
  content: "\f06a";
  color: #bf0000;
}
----

Feel free to modify the CSS to your liking.

Finally, you need to enable the font-based icons in the header of
the document:

[source, asciidoc]
----
:icons:           font
----

or in the site configuration:

[source, yaml]
----
asciidoctor:
  attributes:
    - icons=font
    ...
----

=== Image-based Admonition and Inline Icons

As an alternative to **font-based** icons, you can configure Asciidoctor to
use **image-based** icons In this case, all you need to do is provide the
icons at the proper location.

First, enable image-based icons and configure the path to the icons in
the header of the document:

[source, asciidoc]
----
:icons:
:iconsdir:        /images/icons
----

or your site configuration:

[source, yaml]
----
asciidoctor:
  attributes:
    - icons
    - iconsdir=/images/icons
----

Then, simply put the icon images that the page needs in the *images/icons* directory.
