=== Hash

lightGallery hash plugin lets you provide custom unique URLs for each
gallery image. This link can be used to share media anywhere on the web.
It allows you to navigate to different slides via browser back/forward
buttons too.

[NOTE]
====
You need to include Hash plugin in the document to
use the following options.
====


===== customSlideName

Custom slide name to use in the url when hash plugin is enabled.

boolean +
false



==== galleryId

Unique id for each gallery.

It is mandatory when you use hash plugin for multiple galleries on the
same page.

string +
"1"


==== hash

Enable/Disable hash option.

boolean +
true



=== Autoplay

lightGallery autoplay plugin supports automatic slideshow which can be
stopped on the first user action. It supports progress bar that
indicates the duration of the current slide.

[NOTE]
====
You need to include Autoplay plugin in the document to
use the following options.
====

==== appendAutoplayControlsTo

Specify where the autoplay controls should be appended.

string +
".lg-toolbar"


==== autoplay

Enable autoplay plugin.

boolean +
true

==== autoplayControls

Show/hide autoplay controls.

boolean +
true


==== autoplayPluginStrings

Custom translation strings for aria-labels.

Type:     AutoplayStrings
Default: {toggleAutoplay: 'Toggle Autoplay'} as AutoplayStrings

Custom translation strings for aria-labels.


==== forceSlideShowAutoplay

If false autoplay will be stopped after first user action.

boolean +
false


==== progressBar

Show autoplay progressBar.

boolean +
true


==== slideShowAutoplay

Enable slideshow autoplay.

boolean +
false


==== slideShowInterval

The time (in ms) between each auto transition.

number +
5000


=== Rotate plugin

Rotate plugin support features like rotate clockwise, rotate
anticlockwise, flip horizontal, flip vertical with single click.

[NOTE]
====
You need to include Rotate plugin in the document to
use the following options.
====


==== flipHorizontal

Enable flip horizontal.

boolean +
true


==== flipVertical

Enable flip vertical.

boolean +
true



==== rotate

Enable/Disable rotate option.

boolean +
true


==== rotateLeft

Enable rotate left.

boolean +
true


==== rotatePluginStrings

Custom translation strings for aria-labels.

Type:     RotateStrings
Default:  {
            flipVertical: 'Flip vertical',
            flipHorizontal: 'Flip horizontal',
            rotateLeft: 'Rotate left',
            rotateRight: 'Rotate right'} as RotateStrings



==== rotateRight

Enable rotate right.

boolean +
true

==== rotateSpeed

Rotate speed in milliseconds.

number +
400



=== Share

lightGallery share plugin allows you to share your images/videos to
social media platforms such as Twitter or Facebook with unique url. It
supports adding your own social share button too.

[NOTE]
====
You need to include Share plugin in the document to
use the following options.
====

==== additionalShareOptions

Array of additional share options. This can be used to build additional
share options.

Type:     Array +
Default:  []


==== facebook

Enable Facebook share.

boolean +
true


==== facebookDropdownText

Facebook dropdown text.

string +
"Facebook"



==== pinterest

Enable pinterest share.

boolean +
true


==== pinterestDropdownText

Pinterest dropdown text.

string +
"Pinterest"


==== share

Enable/Disable share options.

boolean +
true

Enable/Disable share options.


==== sharePluginStrings

Custom translation strings for aria-labels.

Type:     ShareStrings
Default:  {share: 'Share'} as ShareStrings



==== twitter

Enable twitter share.

boolean +
true


==== twitterDropdownText

Twitter dropdown text.

string +
"Twitter"



=== Pager plugin

If you prefer minimal layouts, you can opt pagers plugin instead of
thumbnails using the pager plugin. Pagers create minimal graphics that
represent each slide, and hovering over each pager item, shows the
correspondent thumbnails.

[NOTE]
====
You need to include Pager plugin in the document to
use the following options.
====

==== pager

Enable/Disable pager option.

boolean +
true


=== FullScreen plugin

lightGallery Fullscreen plugin supports native HTML5 fullscreen feature
in the gallery. you can toggle fullscreen with one click

[NOTE]
====
You need to include FullScreen plugin in the document to
use the following options.
====

==== fullScreen

Enable/Disable fullscreen option.

boolean +
true


==== fullscreenPluginStrings

Custom translation strings for aria-labels.

Type:     FullscreenStrings
Default:  {toggleFullscreen: 'Toggle Fullscreen'} as FullscreenStrings


==== Comment Box

Comment plugin supports FaceBook and Disqus comments out of the box.
Allows people to comment on slides using their Facebook or Disqus
accounts. You can easily add your own comment widget as well.

[NOTE]
====
You need to include Comment box plugin in the document to
use the following options.
====


==== commentBox

Enable comment box.

boolean +
false


==== commentPluginStrings

Custom translation strings for aria-labels.

Type:      CommentStrings
Default:  {toggleComments: 'Toggle Comments'} as CommentStrings

==== commentsMarkup

Facebook comments default markup.

Type:     string
Default:  "<div id="lg-comment-box" class="lg-comment-box lg-fb-comment-box"><div
class="lg-comment-header"><h3 class="lg-comment-title">Leave a
comment.</h3><span class="lg-comment-close lg-icon"></span></div><div
class="lg-comment-body"></div></div>"


==== disqusComments

Enable disqus comment box.

boolean +
false


==== disqusConfig

Disqus comment config.

boolean +
false

==== fbComments

boolean +
false

Enable facebook comment box


=== MediumZoom

MediumZoom plugin helps you create similar zooming experience as seen on
medium. This is a very basic plugin created just to demonstrate the
customizability of lightGallery.


[NOTE]
====
You need to include  Medium zoom plugin in the document to
use the following options.
====

==== backgroundColor

Background color for the gallery This can be overwritten by passing
background color via `lg-background-color` for each item.

string +
"#000"


==== margin

Space between the gallery outer area and images.

number +
40

==== mediumZoom

Enable/Disable medium like zoom experience.

boolean +
true



=== Vimeo Thumbnails

Vimeo thumbnails plugin helps you load thumbnails automatically for
Vimeo videos. [.badge .rounded-pill .bg-danger .font-12]#v2.5.0#

[NOTE]
====
You need to include Vimeo Thumbnails plugin in the document to
use the following options.
====

==== showThumbnailWithPlayButton

Show thumbnails with play button.

boolean +
false


==== showVimeoThumbnails

Auto load thumbnails for Vimeo videos

boolean +
true
