---
title:                                  Geolocation
title_extention:                        Detect Geolocation
tagline:                                Geolocation Preview

date:                                   2024-02-16
#last_modified:                         2024-01-01

description: >
                                        The Geolocation API is used to retrieve the user's location,
                                        so that it can for example be used to display their position
                                        using a mapping API.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        Internet, Geolocation, API

categories:                             [ Previewer ]
tags:                                   [ Module, Geolocation, API ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/markus-spiske.jpg
  width:                                1920
  height:                               1280

compress:                               false
regenerate:                             false
personalization:                        true
permalink:                              /pages/public/tools/previewer/geolocation/

resources:                              [
                                          animate,
                                          clipboard, rouge
                                        ]
resource_options:
  - attic:
      filters:
        grayscale:                      1
        contrast:                       1
        brightness:                     0.8
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/markus-spiske.jpg
          alt:                          Photo by Markus Spiske on Unsplash
          badge:
            type:                       unsplash
            author:                     Markus Spiske
            href:                       //unsplash.com/@markusspiske
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The link://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API[Geolocation API, {browser-window--new}]
is used to retrieve the user's location so that it can
be used to display their position using a mapping service.

Google Maps provides detailed and interactive maps of locations around the
world. Users can view maps at different zoom levels, switch between map view,
satellite view, and street view, and easily explore various places.

[role="mt-4 mb-4"]
[CAUTION]
====
If you're use a VPN to hide your real IP address, retrieving the location
using the Geolocation API *may fail* or took *longer as expected*.
====

Find your location using the Geolocation API by clicking the below button
*SHOW MY LOCATION*.

++++
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>

<button id="find-me" class="btn btn-primary" type="button">
  <i class="mdib mdib-google-maps mdib-1x mr-2"></i>
  Show my location
</button>
<br>
<p id="status"></p>

<div id="tableContainer" class="mt-4 mb-4" ></div>
<a id="map-link" target="_blank" style="display: none"></a>

<style>
    table {
      border-collapse: collapse;
      width: 100%;
    }
    th, td {
      border: 1px solid black;
      padding: 8px;
      text-align: left;
    }
    th {
      background-color: #f2f2f2;
    }
  </style>

<script>

  // Function to convert object to HTML table
  function objectToTable(obj) {
    let tableHtml = '<table>';
    for (let key in obj) {
      if (obj.hasOwnProperty(key)) {
        tableHtml += '<tr>';
        tableHtml += `<th>${key}</th>`;
        tableHtml += `<td>${obj[key]}</td>`;
        tableHtml += '</tr>';
      }
    }
    tableHtml += '</table>';
    return tableHtml;
  }

  function locatePosition(position) {
    const latitude  = position.coords.latitude;
    const longitude = position.coords.longitude;

    // Reverse geocode to find the country
    fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${latitude}&lon=${longitude}`)
      .then(response => response.json())
      .then(data => {
          const country = data.address.country;
          document.getElementById('tableContainer').innerHTML = objectToTable(data.address);
          $('#map-link').show();
      })
      .catch(error => {
          console.error('Error:', error);
      });
  }

  function geoFindMe() {
    const status = document.querySelector("#status");
    const mapLink = document.querySelector("#map-link");

    mapLink.href = "";
    mapLink.textContent = "";

    function success(position) {
      const latitude = position.coords.latitude;
      const longitude = position.coords.longitude;

      status.textContent  = "";
//    mapLink.href        = `https://www.openstreetmap.org/#map=18/${latitude}/${longitude}`;
//    mapLink.href        = `https://www.google.com/maps?q=" + ${latitude}, ${longitude}`;
      mapLink.href        = `https://www.google.com/maps?q=${latitude},${longitude}`;
      mapLink.textContent = `Google Maps: Latitude: ${latitude} °, Longitude: ${longitude} °`;

      locatePosition(position);
    }

    function error() {
      status.textContent = "Unable to retrieve your location";
    }

    if (!navigator.geolocation) {
      status.textContent = "Geolocation is not supported by your browser";
    } else {
      status.textContent = "Locating ...";
      navigator.geolocation.getCurrentPosition(success, error);
    }
  }

  document.querySelector("#find-me").addEventListener("click", geoFindMe);

</script>
++++
