---
title:                                  Justified Gallery
title_extention:                        Preview supported Galleries
tagline:                                Preview supported Galleries

date:                                   2023-10-18
#last_modified:                         2023-01-01

description: >
                                        J1 Template support valuable features to manage your image-based
                                        content using lightboxes, carousels, sliders, and galleries.
                                        The image modules of J1 Template offer a wide range of complex
                                        functionality based on powerful OpenSource libraries like
                                        Lightbox2, Master Slider, lightGallery, or Justified Gallery
                                        for high-end, masonry-styled preview maps.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        image, lightbox, carousel, slider, gallery,
                                        lightbox2, master slider, lightgallery, justifiedgallery

categories:                             [ Previewer ]
tags:                                   [ Module, Justified-Gallery ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/quino-al-2.jpg
  width:                                1920
  height:                               1280

regenerate:                             false
permalink:                              /pages/public/tools/previewer/justfiedgallery/

resources:                              [
                                          animate, clipboard,
                                          justifiedgallery, lightbox, lightgallery,
                                          rouge, videojs
                                        ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/quino-al-2.jpg
          alt:                          Photo by Quino Al Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Quino Al Angel
            href:                       https://unsplash.com/@quinoal
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-lightbox2--home:                   https://lokeshdhakar.com/projects/lightbox2/
:url-lightbox2--github:                 https://github.com/lokesh/lightbox2/

:url-justified-gallery--home:           https://miromannino.github.io/Justified-Gallery/
:url-justified-gallery--github:         https://github.com/miromannino/Justified-Gallery/

:url-j1-docs--carousel-module:          https://jekyll.one/pages/public/manuals/modules/carousel/
:url-j1-docs--lightbox-module:          https://jekyll.one/pages/public/manuals/modules/lightbox/
:url-j1-docs--masterslider-module:      https://jekyll.one/pages/public/manuals/modules/masterslider/

:url-j1-slick-previewer:                https://jekyll.one/pages/public/tools/previewer/slick/
:url-j1-masonry-previewer:              http://localhost:41000/pages/public/tools/previewer/masonry/
:url-j1-masterslider-previewer:         https://jekyll.one/pages/public/tools/previewer/masterslider/
:url-j1-lightGallery-previewer:         http://localhost:41000/pages/public/tools/previewer/lightgallery/

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Welcome to the preview page focussing on image modules. This page shows
all of the powerful features of the J1 Template to manage your image-based
content using lightboxes and galleries.

Justified Gallery uses a so-called masonry grid layout. It works by placing
elements in an optimal position based on available horizontal and vertical
space. Sort of like mason fitting stones in a wall. You'll have seen it already
in use all over the Internet, for sure.

mdi:clock-time-five-outline[24px, md-gray mt-4 mr-2]
*15-30 Minutes* to read

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Image Galleries

Pictures you've made are typically not even in size. Images may have the
same size (resolution), but some are orientated landscapes, or others
may be portraits. For that reason, a more powerful gallery is needed to create
so-called justified views.

.Old Times
gallery::jg_old_times[]

.Justified Gallery of Images + lightGallery
gallery::jg_mega_cities[]


[role="mt-5"]
== Video Galleries

Video galleries are collections or displays of videos organized in a
specific manner, typically on a website or within a software application.
Galleries of videos are commonly used for various purposes, such as showcasing
videos, organizing content, or providing a visually appealing way to present
video content to an audience.

.Carpool Karoke
gallery::jg_video_online_youtube[]

.HTML4 Video
gallery::jg_video_html5[role="mb-4"]
