---
title:                                  J1 Masonry
title_extention:                        Preview the Masonry module of J1 Template
tagline:                                Preview Masonry Grids

date:                                   2020-11-03
#last_modified:                         2023-01-01

description: >
                                        J1 Template implements a masonry module based on the Javascript
                                        library "Masonry", a popular grid layout API developed by
                                        David DeSandro. The masonry or the Pinterest-style layout is a
                                        popular choice to dispay images of varying sizes.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        masonry, pinterest, grid layout

categories:                             [ Previewer ]
tags:                                   [ Masonry, Module ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/hayden-mills-2.jpg
  width:                                1920
  height:                               1280

tts:                                    true
comments:                               false
regenerate:                             false
permalink:                              /pages/public/tools/previewer/masonry/

resources:                              [
                                          advertising, animate, clipboard, justifiedgallery,
                                          lightbox, lightgallery, masonry,
                                          rouge, slick
                                        ]
resource_options:
  - toccer:
      collapseDepth:                    4
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/hayden-mills-2.jpg
          alt:                          Photo by Hayden Mills on Unsplash
          badge:
            type:                       unsplash
            author:                     Hayden Mills
            href:                       https://unsplash.com/@haydmills
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-roundtrip--present-videos:         /pages/public/learn/roundtrip/present_videos/

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The technical term *Masonry* is used in web development to refer to a *grid*
layout system for arranging elements on a webpage. The masonry layout, also
known as the **Pinterest**-style layout, is a popular choice for displaying
images of varying sizes.

J1 Masonry is based on the popular JavaScript library _Masonry_,  enabling
the creation of responsive, dynamic grid layouts of *groups* of content
elements. It uses a unique algorithm to arrange elements vertically, then
horizontally in a grid. The result is a visually appealing layout that works
well with images and other content like posts ar pages in different sizes.

gad::ad_7522184684["mt-5 mb-5"]

J1 Masonry is easy to use and can be added to a webpage with just a few
lines of configuration. The module provides a flexible configuration to
enabling developers to customize the layout, adjust the column width,
gutter size, and add animations.

mdi:clock-time-five-outline[24px, md-gray mt-4 mr-2]
*15-30 Minutes* to read


// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Grid of Collection

The J1 Masonry module create a *collection grid* by pulling articles from
a specific Jekyll collection. The grid display all *articles* a collection
contains.

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::collection_biography[]
----

.Configuration settings
[source, yaml, role="noclip mt-4 mb-5"]
----
# ------------------------------------------------------------------------------
# Collection Biography
#
- grid:
  enabled:                          true

  id:                               collection_biography
  type:                             collection
  collection:                       biography
  image_styles:                     img-fluid
  image_height:                     470px
  image_width:                      400px
  preview:                          false
  gutters:                          false

  # ----------------------------------------------------------------------------
  # Masonry options
  #
  options:
    originTop:                      true
    originLeft:                     true
    initLayout:                     true
    percentPosition:                true
----

[role="mb-4"]
Additionally, the article *title* and the first *tag* of an article are
displayed. Masonry grids for the J1 Template can be easily customized in
various ways, such as speed and other options.

.Collection Grid + Gutters
masonry::collection_biography[]


[role="mt-5"]
== Grid of Posts

J1 Masonry *posts grid* pulls content from a specific *category* of posts.
All grids display the post category, the title, the author and date. All
grids for the J1 Template can be easily customized in various ways, such
as changing the number of posts displayed, the speed, and other options.

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::post_series_example[]
----

.Configuration settings
[source, yaml, role="noclip mt-4 mb-5"]
----
# ------------------------------------------------------------------------------
# Post Series
#
- grid:
  enabled:                          true

  id:                               post_series_example
  type:                             post
  group:                            Jekyll
  image_styles:                     img-fluid
  image_height:                     400px
  gutters:                          true

  # ----------------------------------------------------------------------------
  # Masonry options
  #
  options:
    originTop:                      true
    originLeft:                     true
    initLayout:                     true
    percentPosition:                true

  # ----------------------------------------------------------------------------
  # CSS filter options
  #
  filters:
    enabled:                        true
    grayscale:                      1
    brightness:                     0.4
----

The Masonry Javascript module has become a go-to library for web developers
who need to create dynamic grid layouts, especially for websites that showcase
many images or other visual content like post series for example.

[role="mb-5"]
[NOTE]
====
The J1 Masonry module supports a series of posts out of the box. If the
grid type of `post-series` is given, all posts of a group (series) are
generated automatically as Bootstrap Cards of type *post*.
====

.Posts Grid + Gutters
masonry::post_series_example[]


[role="mt-5"]
== Grid of Images

J1 Masonry is a great tool to create dynamic image galleries. Image galleries
are popular on many websites, and masonry can be a useful tool for creating
dynamic and visually appealing galleries. By using masonry, you can create a
gallery that displays images of different sizes in an aesthetically pleasing
and functional way.

[role="mt-4"]
=== Bootstrap Cards

Bootstrap cards are a popular component of the Bootstrap front-end framework
that provides a flexible and customizable way to display content on a website.

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::card_example_lb[]
----

.Configuration settings
[source, yaml, role="noclip mt-4 mb-5"]
----
# ------------------------------------------------------------------------------
# Image Cards + Lightbox + Gutters + Captions
#
- grid:
  enabled:                          true

  id:                               card_example
  type:                             card
  image_base_path:                  /assets/images/modules/gallery/mega_cities
  image_styles:                     img-fluid img-object--cover g-height-300
  lightbox:                         true
  gutters:                          true

  # ----------------------------------------------------------------------------
  # Captions
  #
  caption:
    enabled:                        true
    position:                       bottom

  # ----------------------------------------------------------------------------
  # Masonry options
  #
  options:
    originTop:                      true
    originLeft:                     true
    initLayout:                     true
    percentPosition:                true

  # ----------------------------------------------------------------------------
  # Images
  #
  images:

    - image:
      file:                         denys-nevozhai-1_b.jpg
      caption:                      Man posing at the rooftop of Jin Mao Tower Shanghai - China

      ...
----

[role="mb-4"]
A card is a container for content that can be styled and arranged in various
ways to suit the website's needs.

.Image Cards + Gutters + Captions + Lightbox
masonry::card_example_lb[role="mt-4 mb-5"]


[role="mt-5"]
=== Image Grid

The *Image* grid uses all style elements for a grid layout, including a
lightbox.

==== Lightbox V2

The default lightbox *Lightbox V2* supports all images of a grid as a group.
Click on the images in the grid below to see how the lightbox manages the
images of the grid.

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::image_grid_example_lb[]
----

.Configuration settings
[source, yaml, role="noclip mt-4 mb-5"]
----
# --------------------------------------------------------------------------
# Image Grid + Gutters + Captions + Lightbox
#
- grid:
  enabled:                          true

  id:                               image_grid_example_lb
  type:                             image
  gutters:                          3

  image_base_path:                  /assets/images/modules/gallery/mega_cities
  image_styles:                     img-fluid

  # ------------------------------------------------------------------------
  # Lightbox options
  # ------------------------------------------------------------------------
  #
  lightbox:
    enabled:                          true
    type:                             lb                                    # lb | lg

  # ------------------------------------------------------------------------
  # Caption options
  #
  caption:
    enabled:                        true
    position:                       bottom                                  # top|bottom|center

  # ------------------------------------------------------------------------
  # Masonry options
  #
  options:
    originTop:                      true
    originLeft:                     true
    initLayout:                     true
    percentPosition:                true

  # ----------------------------------------------------------------------------
  # Images
  #
  images:

    - image:
      file:                         denys-nevozhai-1_b.jpg
      caption:                      Man posing at the rooftop of Jin Mao Tower Shanghai - China

      ...
----

.Image Grid + Gutters + Captions + Lightbox
masonry::image_grid_example_lb[role="mt-4 mb-5"]

==== lightGallery

Using *lightGallery* for the lightbox on a Masonry grid compared to the
default lightbox, more options are available to manage images. Click on the
images in the grid below to see how lightGallery manages the images of
the grid.

.Asciidoc configuration
[source, config, role="noclip mt-4 mb-4"]
----
masonry::image_grid_example_lg[]
----

.Image Grid + Gutters + Captions + lightGalley
masonry::image_grid_example_lg[role="mt-4 mb-5"]

[role="mt-5"]
== Justified Gallery

As an *alternative* to image grids arranged by *J1 Masonry*, the module
*JustifiedGallery* can also display photos in a masonry-styled gallery.
The module link:{url-justified-gallery--home}[JustifiedGallery, {browser-window--new}]
is a great module to create responsive justified image galleries.

.Masonry Layout of JustifiedGallery
gallery::jg_customizer[]

[role="mt-5"]
Digital image content, pictures or videos, are easy to make. Today, every
mobile has a camera. Presenting a bunch of photos or videos is done very
easily by using *Justified Gallery*. Videos created by a digicam or a mobile
can be played by J1 Template using the HTML5 Video support. Present videos
you have made at it’s best.

Find more on how to present video content using *JustifiedGallery* on the example
page link:{url-roundtrip--present-videos}[Present Videos, {browser-window--new}].
