---
title:                                  Rouge
tagline:                                Highlighter Themes
date:                                   2022-12-08 00:00:00
description: >
                                        Rouge is a pure Ruby library for syntax highlighting
                                        and is fully supported by Jekyll. The library is
                                        integrated with the J1 Theme and supports 100+ script
                                        and programming languages. Multiple styles are available
                                        to customize the highlighter Rouge for light or dark
                                        J1 Themes.

categories:                             [ Previewer ]
tags:                                   [ Highlighter, Rouge ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/mohammad-rahmani.jpg
  width:                                1920
  height:                               1280
  alt:                                  Photo by Mohammad Rahmani on Unsplash

regenerate:                             false
permalink:                              /pages/public/tools/previewer/rouge/

resources:                              [ animate, clipboard, comments, rouge ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/mohammad-rahmani.jpg
          alt:                          Photo by Mohammad Rahmani on Unsplash
          badge:
            type:                       unsplash
            author:                     Mohammad Rahmani
            href:                       https://unsplash.com/de/@afgprogrammer
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
// :source-highlighter: rouge
// https://dzone.com/articles/awesome-asciidoctor-highlight-lines-in-source-code
//
:rouge-line-class: line
:rouge-line-id: X%i


//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Rouge is a pure Ruby library for syntax highlighting and is fully supported
by Jekyll. The library is integrated with the J1 Theme and supports 100+
script and programming languages. Multiple styles are available to customize
the highlighter for light or dark J1 Themes.

// gad::ad_7522184684["mt-6 mb-6"]

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Rouge is a native Ruby themeable syntax highlighter fully integrated width J1
Template. The highlighter supports 100+ different languages and generates HTML
output using standard ANSI 256-colors displayed by all current browsers.

Find available themes for selected languages to see how highlighting works
using Rouge.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-4"]
== Select a Theme

For the default themes `Uno` of J1 Template, the following _Rouge_ themes
are used:

* theme_light: based on theme `igorpro`
* theme_dark:  based on theme `monokai.sublime`

The *default* themes used for the J1 Template can be configured with
the global *template config* file `~/_data/j1_config.yml`.

[source, yaml]
----
# ------------------------------------------------------------------------------
# HIGHLIGHTERs
#
rouge:

  theme_light:                          uno.light
  theme_dark:                           uno.dark
----

To preview *all* themes supported by *J1 Template*, make your selection
from the button *AVAILABLE THEMES* below.

++++
<div class="btn-group">
  <!-- See: https://stackoverflow.com/questions/47242702/force-bootstrap-dropdown-menu-to-always-display-at-the-bottom-and-allow-it-go-of -->
  <!-- NOTE: control the behaviour of popper.js for positioning -->
  <!-- NOTE: set attribute data-flip="false" to open the SELECT list at the BOTTOM of the BUTTON -->
  <button
    class="btn btn-flex btn-lg btn-info dropdown-toggle mt-2 mb-4"
    data-flip="false" type="button"
    data-bs-toggle="dropdown"
    data-bs-target="#navbarDropdown"
    aria-haspopup="true"
    aria-expanded="false">
    Available Themes <span class="ml-2 caret"></span>
  </button>

  <ul class="dropdown-menu scrollable-menu" role="menu">
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('base16')">                 <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>base16</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('base16.dark')">            <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>base16.dark</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('base16.light')">           <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>base16.light</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('base16.monokai')">         <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>base16.monokai</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('base16.monokai.dark')">    <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>base16.monokai.dark</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('base16.monokai.light')">   <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>base16.monokai.light</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('base16.solarized')">       <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>base16.solarized</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('base16.solarized.dark')">  <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>base16.solarized.dark</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('base16.solarized.light')"> <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>base16.solarized.light</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('colorful')">               <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>colorful</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('github')">                 <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>github</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('gruvbox')">                <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>gruvbox</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('gruvbox.light')">          <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>gruvbox.light</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('igorpro')">                <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>igorpro</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('molokai')">                <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>molokai</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('monokai')">                <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>monokai</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('monokai.sublime')">        <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>monokai.sublime</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('pastie')">                 <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>pastie</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('thankful_eyes')">          <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>thankful_eyes</a></li>
    <li><a class="dropdown-item" onclick="j1.adapter.rouge.reaplyStyles('tulip')">                  <i class="mdib mdib-view-quilt mdib-18px mr-2" style="color: #9E9E9E"></i>tulip</a></li>
  </ul>
</div>
<div id="selected" class="mt-1 mb-3"></div>
++++

=== Language examples

Find a selected number languages (code blocks) and their highlightning using
a selected theme.

include::{documentdir}/rouge/100_language_examples.asciidoc[]

== Rouge attributes

You can further customize the source block output with additional Rouge
attributes.

include::{tabledir}/rouge/200_rouge_attributes.asciidoc[]

== Supported languages

Here the list of the (current of Feb, 2022) supported languages and lexers
(language highlighters).

include::{tabledir}/rouge/300_supported_languages.asciidoc[]
