---
title:                                  Video
title_extention:                        Playing HTML5 Video using J1 Template
tagline:                                Playing HTML5 Video

date:                                   2020-11-04
#last_modified:                         2023-01-01

description: >
                                        The J1 Template support playing video on web pages
                                        by HTML5 Video, the new standard of HTML to show
                                        videos on web pages.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        html, html5, video, support,
                                        flash player, quicktime, silverlight, videojs

categories:                             [ Roundtrip ]
tags:                                   [ Module, Video ]

image:
  path:                                 /assets/images/icons/videojs/videojs-poster.png
  width:                                1920
  height:                               1280

regenerate:                             false
personalization:                        true
permalink:                              /pages/public/tools/previewer/videojs/

resources:                              [
                                          animate,
                                          lightGallery, justifiedGallery,
                                          video_js
                                        ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/icons/videojs/videojs-poster.png
          alt:                           Poster
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The J1 Template support playing video on web pages by HTML5 Video, the new
standard of HTML to show videos on webpages.

HTML5 Video opens the doors to your way of presenting video content. All
modern browsers support the video tag `<video>` for the HTML5. Browsers have
a built-in multimedia framework already for decoding and displaying video
content. No need to use such proprietary software components anymore.

mdi:clock-time-five-outline[24px, md-gray mt-4 mb-5 mr-2]
*15-30 Minutes* to read

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== VideoJS Player

If you like *one* HTML5 video player for *all* of your video content,
_VideoJS_ is a good choice. Based on the video tag `<video>` for HTML5,
several plugins are available to be used for playing videos from the:

* _Vimeo_ Video platform
* _Dailymotion_ Video platform
* _YouTube_ Video platform
* Videos available *locally* on the Web Server

[role="mt-5"]
=== Embed YouTube Video
// See: https://www.tutorialspoint.com/how-to-play-youtube-videos-using-video-js-player

YouTube is a popular online video-sharing platform that allows users to
upload, view, share, and comment on videos. It was created in February 2005
and acquired by Google in November 2006. YouTube provides a platform for
people and organizations to publish various video content.

[role="mb-4"]
YouTube has become a significant part of internet culture and a valuable
platform for content creators and viewers. It offers various features and
tools to help content creators build their audiences and monetize their
content through advertising, memberships, merchandise sales, and more.

[NOTE]
====
The YouTube plugin used is in the latest version of *2023*. The player
used is automatically detected and loaded by the YouTube platform.
====

Find the following example Adele and James Cordon get emotional reflecting
about their friendship and the times they've been there for each other.

.YouTube Video
youtube::nV8UZJNBY6Y[poster="/assets/videos/gallery/video_adele_last_carpool_caraoke_poster.jpg" role="mt-4 mb-4"]

/////
[role="mt-4"]
More than 8 years after our premiere, we say goodbye to The Late Late Show
with James Corden in our final episode with guests Harry Styles and Will
Ferrell.

Please enjoy in full and thank you for sharing in so many memories with us.

++++
<div class="gallery-title">Last Late Late Show</div>
<video
  id="videojs_youtube_james"
  class="video-js vjs-theme-uno"
  controls
  width="640" height="360"
  poster="/assets/videos/gallery/video_james_carpool_caraoke_poster.jpg"
  data-setup='{
    "techOrder": [
      "youtube", "html5"
    ],
    "sources": [{
      "type": "video/youtube",
      "src": "//youtube.com/watch?v=AeEYQ62t8hA"
    }],
    "controlBar": {
      "pictureInPictureToggle": false
    }
  }'
>
</video>
++++
/////

[role="mt-5"]
=== Embed Vimeo Video

Vimeo is an online video-sharing platform that allows users to upload,
share, and view videos. It was founded in 2004 by a group of filmmakers
and has since grown into a popular platform for individuals and businesses
to showcase their videos. Vimeo is known for its emphasis on high-quality
video content, creative expression, and a supportive community of creators.

[role="mb-4"]
Vimeo is often compared to other video-sharing platforms like YouTube.
While YouTube focuses on a wide range of user-generated content and has
a larger audience, Vimeo focuses on high-quality and often professional
video. It has gained popularity among filmmakers, artists, and businesses
looking for a platform to showcase their work with a more
creative and controlled approach to sharing videos.

[NOTE]
====
The Vimeo plugin using the Vimeo Player *v2.20.1* version of March 2023.
====

[CAUTION]
====
For the Vimeo plugin *no* VideoJS themes are available. The plugin is
using the *original* skin of the Vimeo Player to control the player.
====

.Vimeo Video
vimeo::179528528[role="mt-5 mb-4"]

// ++++
//   <div class="gallery-title">Vimeo Video</div>
//   <video
//     id="videojs_vimeo"
//     class="video-js vjs-theme-uno"
//     width="640" height="360"
//     controls
//     data-setup='{
//       "techOrder": [
//         "vimeo", "html5"
//       ],
//       "sources": [{
//         "type": "video/vimeo",
//         "src": "//vimeo.com/179528528"
//       }],
//       "controlBar": {
//         "pictureInPictureToggle": false
//       }
//     }'
//   ></video>
// ++++

[role="mt-5"]
=== Embed Dailymotion Video

link:{url-dailymotion--home}[Dailymotion, {browser-window--new}] is a
French video-sharing technology platform primarily owned by
link:{url-vivendi--home}[Vivendi, {browser-window--new}]. The platform is
available worldwide in 183 languages and 43 localised versions featuring local
home pages and local content.

[role="mb-4"]
The platform is a monetization solution that allows to directly
connect to high-quality advertisers through a proprietary Advertising system.
Like YouTube, videos can be watched for free, but ads are shown on each and
every video.

[NOTE]
====
The Dailymotion plugin using the Dailymotion *SDK* in the last version of
October 2022.
====

.Dailymotion Video
dailymotion::x87ycik[role="mt-5 mb-4"]

// ++++
// <div class="gallery-title">Dailymotion Video</div>
// <video
//   id="videojs_dailymotion"
//   class="video-js vjs-theme-uno"
//   controls
//   width="640" height="360"
//   data-setup='{
//     "techOrder": [
//       "dailymotion", "html5"
//     ],
//     "sources": [{
//       "type": "video/dailymotion",
//       "src": "//dailymotion.com/video/x87ycik"
//     }],
//     "controlBar": {
//       "pictureInPictureToggle": false
//     }
//   }'
// ></video>
// ++++

[role="mt-5"]
=== Embed Local Video

Digital image content, simple pictures or videos, are easy to make. Today,
every mobile has a camera. Presenting a bunch of pictures is done very easily
by using *VideoJS*.

.Local Video
video::/assets/videos/gallery/html5/video1.mp4[poster="/assets/videos/gallery/video1-poster.jpg" role="mt-4 mb-5"]


[role="mt-5"]
== Video Galleries

Video galleries are collections or displays of videos organized in a
specific manner, typically on a website or within a software application.
Galleries of videos are commonly used for various purposes, such as showcasing
videos, organizing content, or providing a visually appealing way to present
video content to an audience.

[role="mb-4"]
Here are some key characteristics and uses of video galleries.

Organized Display::
Video galleries are designed to present videos in an organized and visually
appealing manner. They often include thumbnails, titles, and descriptions
to help users browse and select the videos they want to watch.

Categorization:: Videos in a gallery can be categorized or grouped based on
specific criteria, such as topic, date, genre, or any other relevant
classification. Categorization makes it easier for users to find the videos
they are interested in.

User-Friendly Navigation::
Video galleries typically include navigation features like pagination, search
functionality, filters, and sorting options to enhance the user experience
and make it easier to explore the video content.

Embedding::
Video galleries can be embedded on websites or integrated into web
applications. Embedding allows content creators to showcase their videos
to a wider audience while maintaining control over the presentation.

Responsive Design::
Many modern video galleries are designed to be responsive, meaning they
adapt to different screen sizes and devices. Responsiveness ensures that
the gallery remains user-friendly on desktop computers and mobile devices.

Customization::
Depending on the platform or software used, video galleries can often be
customized in terms of appearance, layout, and functionality to match the
branding or style of a website or application.

Playback Options::
Video galleries typically provide playback options, such as play, pause,
volume control, and fullscreen mode, to give users control over their
viewing experience.

Analytics::
Some video gallery platforms offer tools to track viewer engagement and
gather insights into how users interact with the videos.

Social Sharing::
Integration with social media platforms and sharing options are common in
video galleries, allowing users to share videos with their networks easily.

Security and Privacy::
Depending on the context, video galleries may include security features to
protect the content from unauthorized access and privacy settings to control
who can view the videos.

Video galleries are widely used in various industries, including entertainment,
education, e-commerce, and marketing. They provide a versatile way to present
video content and engage with an audience online.


[role="mt-5"]
=== YouTube Gallery

The community at link:{url-youtube--home}[YouTube, {browser-window--new}] is
large, with over 1 billion users that watch hundreds of millions of hours of
content every day. The number of channels on YouTube is enormous. For TV
Stations, it's a must to publish videos of their shows on YouTube. Find below
a real classic channel *Carpool Karaoke* presented by the frontman _James Corden_
of *The Late Late Show* at CBS, Los Angeles.

.James Cordon and Adele
gallery::jg_video_online_youtube_james_and_adele[role="mt-4 mb-5"]


[role="mt-5"]
=== Vimeo Gallery

Vimeo does offer a basic, free membership, but it limits you to 500MB maximum
storage per week. Alternately, you can book on paid plans: Plus, PRO, Business.
Each membership has varied storage limits, but the free plan offers sufficient
space for private projects to present video content without advertising.

.Fashion
gallery::jg_video_online_vimeo[role="mt-4 mb-5"]


[role="mt-5"]
=== DailyMotion Gallery

Dailymotion allows users to search videos by *tags*, topic *channels*, or
user-created *groups*. Users can upload videos of up to 2 gigabytes and a
length of 60 minutes. If a user is a MotionMaker or MotionPartner, a program
for particularly creative users or partners, they can upload videos of
unlimited length.

.SELF Magazine
gallery::jg_video_online_dailymotion[role="mt-4 mb-5"]


[role="mt-5"]
=== Local Video Gallery

The HTML5 specification does *not* define which video and audio formats
browsers *should* support. J1 LightGallery can play all types of standard
HTML5 Video formats on modern browsers today like MP4, WebM, or Ogg.

.Local MP4 Video
gallery::jg_video_html5[role="mb-5 mb-7"]
