---
title:                                  Image Placeholders
tagline:                                Preview
date:                                   2023-04-10 00:00:00
description: >
                                        Image placeholders are important for designers and developers
                                        as they allow them to create and test the layout and functionality
                                        of a website or application before the final content is available.

categories:                             [ Previewer ]
tags:                                   [ Placeholder, Image, Design, Resource ]

regenerate:                             false
permalink:                              /pages/public/tools/previewer/image_placeholder/

resources:                              [ clipboard, lightbox, rouge, slick ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/kelly-sikkemal.jpg
          alt:                          Photo by Kelly Sikkema on Unsplash
          badge:
            type:                       unsplash
            author:                     Kelly Sikkema
            href:                       https://unsplash.com/de/@kellysikkema
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Find an [example lightbox](https://codepen.io/mreq/pen/KgQrQa) on Codepen.

[role="dropcap"]
Image placeholders are temporary images used to represent visual content
that is not yet available or finalized. They are often used as a substitute
for actual images during a website or application's development or design
phase. Placeholder images are typically simple, generic images that can be
easily replaced later with the actual images once they are available.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
== Placekitten.com

_Placekitten.com_ is a website that provides image placeholders of cute
kittens in various sizes and formats. Designer Phil Hawksworth created it
as a fun and quirky alternative to the generic image placeholders commonly
used in web development.

=== HTML code

[source, html]
----
<div id="captions-demo" class="row captions-demo mr-1 ml-1 mb-5">

  <div class="col-lg-4 col-md-6 col-sm-12 col-12 px-1 py-1">
    <a href="https://placekitten.com/1024/768"
       data-caption="Image size 1024x768" target="_blank">
      <img class="img-fluid img-object--cover g-height-300"
           src="https://placekitten.com/1024/768" alt="Image size 1024x768">
    </a>
  </div>

  ...

  <div class="col-lg-4 col-md-6 col-sm-12 col-12 px-1 py-1">
    <a href="https://placekitten.com/1920/1280"
      data-caption="Image size 1920x1280" target="_blank">
      <img class="img-fluid img-object--cover g-height-300"
           src="https://placekitten.com/1920/1280" alt="Image size 1920x1280">
    </a>
  </div>

</div>
----

=== Generated placeholders

Image placeholders are important for designers and developers as they allow
them to create and test the layout and functionality of a website or
application before the final content is available.

++++
<div id="captions-demo" class="row captions-demo mr-1 ml-1 mb-5">
  <div class="col-lg-4 col-md-6 col-sm-12 col-12 px-1 py-1">
    <a href="https://placekitten.com/1024/768" data-caption="Image size 1024x768" target="_blank">
      <img class="img-fluid img-object--cover g-height-300" src="https://placekitten.com/1024/768" alt="Image size 1024x768">
    </a>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-12 col-12 px-1 py-1">
    <a href="https://placekitten.com/1280/1024" data-caption="Image size 1280x1024" target="_blank">
      <img class="img-fluid img-object--cover g-height-300" src="https://placekitten.com/1280/1024" alt="Image size 1280x1024">
    </a>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-12 col-12 px-1 py-1">
    <a href="https://placekitten.com/1920/1280" data-caption="Image size 1920x1280" target="_blank">
      <img class="img-fluid img-object--cover g-height-300" src="https://placekitten.com/1920/1280" alt="Image size 1920x1280">
    </a>
  </div>
</div>

<script>
  $(document).ready(function(){

    $('#captions-demo').slickLightbox({
      caption:      'caption',
      useHistoryApi: true
    });

  });
</script>
++++
