---
title:                                  J1 Paginator
title_extention:                        Page Paginator of Posts for J1 Template
tagline:                                Generate Pages From Posts

date:                                   2022-01-01
#last_modified:                         2023-01-01

description: >
                                        New version of the Pagination Generator for Jekyll (J1 Paginator).
                                        The Generator forms the core of the pagination logic. It is responsible
                                        for reading the posts and collections in your site and split them correctly
                                        across multiple pages according to the supplied configuration. It also
                                        performs the necessary functions to link to the previous and next pages in
                                        the page-sets that it generates.

categories:                             [ Manual ]
tags:                                   [ Jekyll, Paginator, Plugin ]

comments:                               false
fab_menu_id:                            open_toc

image:
  path:                                 /assets/image/module/attic/jeshoots-1-1920x1280.jpg
  width:                                1920
  height:                               1280

tts:                                    true
comments:                               false
regenerate:                             false
permalink:                              /pages/public/manuals/components/j1/plugins/j1_paginator/

resources:                              [ lightbox ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/module/attic/jeshoots-1-1920x1280.jpg
          alt:                          Photo by JESHOOTS.COM on Unsplash
          badge:
            type:                       unsplash
            author:                     JESHOOTS.COM
            href:                       //unsplash.com/@jeshoots
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The *Generator* forms the core of the *pagination logic*. It is responsible
for reading the posts and collections in your site and split them correctly
across multiple pages according to the supplied configuration. It also
performs the necessary functions to link to the previous and next pages in
the page-sets that it generates.

The code was based on the original design of link:{url-github--jekyll-paginate}[Jekyll Paginate, {browser-window--new}]
and features were sourced from discussions such as link:{url-github-issues--jekyll-paginate}[#27, {browser-window--new}]
(thanks link:{url-guenter-kits--home}[Günter Kits, {browser-window--new}]).

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Site configuration

The pagination gem is configured in the site configuration file `_config.yml` by
including the `pagination` configuration element

[source, yaml]
----
#---------------------------------------------------------------------
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
#
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  #
  enabled:        true

  # Set to 'true' to enable pagination debugging. This can be enabled in the
  #site config or only for individual pagination pages
  #
  debug:          false

  # The default document collection to paginate if nothing is specified
  # ('posts' is default)
  #
  collection:     posts

  # How many objects per paginated page, used to be `paginate`
  # (default: 0, means all)
  #
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  # Examples:
  #
  #   # Pages are simple html files
  #   permalink: '/page/:num.html
  #   # Pages are html files, linked jekyll extensionless permalink style.
  #   permalink: '/page/:num'
  #   # Pages are index.html inside this folder (default)
  #   permalink: '/page/:num/'
  #
  permalink:      '/page/:num/'


  # Optional the title format for the paginated pages (supports :title for
  # original page title, :num for pagination page number, :max for total number
  # of pages)
  #
  title:          ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  #
  limit:          0

  # Optional, defines the field that the posts should be sorted on (omit to
  # default to 'date')
  #
  sort_field:     date

  # Optional, sorts the posts in reverse order (omit to default decending or
  # sort_reverse: true)
  #
  sort_reverse:   true

  # Optional, the default category to use, omit or just leave this as 'posts'
  # to get a backwards-compatible behavior (all posts)
  #
  category:       posts

  # Optional, the default tag to use, omit to disable
  #
  tag:            ''

  # Optional, the default locale to use, omit to disable (depends on a field
  # 'locale' to be specified in the posts, in reality this can be any value,
  # suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the
  # ISO-639 language code)
  #
  locale:         ''

  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  #
  trail:
    before:       2
    after:        2
----

Also ensure that you remove the old *jekyll-paginate* gem from your `plugins`
list and add the new one *jekyll-paginate-v2* instead.

[source, yaml]
----
# ---------------------------------------------------------------
# Plugin settings (gem)
#
plugins:
  - jekyll-paginate-v2
----


== Page configuration

To enable pagination on a page then simply include the minimal pagination
configuration in the page front-matter:

[source, yaml]
----
---
layout:           page

pagination:
  enabled:        true
---
----

Then you can use the normal `paginator.posts` logic to iterate through the
posts.

{% raw %}
[source, liquid]
----
{% for post in paginator.posts %}
  <h1>{{ post.title }}</h1>
{% endfor %}
----
{% endraw %}

And to display pagination links, simply

{% raw %}
[source, liquid]
----
{% if paginator.total_pages > 1 %}
<ul>
  {% if paginator.previous_page %}
  <li>
    <a href="{{ paginator.previous_page_path | prepend: site.baseurl }}">Newer</a>
  </li>
  {% endif %}
  {% if paginator.next_page %}
  <li>
    <a href="{{ paginator.next_page_path | prepend: site.baseurl }}">Older</a>
  </li>
  {% endif %}
</ul>
{% endif %}
----
{% endraw %}

NOTE: All posts that have the `hidden: true` flag set in their front matter
gets *ignored* by the pagination logic of J1 Paginator. Following *fields*
are available on the *paginator object*.

include::{tabledir}/paginator_object_fields.asciidoc[]

The code is fully backwards compatible and you will have access to all the
paginator variables of *Paginator V1* defined in the official
link:{url-jekyll-docs--page-variables}[Jekyll Documentation, {browser-window--new}].

////
Don't delay, go see the link:{url-github--jekyll-paginate-v2-examples}[Examples, {browser-window--new}],
they're way more useful than read-me docs at this point :)
////


== Backwards compatibility

This Gem is fully backwards compatible with the old paginator GEM (V1)
link:{url-github--jekyll-paginate-gem-v1}[jekyll-paginate, {browser-window--new}]
and can be used as a zero-configuration replacement for it. If the old
site config is detected then the gem will fall back to the old logic of
pagination.

NOTE: Beware, you cannot run both the new pagination logic from
jekyll-paginate-v2 gem and the old one (jekyll-paginate gem) at
the same time.

The following `_config.yml` settings are honored when running this gem
in compatability mode

[source, yaml]
----
paginate:         8
paginate_path:    '/legacy/page:num/'
----

See more about the old style of pagination at the page
link:{url-github--jekyll-paginate-gem-v1}[Jekyll paginate, {browser-window--new}].

////
CAUTION: Backwards compatibility with the old jekyll-paginate gem is currently
scheduled to be removed after *1st January 2018*. Users will start receiving
warning log messages when running jekyll *two months before* this date.
////


== Paginating Collections

By default the pagination system only paginates `posts`. If you only have
`posts` and `pages` in your site you don't need to worry about a thing,
everything will work as intended without you configuring anything.

However if you use document collections, or would like to, then this
pagination Gem offers extensive support for paginating documents in one or
more collections at the same time.

NOTE: Collections are groups of documents that belong together but should not
be grouped by date. See more about collections on the blog
link:{url-blog--ben-balter-collections}[Ben Balters, {browser-window--new}].

=== Paginating a single collection

Lets expand on Ben's collection discussion (linked above). Let's say that
you have hundreds of cupcake pages in your cupcake collection. To create a
pagination page for only documents from the cupcake collection you would
do this:

[source, yaml]
----
---
layout:           page
title:            All Cupcakes

pagination:
  enabled:        true
  collection:     cupcakes
---
----

=== Paginating multiple collections

Lets say that you want to create a single pagination page for only small cakes
on your page (you have both cupcakes and cookies to sell). You could do that
like this

[source, yaml]
----
---
layout:           page
title:            Litle bits

pagination:
  enabled:        true
  collection:     cupcakes, cookies
---
----

=== The special `all` collection

Now your site has grown and you have multiple cake collections on it and you
want to have a single page that paginates all of your collections at the same
time. You can use the special `all` collection name for this.

[source, yaml]
----
---
layout:           page
title:            All the Cakes!

pagination:
  enabled:        true
  collection:     all
---
----

NOTE: Due to the `all` keyword being reserved for this feature, you cannot
have a collection called `all` in your site configuration. Sorry.


== Paginate categories, tags, locales

Enabling pagination for specific categories, tags or locales is as simple as
adding values to the pagination page front-matter and corresponding values
in the posts.

=== Filtering categories

Filter single category 'software'

[source, yaml]
----
---
layout:           post

pagination:
  enabled:        true
  category:       software
---
----

Filter multiple categories - lists only posts belonging to all categories.

[source, yaml]
----
pagination:
  enabled:        true
  category:       software, ruby
----

To define categories you can either specify them in the front matter or
through the link:{url-jekyll-docs--page-variables}[page variables, {browser-window--new}]
of your _Jekyll_ site (categories are derived from the directory structure above
the `_posts` directory). You can actually use both approaches to assign
your pages to multiple categories.

=== Filtering tags

Filter on a single tag

[source, yaml]
----
pagination:
  enabled:        true
  tag:            cool
----

Filter on multiple tags

[source, yaml]
----
pagination:
  enabled:        true
  tag:            cool, life
----

When specifying tags in your posts make sure that the values are not enclosed
in single quotes (double quotes are fine). If they are you will get a cryptic
error when generating your site that looks like

[role="text-danger"]
----
Error: could not read file : did not find expected key while parsing a block
mapping at line 2 column 1
----

=== Filtering locales

In the case your site offers multiple languages you can include a `locale`
item in your post front matter. The paginator can then use this value to
filter on. The category page front-matter would look like this:

[source, yaml]
----
pagination:
  enabled:        true
  locale:         en_US
----

Then for the relevant posts, include the `locale` variable in their
front-matter

[source, yaml]
----
locale:           en_US
----


== Paginate on combination of filters

Including only posts from categories `ruby` and `software` written in English
language.

[source, yaml]
----
pagination:
  enabled:        true
  category:       software, ruby
  locale:         en_US, en_GB, en_WW
----

Only showing posts tagged with _cool_ and in category _cars_

[source, yaml]
----
pagination:
  enabled:        true
  category:       cars
  tag:            cool
----

... and so on and so on.


== Configuration overrides

All of the configuration elements from the `_config.yml` file can be
overwritten in the pagination pages. E.g. if you want one category page
to have different permalink structure simply override the item like so

[source, yaml]
----
pagination:
  enabled:        true
  category:       cars
  permalink:      '/cars/:num/'
----

Overriding sorting to sort by the post title in ascending order for another
paginated page could be done like so:

[source, yaml]
----
pagination:
  enabled:        true
  category:       ruby
  sort_field:     title
  sort_reverse:   false
----


== Advanced Sorting

Sorting can be done by any field that is available in the post front-matter.
You can even sort by nested fields. When sorting by *nested fields*, separate
the fields with a colon `:` character.

As an example, assuming all your posts have the following front-matter:

[source, yaml]
----
---
layout: post

author:
  name:
    first:        John
    last:         Smith
  born:           1960
---
----

You can define pagination sorting on the nested `first` field like so:

[source, yaml]
----
---
layout:           page
title:            Authors by first name

pagination:
  enabled:        true
  sort_field:     'author:name:first'
---
----

To sort by the `born` year in decending order (youngest first)

[source, yaml]
----
---
layout:           page
title:            Authors by birth year

pagination:
  enabled:        true
  sort_field:     'author:born'
  sort_reverse:   true
---
----


== Creating Pagination Trails

Creating a trail structure for your pagination as shown above can be achieved
by enabling the `trail` configuration and including a little extra code in
your liquid templates.

[source, yaml]
----
pagination:
  trail:
    before:       2 # The number of links before the current page
    after:        2  # The number of links after the current page
----

Your layout file would then have to include code similar to the following to
generate the correct HTML structure:

{% raw %}
[source, erb]
----
{% if paginator.page_trail %}
  {% for trail in paginator.page_trail %}
    <li {% if page.url == trail.path %}class="selected"{% endif %}>
      <a href="{{ trail.path | prepend: site.baseurl }}" title="{{trail.title}}">
        {{ trail.num }}
      </a>
    </li>
  {% endfor %}
{% endif %}
----
{% endraw %}

See link:{url-github--jekyll-paginate-v2-examples-tags}[example3, {browser-window--new}]
for a demo of a *pagination trail*.

The `trail` object exposes three properties:

* `num`: The number of the page
* `path`: The path to the page
* `title`: The title of the page

The algorithm will always attempt to keep the same trail length for all
pages (`trail length = before + after + 1`). As an example if we have only
7 pagination pages in total and the user is currently on page 6 then the
trail would look like this.

Different number of before and after trail links can be specified. Below is an
example of how the yml config below would look like when on the same page 4:

[source, yaml]
----
pagination:
  trail:
    before:       1
    after:        3
----


== Detecting pagination pages

To identify the auto-generated pages that are created by the pagination logic
when iterating through collections such as `site.pages` the `page.autogen`
variable can be used like this:

{% raw %}
[source, liquid]
----
{% for my_page in site.pages %}
  {% if my_page.title and my_page.autogen == nil %}
    <h1>{{ my_page.title | escape }}</h1>
  {% endif %}
{% endfor %}
----
{% endraw %}

In this example only pages that have a title and are not auto-generated are
included. This variable is created and assigned the value:

----
page.autogen = "jekyll-paginate-v2"
----

by the pagination logic. This way you can detect which pages are auto-generated
and by what gem.

== Formatting page titles

The `title` field in both the site.config and the front-matter configuration
supports the following *macros*.

include::{tabledir}/paginator_object_field_macros.asciidoc[]


== Reading pagination meta data

Each pagination page defines an information structure `pagination_info` that
is available to the liquid templates. This structure contains meta information
for the pagination process, such as current pagination page and the total
number of paginated pages.

The following fields are available:

include::{tabledir}/paginator_object_pagination_info.asciidoc[]

See below an example on how to print out a "Page x of n" in the pagination
layout:

{% raw %}
[source, liquid]
----
<h2>Page {{page.pagination_info.curr_page}} of {{page.pagination_info.total_pages}}</h2>
----
{% endraw %}


/////
== Common issues

Find a collection of common errors along with the messages issued.

=== Dependency error

I keep getting a dependency error when running jekyll serve after
installing this gem:

[role="text-danger"]
----
Dependency Error: Yikes! It looks like you don't have jekyll-paginate-v2
or one of its dependencies installed...
----

Check your `Gemfile` in the site root. Ensure that the gem jekyll-paginate-v2
is present in the jekyll_plugins group like the example below. If this group
is missing add to the file.

[source, ruby]
----
group :jekyll_plugins do
  gem "jekyll-paginate-v2"
end
----

=== Bundler error after upgrading (GemNotFound)

I'm getting a bundler error after upgrading the gem (Bundler::GemNotFound)

[role="text-danger"]
----
bundler/spec_set.rb:95:in `block in materialize': Could not find
jekyll-paginate-v2-1.0.0 in any of the sources (Bundler::GemNotFound)
----

Delete your `Gemfile.lock` file and try again.

=== Bundler error after upgrading (Gem::LoadError)

I'm getting a bundler error after upgrading the gem (Gem::LoadError)

[role="text-danger"]
----
bundler/runtime.rb:40:in 'block in setup': You have already activated
addressable 2.5.0, but your Gemfile requires addressable 2.4.0.
Prepending `bundle exec` to your command may solve this.
(Gem::LoadError)
----

Delete your `Gemfile.lock` file and try again.

=== Pagination pages not found

My pagination pages are not being found. I see something like this: Couldn't
find any pagination page. Skipping pagination.

[role="text-danger"]
----
Pagination: Is enabled, but I couldn't find any pagination page.
Skipping pagination...
----

Ensure that you have the correct minimum front-matter in the pagination pages

[source, yaml]
----
pagination:
  enabled:        true
----

NOTE: You can place pagination logic into either the pages or liquid templates
(templates are stored under the `_layouts/` and `_includes/` folders).

=== Nested multiple levels

My pages are being nested multiple levels deep. When using `categories`
for posts it is advisable to explicitly state a `permalink` structure
in your `_config.yml` file.

----
permalink:        '/:year/:month/:title.html'
----

This is because the default behavior in Jekyll is to *nest pages* for
every category that they belong to and Jekyll unfortunately does not
understand multi-categories separated with `,` or `;` but instead does
all separation on `[space]` only.

=== Pagination pages gets overwritten

My pagination pages are overwriting each others pages. If you specify
multiple pages that paginate in the site root then you must give them
unique and separate pagination permalink. This link is set in the
pagination page front-matter like so

[source, yaml]
----
pagination:
  enabled:        true
  permalink:      '/cars/:num/'
----

Make absolutely sure that your pagination permalink paths do not clash
with any other paths in your final site. For simplicity it is
recommended that you keep all custom pagination (non root index.html) in
a single or multiple separate sub folders under your site root.


== Examples

Here are a few example sites that use the new `jekyll-paginate-v2` Ruy GEM.
They can serve as a help and guide on the nitty gritty details of configuring
the GEM and leveraging its more advanced features.

Please feel free to fork and play around with this code to quickly test
out different scenarios and site structures. All examples are generated from
running the `jekyll new` command and they all use the default *minima*
theme.

/////
