---
title:                                  Tester
tagline:                                SlimSelect Tester
date:                                   2022-12-11 00:00:00 +100
description: >
                                        Welcome to the pages of J1 Theme. If your here
                                        first time, a good decision you get on that page first.
                                        For sure, there is no better place to go.
keywords: >
                                        Jekyll, Theme, step, find, project, roundtrip, trip,

categories:                             [ Info ]
tags:                                   [ Places, Introduction ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/j1-starter-mockup-1.jpg
  width:                                1920
  height:                               1280
  alt:                                  Photo by Alexander Redl on Unsplash

fab_menu_id:                            default

permalink:                              /pages/public/slim_select_tester/
regenerate:                             false

resources:                              [ animate, clipboard, iconpicker, slim_select ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/j1-starter-mockup-1.jpg
          alt:                          Photo by Alexander Redl on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexander Redl
            href:                       https://unsplash.com/@alexanderredl
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-j1-jupyter-notebooks--where-to-go: /pages/public/jupyter/where-to-go/

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="dropcap"]
J1 Theme supports popular icons font sets out-of-the-box. The icon sets
Material Design Icons (MDI) and FontAwesome (FA) are exellent in design
and have a rich set of different icons for many categories used for the Web.

The J1 Icon Picker supports the icons font sets:

* link:{url-mdil--preview}[Material Design Icons (Light),  {browser-window--new}], 260+ icons of version v0.2.63 (Feb 2023)
* link:{url-mdi--preview}[Material Design Icons (Regular), {browser-window--new}], 7200+ icons of version v7.2.96 (March 2023)
* link:{url-fontawesome--free-preview}[FontAwesome Icons,  {browser-window--new}], 2000+ icons of version v6.4.0 (March 2023)

[role="mt-4"]
NOTE: The *free* version of FontAwesome does *not* support the full icon
set available. The commercial Pro version supports *26.000+* icons but
requires a *paid* subscription plan.

Select the icon set from the *dropdown* below. To show the selected icons,
click on the button *Show Icons Selected*.

++++
<div id="icon-library-select-wrapper" class="mt-2 mb-3">
    <select name="select-icon-library">

        <optgroup label="MDI Icons">
            <option value="mdi-icons-base"        data-css="/assets/themes/j1/core/css/icon-fonts/mdib.min.css" selected="selected">MDI Icons Base</option>
            <option value="mdi-icons-light"       data-css="/assets/themes/j1/core/css/icon-fonts/mdil.min.css">MDI Icons Light</option>
            <option value="mdi-icons-regular"     data-css="/assets/themes/j1/core/css/icon-fonts/mdi.min.css">MDI Icons Regular</option>
        </optgroup>

        <optgroup label="Font Awesome">
            <option value="font-awesome"          data-css="/assets/themes/j1/core/css/icon-fonts/fontawesome.min.css">Font Awesome (all)</option>
            <option value="font-awesome-solid"    data-css="/assets/themes/j1/core/css/icon-fonts/fontawesome.min.css">Font Awesome Solid</option>
            <option value="font-awesome-regular"  data-css="/assets/themes/j1/core/css/icon-fonts/fontawesome.min.css">Font Awesome Regular</option>
            <option value="font-awesome-brands"   data-css="/assets/themes/j1/core/css/icon-fonts/fontawesome.min.css">Font Awesome Brands</option>
        </optgroup>

    </select>
</div>

<div class="mt-3 mb-4 d-grid gap-2">
  <a id="icon_picker" href="#"
     class="btn btn-info btn-flex btn-lg"
     aria-label="Icon Picker">
     <i class="mdi mdi-emoticon mdi-2x mr-2"></i>
     Show Icons Selected
  </a>
</div>
++++

++++
<script>
var dependencies_met_page_ready = setInterval (function (options) {
  var pageState   = $('#no_flicker').css("display");
  var pageVisible = (pageState == 'block') ? true : false;

  if (j1.getState() === 'finished' && pageVisible) {
    var dependencies_met_iconpicker_ready = setInterval (function (options) {
      var iconPickerFinished = (j1.adapter.iconPicker.getState() === 'finished') ? true: false;

      if (iconPickerFinished) {
        const $selectElement  = document.querySelector('select[name ="select-icon-library"]');
        const icon_picker     = j1.adapter.iconPicker.icon_picker;
        const selection       = new Event('change');

        new SlimSelect({
          select: 'select[name ="select-icon-library"]',
          settings: {
            showSearch: false,
          }
        });

        $selectElement.addEventListener('change', () => {
            var currentIconLibrary    = $selectElement.value;
            var currentIconLibraryCss = $selectElement.options[$selectElement.selectedIndex].dataset.css;

            icon_picker.setOptions({
              iconLibraries:    [ currentIconLibrary + '.min.json' ],
              iconLibrariesCss: [currentIconLibraryCss]
            });
        });

        $selectElement.dispatchEvent(selection);
        clearInterval(dependencies_met_iconpicker_ready);
      } // END 'iconPickerFinished'
    }, 10);
    clearInterval(dependencies_met_page_ready);
  } // END 'pageVisible'
}, 10);
</script>
++++

[TIP]
====
*Double-click* an icon copies the selected icon (class) data to
the *clipboard*.
====
