---
title:                                  iFramer
title_extention:                        Magic HTML iFrames
tagline:                                Module for J1 Template

date:                                   2022-08-14
#last_modified:                         2023-01-01

description: >
                                        The iframeResizer library enables the automatic resizing of the height
                                        and width of both same and cross domain iFrames to fit their
                                        contained content. It provides a wide range of features to address
                                        the most common issues with using.
keywords: >
                                        Jekyll, JekyllOne, Theme, User Guide, Module, iframeResizer,
                                        Manual

categories:                             [ Manual, Module ]
tags:                                   [ iFramer ]

image:
  path:                                 /assets/image/module/attic/jessica-ruscello-1920x1280.jpg
  width:                                1920
  height:                               1280

tts:                                    true
comments:                               false
regenerate:                             false
permalink:                              /pages/public/manuals/modules/iframer/

resources:                              [ iframer, rouge ]
resource_options:
  - toccer:
      collapseDepth:                    3
  - attic:
      slides:
        - url:                          /assets/image/module/attic/jessica-ruscello-1920x1280.jpg
          alt:                          Photo by Jessica Ruscello Unsplash
          badge:
            type:                       unsplash
            author:                     Jessica Ruscello
            href:                       //unsplash.com/@jruscello
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The iframeResizer library enables automatic resizing for iFrames of the height,
the width or both to fit their contained content on same and cross domain.

The library provides a wide range of features to address the most common
issues using iFrames on webpages which includes:

* Height and width resizing of the iFrame to content size
* Works with multiple and nested iFrames
* Domain authentication for cross domain iFrames
* Provides a range of page size calculation methods to support
  complex CSS layouts
* Detects changes to the DOM that can cause the page to resize using
  MutationObserver
* Detects events that can cause the page to resize (Window Resize,
  CSS Animation and Transition, Orientation Change and Mouse events)
* Simplified messaging between iFrame and host page via postMessage
* Fixes in page links in iFrame and supports links between the iFrame
  and parent page
* Provides custom sizing and scrolling methods
* Exposes parent position and viewport size to the iFrame
* Provides onMouseEnter and onMouseLeave events for the iFrame
* Works with ViewerJS to support PDF and ODF documents

// mdi:clock-time-five-outline[24px, md-gray mt-4 mr-2]
// *45-60 Minutes* to read

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== J1 Integration

include::{documentdir}/j1_integration/integration.asciidoc[]


[role="mt-5"]
== Manual Setup

The package contains two (minified) JavaScript files in the folder
`~/assets/theme/j1/modules/iframeResizer/js`. The JS file `iframeResizer.js`
is for the page hosting the iFrames.

It can be called with via JavaScript:

[source, js]
----
const iframes = iFrameResize( [{options}], [css selector] || [iframe] );
----

The second JS file `client/iframeResizer.contentWindow.js`
needs placing in the page(s) contained within your iFrame. This file is
designed to be a guest on someone else’s system, so has no dependencies
and won’t do anything until it’s activated by a message from the
containing page.

[role="mt-4"]
=== Typical setup

The normal configuration is to have the iFrame resize when the browser
window changes size or the content of the iFrame changes. To set this up
you need to configure one of the dimensions of the iFrame to a
percentage and tell the library to only update the other dimension.
Normally you would set the width to 100% and have the height scale to
fit the content.

[source, html]
----
<style>
  iframe {
    width: 1px;
    min-width: 100%;
  }
</style>

<script src="/assets/theme/j1/modules/iframeResizer/js/iframeResizer.min.js"></script>
<iframe id="myIframe" src="http://anotherdomain.com/iframe.html"></iframe>

<script>
  iFrameResize({
      log: true
    },
    '#myIframe'
  )
</script>
----

[NOTE]
====
Using _min-width_ to set the width of the iFrame, works around
an issue in iOS that can prevent the iFrame from sizing correctly.
====

In case of problems, check the <<Troubleshooting>> section.

[role="mt-5"]
== Parent Page API

IFrame-Resizer provides an extensive range of options and APIs for both
the parent page and the iframed page.

include::{documentdir}/parent_page/options.asciidoc[]

include::{documentdir}/parent_page/methods.asciidoc[]

include::{documentdir}/parent_page/events.asciidoc[]

[role="mt-5"]
== IFramed Page API

include::{documentdir}/iframed_page/options.asciidoc[]

include::{documentdir}/iframed_page/methods.asciidoc[]

include::{documentdir}/iframed_page/events.asciidoc[]

[role="mt-5"]
== Use with jQuery

include::{documentdir}/use_with/jquery.asciidoc[]

[role="mt-5"]
== Troubleshooting

include::{documentdir}/troubleshooting.asciidoc[]
