== Library Features

This library uses **vanilla JavaScript**. It is less than 400 bytes of
CSS and about 4Kb of JavaScript (minified and gzipped). The only
dependency this script has is
https://github.com/cferdinandi/smooth-scroll[Smooth Scroll] (which has
no dependencies).

This script works in **all modern browsers and IE 7+**.

=== Initialization

==== CSS load

CSS is used for expanding & collapsing groupings and some basic styling.

[source, html]
----
<link rel="stylesheet" href="/assets/css/tocbot.css">
----

==== JS load

Include the script at the bottom of the page before the closing body
tag.

[source, html]
----
<script src="/assets/js/tocbot.js"></script>
----


==== JS initialization

Initialize the script

[source, js]
----
tocbot.init({
  // Where to render the table of contents.
  tocSelector: '.js-toc',
  // Where to grab the headings to build the table of contents.
  contentSelector: '.js-toc-content',
  // Which headings to grab inside of the contentSelector element.
  headingSelector: 'h1, h2, h3',
});
----

If content in the div has changed then trigger a refresh (optionally
with new options).

[source, js]
----
tocbot.refresh();
----

=== Options

lorem:sentences[5]

==== tocSelector

lorem:sentences[5]

==== headingSelector

lorem:sentences[5]

==== ignoreSelector

lorem:sentences[5]

==== contentSelector

lorem:sentences[5]

==== activeLinkColor

lorem:sentences[5]

==== collapseDepth

lorem:sentences[5]

==== headingsOffset

lorem:sentences[5]

==== throttleTimeout

lorem:sentences[5]

==== includeHtml

lorem:sentences[5]

==== scrollOptions

lorem:sentences[5]

==== easing

lorem:sentences[5]

==== offset

lorem:sentences[5]

==== speed

lorem:sentences[5]

==== updateURL

lorem:sentences[5]



=== Callbacks

No callbacks or events.

lorem:sentences[5]

=== Methods

lorem:sentences[5]

==== .init

Initialize tocbot with an options object.

[source, js]
----
tocbot.init(options)
----

==== .destroy

Destroy tocbot and remove event listeners.

[source, js]
----
tocbot.destroy()
----

==== .refresh

Refresh tocbot if the document changes and it needs to be rebuilt.

[source, js]
----
tocbot.refresh()
----

