---
title:                                  Speak2Me
title_extention:                        Module for Speech Synthesise (SST)
tagline:                                Testing Speech Synthesise (SST)

date:                                   2023-07-26
#last_modified:                         2023-01-01

description: >
                                        Speak2Me is J1 SST Module that enables developers,
                                        with as little as one line of code, to create links
                                        that allow users to click, sit back, and listen to
                                        the browser read aloud the important content on
                                        a Web page.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        speech synthesise, sst, j1 module, jquery

categories:                             [ Module ]
tags:                                   [ Speech Synthesise, SST, Tester ]

tts:                                    true
regenerate:                             true
permalink:                              /pages/public/learn/speak2me_tester/

resources:                              [ animate, clipboard, lightbox, rouge ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       https://unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// https://github.com/mdn/dom-examples/tree/main/web-speech-api
// https://mdn.github.io/dom-examples/web-speech-api/speak-easy-synthesis/
// https://stackoverflow.com/questions/11279291/a-good-text-to-speech-javascript-library
// https://github.com/acoti/articulate.js
// https://codepen.io/meetselva/pen/EVaLmP


// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Unordered list

* _Windows_, _Linux_ and _MacOS_ platforms supported
* _Jekyll_ v4 Support
* _Ruby_ v3 Support
* Asciidoc and Markdown Support


== Definition list

Performance::
*The better performance and a crazy fast load time*.
One of the main advantages of using a static site is the fact that
it is crazy fast to load. Indeed, when the user requests a page, there is
no need to request a database and various files to generate the
page itself as all the content is already placed in a one and only file:
an HTML one.

Security::
*Having a static website: say goodbye to hacking and security issues*.
Are you tired of getting WordPress notifications about security issues and
updates every week? No worries, as a static site has no database, there are
close to no hack possible compared to a WordPress website. Indeed, your
site will have way fewer footprints and security issues since it will
only load plain HTML and CSS files.


== Chapter One

    Tyrion Lannister stood resolute upon the prow of the majestic vessel,
the Wind's Grace, its timeworn planks creaking beneath his weight.

    His mismatched eyes, one green as the emerald depths of the
Whispering Wood, the other a glimmering pale amethyst, stared out into
the boundless expanse of the Narrow Sea. As the ship cut through the
frothing waves, the wind, bearing the salty tang of the ocean, lashed at
his face, sending raven-black locks of hair spiraling across his brow.

=== Section One

    It was a gusty tempest, much like the swirling turmoil that had
beset his life ever since he had been forced to flee the shores of
Westeros. The crimson light of the setting sun cast an ethereal glow
upon Tyrion's countenance, accentuating the shadows that danced upon his
visage, mirroring the darkness that had shadowed his soul for far too
long.

    His lips, full and pursed in contemplation, were tinged with a touch
of melancholy, the weight of his troubled past etched upon his face like
the lines of a map charting the arduous journey he had undertaken.

    Lost in his ruminations, Tyrion found solace in the rhythmic cadence
of the waves crashing against the ship's hull. Each thunderous collision
reverberated through his being, echoing the tumultuous path he had
traversed.
