---
title:                                  Features
tagline:                                Modules, Extensions and Integrations
date:                                   2021-01-01 00:00:00 +100
description: >
                                        Simple documents are used quite often. If the number
                                        of chapters is about or less than three and the document
                                        is small in size. This document type does not use any
                                        (local) Asciidoc include files or attributes.

categories:                             [ Features ]
tags:                                   [ Module, Extension, Integration ]

sitemap:                                false
advertising:                            false
comments:                               false

robots:
  index:                                false
  follow:                               false

permalink:                              /pages/public/features/modules/
regenerate:                             false

resources:                              []
resource_options:
  - toccer:
      collapseDepth:                    4
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/skeleton/antonino-visalli-1920x1280.jpg
          alt:                          Photo by Antonino Visalli on Unsplash
          alignY:                       top
          badge:
            type:                       unsplash
            author:                     Antonino Visalli
            href:                       https://unsplash.com/@_visalli
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-fontawesome--home:                 https://fontawesome.com/

:url-roundtrip--mdi-icons:              /pages/public/learn/roundtrip/mdi_icon_font/#material-design-icons

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The Asciidoc *skeleton simple-document* a helper for setting up a base file and
folder structure for simple-document AsciiDoc pages based on _Jekyll_ and
_J1 Template_. You need *both* to use this skeleton creating AsciiDoc
documents from it.

Simple documents are used quite often for documents of a website. If the number
of chapters is about or less than three and the document is small in size,
simple documents should fit. This document type is based on a *single* Asciidoc
document and does *not* use any (local) Asciidoc include files or attributes.

== Modules

J1 Template support popular icons font sets out-of-the-box:

* link:{url-mdi--home}[Material Design Icons, {browser-window--new}] (MDI)
* link:{url-fontawesome--home}[FontAwesome Icons V5, {browser-window--new}] (FA)
* link:{url-iconify--home}[Iconify Icons, {browser-window--new}] (II)

The icon sets MDI and FA are very good in design and have a rich set of
different icons for many categories used for the Web. See below some details
for link:{url-roundtrip--mdi-icons}[Material Design Icons, {browser-window--new}]
and link:{url-roundtrip--fontawesome-icons}[FontAwesome Icons, {browser-window--new}].

== Extensions

J1 Template support popular icons font sets out-of-the-box:

* link:{url-mdi--home}[Material Design Icons, {browser-window--new}] (MDI)
* link:{url-fontawesome--home}[FontAwesome Icons V5, {browser-window--new}] (FA)
* link:{url-iconify--home}[Iconify Icons, {browser-window--new}] (II

== Devices

J1 Template support popular icons font sets out-of-the-box:

* link:{url-mdi--home}[Material Design Icons, {browser-window--new}] (MDI)
* link:{url-fontawesome--home}[FontAwesome Icons V5, {browser-window--new}] (FA)
* link:{url-iconify--home}[Iconify Icons, {browser-window--new}] (II
