---
title:                                  Magic SEO - Structured Data
title_extention:                        Creating structured data in 2023
tagline:                                Structured Data in 2023

#date:                                  2023-07-17
#last_modified:                         2023-01-01

categories:                             [ Seo ]
tags:                                   [ Structured Data ]

image:
  path:                                 /assets/images/modules/attics/giammarco-boscaro-1920x1280.jpg
  width:                                1920
  height:                               1280

group:                                  SEO
series:                                 SEO

regenerate:                             false

resources:                              [ advertising, animate, bmd, clipboard, lightbox, rouge ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/giammarco-boscaro-1920x1280.jpg
          alt:                          Photo by Giammarco on Unsplash
          badge:
            type:                       unsplash
            author:                     Giammarco
            href:                       https://unsplash.com/@giamboscaro
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

// Place an excerpt at the most top position
// -----------------------------------------------------------------------------
[role="dropcap"]
Creating structured data is one of the most powerful and simultaneously
least understood technique for Search Engine Optimizing. Structured data
for webpages is a programming work, mostly supported by already existing
software modules and libraries.

The data required is taken out of the existing source of a webpage. That
means no additional content is required but some programming to enhance the
already existing content.

excerpt__end

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Include sub-documents (if any)
// -----------------------------------------------------------------------------
The data enables search providers to understand how to interpret the content
of a webpage by their robots. The additional information enables search engines
to have a more *human-like* understanding of the content to add *extended*
information to the index to support for *better-rendered* result pages.

mdi:clock-time-five-outline[24px, md-gray mr-2]
*5 Minutes* to read

[role="mt-5"]
== Real world example

One of the formats for structured data supported by search engines, like
_Google_ or _Bing_, is *JSON-LD*. JSON-LD does *not* require any HTML tag
extention and can be generated by additional software modules to accompany
the HTML code generation.

gad::ad_7522184684_post["mt-5 mb-5"]

link:{url-structured-data--json-ld}[JSON-LD, {browser-window--new}] stands
for *JavaScript Object Notation for Linked Data*. It is a data-based method
of embedding JSON data in a website placed in a webpage's `<head>` section.
JSON-LD uses the standard *JSON* notation and extends this with a syntax
(keywords) that allows data to be distinguished according to universally
standardized schemata.

I'm the programmer of the template system
link:{url-j1-template--home}[J1 Template, {browser-window--new}]
for so-called *static websits*. The system is a skeleton for building modern
websites using the SSG (static site generator) *Jekyll*. For the SSG, a
powerful add-on software is available to *automatically* generate structured
data in parallel of outputting the (static) HTML code.

.JSON-LD excerpt
[source, html, role="noclip"]
----
<script type="application/ld+json">   <1>
  {
    "@context": "https://schema.org", <2>
    "@type": "BlogPosting",
    "author": {
      "@type": "Person",
      "name": "Juergen Adams",
      "url": "https://jekyll.one/"
    },
    ...
  }
</script>
----
<1> Embedding the JSON data
<2> Keywords to interprete the additional data

=== Inspect a Website

To understand better what *JSON-LD* is, I recomment to go for a website
that already supports the software required to create structured data.
I prepared a website at _Github Pages_ to have a sandbox at your fingertips:

mdi:link-variant[24px, md-gray mr-2 ml-3]
link:{url-j1-template--github-pages}[J1 Starter -- Home, {browser-window--new}] +
mdi:link-variant[24px, md-gray mr-2 ml-3]
link:{url-github-pages--site-generators}[J1 Starter -- Article, {browser-window--new}]

In my eyes it is important to learn first how structured data like *JSON-LD*
may look-alike and what is the outcome in terms of so-called *extended*
search results generated by modern search engines.

Open the link:{url-github-pages--site-generators}[article page, {browser-window--new}]
in a browser and display the HTML *source code* using the key sequence
kbd:[CTRL + U]. Search on that page in the code for the keywords *J1 SEO*.

.SEO data
lightbox::knowledge--seo-data[ 800, {data-knowledge--seo-data}, role="mb-4" ]

You'll find *all* SEO-related data *automatically* generated for that page.
At the end of the SEO section, the JSON-LD record is placed to request search
engines to generate extended search results.

.Extended search results at Google
lightbox::knowledge--google-search-results[ 800, {data-knowledge--google-search-results}, role="mb-4" ]

.Extended search results at Bing
lightbox::knowledge--bing-search-results[ 800, {data-knowledge--bing-search-results}, role="mb-2" ]

callout::1[Generated from data at Github, ml-2]
callout::2[Generated from data at Jekyll One, ml-2 mb-3]

In both search engines, the search results stand out clearly and show the
importance of structured data for better *visibility* in the search results.


=== Rich Results Tester

The presence and validity of *JSON-LD* data injected in a page can be easily
tested at:

mdi:link-variant[24px, md-gray mr-2 ml-3]
Google Search Central -- link:{url-search-google--test-rich-results}[Rich Results Test, {browser-window--new}] +

.Rich Results Tester
lightbox::knowledge-tester--rich-results-home[ 800, {data-knowledge-tester--rich-results-home}, role="mb-4" ]

The tester checks a given *URL*, or a *HTML code* snippet, if structured data
is available on a page, verifies the validity and type of structured data
detected.

Open the Rich Results Test at *Google Search Central* and copy the URL
into the URL field:

mdi:link-variant[24px, md-gray mr-2 ml-3]
Google Search Central -- link:{url-github-pages--site-generators}[Static Site Generators, {browser-window--new}]

The data found in the page should look like so:

.Tester Results
lightbox::knowledge-tester--rich-results[ 800, {data-knowledge-tester--rich-results}, role="mb-4" ]


== Summary

The examples of the *extended* search results on Google and Bing impressively
show the importance of structured data. In both search engines, the search
results will stand out clearly and will deliver a significantly larger number
of visitors.
