---
title:                                  lightGallery Lightbox
title_extention:                        API
tagline:                                Application Interface

date:                                   2026-04-28
#last_modified:                         2026-01-01

description: >
                                        The lightGallery module is a fast, modular and responsive
                                        jQuery Plugin to create simple but beautiful looking, featured
                                        image and video galleries.
keywords: >
                                        Jekyll, JekyllOne, Theme, User Guide, Module, lightGallery,
                                        Manual

categories:                             [ Manual ]
tags:                                   [ Module, lightGallery, Core ]

image:
  path:                                 /assets/image/module/attic/1920x1280/bp-miller.jpg
  width:                                1920
  height:                               1280

attic:                                  false
regenerate:                             false
personalization:                        true
permalink:                              /pages/public/manual/module/lightgallery2/lightgallery/

resources:                              [
                                          lightbox3, lightgallery,
                                          gallery, videojs
                                        ]
resource_options:
  - toccer:
      collapseDepth:                    3
  - attic:
      slides:
        - url:                          /assets/image/module/attic/1920x1280/isaac-davis.jpg
          alt:                          Photo by Isaac Davis on Unsplash
          badge:
            type:                       unsplash
            author:                     Isaac Davis
            href:                       //unsplash.com/@isaacdavis
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Attribute settings for page content control (e.g includes)
//
:documentdir:                           _includes/documents


//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
J1 Template support lightboxes out of the box. A *lightbox* is a helper module
that displays enlarged, almost screen-filling versions of images and videos
while dimming the rest of the web page. The technique used by Lightbox gained
widespread popularity due to its simple and elegant style.


[role="mt-5"]
== lightGallery

The lightGallery module is a fast, modular and responsive jQuery Plugin to
create simple but beautiful looking, featured image and video galleries.

* Fully responsive, HTML iframe support
* Modular architecture with built-in plugins
* Multiple instances per page
* Smart image preloading and Font icon support
* Touch support for Mobile Devices
* Keyboard navigation and Mouse drag support for Desktops
* Double-click|Double-tap support for fullsize view
* Support for Youtube, Vimeo, Dailymotion, VK and HTML5 video
* 20+ Hardware-Accelerated CSS3 transitions
* Animated thumbnails, Full screen and Image Zoom support for the Lightbox
* Easy customizable via CSS, SCSS and Module Settings


// Include sub-documents
// See: https://www.lightgalleryjs.com/docs/getting-started/
// See: https://www.lightgalleryjs.com/docs/
// -----------------------------------------------------------------------------

include::{documentdir}/100_lightgallery_integration.asciidoc[]
include::{documentdir}/110_lightgallery_library.asciidoc[]

// include::{documentdir}/120_lightgallery_examples.asciidoc[]

