---
title:                                  YAML Quick Reference
title_extention:                        YAML Quick Reference for J1 Template
tagline:                                Reference For J1 Template

date:                                   2022-01-01
#last_modified:                         2023-01-01

description: >
                                        YAML Quick Reference for J1 Template.
                                        A Cheat Sheet for YAML Ain't Markup Language.
                                        YAML Quick Reference (Cheat Sheet) for Jekyll
                                        data files, page front matters and collections.
keywords: >
                                        Jekyll, JekyllOne, Theme, User Guide, Tool, YAML,
                                        Reference

categories:                             [ Manual, Toolbox ]
tags:                                   [ YAML, Quickreference ]

image:
  path:                                 /assets/image/module/attic/1920x1280/chris-curry.jpg
  width:                                1920
  height:                               1280

tts:                                    true
comments:                               false
exclude_from_search:                    false
regenerate:                             false
permalink:                              /pages/public/manuals/yaml/quick_reference/

resources:                              [ lightbox ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/module/attic/1920x1280/chris-curry.jpg
          alt:                          Photo by Chris Curry on Unsplash
          badge:
            type:                       unsplash
            author:                     Chris Curry
            href:                       //unsplash.com/@chriscurry92
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// See: https://github.com/planetjekyll/quickrefs/blob/master/YAML.md

YAML Quick Reference (Cheat Sheet) for Jekyll data files, page front matters
and collections.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
== Comments, blank lines or spaces

_YAML_, contrasting to JSON, let's you use *comments* on your datablocks.
To make your data more human readable, blank lines or spaces can be used.

.Example `themes.yml`
[source, yaml]
----
#########################################
# Dr Jekyll's Themes - Add Your Theme!
#
- title:          Bootstrap
  github:         drjekyllthemes/jekyll-bootstrap-theme
  branch:         gh-pages
  author:         Edward Hyde
  thumbnail:      drjekyll-bootstrap.jpg
  license:        Public Domain

# Another possible formatting style could be like this
#
- title:          Classics Book
  github:         drjekyllthemes/jekyll-book-theme
  branch:         gh-pages
  author:         Edward Hyde
  thumbnail:      drjekyll-book.jpg
  license:        Public Domain
----

is the same as:

[source, yaml]
----
- title:          Bootstrap
  github:         drjekyllthemes/jekyll-bootstrap-theme
  branch:         gh-pages
  author:         Edward Hyde
  thumbnail:      drjekyll-bootstrap.jpg
  license:        Public Domain

- title:          Classics Book
  github:         drjekyllthemes/jekyll-book-theme
  branch:         gh-pages
  author:         Edward Hyde
  thumbnail:      drjekyll-book.jpg
  license:        Public Domain
----

NOTE: The colon (`:`) key/value separator MUST (only) be followed by a
space, thus, you can use `title  :  Classics Books` and so on.
The number sign / hash (`#`) used for inline end-of-line comments
MUST have both a leading and trailing space e.g.
`some text here  # comment starts here`, otherwise the number sign /
hash is just part of the string e.g.
`Jekyll - The #1 Static Site Generator` works as expected.


== Strings or Keys without quotes

Let's you use strings or keys without (requiring) quotes

[source, yaml]
----
title:            Bootstrap
github:           drjekyllthemes/jekyll-bootstrap-theme
author:           Edward Hyde
----

is the same as:

[source, yaml]
----
"title":          "Bootstrap"
"github":         "drjekyllthemes/jekyll-bootstrap-theme"
"author":         "Edward Hyde"
----

=== When to use quotes for your strings

If your string includes a colon (`:`) you MUST quote your string. Otherwise,
the colon is interpreted as a key-value separator (e.g. `key:value`).

.Example
[source, yaml]
----
title:            "Text Processing with Ruby: Extract Value from the Data That Surrounds You"
title:            "Sinatra: Up and Running - Ruby for the Web, Simply"
title:            "Using JRuby: Bringing Ruby to Java"
----

Note: You can quote your strings using double quotes (`""`) e.g. "Using
JRuby: Bringing Ruby to Java" or single quotes(`''`) e.g. 'Using JRuby:
Bringing Ruby to Java'.

== Data File Examples

* List of key-value records
* Nested List of key-value records
* Hash (Dictionary) of key-value records
* Multi-File List of key-value records

You can browse the examples live in action at the Sandbox Example Site at
Planet Jekyll. See the https://planetjekyll.github.io/sandbox[start page, {browser-window--new}]
or the https://github.com/planetjekyll/sandbox[sandbox site sources, {browser-window--new}].

To verify and/convert your _YAML_ data structures, check the
https://yaml-online-parser.appspot.com/[Online YAML Parser, {browser-window--new}].

=== List of key-value records

.Book List Example: `books.yml`
[source, yaml]
----
- title:          "Text Processing with Ruby:
                  Extract Value from the Data That Surrounds You"
  author:         Rob Miller
  cover:          2015/text-processing-with-ruby.jpg
  publisher:      Pragmatic Bookshelf
  date:           Nov 2015
  pages:          200 pages (est)
  book_url:       https://pragprog.com/book/rmtpruby/text-processing-with-ruby

- title:          Learn Ruby the Hard Way
  subtitle:       A Simple and Idiomatic Intro to the Imaginative World Of Computational Thinking with Code
  edition:        3rd Edition
  author:         Zed Shaw
  cover:          2014/learn-ruby-the-hard-way.jpg
  publisher:      Addison-Wesley Professional (Zed Shaw's Hard Way Series)
  date:           Dec 2014
  pages:          336 pages
  book_url:       https://www.informit.com/store/learn-ruby-the-hard-way

- title:          "Sinatra: Up and Running - Ruby for the Web, Simply"
  author:         Alan Harris, Konstantin Haase
  cover:          2011/sinatra-up-and-running.jpg
  publisher:      O'Reilly Media
  date:           Dec 2011
  pages:          122 pages
  book_url:       https://shop.oreilly.com/product/0636920019664.do
----

Use like:

[source, html]
----
{% for book in site.data.books %}
  <div>
  <a href="{{ book.book_url }}">
    <img src="{{site.url}}/i/{{book.cover}}">
  </a>
  {{ book.title }}
  {% if book.edition %}
    ({{ book.edition}})
  {% endif %}
  by {{ book.author }};
  {{ book.publisher }}, {{ book.date }}; {{ book.pages}}
  </div>
{% endfor %}
----

=== Nested list of key-value records

.Navigation Menu Example: `nav.yml`
[source, yaml]
----
- title:          Home
  href:           /

- title:          Learn
  href:           /learning-resources/
  subcategories:
  - title:        Learning topic one
    href:         /learn1/
  - title:        Learning topic two
    href:         /learn2/
  - title:        Learning topic three
    href:         /learn3/

- title:          Tools
  subcategories:
  - title:        Tools one
    href:         /tools1/
  - title:        Tools two
    href:         /tools2/

- title:          About Us
  href:         /about-us/
----

Use like:

[source, html]
----
  <nav>
    <ul>
    {% for nav in site.data.nav %}
      {% if nav.subcategories %}
        <li>
          <a href="{{ site.url }}{{ nav.href }}">{{ nav.title }}</a>
          <ul>
          {% for subcategory in nav.subcategories %}
            <li>
              <a href="{{ site.url }}{{ subcategory.href }}">
                {{ subcategory.title }}
              </a>
            </li>
          {% endfor %}
          </ul>
        </li>
      {% else %}
        <li>
          <a href="{{ site.url }}{{ nav.href }}">{{ nav.title }}</a>
        </li>
      {% endif %}
    {% endfor %}
    </ul>
  </nav>
----

=== Hash (Dictionary) of key-value records

.Author List Example: `authors.yml`
[source, yaml]
----
henry:
  name:           Dr Henry Jekyll
  twitter:        henryjekyll

edward:
  name:           Edward Hyde
  twitter:        edhyde
----

Use like:

Example 1) Lookup author info in a post

[source, html]
----
  ---
  title:  A Strange Case
  author: henry
  ---

  {% assign author = site.data.authors[ page.author ] %}

  <a href="https://twitter.com/{{ author.twitter }}">
     {{ author.name }}
  </a>
----

=== Multi-File list of key-value records

Note: You can place data files in (sub)folders of the `_data` folder.
Each folder level will get added to the variable's namespace e.g.
`site.data.orgs`.

.Org Example #1: `orgs/jekyll.yml`
[source, yaml]
----
name:             Jekyll
github:           jekyll

members:
- name:           Parker Moore
  github:         parkr
- name:           Jordon Bedwell
  github:         envygeeks
----

.Org Example #2 `orgs/octopress.yml`
[source, yaml]
----
name:             Octopress
github:           octopress

members:
- name:           Brandon Mathis
  github:         imathis
----

Use like:

[source, html]
----
  <ul>
    {% for org_hash in site.data.orgs %}
    {% assign org = org_hash[1] %}
      <li>
        <a href="https://github.com/{{ org.username }}">
          {{ org.name }}
        </a>
        ({{ org.members | size }} members)
      </li>
    {% endfor %}
  </ul>
----

== Front Matter Examples

List of key-value records • Multi-File List of key-value records w/
Collections

=== List of key-value records

Portfolio Example, Part 1/2 (Front Matter) `portfolio.html`:

[source, yaml]
----
  ---
  layout:         default
  title:          Histories, Tragedies and Comedies
  portfolio:
  - title:        Richard II
    category:     History
    cover:        richard-ii.jpg
  - title:        Henry VI, Part 1
    category:     History
    cover:        henry-vi-1.jpg
  - title:        Romeo and Juliet
    category:     Tragedy
    cover:        romeo-n-juliet.jpg
  - title:        Hamlet
    category:     Tragedy
    cover:        hamlet.gif
  - title:        Antony and Cleopatra
    category:     Tragedy
    cover:        antony-n-cleopatra.jpg
  - title:        All's Well That Ends Well
    author:       Comedy
    cover:        alls-well-that-ends-well.jpg
  - title:        A Midsummer Night's Dream
    author:       Comedy
    cover:        a-midsummer-nights-dream.jpg
  ---
----

Use like:

Portfolio Example, Part 2/2 (Continued) `portfolio.html`:

[source, html]
----
  <h1>{{ page.title }}

  <div class='porfolio'>
  {% for work in page.portfolio %}

    <div class='work'>
      <img src="{{site.url}}/i/portfolio/{{work.cover}}">
      {{ work.title }} // {{ work.category }}
    </div>

  {% endfor %}
  </div>
----

NOTE: The portfolio is defined inside the page (in the front matter),
thus, use `page.portfolio` instead of
[line-through]*`site.data.portfolio`* to reference (e.g. loop over) the
list.

=== Multi-File list of key-value records

.Albums Example #1 `_albums/josquin.html`
[source, yaml]
----
  ---
  title:          "Josquin: Missa De beata virgine and Missa Ave maris stella"
  artist:         "The Tallis Scholars"
  director:       "Peter Phillips"
  works:
  - title:        "Missa De beata virgine"
    composer:     "Josquin des Prez"
    tracks:
    - title:      "Kyrie"
      duration:   "4:25"
    - title:      "Gloria"
      duration:   "9:53"
    - title:      "Credo"
      duration:   "9:09"
    - title:      "Sanctus & Benedictus"
      duration:   "7:47"
    - title:      "Agnus Dei I, II & III"
      duration:   "6:49"
  ---
----

Use like:

.Example Catalog `catalog.html`
[source, html]
----
  ---
  layout:         default
  title:          Album Catalog
  ---
  {% for album in site.albums %}
    <h2>{{ album.title }}</h2>
    Performed by {{ album.artist }}
    {% if album.director %}, directed by {{ album.director }}{% endif %}
    {% for work in album.works %}
      <h3>{{ work.title }}</h3>
      <p>Composed by {{ work.composer }}</p>
      <ul>
      {% for track in work.tracks %}
        <li>{{ track.title }} ({{ track.duration }})</li>
      {% endfor %}
      </ul>
    {% endfor %}
  {% endfor %}
----

Note: Using collections you can access *ALL* front matters from all
files from anywhere (not just inside a collection page) using the
collection name e.g. `site.albums`.

=== Multi-Line Strings

Quite often, especially for to use of Jekyll, longer sequences of text or code
are used. To make those better human readable, the sequence can be broken down
in multi-Line strings.

==== Unfolded

Use `unfolded` multi-Line strings by *keeping* newlines by using `|`.

[source, yaml]
----
text: |
                  There once was a short man from Ealing
                  Who got on a bus to Darjeeling
                     It said on the door
                     "Please don't spit on the floor"
                  So he carefully spat on the ceiling
----

The leading indent (of the first line) and trailing white space gets
stripped e.g. becoming:

....
  There once was a short man from Ealing\n
  Who got on a bus to Darjeeling\n
      It said on the door\n
      "Please don't spit on the floor"\n
  So he carefully spat on the ceiling\n
....

==== Folded

Use `folded` multi-Line strings by *stripping* newlines by using `>`.

[source, yaml]
----
text: >
                  Wrapped text
                  will be folded
                  into a single
                  paragraph

                  Blank lines  denote
                  paragraph breaks
----

Folded text converts newlines to spaces and removes leading whitespaces.
The example becomes:

....
  Wrapped text will be folded into a single paragraph\n
  \n
  Blank lines denote paragraph breaks\n
....

=== Inline Style a.k.a. JSON-Style

As an alternative syntax you can use the inline style for lists
(e.g. JSON arrays) and hashes (dictionaries, JSON objects).

.Example
[source, yaml]
----
[
  { "title":      "Bootstrap",
   "github":      "drjekyllthemes/jekyll-bootstrap-theme",
   "author":      "Edward Hyde",
   "thumbnail":   "drjekyll-bootstrap.jpg" },
  { "title":      "Classics Book",
   "github":      "drjekyllthemes/jekyll-book-theme",
   "author":      "Edward Hyde",
   "thumbnail":   "drjekyll-book.jpg"
  }
]
----

is the same as:

[source, yaml]
----
[
 { "title": Bootstrap", "github": "drjekyllthemes/jekyll-bootstrap-theme", "author": "Edward Hyde", "thumbnail": "drjekyll-bootstrap.jpg" },
 { "title": "Classics Book", "github": "drjekyllthemes/jekyll-book-theme", "author": "Edward Hyde", "thumbnail": "drjekyll-book.jpg" }
]
----

or the same as:

[source, yaml]
----
- title:          Bootstrap
  github:         drjekyllthemes/jekyll-bootstrap-theme
  author:         Edward Hyde
  thumbnail:      drjekyll-bootstrap.jpg
- title:          Classics Book
  github:         drjekyllthemes/jekyll-book-theme
  author:         Edward Hyde
  thumbnail:      drjekyll-book.jpg
----

The JavaScript Object Notation (JSON) is a just another (welcome and working)
formatting style for datafiles.

=== Literal Keys

You can use upper case letters in your keys (e.g. `Teams`), add spaces
(e.g. `Bundesliga Teams`) and even start with numbers (e.g. `18 Teams`).

.Example
[source, yaml]
----
18 Teams:
  - Austria Wien
  - SC Salzburg
  - Sturm Graz
----

== More Gotchas

* Don't use tabs for indentation. Use spaces instead. Always use spaces for
  indentation. Make sure no tabs (`\t`) have somehow ended up in your datafile
  leading to prevent unexpected results.
* Use predefined boolean constants. The boolean `true` and `false` constants
  are:

[source, text, role="noclip"]
----
true, True, TRUE
y, Y, yes, YES, YES
on, ON, ON
false, False, FALSE
n, N, no, No, NO
off, Off, OFF
----

All of them will become boolean values e.g. `true` or `false`.

[source, yaml]
----
recommend: Yes       # note: will become => true (boolean)
----

If you want end-up with a *string* make sure you use a *quoted* version like
so:

[source, yaml]
----
recommend: "Yes"     # note: will become => "Yes" (string)
----

The same holds for the no value `null` constants:

[source, text, role="noclip"]
----
~
null, Null, NULL
----

All of those become `null`, the `no value`. A key without a value will
end-up with a `null` value and *not* an empty string. To get an empty
string use double quotes `""`:

[source, yaml]
----
key1:           # note: value will become => null (no value); same as key1: null  or key1: ~
key2: ""        # note: value will become => "" (string)
----

== Online Tools

Some handy tools are available online on the Internet. Try out the following
example sites to check the validity of your YAML data code.

* The https://www.yamllint.com[YAML Linter, {browser-window--new}].
  Paste in your YAML and click *Go*. The linter will tell you if your data
  is valid or not, and print out a nice clean formatted version in UTF-8.

* The https://yaml-online-parser.appspot.com/[YAML Parser, {browser-window--new}].
  Verify and convert your YAML data structures e.g. into JSON.

* The https://www.345tool.com/formatter/yaml-formatter[YAML Formatter, {browser-window--new}].
  Verify your YAML data structures even from a file.

NOTE: The *YAML Linter* tool will add a tree-dashes-line on top of the linted
(and beautified) data. This line is used to indicate the following data as
_YAML_ as used in the Ruby language.

WARNING: Be careful using YAML data validators/beautifiers on your (personal)
styled YAML files. A beautifier may destroy your formatting by replacing your
tags by a machine readable format for faster loading and processing.
