
== What is a static site?

A static site serves the content straight to the user as it is stored on
the server-side. To put it in another way, in opposition to WordPress
which use a database to load dynamic content, a static site will display
the same content to every user as it will directly load the HTML files
on the server.

A static website uses server-side rendering to serve *pre-built* HTML, CSS,
and JavaScript files to a web browser, in contrast to traditional dynamic
sites that work by *rendering* the webpage *at the time of the request*.

.Static Website
lightbox::kickstart-wiad--client-server-web[ 800, {data-kickstart-wiad--client-server-web} ]

callout::1[Web Browser]
callout::2[Web Server]
callout::3[Static content, ml-2 mb-3]

NOTE: The static content conum:3[] is generated by Jekyll.

/////
.Jekyll variables (Liquid)
[cols="3,3a,6a, subs=+macros, options="header", width="100%", role="rtable mt-3"]
|===============================================================================
|Name |Value |Description

|`page.path`
|{{ page.path }}
|The path to the raw post or page. Example usage: Linking back to the page
or post's source on GitHub. This can be overridden in the `YAML Front Matter`.

|`site.collections_dir`
|{{ site.collections_dir }}
|lorem:sentences[1]

|`page.images.dir`
|{{ page.images.dir }}
|Image path set pagewise. See FRONTMATTER defaults in `_config.yml` for the
images path specified by: `images.dir` for specific page *type*. See the
example below for a page of type *pages*.
[source, yaml]
----
defaults:
  - scope:
      path:          pages
      type:          pages

    values:
      images:
        dir:        /assets/images/pages
----

|`page-imagesdir`
|{{ page-imagesdir }}
| Images path set in the page by `:page-imagesdir:`.

|`template`
|{{ site.template.name }}
|Name of the template used for rendering a page. Settings are taken from
sitewide configuration defined by `_config.yml`.

|`includedir`
|{{ includedir }}
|lorem:sentences[1]

|===============================================================================
/////

In the last few years, static sites have greatly increased in popularity.
This surge is primarily due to advances in developer tools (languages and
libraries) and a stronger desire among businesses to optimize website
performance beyond the limits of a database-driven site.
