---
title:                                  J1 Template
tagline:                                top features
date:                                   2022-09-15 00:00:00
description: >
                                        J1 Template is a gem-based template system to be used with the
                                        static web site generator Jekyll. Find the top features of
                                        Jekyll One Template and check what can be done for modern web sites
                                        using j1 template. Download the latest version of the Ruby Gem for
                                        the template system at https://rubygems.org/gems/j1-template/.

                                        ~~~ j1, jekyll, one, template, ruby, nodejs, gem, jamstack, module,
                                        provider, google, netlify, bootstrap, facebook, twitter, open, source,
                                        javascript, css, scss, html, yaml, service, internet, support, analytics,
                                        advertising, search, console, silverlight, score,  1-Click, deployment,
                                        responsive, design, theme, desktop, mobile, navigation, static, web, site,
                                        blog, post, article, royalty, free, images, carousel, slider, gallery,
                                        video, player, clipboard, cookie, consent, fulltext, search, engine.

categories:                             [ About ]
tags:                                   [ J1, Template, Features ]

scrollbar:                              false
comments:                               false
fab_menu_id:                            page_ctrl

permalink:                              /pages/public/about/features/
regenerate:                             false

resources:                              [ animate, carousel, comments, lightbox ]
resource_options:

  - attic:

      padding_top:                      550

      slides:

        - url:                          /assets/images/modules/attics/1920x1280/alexander-redl.jpg
          alt:                          Photo by Alexander Redl on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexander Redl
            href:                       https://unsplash.com/@alexanderredl
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        true
:legal-warning:                         true

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// {badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ifeval::[{badges-enabled} == true]
{badge-j1--version-latest} {badge-j1--downloads}
endif::[]

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

J1 Template is a **gem**-based *template* system to be used with the static
site generator _Jekyll_. Find the top features of Jekyll One Template and check
what can be done for modern web sites using j1. Download the latest version of
the Ruby Gem for the template system at {url-j1--download}[RubyGems, {browser-window--new}].

== General Features

* _Windows_, _Linux_ and _MacOS_ supported
* _Jekyll_ v4.2 Support
* _Ruby_ v3 Support
* Asciidoc and Markdown Support
* _Asciidoctor_ plugins included
* _Bootstrap_ V5 Support
* Responsive Design
* Material Design
* Responsive Text
* Responsive HTML Tables
* Compressed HTML, CSS and Javascript Support
* Bootstrap Themes from _Bootswatch_ supported
* Icon Font Support for _MDI_, _FA_, _Iconify_ and _Twitter Emojis_
* Themeable source code highlighting (_Rouge_)
* Desktop and Mobile Web Navigation ready
* Fully configurable, no programming needed
* Near 100/100/100 _Google Lighthouse_ Scores

== Modules and Extensions

* _Bootstrap_ extensions included
* _Asciidoctor_ extensions included
* Infinite Scroll Support
* Animate on Scroll Support
* Smooth-Scoll Support
* Full-text Search Engine (Lunr) included
* Master Header Module included
* Cookie Consent Module (GDPR compatible OptIn/Out) included
* Clipboard Module included
* Floating Action Buttons (FABs) included
* Navigation Modules included
* Desktop Web Navigation included
* Mobile Web Navigation included
* Blog Post Navigation included
* Lightbox Modules included
* Gallery Module included
* Carousel Module included
* Slider Module included
* Video Player Modules included

== Addons and Integrations

* *Starter Web* including featured Example Content
* *Royalty free* Images included
* Comment Provider Support for _Disqus_ and _Hyvor_
* _Jupyter Notebook_ Support
* _Github Sponsors_ Support
* _Google_ Translation Support
* _Google Analytics_ Support (includes OptIn/OptOut support)
* Deploy on _Github Pages_, _Netlify_ and _Heroku_ ready
