---
title:                                  J1 Template
tagline:                                features
date:                                   2021-04-13 00:00:00
description: >
                                        Things you should know about this site,
                                        about the software used. Read a bit what
                                        people, what companies has contributed
                                        to make a project like J1 Template real.

categories:                             [ About ]
tags:                                   [ J1, Template, Features ]

scrollbar:                              false
comments:                               true

permalink:                              /pages/public/about/features/
regenerate:                             false

resources:                              [ animate, lightbox ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/runner-1920x1200.jpg
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        true
:legal-warning:                         true

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// {badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ifeval::[{badges-enabled} == true]
{badge-j1--version-latest} {badge-j1--downloads}
endif::[]

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
== Features

J1 Template is a *gem-based* website template to be used with the static site
generator _Jekyll_. The Template System cannot operate on its own. A Ruby
development environment is needed to run J1. If you're an experienced user
of _Jekyll_, the latest version is available at
{url-j1--download}[RubyGems, {browser-window--new}].

=== General

* Windows, Linux, MacOS supported
* Jekyll 4.2 support
* Ruby 2.7 support
* Asciidoc (Asciidoctor) and Markdown support
* Asciidoctor plugins included
* Bootstrap V5
* Responsive Design
* Material Design
* Responsive Text
* Responsive HTML tables
* Compressed HTML, CSS and Javascript support
* Bootstrap Themes support (Bootswatch/BS V5)
* Icon Font support (MDI, FA, Iconify, Twitter Emoji)
* Themeable source code highlighting (Rouge)
* Desktop and Mobile Web and navigation ready
* Fully configurable, no programming needed
* Near 100/100/100 Google Lighthouse scores (performance depends on the webserver)

=== Modules and Extensions

* Bootstrap extensions included
* Asciidoctor extensions included
* Smooth-Scoll support
* Full-text search engine (Lunr) included
* Blog Post navigation included
* Cookie Consent module (GDPR compatible OptIn/Out) included
* Clipboard module included
* Floating Action Buttons included
* Navigation modules included
* Lightbox modules included
* Gallery modules included
* Carousel module included
* Video modules included

=== Addons and Integrations

* Featured example content included
* Royalty free images included
* Support of comment provider APIs (Disqus, Hyvor)
* Google Analytics support (includes OptIn/OptOut support)
* Deploy to Github Pages, Netlify and Heroku ready
