---
title:                                  J1 Template
tagline:                                about
date:                                   2022-01-01 00:00:00
description: >
                                        Whether you work solo or as part of a team, it’s always a great idea to
                                        help visitors put a face to the names behind a website. The best place to
                                        include a bit of information about you and your team is on your homepage
                                        with an about page so that no one will miss it.

                                        ~~~ j1, jekyll, one, template, ruby, nodejs, gem, jamstack, module,
                                        provider, google, netlify, bootstrap, facebook, twitter, open, source,
                                        javascript, css, scss, html, yaml, service, internet, support, analytics,
                                        advertising, search, console, silverlight, score,  1-Click, deployment,
                                        responsive, design, theme, desktop, mobile, navigation, static, web, site,
                                        blog, post, article, royalty, free, images, carousel, slider, gallery,
                                        video, player, clipboard, cookie, consent, fulltext, search, engine.

categories:                             [ About ]
tags:                                   [ Software, Platforms, Contributers ]

scrollbar:                              false
regenerate:                             false

permalink:                              /pages/public/about/site/

page_excerpts:                          true

resources:                              [ animate ]
resource_options:

  - attic:
      padding_top:                      550

      slides:
        - url:                          /assets/images/modules/attics/1920x1280/alexander-redl.jpg
          alt:                          Photo by Alexander Redl on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexander Redl
            href:                       https://unsplash.com/@alexanderredl
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

// Attribute settings for section control
//
:badges-enabled:                        true

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// {badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ifeval::[{badges-enabled} == true]
{badge-j1--version-latest} {badge-j1--downloads}
endif::[]

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== About this site

Whether you work solo or as part of a team, it’s always a great idea to
help visitors put a face to the names behind a website. The best place to
include a bit of information about you and your team is on your homepage with
an About page so that no one will miss it.

Good luck presenting your site to the world!
