== Introduction and Setup

Bokeh is an interactive visualization library that targets modern web browsers
for presentation. It is good for:

* Interactive visualization in modern browsers
* Standalone HTML documents, or server-backed apps
* Expressive and versatile graphics
* Large, dynamic or streaming data
* Easy usage from python (or Scala, or R, or...)

IMPORTANT: No programming of Javascript is required using Bokeh

Bokeh is an interactive visualization library for modern web browsers. It
provides elegant, concise construction of versatile graphics, and affords
high-performance interactivity over large or streaming datasets. Bokeh can
help anyone who would like to quickly and easily make interactive plots,
dashboards, and data applications.

=== Clone or download the repo

First get local copies of the tutorial notebooks:

[source, sh]
----
$ git clone https://github.com/bokeh/bokeh-notebooks.git
----

Or download from: https://github.com/bokeh/bokeh-notebooks/archive/master.zip

=== Install the dependencies

This tutorial has been tested on:

* bokeh 1.4.0
* pandas 0.25.2
* notebook 6.0.1
* phantomjs 2.1.1
* pillow 6.1.0
* selenium 3.8.0

Other combinations may work also.

The quickest, easiest way to install is to use Anaconda (or Miniconda):

==== Installing with Anaconda

Install http://anaconda.com/downloads[anaconda]

Anaconda should come with all the dependencies included, but you may need to update your versions.

==== Installing with Miniconda

Install http://conda.pydata.org/miniconda.html[miniconda].

Use the command line to create an environment and install the packages:

[source, sh]
----
conda env create
source activate bokeh-notebooks
----

NOTE: Run this in the `tutorial` directory where `environment.yml` file is.

Once you've got a base install, you can install the remaining dependencies with:

[source, sh]
----
conda install phantomjs pillow selenium
----

=== Get the sample data

Bokeh has a https://docs.bokeh.org/en/latest/docs/installation.html#sample-data[sample data]
download that gives us some data to build demo visualizations. To get it run
the following command at your command line:

[source, sh]
----
$ bokeh sampledata
----

or run the following from within a Python interpreter:

[source, python]
----
import bokeh.sampledata
bokeh.sampledata.download()
----
