---
title:                                  Roundtrip
tagline:                                present videos
date:                                   2020-11-04 00:00:00  +100
description: >
                                        Playing video on web pages seems not that special since you can already
                                        watch videos on web pages through plugins like Flash Player, Quicktime
                                        or Silverlight. A new standard goes to HTML5 Video, a pure HTML way to
                                        show video on the web; instead of the previous de facto standard of using
                                        proprietary software.

categories:                             [ Roundtrip ]
tags:                                   [ Introduction, Module, Video ]

permalink:                              /pages/public/learn/roundtrip/present_videos/
regenerate:                             false

personalization:                        true

fab_menu_id:                            page_ctrl_simple

resources:                              [
                                          animate, lightGallery, justifiedGallery, video_js,
                                          vimeo_player, vimeo_froogaloop
                                        ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      background_color:
        color_1:                        md_grey_100
        color_2:                        md_grey_400
      slides:
        # Broadway Underground - still image (animate default)
        - url:                          /assets/videos/headers/still/underground-broadway.jpg
          alt:                          Broadway Underground
          alignY:                       top
          animateFirst:                 false
        # Broadway Underground - FAYETTE ST, moved file to Github/LFS
        - url:                          https://github.com/jekyll-one-org/jekyll-one-lfs/raw/master/videos/underground-broadway.mp4
          alignY:                       0
          isVideo:                      true
          loop:                         false
          duration:                     12000
        # Broadway Underground - still image (animate random)
        - url:                          /assets/videos/headers/still/underground-broadway.jpg
          alt:                          Broadway Underground
          alignY:                       top
          transition:                   push_left|push_right|cover_up|cover_down|fade|fadeInOut
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

++++
<!-- insert Google Ad (Displayanzeige): horizontal-2, adSlot="5128488466" -->
<div class="5128488466 mb-5">
  <ins class="adsbygoogle"
    style="display: block;"
    data-ad-client="ca-pub-3885670015316130"
    data-ad-slot="5128488466"
    data-ad-format="auto"
    data-adtest="on"
    data-full-width-responsive="true">
  </ins>
</div>
++++

++++
<script>

  $(document).ready(function() {
    var logger              = log4javascript.getLogger('j1.google.ads');
    var autoHideOnUnfilled  = true;

    var dependencies_met_page_ready = setInterval (function (options) {
      if ( j1.getState() === 'finished' ) {

        // monitor for state changes on the ad
        // ---------------------------------------------------------------------
        $('.adsbygoogle').attrchange({
          trackValues: true,
          callback: function (event) {
            if (event.newValue === 'unfilled') {
              var elm = event.target.dataset;
              if (elm.adClient) {
                logger.warn('\n' + 'initialized ad detected as: ' + event.newValue);
                if (autoHideOnUnfilled) {
                  logger.info('\n' + ' hide ad for slot: ' + elm.adSlot);
                  $('.' + elm.adSlot ).hide();
                }
              }
            }
          }
        });

        // manage uncaught execeptions
        // ---------------------------------------------------------------------
        // window.onerror = function (msg, url, line) {
        //    alert("Message : " + msg );
        //    alert("url : " + url );
        //    alert("Line number : " + line );
        // }

        logger.info('\n' + 'initialize Google Ad on slot: ' + '5128488466');
        (adsbygoogle = window.adsbygoogle || []).push({});

        clearInterval(dependencies_met_page_ready);
      }
   });

  });

</script>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
Playing video on web pages seems not that special since you can already
watch videos on web pages through plugins like _Flash Player_, _Quicktime_,
or _Silverlight_. A new standard goes to HTML5 Video, a pure HTML way to
show video on the web, instead of the previous de facto standard of using
proprietary software.

== Video Galleries

HTML5 Video opens the doors to your way of presenting video content. Modern
browsers support the video tag `<video>` for the HTML5 video standard.
Browsers have a built-in multimedia framework already for decoding and displaying
video content. No need to use such proprietary software components anymore!

HTML5 Video support is given by the App gallery combined with the lightbox
LightGallery.

Two types of video sources are supported:

. Video files from local folders (your webspace)
. Video files from online sources (on the Internet) like YouTube, Vimeo, etc.

The combination of the App gallery and the lightbox LightGallery is entirely
usable for all the video content you want to present on your site. You can
place Galleries elsewhere with your content. You can use them for video blogs
by putting them into your blog article's content.

WARNING: LightGallery can be used for free for private use, but a commercial
license is needed for business use. See
link:{url-light-gallery--license}[LightGallery licenses, {browser-window--new}]
how to use LightGallery for commercial websites and projects.

== Local Video content

Digital image content, simple pictures or videos, are easy to make. Today, every mobile has a camera - not that bad! Presenting a bunch
of (digital) pictures is done very easily by using Justified Gallery, for example.
Videos created by a digicam or a mobile can be played by J1 Template using the
HTML5 Video support of LightGallery.

Two players are available with LightGallery:

. an internal player used by default
. {url-videojs--home}[video.js, {browser-window--new}], a excellent
  Javascript video library

NOTE: The HTML5 specification does _not_ define which video and audio formats
browsers _should_ support. J1 LightGallery can play all types of standard
HTML5 Video formats on modern browsers today (MP4, WebM, and Ogg).

gallery::jg_video_html5[role="mb-5"]

== Online Video content

The Internet is full of inspiring content. If you want to present video
content from the Internet, the online video support of J1 Template is the
right choice.

=== YouTube

YouTube’s community is large, with over 1 billion users that watch hundreds
of millions of hours of content – each day! With that many people comes risks.
You may run into some questionable, highly offensive users that are not
afraid to tell you exactly how they feel about your video.

The number of channels on YouTube is enormous. For TV-Stations, it's a must
to publish videos of their shows. Find below a current gallery from Germany's
*The Voice Kids* (SAT.1) and a real classic channel from the frontman James
Corden of *The Late Late Show* at CBS, Los Angeles.

.The Voice Kids, Germany 2021
gallery::jg_video_online_youtube_2[role="mb-5"]

.James Cordon's Carpool Karaoke
gallery::jg_video_online_youtube[role="mb-5"]

=== Vimeo

Vimeo is a video sharing platform that includes features such as live-streaming
and customization. These services include video creation, editing, broadcasting
tools and connecting with clients. The bottom line is that Vimeo allows you
to create high quality, professional videos and reach audiences worldwide.

Vimeo does offer a basic, free membership, but it limits you to 500MB maximum
storage per week. Alternately, you can book on Paid plans: Plus, PRO, Business.
Each have varied storage limits. A plus using Vimeo is, *no advertising* is
used on that platform.

.Vimeo Video Gallery - Fashion
gallery::jg_video_online_vimeo[role="mb-5"]


=== DailyMotion

Dailymotion is a French video-sharing technology platform primarily owned by
Vivendi. The platform is available worldwide in 183 languages and 43 localised
versions featuring local home pages and local content.

The platform is a monetization solution that allows allows to directly connect
to high-quality advertisers through a proprietary Advertising Solution. Like
YouTube, videos cav be watched for free, but ads are shown on each and every
video.

Dailymotion allows users to search videos by *tags*, topic *channels*, or
user-created *groups*. Users can upload videos of up to 2 gigabytes and a
length of 60 minutes. If a user is a MotionMaker or MotionPartner, a program
for particularly creative users or partners, they can upload videos of
unlimited length.

.DailyMotion Video Gallery - Lifestyle
gallery::jg_video_online_dailymotion[role="mb-5"]

=== VK

VK (vk.com), former Vkontakte.ru until January 2012, is a multilingual social
network operated from Russia. Registered users can create a profile on VK and
exchange information with other users.

According to the operator, as of March 2014, there were over 100 million
active users, mainly in Russia, Ukraine, and other Russian spoken countries.
According to Alexa Internet, vk.com is among the most popular websites in
Russia.

NOTE: VK is accused of insufficient protection of personal data. The platform
is also openly criticized by neo-Nazi and neo-fascist Groups used without
there being a handle against them so far. To date, the Russian investigative
authorities (especially the FSB) have not made any efforts to identify
right-wing extremists or to suppress racist currents on the platform.

.VK Video Gallery - Wildlife
gallery::jg_video_online_vk[role="mb-5"]


== What next

Images and videos are pretty visual. And it can be impressive, for sure.
But the most visual component is the text for all pages, for all sites on the
Internet. To see how text could be presented great for modern responsive
websites, check the section Typography next.

What? Please find out how it works. Go for: link:{url-roundtrip--typography}[Typography], then.
