---
title:                                  Master Slider
tagline:                                common templates
date:                                   2020-11-03 00:00:00
description: >
                                        Welcome to the preview page focussing on the image module. This page
                                        shows some valuable features of the J1 Template to manage your image-based
                                        content using Master Slider.

categories:                             [ Testpages ]
tags:                                   [ Example ]

comments:                               false
fab_menu_id:                            page_ctrl_simple

permalink:                              /pages/public/previewer/masterslider/
regenerate:                             false

resources:                              [ animate, lightbox, lightGallery, masterslider ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50

      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       https://unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

Welcome to the preview page focussing on the image module. This page
shows some valuable features of the J1 Template to manage your image-based
content using Master Slider.

== Slider 1 - Simple Boxed

lorem:sentences[3]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00001[role="mt-3 mb-5"]


== Slider 2 - Full Width

lorem:sentences[3]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00002[role="mt-3 mb-5"]


== Slider 3 - SlideInfo (Boxed|Animated)

lorem:sentences[3]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00003[role="mt-3 mb-5"]


== Slider 4 - ThumbView (position right|vertical)

lorem:sentences[2]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00004[role="mt-3 mb-5"]


== Slider 5 - ThumbView  (position bottom|horizontal)

lorem:sentences[2]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00005[role="mt-3 mb-5"]


== Slider 6 - ThumbNail  (position bottom|horizontal)

lorem:sentences[2]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00006[role="mt-3 mb-5"]


== Slider 7 - ThumbNail  (position right|vertical)

lorem:sentences[2]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00007[role="mt-3 mb-5"]


== Slider 8 - Blog articles (PartialView)

lorem:sentences[3]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00008[role="mt-3 mb-5"]


== Slider 9 - PartialView/MS-Info (info position below)

lorem:sentences[3]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00009[role="mt-3 mb-5"]



++++
<style>



</style>
++++
