---
title:                                  Translation Tester
tagline:                                google translate
date:                                   2020-11-03 00:00:00 +100
description: >
                                        The free service from Google translates words,
                                        sentences and websites between
                                        100+ languages vice versa ​​in a matter of seconds.

categories:                             [ Testpages ]
tags:                                   [ Example ]

comments:                               false
fam_menu_id:                            page_ctrl_simple

permalink:                              /pages/public/previewer/google-translator/
regenerate:                             false

resources:                              [
                                          clipboard, rouge, carousel, lightbox,
                                          justifiedGallery, lightGallery
                                        ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       https://unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// https://www.py4u.net/discuss/929705

// Include sub-documents
// -----------------------------------------------------------------------------
Machine translation (MT) transfers information from one language to another
by a computer without human intervention. NMT is the most advanced method
of computer-generated translations. Thanks to autonomous learning based on
artificial intelligence.

== Neural Machine Translation

Neural Machine Translation (NMT) works on a completely different principle
than previous statistics-based or rule-based machine translation methods.
The NMT uses a large neural network based on the human brain model with
the help of artificial intelligence.

The NMT is the most advanced method of computer-generated translations.
Thanks to autonomous learning based on artificial intelligence, Big Data,
and Deep Learning, this method has made enormous progress in the last recent
years. Nowadays, neural machine translation programs can be used as a basis
for professional translations.

Neural algorithms can generate accurate translations as well as *learn* a
language. This technology improves the quality of the translated data
continuously. For the NMT to work well, it must be trained to be used.
Training means that a large amount of data feeds the algorithms to
improve the reliability of the final results.

== Translation issues

Human language translation is a tricky business. Languages offer many ways
of expressing something. Languages use different letter systems, grammar,
and spelling. A lot of pitfalls are on the way from one language to another.

Read about the the most frequent sources of issues with the sections below.

=== Everyday language (slang)

Everyday language is exposed to rapid social development. Nobody knows which
words that are currently on everyone's lips are yesterday's news again. In
addition, terms change their meaning.

=== Grammar

NMT marks the beginning of a new era for artificial intelligence. Neural
networks for translation no longer operate according to the rules of grammar.
These procedures establish their own rules and even create their own (meta-)
language.

NMT algorithms first translate the sentences of a text into their own machine-
language. Then the algorithm *thinks* about how this machine text is translated
into an understandable sentence for the human language. Quite similar what
a human brain would do.

=== Spelling

The next issue comes up by written words in large and lower case. In English,
for example, it is often not clear whether there are words the lower case
ones are nouns or verbs.

Usually, people recognize it based on their language experience in no time.
Computer algorithms do not. They require a lot of calculations to find this
out.

=== Ambiguity

The problem with any translation is ambiguity. Human beings notice ambiguities
mostly not because they usually recognize the meaning through the relationship.
The problems related to ambiguity cannot be solved either by more data. The
opposite is the case. Larger amounts of data can even worsen the problem because
more ambiguities arise (Paradox of Knowledge).

One study tested Google Translate from 2010 to 2013 with the same text.
2010 was the translation bad. In 2011, the translation got better, and in
2012 it got even better. However, in 2013 the quality of the translation
fell and got worse again.

=== Poems or verse

Artificial intelligence continues to struggle with the enormous complexity
of human language, and nowhere is language as complex and meaningful as in
literature. In music, novels, poems, and plays, the beauty of words often
lies in nuance and subtlety.

A very successful way out of the *hell of complexity* for the translation
of lyrical texts is proven by the algorithms of the NMT (Neural Machine
Translation). These systems can learn over time, including the complexity
of literary translations.

=== Recommondations

For a correct translation, it is recommended to use simple language that
does not use country-specific expressions (slang). A simple structure of
the sentences will help enormously to consider the foreign language's
grammar and spelling.

Write short sentences and especially avoid complicated subordinate clauses.
Avoid rare words or words that are only used in certain languages. A simple
language will not always be easy, especially when good language is important
for you.

Test your text with freely available translators on the internet to check
the outcomes. Those first translations will be the base for optimizations
on your text for internationalization.

Writing texts for machine translation is a thing of its own. If you run a
website international, the effort will be very worthwhile.

== Translation with Google

The free service from Google translates words, sentences and websites between
100+ languages vice versa ​​in a matter of seconds.

[WARNING]
====
Google uses cookies to provide its services, personalize ads and analyze
traffic. You can adjust your privacy settings at any time in the Google
settings.
====

According to Google's own information, 3.5 million users had already made
90 million suggestions for changes in April 2016. For common languages such
as English, German, French and Italian, Google uses the Neural Machine
Translation System (GNMT). GNMT is based on neural networks. Here, not every
word is translated individually, but entire sentences and words are placed in
context with one another.

Try the translator with _Jekyll One_ and _Google Translate_ on your own!

=== Text examples

Check the quality of Deepl's NMT engine. Translate some of the passages from
the sections. See typical machine translation limitations with the following
examples.

==== Slang

Slang is a typically spoken language, not written. Many slang words are not
known to the algorithms because they are seldom used for written text. Unknown
words or proper names are not translated and returned for translation as they
are.

.Means: a man
----
Bloke would be the American English equivalent of dude.
----

Everyday language use quite often common words in a different meaning. A good
reason to avoid such expressions.

.Means: Not my thing
----
Not my religion
----

==== Grammar

Typical mistakes students make are bloopers. Translations may become wrongly
understood sometimes the same way.

.Language blooper
----
The thing that first caught my eye was a large silver cup that Charles
had won for skating on the mantelpiece
----

==== Ambiguities

Human languages are full of ambiguities. A good example of using them
explicitly is a Joke.

.Jokes
----
A man tells his doctor: “Doc, help me. I’m addicted to Twitter!
The doctor replies: Sorry, I can't follow you.
----

==== Song lyrics

Many translations for song lyrics are wrong and do not give meaning to what
the artists express. The reason: using machine translators of bad quality.

++++
<br/>
++++

[quote, Love of a Lifetime - FireHouse]
____
I guess the time was right for us to say +
we'd take our time and live our lives together day by day +
We'll make a wish and send it on a prayer +
We know our dreams can all come true with love that we can share

With you I never wonder +
will you be there for me? +
With you I never wonder +
you're the right one for me

I finally found the love of a lifetime +
A love to last my whole life through +
I finally found the love of a lifetime +
forever in my heart
____

== Translation languages

++++
<div class="ct-topbar">
  <div class="container">
    <ul class="list-unstyled">
      <li><a href="#void" class="lang-select" src-lang="en" dest-lang="en"><i class="flag-icon flag-icon-gb rectangle size-md" alt="English"></i></a> English</li>
      <li><a href="#void" class="lang-select" src-lang="en" dest-lang="de"><i class="flag-icon flag-icon-de rectangle size-md" alt="German"></i></a> German</li>
      <li><a href="#void" class="lang-select" src-lang="en" dest-lang="es"><i class="flag-icon flag-icon-es rectangle size-md" alt="Spanish"></i></a> Spanish</li>
      <li><a href="#void" class="lang-select" src-lang="en" dest-lang="fr"><i class="flag-icon flag-icon-fr rectangle size-md" alt="French"></i></a> French</li>
    </ul>
  </div>
</div>
++++

++++
<style>

/* hide the suggestion box */
#goog-gt-tt, .goog-te-balloon-frame {
  display: none !important;
}
.goog-text-highlight {
  background: none !important;
  box-shadow: none !important;
}

/* hide the powered by */
.goog-logo-link {display: none !important;}
.goog-te-gadget {height: 28px !important;  overflow: hidden;}

/* remove the top frame */
body{ top: 0 !important;}
.goog-te-banner-frame{display: none !important;}

</style>
++++

++++
<script>

  var gtranslate = true;

  // ---------------------------------------------------------------------------
  // helper functions
  // ---------------------------------------------------------------------------
  function googleTranslateElementInit() {
    new google.translate.TranslateElement({
      pageLanguage: 'en',
      layout: google.translate.TranslateElement.FloatPosition.TOP_LEFT
    },
    'google_translate_element'
    );
  }

  // Set a Cookie
  function setCookie(options /*cName, cValue, expDays*/) {
    var defaults = {
        name: '',
        path: '/',
        expires: 0,
        domain: 'localhost'
    };
    var settings = $.extend(defaults, options);

    var date = new Date();
    date.setTime(date.getTime() + (settings.expires * 24 * 60 * 60 * 1000));
    const expires = "expires=" + date.toUTCString();
    // document.cookie = cName + "=" + cValue + "; " + expires + "; path=/";
    // document.cookie = settings.name + "=" + settings.data  + "; " + expires + "; path=/";
    document.cookie = settings.name + "=" + settings.data  + "; path=/";
  }

  // ---------------------------------------------------------------------------
  // event handler
  // ---------------------------------------------------------------------------
  window.onload = function (event) {
    var cookie_names  = j1.getCookieNames();
    var date          = new Date();
    var timestamp_now = date.toISOString();
    var user_state    = j1.readCookie(cookie_names.user_state);
    var user_consent  = j1.readCookie(cookie_names.user_consent);
    var head          = document.getElementsByTagName('head')[0];
    var script        = document.createElement('script');

    // set script details for google-translate
    script.id  = 'google-translate';
    script.src = '//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';

    // set current TS
    user_state.last_session_ts = timestamp_now;

    // enable|disable google-translate
    if (!user_consent.personalization || !gtranslate) {
      user_state.google_translate = 'disabled';
      cookie_written = j1.writeCookie({
        name:     cookie_names.user_state,
        data:     user_state,
        samesite: 'Strict',
        expires:  0
      });
      j1.removeCookie({name: 'googtrans'});
    } else {
      user_state.google_translate = 'enabled';
      cookie_written = j1.writeCookie({
        name:     cookie_names.user_state,
        data:     user_state,
        samesite: 'Strict',
        expires:  365
      });
      head.appendChild(script);
    }
  }; // END onload

  $('.lang-select').click(function() {
    var srcLang   = $(this).attr('src-lang');
    var destLang  = $(this).attr('dest-lang');
    var transCode = '/' + srcLang + '/' + destLang;

    // set new language settings
    setCookie({
      name: 'googtrans',
      data: transCode
    });

    // relod the page to apply new language settings
    // window.location = window.location.pathname;
    location.reload();
  });

</script>
++++
