---
title:                                  Translation
tagline:                                j1 translator
date:                                   2021-10-06 00:00:00 +100
description: >
                                        Translate with the _Deepl_. J1 integrates the _Deepl_ for free translations
                                        (Free API) as well as for the professional version of the Pro API. The API
                                        in version 2 offers one of the best machine translation technologies
                                        for 26 popular spoken languages worldwide.

categories:                             [ Previewer ]
tags:                                   [ Translator, Deepl ]

comments:                               false
fam_menu_id:                            page_ctrl_simple

permalink:                              /pages/public/previewer/translator/
regenerate:                             false

resources:                              [ j1deepl ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       https://unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// https://github.com/EdwardBalaj/Simple-DeepL-API-Integration

// Include sub-documents
// -----------------------------------------------------------------------------

== Translation with Deepl

Translate with the _Deepl_. J1 integrates the _Deepl_ for free translations
(Free API) as well as for the professional version of the Pro system. The API
in version 2 offers one of the best machine translation technologies for 26
popular spoken languages worldwide.

++++
<div class="mt-3">

	<form id="layout">
		<!-- Source languages -->
    <div class="form-group bmd-form-group">
      <select id="source-language" class="form-control">
        <option selected value="auto">Auto Detection</option>
        <option value="CS">Czech</option>
        <option value="DA">Danish</option>
        <option value="DE">German</option>
        <option value="ES">Spanish</option>
        <option value="EN">English</option>
        <option value="EL">Greek</option>
        <option value="FI">Finnish</option>
        <option value="FR">French</option>
        <option value="HU">Hungarian</option>
        <option value="IT">Italian</option>
        <option value="NL">Dutch</option>
        <option value="PT">Portuguese</option>
        <option value="RO">Romanian</option>
        <option value="RU">Russian</option>
        <option value="SK">Slovak</option>
        <option value="SL">Slovenian</option>
        <option value="SV">Swedish</option>
        <option value="SV">Swedish</option>
      </select>
      <label for="source-language" class="bmd-label-floating">Source Languages</label>
    </div>

    <div id="source-group"class="form-group bmd-form-group mb-4">
      <textarea id="original-text" class="form-control" type="text" rows="5"></textarea>
      <label for="original-text" class="bmd-label-floating ml-0 mt-0">Your text</label>
    </div>

		<!-- Destination languages -->
		<div id="destination">
      <div class="form-group bmd-form-group">
        <select id="destination-language" class="form-control" name="destination-language">
  				<option value="BG">Bulgarian</option>
  				<option value="CS">Czech</option>
  				<option value="DA">Danish</option>
          <option value="DE">German</option>
          <option value="EL">Greek</option>
          <option value="ES">Spanish</option>
          <option selected value="EN">English</option>
  				<option value="EN-US">English (American)</option>
  				<option value="EN-GB">English (British)</option>
  				<option value="ET">Estonian</option>
  				<option value="FI">Finnish</option>
  				<option value="FR">French</option>
  				<option value="HU">Hungarian</option>
  				<option value="IT">Italian</option>
  				<option value="JA">Japanese</option>
  				<option value="LV">Latvian</option>
  				<option value="LT">Lithuanian</option>
          <option value="NL">Dutch</option>
  				<option value="PL">Polish</option>
          <option value="PT">Portuguese</option>
  				<option value="PT-PT">Portuguese (Portugal)</option>
  				<option value="PT-BR">Portuguese (Brazilian)</option>
  				<option value="RO">Romanian</option>
  				<option value="RU">Russian</option>
  				<option value="SK">Slovak</option>
  				<option value="SL">Slovenian</option>
  				<option value="SV">Swedish</option>
          <option value="ZH">Chinese</option>
        </select>
        <label for="destination-language" class="bmd-label-floating">Destination Languages</label>
      </div>

      <div id="translated-group" class="form-group bmd-form-group">
        <textarea id="translated-text" class="form-control"  type="text" rows="5"></textarea>
        <label for="translated-text" class="bmd-label-floating ml-0 mt-0">Your translation</label>
      </div>

      <!-- Translation control buttons -->
  		<input id="translate" class="btn btn-info btn-raised mt-5" style="min-width: 10rem" type="button" value="Translate">
      <button id="clear-translate" type="button" name="clear"
        class="btn btn-raised btn-flex btn-primary mt-5 ml-2"
        aria-label="Clear Button">
        Clear Translation
      </button>

		</div>

	</form>
</div>

<style>

.form-control {
  line-height: 1.5 !important;
}

textarea {
	min-height: 8em;
}

</style>

<script>
  $(document).ready(function() {
    // clear all text-area elements
    $('#clear-translate').click(function() {
      $("#original-text").val('');
      $("#translated-text").val('');

      // manually reset filled state
      $('#source-group').removeClass('is-filled');
      $('#translated-group').removeClass('is-filled');

    });

    // run translation
    $('#translate').click(function() {
      var fromLanguage  = $('#source-language').val();
      var toLanguage    = $('#destination-language').val();

      // Create new translations (jquery objects)
      $('#original-text').j1deepl({
        api:      'pro',
        auth_key: '1c360075-1a30-28c7-e4eb-2c0c0164ce4b',
        source_lang: fromLanguage,
        target_lang: toLanguage,
        targetElement: '#translated-text'
      });
      // destroy existing jquery objects for next translation
      $('#original-text').j1deepl('destroy');

      // manually set filled state
      $('#translated-group').addClass('is-filled');
     });
  });
</script>
++++
