---
title:                                  J1 Gallery
title_extention:                        Preview supported Galleries
tagline:                                Preview supported Galleries

date:                                   2023-10-18
#last_modified:                         2023-01-01

description: >
                                        J1 Template support valuable features to manage your image-based
                                        content using lightboxes, carousels, sliders, and galleries.
                                        The image modules of J1 Template offer a wide range of complex
                                        functionality based on powerful Open Source libraries like
                                        Lightbox2, Master Slider, lightGallery, or Justified Gallery
                                        for high-end, masonry-styled preview maps.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        image, lightbox, carousel, slider, gallery,
                                        lightbox2, master slider, lightgallery, justifiedgallery

categories:                             [ Previewer ]
tags:                                   [ Module, Gallery ]

image:
  path:                                 /assets/image/modules/attics/1920x1280/quino-al-2.jpg
  width:                                1920
  height:                               1280

toc:                                    true
tts:                                    true
comments:                               false
exclude_from_search:                    false
fab_menu_id:                            open_toc
personalization:                        true
regenerate:                             false
permalink:                              /pages/public/tools/previewer/vjs_shared/

resources:                              [
                                          animate, clipboard,
                                          gallery, lightbox, lightgallery,
                                          rouge, videojs
                                        ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/modules/attics/1920x1280/quino-al-2.jpg
          alt:                          Photo by Quino Al Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Quino Al Angel
            href:                       //unsplash.com/@quinoal
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-lightbox2--home:                   https://lokeshdhakar.com/projects/lightbox2/
:url-lightbox2--github:                 https://github.com/lokesh/lightbox2/

:url-justified-gallery--home:           https://miromannino.github.io/Justified-Gallery/
:url-justified-gallery--github:         https://github.com/miromannino/Justified-Gallery/

:url-j1-docs--carousel-module:          https://jekyll.one/pages/public/manuals/modules/carousel/
:url-j1-docs--lightbox-module:          https://jekyll.one/pages/public/manuals/modules/lightbox/
:url-j1-docs--masterslider-module:      https://jekyll.one/pages/public/manuals/modules/masterslider/

:url-j1-slick-previewer:                https://jekyll.one/pages/public/tools/previewer/slick/
:url-j1-masonry-previewer:              http://localhost:41000/pages/public/tools/previewer/masonry/
:url-j1-masterslider-previewer:         https://jekyll.one/pages/public/tools/previewer/masterslider/
:url-j1-lightGallery-previewer:         http://localhost:41000/pages/public/tools/previewer/lightgallery/

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Welcome to the preview page focussing on image modules. This page shows
all of the powerful features of the J1 Template to manage your image-based
content using lightboxes and galleries.

mdi:clock-time-five-outline[24px, md-gray mt-4 mr-2]
*15-30 Minutes* to read

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== FlvH265 VideoJS

This is a Video.js [Tech](https://docs.videojs.com/tutorial-tech_.html) for
FLV + H265. Make [Video.js](https://videojs.com/) has the ability to play
flv + live/local video encoded with h264/h265.It's decoder comes from
[WXInlinePlayer](https://github.com/coffe1891/WXInlinePlayer).

++++
<video id="player"
  height="300"
  width="600"
  class="video-js vjs-big-play-centered"
  controls
  autoplay
  loop
  ish265
  islive
  hasvideo
  hasaudio
>
  <source src="//localhost:40000/assets/videos/gallery/h265/5s_265.flv" type='video/x-flv'/>
</video>

<script>
  $(function() {
    videojs('player', {
      techOrder: [
        'html5',
        'flvh265'
      ],
      controlBar:{
        pictureInPictureToggle:false
      }
    });
  });
</script>
++++



/////
[role="mt-5"]
== Shared VideoJS

Justified Gallery uses a so-called masonry grid layout. It works by placing
elements in an optimal position based on available horizontal and vertical
space. Sort of like mason fitting stones in a wall. You'll have seen it already
in use all over the Internet, for sure.

++++
<video
  id="vjs-shared"
  class="video-js vjs-default-skin"
  controls>
    <source src="//vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
</video>

<script>
  $(function() {
    var vjsPlayer = videojs('vjs-shared');
    vjsPlayer.share({
      fbAppId: '150778729046724',
    });
  });
</script>
++++
/////
