---
title:                                  Tester
title_extention:                        SlimSelect and IconPicker API
tagline:                                SlimSelect and IconPicker

date:                                   2024-03-16
#last_modified:                         2024-01-01

description: >
                                        SlimSelect is an advanced Javascript API for the browser to
                                        create featured configurable (HTML) select dropdowns. Icon
                                        Picker is a Javascript API that creates picker interfaces to
                                        display and select icons from any icon library in a user-friendly
                                        UI.
keywords: >
                                        open source, free, template, jekyll, jekyllone, static web,
                                        sites, jamstack, bootstrap, select, dropdown,
                                        SlimSelect, IconPicker

categories:                             [ Tester ]
tags:                                   [ Module, slimSelect, IconPicker ]

image:
  path:                                 /assets/images/pages/roundtrip/icon-fonts-1920x1280-bw.jpg
  width:                                1920
  height:                               1280

regenerate:                             false
permalink:                              /pages/public/test_icon_picker/

resources:                              [
                                          animate, clipboard,
                                          iconpicker
                                        ]
resource_options:
  - attic:
      padding_top:                      600
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/roundtrip/icon-fonts-1920x1280-bw.jpg
          alt:                          Icon Fonts
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

{% comment %} Process YML config data (slim_select)
================================================================================ {% endcomment %}

{% comment %} Set config files
-------------------------------------------------------------------------------- {% endcomment %}
{% assign modules              = site.data.modules %}

{% comment %} Set config data (settings only)
-------------------------------------------------------------------------------- {% endcomment %}
{% assign icon_picker_defaults = modules.defaults.icon_picker.defaults %}
{% assign icon_picker_settings = modules.icon_picker.settings %}

{% comment %} Set config options
-------------------------------------------------------------------------------- {% endcomment %}
{% assign icon_picker_options  = icon_picker_defaults | merge: icon_picker_settings %}

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// See: https://github.com/brianvoe/slim-select
// See: https://slimselectjs.com/

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="dropcap"]
SlimSelect is an advanced Javascript API for the browser to create featured
configurable (HTML) select dropdowns. Icon Picker is a Javascript API that
creates picker interfaces to display and select icons from any icon library
in a user-friendly UI.

mdi:clock-time-five-outline[24px, md-gray mt-4 mr-2]
*5-10 Minutes* to read.


[role="mt-5"]
== Introduction

The tester combines both APIs to create a user interface to select and show
supported icon sets. J1 Theme supports out-of-the-box popular icon font sets.
The available icon sets Material Design Icons MDI and FontAwesome FA are excellent
in design and have a rich set of icons for many categories typically used on
web pages.

The J1 Icon Picker supports the following icon sets:

* link:{url-mdil--preview}[Material Design Light Icons MDIL,  {browser-window--new}], 260+ icons of version 0  (February 2024)
* link:{url-mdi--preview}[Material Design Regular Icons MDI,  {browser-window--new}], 7200+ icons of version 7 (March 2024)
* link:{url-fontawesome--free-preview}[FontAwesome Icons FA,  {browser-window--new}], 2000+ icons of the *free* version 6 (March 2024)

[role="mt-4"]
.Icon sets
[NOTE]
====
The *free* version of FontAwesome does *not* support the *full* icon set
available for FA. The commercial Pro Version supports *26000+* icons but
requires a *paid* subscription plan.

The MDI *Base* Icons is a *subset* of about 2600+ icons taken out of the
full set provided by the *regular* MDI icon set. Because the regular
icon set is very huge, 7200+ icons, for performance reasons it is *not*
recommended to load all icons while a page is being initialized.
====


[role="mt-5"]
== Select Icons

Select the icon set to be shown from the *dropdown* below. To open a picker UI
for the icon set selected, click on the button *SHOW ICON SET SELECTED*.

[role="mt-4 mb-5"]
[TIP]
====
*Double-click* an icon in the Picker UI to copy the selected icon data to the
*clipboard*.
====

// Button to open the picker UI for the selected icon set
++++
<div class="{{icon_picker_options.picker_button_wrapper_classes}}">
  <a id="{{icon_picker_options.picker_button_id}}" href="#"
     class="{{icon_picker_options.picker_button_classes}}"
     aria-label="{{icon_picker_options.picker_button_label}}">
     <i class="mdi mdi-{{icon_picker_options.picker_button_icon}} mdi-2x mr-2"></i>
     {{icon_picker_options.picker_button_label}}
  </a>
</div>
++++

// Wrapper (div) placed for the <select> loaded by module slimSelect
slimSelect::icon_library_select_wrapper[role="mt-4 mb-7"]

[[dummy]]
=== Dummy
