---
title:                                  Canonical Links
tagline:                                Specify Original Content
#date:                                  2023-07-08 00:00:00 +0100

categories:                             [ Jekyll, Featured ]
tags:                                   [ Template, Canonical, Links ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/alina-grubnyak.jpg
  width:                                1920
  height:                               1200
  alt:                                  Jekyll for Everyone

group:                                  Featured
series:                                 Featured
regenerate:                             false

resources:                              [ animate, rouge ]
resource_options:
  - attic:
      padding_top:                      600
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/alina-grubnyak.jpg
          alt:                          Photo by Alina Grubnyak on Unsplash
          badge:
            type:                       unsplash
            author:                     Alina Grubnyak
            href:                       https://unsplash.com/@alinnnaaaa
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-rfc--6596:                         https://datatracker.ietf.org/doc/html/rfc6596
:url-previewer--rouge:                  https://jekyll.one/pages/public/tools/previewer/rouge/
:url-roundtrip--rouge:                  https://jekyll.one/pages/public/learn/roundtrip/rouge/

// Place an excerpt at the most top position
// -----------------------------------------------------------------------------
[role="dropcap"]
A canonical link (canonical URL) allows website operators in an HTML document
to identify the original resource with the content used more than once
(duplicate content).

excerpt__end

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
This link type is defined in link:{url-rfc--6596}[{RFC 6596}] and is assigned
as a link element to the *canonical attribute*, noted in the `<head>` section
of an HTML document.

.Example
[sourve, html]
----
<link rel="canonical" href="https://example.com/canonical_link/">
----

== Why to specify canonical links

Several URIs often refer to the same content. Examples are dynamically
generated content, as in forums or others. Content management systems (CMS) or
website generators (SSGs) like _Jekyll_ may reference to URLs where the
same (or similiar) content available is under different addresses.

Linking websites, particularly search engines with their link databases,
can thus find the original document for a page and click on it in the search
results. The attribute was introduced by search engine operators, above all
Google, to make it easier for their web crawlers the primary resource to
be identified with certainty.

CAUTION: Incorrect use of canonical links (e.g., multiple in one
HTML document placement of the item in the search results deteriorates
or leads to deletion from the search engine's index. It is highly
recommended to specify the URL of the original content when other pages
use the same or quite similia content.


[role="mt-5"]
== Generate canonical links using J1

For J1 Template it is very easy to specify the URL of the original content
by using the `canonical` tag in the *frontmatter* of a `page` or `post`:

.Frontmatter example
[source, yaml]
----
---
  title:                                  Rouge
  tagline:                                Code Highlighter

  ...

  canonical:                              true
  regenerate:                             false
  permalink:                              /pages/public/learn/roundtrip/rouge/

  ...
----

NOTE: For the build-in web, the source code of the *previewer* page at
link:{url-previewer--rouge}[Rouge -- Highlighter Themes, {browser-window--new}]
is quite similiar to link:{url-roundtrip--rouge}[Roundtrip -- Rouge, {browser-window--new}].
