---
title:                                  Is Jekyll Still Used
tagline:                                Jekyll In 2023

categories:                             [ FAQ ]
tags:                                   [ Jekyll ]

series:                                 faq

image:
  path:                                 /assets/images/promo/jekyll/jekyll-generator.jpg
  width:                                1920
  height:                               1200
  alt:                                  Jekyll Static Site Generator

fab_menu_id:                            default
comments:                               false
regenerate:                             false

share:                                  facebook

resources:                              [ animate ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/promo/jekyll/jekyll-generator.jpg
          alt:                          Jekyll Static Site Generator
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        false

// Place an excerpt at the most top position
// -----------------------------------------------------------------------------
[role="dropcap"]
Description|Excerpt to be changed.

excerpt__end

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Static Site Generator: SSG

// Include sub-documents (if any)
// -----------------------------------------------------------------------------


// == Is Jekyll Still Used?

lorem:sentences[5]

lorem:sentences[5]

lorem:sentences[5]

lorem:sentences[5]

////

=== Is Jekyll a CMS?

lorem:sentences[5]

=== Is Jekyll faster than WordPress?

lorem:sentences[5]

=== Is Jekyll a framework?

lorem:sentences[5]

=== Is Jekyll a programming language?

lorem:sentences[5]

=== Is Jekyll based on Ruby?

lorem:sentences[5]

=== Is Jekyll a Ruby gem

lorem:sentences[5]

=== Is Jekyll using Ruby on Rails?

lorem:sentences[5]

=== Is knowledge of Ruby needed to use Jekyll?

lorem:sentences[5]

////
