== Text-fitting and Printing

lorem:sentences[5]
lorem:sentences[3]

=== Autofitting Text

Verbatim blocks often have long lines that don't fit within the fixed width
of the PDF canvas. And unlike on the web, the PDF reader cannot scroll
horizontally to reveal the overflow text. Therefore, the long lines are
forced to wrap. Wrapped lines can make the verbatim blocks hard to read or
even cause confusion.

To help address this problem, _Asciidoctor PDF_ provides the `autofit` option
on all verbatim (i.e., literal, listing and source) blocks to attempt to fit
the text within the available width. When the `autofit` option is enabled,
_Asciidoctor PDF_ will decrease the font size until the longest line fits without
wrapping.

CAUTION: The font size will not be decreased beyond the value of the
`base_font_size_min` key specified in the PDF theme. If that threshold is
reached, lines may still wrap.

Here's an example of the autofit option enabled on a source block:

[source,asciidoc]
....
[source%autofit,java]
----
@SessionScoped
public class WidgetRepository {
    @GET
    @Produces("application/json")
    public List<String> listAll(@QueryParam("start") Integer start, @QueryParam("max") Integer max) {
        ...
    }
}
----
....

If you want to enable the autofit option globally, set the `autofit-option`
document attribute in the document header (or somewhere before the relevant
blocks):

[source,asciidoc]
----
:autofit-option:
----

=== Printing Pages

The print dialogfor printing *ranges* doesn't understand the page numbers
labels (which appear in the running content). Instead, it only considers
physical pages. Therefore, to print a range of pages as they are labeled in
the document, you need to add the number of front matter pages (i.e., the
non-numbered pages) to the page number range in the print dialog.

For example, if you only want to print the first 5 pages labeled with a page
number (e.g., 1-5), and there are 2 pages before the page labeled as page 1,
you need to add 2 to both numbers in the range, giving you a physical page
range of 3-7. That's the range you need to enter into the print dialog.
