

[[resources,Links]]
== Resources

lorem:sentences[3]

=== Optional Scripts

_Asciidoctor PDF_ also provides a shell script that invokes _GhostScript_ (`gs`)
to optimize and compress the generated PDF with minimal impact on quality.
You must have _GhostScript_ installed to use it.

Here's an example usage:

 $ ./bin/optimize-pdf basic-example.pdf

The command will generate the file *example-optimized.pdf* in the current
directory.

WARNING: The `optimize-pdf` script currently requires a Bash shell (Linux,
OSX, etc). We plan to rewrite the script in _Ruby_ so it works across platforms
(see {uri-asciidoctor-pdf}[issue #1, {browser-window--new}])

IMPORTANT: The `optimize-pdf` script relies on _GhostScript_ >= 9.10.
Otherwise, it may actually make the PDF larger. Also, you should only
consider using it if the file size of the original PDF is > 5MB.

If a file is found with the extension `.pdfmark` and the same rootname as the
input file, it is used to add metadata to the generated PDF document. This file
is necessary to preserve the document metadata since _GhostScript_ will otherwise
drop it. That's why _Asciidoctor PDF_ always creates this file in addition to the PDF.

=== Image quality

lorem:sentences[5]

* {uri-google-groups-image-quality}[Discussion about image quality in PDFs, {browser-window--new}]
