---
title:                                  Speak2Me Tester
title_extention:                        jQuery plugin for Speech Synthesise
tagline:                                Speech synthesise

date:                                   2023-07-26
#last_modified:                         2023-01-01

description: >
                                        Speak2Me is a jQuery plugin that enables developers,
                                        with as little as one line of code, to create links
                                        that allow users to click, sit back, and listen to
                                        the browser read aloud the important content on
                                        a Web page.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        speech, synthesise, sst, j1 module, jquery

categories:                             [ Tester ]
tags:                                   [ Speech Synthesise, jQuery ]

regenerate:                             true
permalink:                              /pages/public/learn/s2m_tester/

resources:                              [ animate, clipboard, lightbox, rouge, speak2me]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       https://unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// https://github.com/mdn/dom-examples/tree/main/web-speech-api
// https://mdn.github.io/dom-examples/web-speech-api/speak-easy-synthesis/
// https://stackoverflow.com/questions/11279291/a-good-text-to-speech-javascript-library
// https://github.com/acoti/articulate.js
// https://codepen.io/meetselva/pen/EVaLmP

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
// == Tester

++++
<div class="articulate-area mt-5 mb-5" data-speak2me-ignore>

  <h2 class="ml-2 mt-2 mb-4">Voice Settings</h2>
  <div class="mb-3">
    <div>
      <label class="form-label mr-3" for="rate">Speed</label>
      <input id="rate" class="form-range" style="height: unset"
        name="rate"
        type="range"
        min="0.1"
        max="3"
        step="0.1"
        value="1.0"
        oninput="j1.adapter.speak2me.update(this, value)"
        onchange="j1.adapter.speak2me.update(this, value)"
      />
      <span class="val ml-3">1.0</span>
    </div>

    <div>
      <label for="pitch" class="form-label mr-3">Pitch</label>
      <input id="pitch" class="form-range" style="height: unset"
        name="pitch"
        type="range"
        min="0.1"
        max="2"
        step="0.1"
        value="1"
        oninput="j1.adapter.speak2me.update(this, value)"
        onchange="j1.adapter.speak2me.update(this, value)"
      />
      <span class="val ml-3">1.0</span>
    </div>

    <div>
      <label for="volume" class="form-label mr-3">Volume</label>
      <input id="volume" class="form-range" style="height: unset"
        name="volume"
        type="range"
        min="0"
        max="1"
        step="0.1"
        value="1"
        oninput="j1.adapter.speak2me.update(this, value)"
        nchange="j1.adapter.speak2me.update(this, value)"
      />
      <span class="val ml-3">1.0</span>
    </div>

  	<div id="voiceSelect" class="ml-2 mt-3" ></div>

  </div>

  <h2 class="ml-2 mt-4 mb-3">Voice Control</h2>

  <div class="ml-2">
    <!-- button onclick="create('#voiceSelect')">Create Menu</button -->
    <button type="button"
      class="btn btn-primary btn-sm"
      style="min-width: 120px"
      onclick="j1.adapter.speak2me.speak('main')">
      <i class="mdi mdi-speaker mdi-sm mr-2"></i>
      Speak
    </button>

    <!-- button onclick="speak('#w3review')">Speak</button -->

    <button type="button"
      class="btn btn-primary btn-sm"
      style="min-width: 120px"
      onclick="j1.adapter.speak2me.pause()">
      <i class="mdi mdi-pause mdi-sm mr-2"></i>
      Pause
    </button>

    <button type="button"
      class="btn btn-primary btn-sm"
      style="min-width: 120px"
      onclick="j1.adapter.speak2me.resume()">
      <i class="mdi mdi-play-pause mdi-sm mr-2"></i>
      Resume
    </button>

    <button type="button"
      class="btn btn-primary btn-sm"
      style="min-width: 120px"
      onclick="j1.adapter.speak2me.stop()">
      <i class="mdi mdi-speaker-off mdi-sm mr-2"></i>
      Stop
    </button>

    <!-- button onclick="populate()">Populate Table of Voices Below Speech</button -->

    <button onclick="j1.adapter.speak2me.populate()">Populate Table of Voices Below Speech</button>

  </div>

</div>

<div class="voice-table" data-speak2me-ignore>
  <h2>Names and Languages Available</h2>
  <h3>Use these exact names when setting a voice manually.</h3>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Language</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
++++

== Chapter One

Tyrion Lannister, dwarf and exile, stood resolute upon the prow of
the majestic vessel, the Wind's Grace, its timeworn planks creaking
beneath his weight. +
    His mismatched eyes, one green as the emerald depths of the
Whispering Wood, the other a glimmering pale amethyst, stared out into
the boundless expanse of the Narrow Sea. As the ship cut through the
frothing waves, the wind, bearing the salty tang of the ocean, lashed at
his face, sending raven-black locks of hair spiraling across his brow. +
    It was a gusty tempest, much like the swirling turmoil that had
beset his life ever since he had been forced to flee the shores of
Westeros. The crimson light of the setting sun cast an ethereal glow
upon Tyrion's countenance, accentuating the shadows that danced upon his
visage, mirroring the darkness that had shadowed his soul for far too
long. +
    His lips, full and pursed in contemplation, were tinged with a touch
of melancholy, the weight of his troubled past etched upon his face like
the lines of a map charting the arduous journey he had undertaken. +
    Lost in his ruminations, Tyrion found solace in the rhythmic cadence
of the waves crashing against the ship's hull. Each thunderous collision
reverberated through his being, echoing the tumultuous path he had
traversed.

=== Section One

    The sea, a fickle mistress, had become both his savior and his
captor, carrying him away from the turmoil of his homeland, yet never
relinquishing its grip upon his restless spirit. +
    Amidst the roar of the wind and the ceaseless turmoil of the ocean,
a voice emerged from behind him, its tone laced with both concern and
familiarity. "Tyrion," came the gruff voice of Ser Jorah Mormont, his
greying beard glimmering with flecks of gold in the fading light. "Your
thoughts seem as stormy as the sea itself. What troubles your mind, my
friend?" +
    Tyrion turned to face the knight, his gaze meeting Ser Jorah's
piercing eyes, storm-grey and weathered by a life lived on the edge of
peril. A wry smile tugged at the corner of his mouth, a glimmer of
mischief flickering within his gaze. +
    "Ah, Ser Jorah," he replied, his voice carrying a trace of both
resignation and determination. "What troubles my mind? Why, the unending
dance between fate and fortune, of course. It seems the gods have deemed
me a pawn in their ever-twisting game. But fear not, my loyal knight,
for I shall not be so easily swept away by the tides of destiny." +
    The ship, its sails billowing with the force of the wind, continued
its relentless journey across the Narrow Sea, carrying with it the
weight of Tyrion's past and the promise of an uncertain future. As the
fading light bathed the world in hues of fiery amber and burnt sienna,
Tyrion Lannister, the Imp who had defied all expectations, remained
steadfast upon the bow, his resolve unyielding, ready to face whatever
treacherous waters lay ahead.

++++
<script>

  // function create(obj) {
  //   $().speak2me('getVoices', obj, 'Choose a New Voice');
  // }

  // function speak(obj) {
  //
  //   // Get the parameter values from the input sliders
  //   //
  //   var r = parseFloat(document.getElementById('rate').value);
  //   var p = parseFloat(document.getElementById('pitch').value);
  //   var v = parseFloat(document.getElementById('volume').value);
  //
  //   // Note: Function calls can be perfromed individually or
  //   // chained together as demonstrated below
  //   //
  //   $(obj).speak2me('rate',r).speak2me('pitch',p).speak2me('volume',v);
  //   // $(obj).speak2me('ignore', 'h2','h3');
  //   $(obj).speak2me('speak');
  // }

  // function pause() {
  //   $().speak2me('pause');
  // }
  //
  // function resume() {
  //   $().speak2me('resume');
  // }
  //
  // function stop() {
  //   $().speak2me('stop');
  // }

  // function populate() {
  //   $('div.voice-table').show();
  //     var voices = $().speak2me('getVoices');
  //     for (var i = 0; i < voices.length; i++) {
  //       voiceName = voices[i].name;
  //       voiceLang = voices[i].language;
  //       row = "<tr><td>" + voiceName + "</td>";
  //       row += "<td>" + voiceLang + "</td></tr>";
  //       $('table tbody').append(row);
  //     }
  //   }

  // update the value to the right of the input sliders
  //
  // function update(obj,value) {
  //   var n = parseFloat(value).toFixed(1)
  //   $(obj).parent().find('span').text(n);
  // }

  // $(function() {
  //
  //   var dependencies_met_page_ready = setInterval (function (options) {
  //     var pageState     = $('#no_flicker').css("display");
  //     var pageVisible   = (pageState == 'block') ? true : false;
  //     var atticFinished = (j1.adapter.attic.getState() == 'finished') ? true: false;
  //
  //     if (j1.getState() === 'finished' && pageVisible) {
  //       create('#voiceSelect');
  //       clearInterval(dependencies_met_page_ready);
  //     }
  //   });
  //
  // });

</script>
++++
