---
title:                                  Skeleton
tagline:                                simple document
date:                                   2021-01-01 00:00:00 +100
description: >
                                        Simple documents are used quite often. If the number
                                        of chapters is about or less than three and the document
                                        is small in size. This document type does not use any
                                        (local) Asciidoc include files or attributes.

categories:                             [ Knowledge ]
tags:                                   [ Asciidoc, Skeleton, Document ]

sitemap:                                false
advertising:                            false
comments:                               false

robots:
  index:                                false
  follow:                               false

permalink:                              /pages/public/skeleton/simple/
regenerate:                             false

resources:                              []
resource_options:
  - toccer:
      collapseDepth:                    4
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/skeleton/antonino-visalli-1920x1280.jpg
          alt:                          Photo by Antonino Visalli on Unsplash
          alignY:                       top
          badge:
            type:                       unsplash
            author:                     Antonino Visalli
            href:                       https://unsplash.com/@_visalli
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-fontawesome--home:                 https://fontawesome.com/
:url-fontawesome--icons:                https://fontawesome.com/icons?d=gallery/
:url-fontawesome--get-started:          https://fontawesome.com/get-started/

:url-mdi--home:                         https://materialdesignicons.com/
:url-mdi-icons--cheatsheet:             https://cdn.materialdesignicons.com/3.3.92/

:url-iconify--home:                     https://iconify.design/
:url-iconify--icon-sets:                https://iconify.design/icon-sets/
:url-iconify--medical-icons:            https://iconify.design/icon-sets/medical-icon/
:url-iconify--brand-icons:              https://iconify.design/icon-sets/logos/

:url-roundtrip--mdi-icons:              /pages/public/learn/roundtrip/mdi_icon_font/#material-design-icons
:url-roundtrip--fontawesome-icons:      /pages/public/learn/roundtrip/mdi_icon_font/#fontawesome-icons
:url-roundtrip--iconify-icons:          /pages/public/learn/roundtrip/mdi_icon_font/#iconify-icons
:url-roundtrip--asciidoc-extensions:    /pages/public/learn/roundtrip/asciidoc_extensions/

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The Asciidoc skeleton *simple-document* a helper for setting up a base file
and folder structure for simple-document AsciiDoc pages based on _Jekyll_ and
_J1 Template_. You need *both* to use this skeleton creating AsciiDoc
documents from it.

Simple documents are used quite often for documents of a website. If the number
of chapters is about or less than three and the document is small in size,
simple documents should fit. This document type is based on a *single* Asciidoc
document and does *not* use any (local) Asciidoc include files or attributes.

[NOTE]
====
.Moving documents based on a J1 Skeleton

All J1 Asciidoc Skeletons are fully *relocateable* and can be placed in any
subfolder of your Jekyll site.
====

// Include sub-documents
// -----------------------------------------------------------------------------
== Chapter

lorem:sentences[5]

lorem:sentences[3]

=== Section

lorem:sentences[3]

lorem:sentences[5]

==== Subsection

lorem:sentences[5]

lorem:sentences[3]
