---
title:                                  SwiperJS
title_extention:                        Application Interface
tagline:                                Application Interface

date:                                   2025-01-07
#last_modified:                         2025-01-01

description: >
                                        Swiper comes with a very rich API. It allows
                                        creating your own pagination, navigation buttons,
                                        parallax effects and many more.

keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        html, html5, slider, swiper

categories:                             [ Roundtrip ]
tags:                                   [ Module, Swiper ]

image:
  path:                                 /assets/image/modules/attics/markus-spiske-1920x1280.jpg
  width:                                1920
  height:                               1280

attic:                                  false
regenerate:                             true
personalization:                        true
permalink:                              /pages/public/swiper_api/

resources:                              [ swiper ]
resource_options:
  - toccer:
      collapseDepth:                    2
  - attic:
      slides:
        - url:                          /assets/image/modules/attics/markus-spiske-1920x1280.jpg
          alt:                          Swiper API
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Attribute settings for page content control (e.g includes)
//
:documentdir:                           _includes/documents

// Attribute settings for section control
//
:swiper--features:                      false
:swiper--global-options:                true
:swiper-modules:                        /pages/public/swiper_api/#swiper-modules
:swiper-modules--a11y:                  /pages/public/swiper_api/#swiper-modules-a11y

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// See: https://swiperjs.com/swiper-api

[role="dropcap"]
Swiper is a free, modern touch slider with hardware-accelerated transitions.
The slider is intended for desktop websites, mobile (web) apps, and native or
hybrid mobile environments.

Swiper comes with a rich https://swiperjs.com/swiper-api[API, {browser-window--new}].
The programming interface allows developers to create individual user
interfaces (UI) for pagination, navigation and more. Find large number of
complex examples on the pages of the
https://uiinitiative.com/[UI Initiative project, {browser-window--new}].

The rich API makes Swiper an excellent choice for *web developers*, not least
for template systems like J1 Template. In the current version of the J1 template
(version 2025.x), Swiper is the *default slider* and *replaces* the *previously*
used *carousels* _Owl Carousel_, _Slickslider_, and _Masterslider_ by their
implementations based on _SwiperJS_.

The https://swiperjs.com/swiper-api[Swiper API documentation, {browser-window--new}]
pages are based on version *v11.2.1* (January 7, 2025) for the current version
of J1 template (2025.x). The documentation can **generally be used* for all
*web browser-based projects* that use SwiperJS for creating sliders.

The idea of providing this documentation is *not to copy* the *original pages*
as *duplicates*. All pages are restructured and enhanced with code examples
or improved by additional description texts for better readability and
usability.

[NOTE]
====
The documentation pages for the J1 Template project will be used for the 
**AI**-based **chat client** (*planned* for 4th quarter of 2025). The agent
will be trained by all available documentation pages of the Template system
to give users an easy-to-use source for using the J1 Template to create
websites for their needs.

All previously used slider *resources* are available in version 2025.x for
*backward compatibility* but are no longer used for the example
pages of the *built-in web*.
====


// Include sub-documents
// -----------------------------------------------------------------------------
include::{documentdir}/swiper/100_swiper_features.asciidoc[]

include::{documentdir}/swiper/100_swiper_html_layout.asciidoc[]

include::{documentdir}/swiper/100_swiper_initialization.asciidoc[]

include::{documentdir}/swiper/110_swiper_common_options.asciidoc[]


include::{documentdir}/swiper/200_swiper_parameters_a_k.asciidoc[]

include::{documentdir}/swiper/200_swiper_parameters_l_o.asciidoc[]

include::{documentdir}/swiper/200_swiper_parameters_p_s.asciidoc[]

include::{documentdir}/swiper/200_swiper_parameters_t_z.asciidoc[]


include::{documentdir}/swiper/300_swiper_instance_properties.asciidoc[]


include::{documentdir}/swiper/400_swiper_modules.asciidoc[]

include::{documentdir}/swiper/500_swiper_methods.asciidoc[]

include::{documentdir}/swiper/600_swiper_events.asciidoc[]
