/*
 # -----------------------------------------------------------------------------
 # ~/src/js/modules/lit/speak2me-modal.lit.js
 # Lit 3 web component for the J1 speak2me settings modal.
 #
 # Product/Info:
 # https://jekyll.one
 #
 # Copyright (C) 2023-2026 Juergen Adams
 #
 # J1 Template is licensed under the MIT License.
 # See: https://github.com/jekyll-one-org/j1-template/blob/main/LICENSE
 # -----------------------------------------------------------------------------
 # claude - improve SpeakToMe code using lit #1
 #
 # This component is a drop-in replacement for the static modal body that was
 # previously generated by ~/assets/data/speak2me.html (Liquid).  It keeps the
 # exact same Bootstrap markup the rest of the J1 theme expects (modal-dialog,
 # modal-content, modal-header, modal-body, modal-footer, btn-*, form-range,
 # mdib icons), so no CSS changes are needed.
 #
 # Why a web component:
 #   - rate / pitch / volume / selectedVoice become reactive properties — no
 #     more `oninput="j1.adapter.speak2me.update(this, value)"` inline strings
 #   - speak / pause / resume / stop button visibility is bound to state
 #     instead of toggled by id-based `style.display = …` calls
 #   - the voice dropdown is a declarative .map() instead of an imperative
 #     jQuery append loop
 #   - the component dispatches CustomEvents (`j1-speak2me-speak`, `-pause`,
 #     `-resume`, `-stop`, `-update`) AND, for backwards compatibility, still
 #     invokes the existing `window.j1.adapter.speak2me` methods if present
 # -----------------------------------------------------------------------------
*/

// claude - improve SpeakToMe code using lit #1
// Lit 3 is already a direct dependency (package.json: "lit": "^3.3.3").
// We use the static `properties` form rather than the @property decorator so
// no Babel decorator plugin is needed in the existing webpack pipeline.
import { LitElement, html, nothing } from 'lit';

// claude - improve SpeakToMe code using lit #1
// Default labels mirror the YAML defaults from
// ~/_data/modules/defaults/speak2me.yml so the component is usable even
// without Liquid-driven attributes.
const DEFAULT_LABELS = Object.freeze({
  title:          'Speak To Me',
  voiceSettings:  'Voice Settings',
  voiceControl:   'Voice Control',
  speedLabel:     'Speed',
  pitchLabel:     'Pitch',
  volumeLabel:    'Volume',
  speakText:      'Speak',
  pauseText:      'Pause',
  resumeText:     'Resume',
  stopText:       'Stop',
  exitText:       'Exit',
  voicePlaceholder: 'Choose a voice',
});

// claude - improve SpeakToMe code using lit #1
// Default Bootstrap button styles, again mirroring the YAML defaults.
const DEFAULT_STYLES = Object.freeze({
  speakBtn:   'primary',
  pauseBtn:   'warning',
  resumeBtn:  'success',
  stopBtn:    'danger',
  exitBtn:    'secondary',
});

// claude - improve SpeakToMe code using lit #1
// Voice filter constants — preserved verbatim from speak2me.js so behaviour
// is identical to the legacy `getVoices()` implementation.
const IGNORE_PROVIDER = 'eSpeak';

class J1Speak2MeModal extends LitElement {

  // claude - improve SpeakToMe code using lit #1
  // Light DOM rendering: the J1 theme's Bootstrap stylesheet lives in the
  // document scope, so we render into the host element itself instead of an
  // attached Shadow Root.  This is the path of least friction for a drop-in
  // replacement; switching to Shadow DOM later only requires removing this
  // override and adding adopted stylesheets.
  createRenderRoot() {
    return this;
  }

  // claude - improve SpeakToMe code using lit #1
  // Reactive properties.  Note the `attribute` mapping for kebab-case HTML
  // attribute access from the Liquid template.
  static properties = {
    // Voice parameters — bound to the range sliders.
    rate:            { type: Number },
    pitch:           { type: Number },
    volume:          { type: Number },

    rateMin:         { type: Number, attribute: 'rate-min' },
    rateMax:         { type: Number, attribute: 'rate-max' },
    rateStep:        { type: Number, attribute: 'rate-step' },
    pitchMin:        { type: Number, attribute: 'pitch-min' },
    pitchMax:        { type: Number, attribute: 'pitch-max' },
    pitchStep:       { type: Number, attribute: 'pitch-step' },
    volumeMin:       { type: Number, attribute: 'volume-min' },
    volumeMax:       { type: Number, attribute: 'volume-max' },
    volumeStep:      { type: Number, attribute: 'volume-step' },

    // Voice selection.
    voices:          { state: true },          // SpeechSynthesisVoice[]
    selectedVoice:   { type: String, attribute: 'selected-voice' },

    // Playback state — drives button visibility.
    isSpeaking:      { state: true },
    isPaused:        { state: true },

    // Selector used by the legacy `speak()` adapter call.
    speechSelector:  { type: String, attribute: 'speech-selector' },

    // Labels (i18n).  Passed in by the Liquid template; fall back to defaults.
    labels:          { state: true },
    styles:          { state: true },
  };

  constructor() {
    super();
    this.rate          = 1.0;
    this.pitch         = 1.0;
    this.volume        = 1.0;
    this.rateMin       = 0.1;
    this.rateMax       = 10;
    this.rateStep      = 0.1;
    this.pitchMin      = 0.1;
    this.pitchMax      = 2;
    this.pitchStep     = 0.1;
    this.volumeMin     = 0;
    this.volumeMax     = 1;
    this.volumeStep    = 0.1;
    this.voices        = [];
    this.selectedVoice = '';
    this.isSpeaking    = false;
    this.isPaused      = false;
    this.speechSelector = '#content';
    this.labels        = { ...DEFAULT_LABELS };
    this.styles        = { ...DEFAULT_STYLES };

    // claude - improve SpeakToMe code using lit #1
    // Bound handler so we can attach AND remove it on (dis)connectedCallback.
    this._onVoicesChanged = this._loadVoices.bind(this);
  }

  // claude - improve SpeakToMe code using lit #1
  // Standard Lit lifecycle hook.  We hook the SpeechSynthesis voiceschanged
  // event here (rather than in constructor) so the listener is attached only
  // while the component is in the DOM, and detached cleanly on removal — the
  // legacy implementation never cleaned up its `speechSynthesis.onvoiceschanged`
  // assignment, which leaked across page navigations.
  connectedCallback() {
    super.connectedCallback();

    // claude - improve SpeakToMe code using lit #1
    // Pick up labels & styles from the sibling JSON config block emitted by
    // the Liquid template (~/assets/data/speak2me.html).  This is done in
    // connectedCallback rather than in the constructor because the script
    // element is not in the DOM yet at construction time.
    this._loadConfig();

    if ('speechSynthesis' in window) {
      this._loadVoices();
      speechSynthesis.addEventListener('voiceschanged', this._onVoicesChanged);
    }
  }

  // claude - improve SpeakToMe code using lit #1
  // Look for a sibling <script type="application/json" data-j1-speak2me-config>
  // block (the Liquid template emits one) and merge its `labels` and `styles`
  // entries into the component's defaults.  Falls back silently if the block
  // is missing or malformed — the component still works with defaults alone.
  _loadConfig() {
    let script = null;
    const parent = this.parentElement;
    if (parent) {
      script = parent.querySelector('script[data-j1-speak2me-config]');
    }
    if (!script) {
      script = document.querySelector('script[data-j1-speak2me-config]');
    }
    if (!script) return;

    try {
      const cfg = JSON.parse(script.textContent || '{}');
      if (cfg && typeof cfg === 'object') {
        if (cfg.labels && typeof cfg.labels === 'object') {
          this.labels = { ...DEFAULT_LABELS, ...cfg.labels };
        }
        if (cfg.styles && typeof cfg.styles === 'object') {
          this.styles = { ...DEFAULT_STYLES, ...cfg.styles };
        }
      }
    } catch (e) {
      if (window?.j1?.env !== 'prod') {
        console.warn('j1-speak2me-modal: invalid JSON config', e);
      }
    }
  }

  disconnectedCallback() {
    if ('speechSynthesis' in window) {
      speechSynthesis.removeEventListener('voiceschanged', this._onVoicesChanged);
    }
    super.disconnectedCallback();
  }

  // claude - improve SpeakToMe code using lit #1
  // Public API: external code (e.g. the j1.adapter.speak2me bridge) can call
  // these to push state changes into the component.  They replace the legacy
  // pattern of imperatively flipping `document.getElementById('speak_button')
  // .style.display = 'none'` from outside.
  setSpeakingState({ speaking = false, paused = false } = {}) {
    this.isSpeaking = !!speaking;
    this.isPaused   = !!paused;
  }

  setVoiceList(voices) {
    if (Array.isArray(voices)) {
      this.voices = voices;
    }
  }

  // claude - improve SpeakToMe code using lit #1
  // Reads the available SpeechSynthesis voices and applies the same filtering
  // logic used by the legacy `getVoices()` method (skip eSpeak on Chrome,
  // require "Natural" on Edge).  Browser detection is centralised here.
  _loadVoices() {
    if (!('speechSynthesis' in window)) return;
    const ua        = navigator.userAgent;
    const isChrome  = /Chrome/.test(ua) && /Google Inc/.test(navigator.vendor) && !/Edg/.test(ua);
    const isEdge    = /Edg/.test(ua);

    const all = speechSynthesis.getVoices() || [];
    this.voices = all.filter((voice) => {
      if (isChrome && voice.name && voice.name.includes(IGNORE_PROVIDER)) return false;
      if (isEdge && !(voice.name || '').includes('Natural'))               return false;
      return true;
    });
  }

  // claude - improve SpeakToMe code using lit #1
  // Slider change handler.  Updates the reactive property, dispatches a
  // `j1-speak2me-update` CustomEvent for new consumers, AND calls the legacy
  // `j1.adapter.speak2me.update(node, value)` for backwards compatibility
  // with existing code paths.
  _onSliderInput(event) {
    const input = event.target;
    const name  = input.name;          // 'rate' | 'pitch' | 'volume'
    const value = parseFloat(input.value);

    if (Number.isFinite(value) && (name in this)) {
      this[name] = value;
    }

    this.dispatchEvent(new CustomEvent('j1-speak2me-update', {
      detail:   { name, value, source: input },
      bubbles:  true,
      composed: true,
    }));

    // Legacy bridge — keep working with the existing adapter shim.
    const adapter = window?.j1?.adapter?.speak2me;
    if (adapter && typeof adapter.update === 'function') {
      try { adapter.update(input, value); }
      catch (e) { /* swallow — legacy adapter optional */ }
    }
  }

  _onVoiceChanged(event) {
    this.selectedVoice = event.target.value;
    this.dispatchEvent(new CustomEvent('j1-speak2me-voice-changed', {
      detail:   { voice: this.selectedVoice },
      bubbles:  true,
      composed: true,
    }));
  }

  // claude - improve SpeakToMe code using lit #1
  // Generic action dispatcher used by all four control buttons.  Replaces
  // four separate inline `onclick="j1.adapter.speak2me.X()"` attributes.
  _dispatchAction(action) {
    const detail = action === 'speak'
      ? { action, selector: this.speechSelector }
      : { action };

    this.dispatchEvent(new CustomEvent(`j1-speak2me-${action}`, {
      detail,
      bubbles:  true,
      composed: true,
    }));

    const adapter = window?.j1?.adapter?.speak2me;
    if (adapter && typeof adapter[action] === 'function') {
      try {
        if (action === 'speak') adapter.speak(this.speechSelector);
        else adapter[action]();
      } catch (e) {
        // claude - improve SpeakToMe code using lit #1
        // Logging is intentionally minimal here; the adapter has its own
        // dev-mode logger.  We do not swallow silently in development.
        if (window?.j1?.env !== 'prod') {
          console.warn('j1-speak2me-modal: adapter call failed', action, e);
        }
      }
    }
  }

  // claude - improve SpeakToMe code using lit #1
  // Slider renderer — kept in a helper so the three sliders share one source
  // of truth and the render() method stays readable.
  _renderSlider({ id, label, value, min, max, step, indent }) {
    return html`
      <div>
        <label class="form-label mr-3" for="${id}">${label}</label>
        <input
          id="${id}"
          name="${id}"
          class="form-range"
          style="margin-left: ${indent}px; height: unset;"
          type="range"
          min="${min}"
          max="${max}"
          step="${step}"
          .value=${String(value)}
          @input=${this._onSliderInput}
          @change=${this._onSliderInput}
        />
        <span class="val ml-3">${value}</span>
      </div>
    `;
  }

  _renderVoiceSelector() {
    return html`
      <div id="voiceSelector" class="ml-2 mt-3">
        <select
          id="voiceSelect"
          name="voiceSelect"
          @change=${this._onVoiceChanged}
        >
          <option value="none">${this.labels.voicePlaceholder}</option>
          ${this.voices.map((voice) => html`
            <option
              value="${voice.name}"
              ?selected=${voice.name === this.selectedVoice}
            >${voice.name}</option>
          `)}
        </select>
      </div>
    `;
  }

  _renderButton({ id, action, styleKey, text, icon, hidden }) {
    if (hidden) return nothing;
    return html`
      <button
        type="button"
        id="${id}"
        class="btn btn-${this.styles[styleKey]} btn-sm mr-2"
        style="min-width: 180px;"
        data-bs-dismiss="modal"
        @click=${() => this._dispatchAction(action)}
      >
        <i class="mdib ${icon} mdib-sm mr-2"></i>${text}
      </button>
    `;
  }

  // claude - improve SpeakToMe code using lit #1
  // Render method.  Compare to the original ~200-line static Liquid template:
  // the structure is identical, but state-dependent visibility (which used to
  // require inline `style="display: none"` plus external JS toggling) is now
  // bound to `isSpeaking` / `isPaused`.
  render() {
    const speaking = this.isSpeaking;
    const paused   = this.isPaused;

    return html`
      <div id="speak2me-modal-data">
        <div
          id="speak2me-modal"
          class="modal-dialog modal-frame modal-top modal-notify modal-primary"
          data-bs-backdrop="static"
          data-bs-keyboard="false"
          tabindex="-1"
          role="document"
          aria-labelledby="Modal Speak2Me"
        >
          <div class="modal-content">
            <div class="modal-header">
              <p class="lead">${this.labels.title}</p>
              <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
            </div>

            <div class="modal-body mt-4">
              <div class="settings-area mb-5" data-speak2me-ignore>
                <h2 class="ml-2 mt-4 mb-4">${this.labels.voiceSettings}</h2>

                <div class="mb-3">
                  ${this._renderSlider({
                    id:     'rate',
                    label:  this.labels.speedLabel,
                    value:  this.rate,
                    min:    this.rateMin,
                    max:    this.rateMax,
                    step:   this.rateStep,
                    indent: 30,
                  })}
                  ${this._renderSlider({
                    id:     'pitch',
                    label:  this.labels.pitchLabel,
                    value:  this.pitch,
                    min:    this.pitchMin,
                    max:    this.pitchMax,
                    step:   this.pitchStep,
                    indent: 36,
                  })}
                  ${this._renderSlider({
                    id:     'volume',
                    label:  this.labels.volumeLabel,
                    value:  this.volume,
                    min:    this.volumeMin,
                    max:    this.volumeMax,
                    step:   this.volumeStep,
                    indent: 18,
                  })}

                  ${this._renderVoiceSelector()}
                </div>

                <h2 class="ml-2 mt-5 mb-3">${this.labels.voiceControl}</h2>

                <div class="modal-footer">
                  ${this._renderButton({
                    id:       'stop_button',
                    action:   'stop',
                    styleKey: 'stopBtn',
                    text:     this.labels.stopText,
                    icon:     'mdib-speaker-off',
                    hidden:   !speaking,
                  })}
                  ${this._renderButton({
                    id:       'speak_button',
                    action:   'speak',
                    styleKey: 'speakBtn',
                    text:     this.labels.speakText,
                    icon:     'mdib-speaker',
                    hidden:   speaking,
                  })}
                  ${this._renderButton({
                    id:       'pause_button',
                    action:   'pause',
                    styleKey: 'pauseBtn',
                    text:     this.labels.pauseText,
                    icon:     'mdib-pause',
                    hidden:   !speaking || paused,
                  })}
                  ${this._renderButton({
                    id:       'resume_button',
                    action:   'resume',
                    styleKey: 'resumeBtn',
                    text:     this.labels.resumeText,
                    icon:     'mdib-play-pause',
                    hidden:   !paused,
                  })}
                  ${this._renderButton({
                    id:       'exit_button',
                    action:   'exit',
                    styleKey: 'exitBtn',
                    text:     this.labels.exitText,
                    icon:     'mdib-close',
                    hidden:   false,
                  })}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    `;
  }
}

// claude - improve SpeakToMe code using lit #1
// Register the custom element exactly once.  Guarding the define() call is
// important because template.js is the entry chunk and may be evaluated more
// than once during HMR.
if (!customElements.get('j1-speak2me-modal')) {
  customElements.define('j1-speak2me-modal', J1Speak2MeModal);
}

// claude - improve SpeakToMe code using lit #1
// CommonJS export so the existing webpack pipeline (template.js uses
// require()) can pick this up without changing module syntax across the
// codebase.  Lit itself is published as ESM but webpack 5 interops cleanly.
module.exports = J1Speak2MeModal;
module.exports.J1Speak2MeModal = J1Speak2MeModal;
