---
title:                                  Google Gemini
title_extention:                        Preview the Chatbot
tagline:                                Chatbot Preview

date:                                   2024-02-14
#last_modified:                         2024-01-01

description: >
                                        The Google Gemini platform provides an AI-based ChatBot system
                                        (formerly "Bard") based on a family of so-called large language
                                        models (LLMs) developed by Google AI, announced in December 2023.
                                        The Chatbot of Gemini are the successors to LaMDA and PaLM 2,
                                        positioning itself as a competitor to OpenAIs' ChatGPT
                                        for the current version of "GPT-4".
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        Internet, Search, Google, Gemini, Chatbot

categories:                             [ Previewer ]
tags:                                   [ Module, Gemini, ChatBot ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/markus-spiske.jpg
  width:                                1920
  height:                               1280

compress:                               false
regenerate:                             false
personalization:                        true
permalink:                              /pages/public/tools/previewer/google-gemini-ai/

resources:                              [
                                          animate,
                                          clipboard, rouge
                                        ]
resource_options:
  - attic:
      filters:
        grayscale:                      1
        contrast:                       1
        brightness:                     0.8
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/markus-spiske.jpg
          alt:                          Photo by Markus Spiske on Unsplash
          badge:
            type:                       unsplash
            author:                     Markus Spiske
            href:                       //unsplash.com/@markusspiske
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The Google Gemini platform provides an AI-based ChatBot system (formerly *Bard*)
based on a family of so-called large language models (LLMs) developed by
Google AI, announced in December 2023. The LLMs of Gemini are the successors
to LaMDA and PaLM 2, positioning itself as a competitor to OpenAIs' ChatGPT
for the current version of *GPT-4*.

Searching the Internet today typically requires multiple search engine requests
for proper results. Modern AI-based Chatbots can simplify an Internet search
to a single request by asking a Bot.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Supported regions

Following its initial launch in the United States, Google's next-generation
AI assistant Gemini is now available in select regions across Latin America,
Africa, Asia Pacific, and Canada. Find more details on where you can use
link:{url-google--gemini-regions-en}[Google Gemini, {browser-window--new}].

Note that Google Gemini is currently *not supported* for the *EU* and some
other regions. Google Gemini is a personalized advertising solution that uses
cookies and other tracking technologies to make advertising more relevant.
However, this may violate EU data protection laws that govern companies
prohibit the use of personal data without the express consent of the to
collect user information.

Gemini requires collecting personal information, such as IP addresses and
device identifiers, which are only collected with the user's consent in the
EU. The lack of support for Google Gemini in the EU region has essentially
the following reasons:

Privacy Policys::
Google Gemini is a tool that enables display ad targeting across multiple
platforms, which requires collecting and sharing data about users'
online activities. The EU has strict data protection regulations that make
it difficult for companies to process data and collect and share user
information. These provisions make it difficult for Google to operate
Google Gemini in the EU.

Competition law regulations::
Google's Gemini could allow the company to gain a dominant position in the
digital advertising market. The EU has a competition law. Some regulations
prohibit companies from establishing their dominant position which may in the
EU conflict with these provisions.


[role="mt-5"]
== Use out of supported regions

With the help of a virtual private network (VPN), you can use Google Gemini,
which is also used in regions that are not currently supported. VPNs hide
the user's actual IP address. Instead, a new IP address that comes from a
selectable region, for example, the USA, will be used.

A virtual private network (VPN) is a private network that is built and
operated over a public network such as the Internet. VPNs allow users to
establish secure connections to other networks over the Internet. They can
be used to provide access to geographically restricted websites and services,
improve privacy and security, and optimize network performance.

Common features of VPNs:

Traffic Encryption::
VPNs encrypt all traffic sent and received over the network. Encryption
prevents third parties, such as Internet service providers or hackers,
from accessing and reading the data. Encryption, therefore, ensures that
the privacy of users is protected.

Hiding the IP address::
VPNs hide the user's actual IP address. Instead, a new IP address belonging
to the VPN provider is used. Third parties can no longer determine the users'
location or track them based on their IP address., which protects their privacy.

Access restricted content::
Many VPNs allow users to access blocked content in their country or region
because VPNs hide the user's true IP address, allowing them to access content
unavailable in their country or region.

[role="mt-4"]
.Privacy
[NOTE]
====
Using Google Gemini outside supported regions via a VPN, your privacy is
protected and no *real* user information is used or transferred to the
service.
====


[role="mt-5"]
== Ask the Bot

The Google Gemini platform provides a ChatBot system using a significant
advancement in the field of LLMs. The ability to process information from
multiple sources, text and images, and its flexible architecture makes it
a powerful tool for many applications and websites.

[role="mt-4"]
=== Examples for Prompts

Find below some examples what can be used for a prompt.

.Place
[source, text, role="mb-4"]
----
What ist the Fifth Avenue in New York City?
----

.Technical explanation
[source, text, role="mb-4"]
----
What is the JekyllOne Template and what types of websites are supported?
----

.Google Gemini support
[source, text, role="mb-4"]
----
Why is Google Gemini currently not supported for the EU region?
----

.Storys
[source, text, role="mb-4"]
----
Tell a wonderful story for your child every single night.
Generate a bedtime story for the chield bease on child's favourite things, country, and age.
Give some advice for kids to be good and do good for the sociaty.`
End of the story motivate them to belive themselefs.
----

Use the copy function of the examples given to copy the function from the
examples above to test Google Gemini. Copy such a given *text* and paste it
into the input field *prompt* for a generation.

[role="mt-4"]
=== Generate

You can enter your requests in the input field *Prompt*. If you need help
formulating such requests, leave the prompt field empty and start a
generation.

++++
<div class="gallery-title mt-3">Prompt (Input)</div>
<div class="form-group">
  <textarea id="prompt" class="form-control mb-3" placeholder="Enter a clear and concise text that conveys the task or question you want the chatbot to perform" rows="5"></textarea>

  <button id="send" class="btn btn-primary" type="button">
    <span id="spinner" class="spinner-grow spinner-grow-sm" aria-hidden="true"></span>
    <span role="status">Generate</span>
  </button>

  <button id="reset" type="button" class="btn btn-warning btn-raised mt-1">Reset</button>
</div>

<div id="output" class="mt-5 mb-7">
  <h3 id="result" class="mb-2 notoc speak2me-ignore">Result</h3>
  <div id="md_result"></div>
</div>

<!-- Side Modal Top Right Success -->
<div id="sideModalTRSuccessDemo"
  class="modal fade right"
  tabindex="-1"
  role="dialog"
  aria-labelledby="myModalLabel" aria-hidden="true"
  data-keyboard="false"
  data-backdrop="static">
  <div class="modal-dialog modal-side modal-top-right modal-notify modal-danger" role="document">
    <!-- Content -->
    <div class="modal-content">
      <!--Header-->
      <div class="modal-header">
        <p class="lead">Processing Error</p>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <i class="mdi mdi-close mdi-dark mdi-48px"></i>
        </button>
      </div>
      <!-- Body -->
      <div class="modal-body">
        <div class="text-center">
          <i class="mdi mdi-4x mdi-bug md-red mb-1"></i>
          <p>User location is not supported.</p>
        </div>
      </div>
      <!-- Footer -->
      <!-- div class="modal-footer justify-content-center">
        <a type="button" class="btn btn-primary mr-2">Yes, please</a>
        <a type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">No, thanks</a>
      </div -->
    </div>
    <!-- END Content -->
  </div>
</div>
<!-- END Side Modal Top Right Success -->


<script src="//cdn.jsdelivr.net/npm/marked/marked.min.js"></script>

<script type="importmap">
  {
    "imports": {
      "@google/generative-ai": "//esm.run/@google/generative-ai"
    }
  }
</script>

<script type="module">
  $("#spinner").hide();
  $("#output").hide();

  const API_KEY       = "AIzaSyAtiLEW4oQiOJtGiPsdsGwMHi8O__7cqjU";
  const genAI         = new GoogleGenerativeAI(API_KEY);
  var genAIError      = false;
  var response        = '';
  const httpError400  ='User location is not supported for the API use.';
  const defaultPrompt = 'Please provide tips on how using the prompt for a chat bot';

  var result;

  import { GoogleGenerativeAI } from "//esm.run/@google/generative-ai";

  async function run() {
    let input = document.getElementById("name");

    // For text-only input, use the gemini-pro model
    const model = genAI.getGenerativeModel({ model: "gemini-pro"});

    var prompt = $('textarea#prompt').val();
    if (prompt.length == 0) {
      prompt = defaultPrompt;
      document.getElementById('prompt').value = prompt;
    }

    try {
        result = await model.generateContent(prompt);
    } catch (e) {
        console.warn(httpError400);
        genAIError = true;
    } finally {
        if (!genAIError) {
          // console.log("result: ", result);

          try {
              response = await result.response;
          } catch (e) {
              console.warn(e);
          } finally {
            // console.log("response: ", response);
            const text = response.text();
            // console.log(text);

            if (text.length > 0) {
               document.getElementById('md_result').innerHTML = marked.parse(text);
               $("#spinner").hide();
               $("#output").show();
             }
          }
        } else {
         console.warn('Processing failed.');
         $('#sideModalTRSuccessDemo').modal('show');
         $("#spinner").hide();
       }
    }
  } //END async run()

  var dependencies_met_page_ready = setInterval (function (options) {
  var pageState   = $('#no_flicker').css("display");
  var pageVisible = (pageState == 'block') ? true : false;

  if (j1.getState() === 'finished' && pageVisible) {
    const sendButton = document.getElementById('send');
    sendButton.addEventListener('click', (event) => {
      // Prevent default form submission
      event.preventDefault();
      $("#spinner").show();
      run();
    });

    const resetButton = document.getElementById('reset');
    resetButton.addEventListener('click', (event) => {
      // Prevent default form submission
      event.preventDefault();
      document.getElementById("prompt").value = "";
      document.getElementById("output").value = "";
      $("#spinner").hide();
      $("#output").hide();
    });

    clearInterval(dependencies_met_page_ready);
  }
}, 10);

</script>
++++
