---
title:                                  Google Gemini AI
title_extention:                        Previewer
tagline:                                Previewer

date:                                   2024-02-14
#last_modified:                         2024-01-01

description: >
                                        Google Gemini is a family of large language models (LLMs) developed by
                                        Google AI, announced in December 2023. It's the successor to LaMDA and PaLM 2,
                                        and positions itself as a competitor to OpenAI's GPT-4.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        Google, Gemini

categories:                             [ Previewer ]
tags:                                   [ Module, Gemini ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/markus-spiske.jpg
  width:                                1920
  height:                               1280

compress:                               false
regenerate:                             false
personalization:                        true
permalink:                              /pages/public/tools/previewer/google-gemini-ai/

resources:                              [
                                          animate, clipboard, rouge
                                        ]
resource_options:
  - attic:
      filters:
        grayscale:                      1
        contrast:                       1
        brightness:                     0.8
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/markus-spiske.jpg
          alt:                          Photo by Markus Spiske on Unsplash
          badge:
            type:                       unsplash
            author:                     Markus Spiske
            href:                       https://unsplash.com/@markusspiske
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Google Gemini is a family of large language models (LLMs) developed by
Google AI, announced in December 2023. It's the successor to LaMDA and PaLM 2,
and positions itself as a competitor to OpenAI's GPT-4.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Ask the Bot

Google Gemini is a significant advancement in the field of LLMs. Its
ability to process information from multiple modalities and its flexible
architecture make it a powerful tool for a wide range of applications.

[role="mt-4"]
=== Examples for Prompts

Find below some examples what can be used for a prompt.

.Place
[source, text, role="mb-4"]
----
What ist the Fifth Avenue in New York City?
----

.Technical explanation
[source, text, role="mb-4"]
----
What is the JekyllOne Template?
----

.Story
[source, text, role="mb-5"]
----
Tell a wonderful story for your child every single night.
Generate a bedtime story for the chield bease on child's favourite things, country, and age.
Give some advice for kids to be good and do good for the sociaty.`
End of the story motivate them to belive themselefs.
----

[role="mt-4"]
=== Generate

++++
<div class="gallery-title mt-3">Prompt</div>
<div class="form-group">
  <textarea id="prompt" class="form-control mb-3" rows="5"></textarea>

  <button id="send" class="btn btn-primary" type="button">
    <span id="spinner" class="spinner-grow spinner-grow-sm" aria-hidden="true"></span>
    <span role="status">Generate</span>
  </button>

  <button id="reset" type="button" class="btn btn-warning btn-raised mt-1">Reset</button>
</div>

<div id="output" class="mt-5 mb-7">
  <h3 id="result" class="mb-2 notoc">Result</h3>
  <div id="md_result"></div>
</div>

<!-- Side Modal Top Right Success -->
<div id="sideModalTRSuccessDemo"
  class="modal fade right"
  tabindex="-1"
  role="dialog"
  aria-labelledby="myModalLabel" aria-hidden="true"
  data-keyboard="false"
  data-backdrop="static">
  <div class="modal-dialog modal-side modal-top-right modal-notify modal-danger" role="document">
    <!-- Content -->
    <div class="modal-content">
      <!--Header-->
      <div class="modal-header">
        <p class="lead">Processing Error</p>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <i class="mdi mdi-close mdi-dark mdi-48px"></i>
        </button>
      </div>
      <!-- Body -->
      <div class="modal-body">
        <div class="text-center">
          <i class="mdi mdi-4x mdi-bug md-red mb-1"></i>
          <p>User location is not supported.</p>
        </div>
      </div>
      <!-- Footer -->
      <!-- div class="modal-footer justify-content-center">
        <a type="button" class="btn btn-primary mr-2">Yes, please</a>
        <a type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">No, thanks</a>
      </div -->
    </div>
    <!-- END Content -->
  </div>
</div>
<!-- END Side Modal Top Right Success -->


<script src="//cdn.jsdelivr.net/npm/marked/marked.min.js"></script>

<script type="importmap">
  {
    "imports": {
      "@google/generative-ai": "https://esm.run/@google/generative-ai"
    }
  }
</script>

<script type="module">
  $("#spinner").hide();
  $("#output").hide();

  const API_KEY       = "AIzaSyAtiLEW4oQiOJtGiPsdsGwMHi8O__7cqjU";
  const genAI         = new GoogleGenerativeAI(API_KEY);
  var genAIError      = false;
  var response        = '';
  const httpError400  ='User location is not supported for the API use.';
  const defaultPrompt = 'Please provide tips on how using the prompt for a chat bot';

  var result;

  import { GoogleGenerativeAI } from "https://esm.run/@google/generative-ai";

  async function run() {
    let input = document.getElementById("name");

  	// For text-only input, use the gemini-pro model
  	const model = genAI.getGenerativeModel({ model: "gemini-pro"});

    var prompt = $('textarea#prompt').val();
    if (prompt.length == 0) {
      prompt = defaultPrompt;
      document.getElementById('prompt').value = prompt;
    }

    try {
        result = await model.generateContent(prompt);
    } catch (e) {
        console.warn(httpError400);
        genAIError = true;
    } finally {
        if (!genAIError) {
          // console.log("result: ", result);

          try {
              response = await result.response;
          } catch (e) {
              console.warn(e);
          } finally {
          	// console.log("response: ", response);
          	const text = response.text();
          	// console.log(text);

            if (text.length > 0) {
               document.getElementById('md_result').innerHTML = marked.parse(text);
               $("#spinner").hide();
               $("#output").show();
             }
          }
        } else {
         console.warn('Processing failed.');
         $('#sideModalTRSuccessDemo').modal('show');
         $("#spinner").hide();
       }
    }
  } //END async run()

  var dependencies_met_page_ready = setInterval (function (options) {
  var pageState   = $('#no_flicker').css("display");
  var pageVisible = (pageState == 'block') ? true : false;

  if (j1.getState() === 'finished' && pageVisible) {
    const sendButton = document.getElementById('send');
    sendButton.addEventListener('click', (event) => {
      // Prevent default form submission
      event.preventDefault();
      $("#spinner").show();
      run();
    });

    const resetButton = document.getElementById('reset');
    resetButton.addEventListener('click', (event) => {
      // Prevent default form submission
      event.preventDefault();
      document.getElementById("prompt").value = "";
      document.getElementById("output").value = "";
      $("#spinner").hide();
      $("#output").hide();
    });

    clearInterval(dependencies_met_page_ready);
  }
}, 10);

</script>
++++
