---
title:                                  Google Gemini
title_extention:                        Preview the Chatbot
tagline:                                Chatbot Preview

date:                                   2024-02-14
#last_modified:                         2024-01-01

description: >
                                        The Google Gemini platform provides an AI-based ChatBot system
                                        (formerly "Bard") based on a family of so-called large language
                                        models (LLMs) developed by Google AI, announced in December 2023.
                                        The Chatbot of Gemini are the successors to LaMDA and PaLM 2,
                                        positioning itself as a competitor to OpenAIs' ChatGPT
                                        for the current version of "GPT-4".
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        Internet, Search, Google, Gemini, Chatbot

categories:                             [ Previewer ]
tags:                                   [ Module, Gemini, ChatBot ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/markus-spiske.jpg
  width:                                1920
  height:                               1280

compress:                               false
regenerate:                             false
personalization:                        true
permalink:                              /pages/public/tools/previewer/google-gemini-ai/

resources:                              [
                                          animate,
                                          clipboard, lightbox, rouge
                                        ]
resource_options:
  - attic:
      filters:
        grayscale:                      1
        contrast:                       1
        brightness:                     0.8
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/markus-spiske.jpg
          alt:                          Photo by Markus Spiske on Unsplash
          badge:
            type:                       unsplash
            author:                     Markus Spiske
            href:                       //unsplash.com/@markusspiske
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The Google Gemini platform provides an AI-based ChatBot system (formerly *Bard*)
based on a family of so-called large language models (LLMs) developed by
Google AI, announced in December 2023. The LLMs of Gemini are the successors
to LaMDA and PaLM 2, positioning itself as a competitor to OpenAIs' ChatGPT
for the current version of *GPT-4*.

Searching the Internet today typically requires multiple search engine requests
for proper results. Modern AI-based Chatbots can simplify an Internet search
to a single request by asking a Bot.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Supported regions

Following its initial launch in the United States, Google's next-generation
AI assistant Gemini is now available in select regions across Latin America,
Africa, Asia Pacific, and Canada. Find more details on where you can use
link:{url-google--gemini-regions-en}[Google Gemini, {browser-window--new}].

Note that Google Gemini is currently *not supported* for the *EU* and some
other regions. Google Gemini is a personalized advertising solution that uses
cookies and other tracking technologies to make advertising more relevant.
However, this may violate EU data protection laws that govern companies
prohibit the use of personal data without the express consent of the to
collect user information.

[role="mt-3 mb-4"]
[NOTE]
====
Google is working on making Gemini compliant with GDPR for the EU region.
However, it is not clear when this will happen.
====

Gemini requires collecting personal information, such as IP addresses and
device identifiers, which are only collected with the user's consent in the
EU. The lack of support for Google Gemini in the EU region has essentially
the following reasons:

Privacy Policys::
Google Gemini is a tool that enables display ad targeting across multiple
platforms, which requires collecting and sharing data about users'
online activities. The EU has strict data protection regulations that make
it difficult for companies to process data and collect and share user
information. These provisions make it difficult for Google to operate
Google Gemini in the EU.

Competition law regulations::
Google's Gemini could allow the company to gain a dominant position in the
digital advertising market. The EU has a competition law. Some regulations
prohibit companies from establishing their dominant position which may in the
EU conflict with these provisions.


[role="mt-5"]
== Use out of supported regions

With the help of a virtual private network (VPN), you can use Google Gemini,
which is also used in regions that are not currently supported. VPNs hide
the user's actual IP address. Instead, a new IP address that comes from a
selectable region, for example, the USA, will be used.

A virtual private network (VPN) is a private network that is built and
operated over a public network such as the Internet. VPNs allow users to
establish secure connections to other networks over the Internet. They can
be used to provide access to geographically restricted websites and services,
improve privacy and security, and optimize network performance.

Common features of VPNs:

Traffic Encryption::
VPNs encrypt all traffic sent and received over the network. Encryption
prevents third parties, such as Internet service providers or hackers,
from accessing and reading the data. Encryption, therefore, ensures that
the privacy of users is protected.

Hiding the IP address::
VPNs hide the user's actual IP address. Instead, a new IP address belonging
to the VPN provider is used. Third parties can no longer determine the users'
location or track them based on their IP address., which protects their
privacy.

Access restricted content::
Many VPNs allow users to access blocked content in their country or region
because VPNs hide the user's true IP address, allowing them to access content
unavailable in their country or region.

[role="mt-4"]
.Privacy
[NOTE]
====
Using Google Gemini outside supported regions via a VPN, your privacy is
protected and no *real* user information is used or transferred to the
service.
====

[role="mt-5"]
== VPN Clients on Windows

Several VPN clients on Windows are available that can be used for free.

VPN Clients providing a *free plan*:

* link://windscribe.com/[Windscribe VPN, {browser-window--new}],
  Offers AES-256 encryption and secure browsing features.
* link://protonvpn.com/[Proton VPN, {browser-window--new}],
  Focuses on privacy and offers secure OpenVPN connections. ProtonVPN
  offers a usable *free* plan and *premium* plans for more options
  as well.
* link://tunnelbear.com/[TunnelBear VPN, {browser-window--new}],
  Provides a user-friendly interface and unlimited data
  for free users.

[role="mt-4"]
.Build-in VPN
[TIP]
=====
Some computer *security applications* like link://avast.com/[Avast, {browser-window--new}]
provide for *paid plans* a VPN solution *build-in*. You should check if a VPN
client is already availabe for the security application you'e using.
=====

I've tested the VPN client _TunnelBear VPN_ on Windows with success. The
limitation I found is the *amount* of *data* transferred over the VPN gateway.
The limit is *2GB* for the *free* version, but should be enough for testing
Google Gemini.

[role="mt-4"]
=== Setting up TunnelBear VPN

Setting up TunnelBear VPN is a simple three step procedure. First, subscribe
at link://tunnelbear.com/[TunnelBear VPN, {browser-window--new}] and install
the product:

.Subscribe at TunnelBear VPN
lightbox::tunnelbear-subscribe[1280, {data-image-tunnelbear--subscribe}, role="mt-4 mb-4"]

.Verify your email address
lightbox:::tunnelbear-verify-email-address[1280, {data-image-tunnelbear--verify-email-address}, role="mt-4 mb-4"]

.Set the VPN Gateway
lightbox::tunnelbear-set-vpn-gateway[1280, {data-image-tunnelbear--set-vpn-gateway}, role="mt-4 mb-4"]

If _TunnelBear VPN_ is setting up and running successfully using a *supported*
region for the *VPN Gateway*, you can start testing Google Gemini out of any
region you are located.


[role="mt-5"]
== Ask the Bot

The _Google Gemini_ platform provides a *ChatBot* system using a significant
advancement in the field of LLMs. The ability to process information from
multiple sources, text and images, and its flexible architecture makes it
a powerful tool for many applications and websites.

[role="mt-4"]
=== Examples for Prompts

Find below some examples what can be used for a prompt.

.Place
[source, text, role="mb-4"]
----
What ist the Fifth Avenue in New York City?
----

.Technical explanation
[source, text, role="mb-4"]
----
What is the JekyllOne Template and what types of websites are supported?
----

.Google Gemini support
[source, text, role="mb-4"]
----
Why is Google Gemini currently not supported for the EU region?
----

.Storys
[source, text, role="mb-4"]
----
Tell a wonderful story for your child every single night.
Generate a bedtime story for the chield bease on child's favourite things, country, and age.
Give some advice for kids to be good and do good for the sociaty.`
End of the story motivate them to belive themselefs.
----

Use the copy function of the examples given to copy the function from the
examples above to test Google Gemini. Copy such a given *text* and paste it
into the input field *prompt* for a generation.

[role="mt-4"]
=== Generate

You can enter your requests in the input field *Prompt*. If you need help
formulating such requests, leave the prompt field empty and start a
generation.

++++
<div class="gallery-title mt-3">Prompt (Input)</div>
<div class="form-group">
  <textarea id="prompt" class="form-control mb-3" placeholder="Enter a clear and concise text that conveys the task or question you want the chatbot to perform" rows="5"></textarea>

  <button id="send" class="btn btn-primary" type="button">
    <span id="spinner" class="spinner-grow spinner-grow-sm" aria-hidden="true"></span>
    <span role="status">Generate</span>
  </button>

  <button id="reset" type="button" class="btn btn-warning mt-1">Reset</button>
</div>

<div id="output" class="mt-5 mb-7">
  <h3 id="result" class="mb-2 notoc speak2me-ignore">Result</h3>
  <div id="md_result"></div>
</div>

<!-- Consent Modal -->
<div id="consentModal" class="modal">
  <div class="modal-info-content">
    <p>This page requires to detect the current location for using Google Gemini.</p>
    <button id="infoConsentButtonAccept" class="btn btn-primary" type="button" data-bs-dismiss="modal" aria-label="Accept">
      <i class="mdi mdi-check mdi-1x mr-2"></i>
      Yes, I agree
    </button>
    <button id="infoConsentButtonDecline" class="btn btn-warning" type="button" data-bs-dismiss="modal" aria-label="Decline">
      <i class="mdi mdi-close mdi-1x mr-2"></i>
      No, I don't agree
    </button>
  </div>
</div>

<!-- Modal Top Right -->
<div id="errorModal"
  class="modal fade right"
  tabindex="-1"
  role="dialog"
  aria-labelledby="errorModalLabel" aria-hidden="true"
  data-keyboard="false"
  data-backdrop="static">
  <div class="modal-dialog modal-side modal-top-right modal-notify modal-danger" role="document">
    <!-- Content -->
    <div class="modal-content">
      <!-- Header -->
      <div class="modal-header">
        <p class="lead">Processing Error</p>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <i class="mdi mdi-close mdi-dark mdi-48px"></i>
        </button>
      </div>
      <!-- Body -->
      <div class="modal-body">
        <div class="text-center">
          <i class="mdi mdi-4x mdi-bug md-red mb-1"></i>
          <p id="modal_error">Error text placeholder</p>
        </div>
      </div>
      <!-- Footer -->
      <!-- div class="modal-footer justify-content-center">
        <a type="button" class="btn btn-primary mr-2">Yes, please</a>
        <a type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">No, thanks</a>
      </div -->
    </div>
    <!-- END Content -->
  </div>
</div>
<!-- END Side Modal Top Right Success -->

<script src="//unpkg.com/leaflet/dist/leaflet.js"></script>
<script src="//unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>
<script src="//cdn.jsdelivr.net/npm/marked/marked.min.js"></script>

<style>
  /* Styles for the modal */
  .modal-info {
    display: none;
    position: fixed;
    z-index: 1;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgba(0, 0, 0, 0.4);
  }

  .modal-info-content {
    background-color: #fefefe;
    margin: 15% auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
  }

  .modal-info-content p {
    margin-bottom: 20px;
  }

  .modal-info-content button {
    color: white;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
  }

  .modal-info-content button:hover {
    background-color: #E0E0E0;
  }
</style>

<script type="importmap">
  {
    "imports": {
      "@google/generative-ai": "//esm.run/@google/generative-ai"
    }
  }
</script>

<script type="module">

  var consentModal = document.getElementById("consentModal");

   // Get the button that opens the modal
   var infoConsentButtonAccept = document.getElementById("infoConsentButtonAccept");

   // When the page loads, ask for consent
   window.onload = function() {
     // Display the modal
     consentModal.style.display = "block";
   };

   // When the user clicks on the consent button, close the modal
   // and collect the geolocation
   infoConsentButtonAccept.onclick = function() {
     // Hide the modal
     consentModal.style.display = "none";
     if (navigator.geolocation) {
       navigator.geolocation.getCurrentPosition(showPosition);
     } else {
       alert("Geolocation is not supported by the browser.");
     }
   };
    // When the user clicks on the deline button, close the modal and reditec to home page
   infoConsentButtonDecline.onclick = function() {
     // Hide the modal
     consentModal.style.display = "none";
     document.location.href="/";
   };

   // log the geolocation position
   function showPosition(position) {
     var latitude = position.coords.latitude;
     var longitude = position.coords.longitude;
     console.debug("Detected geocode (lat:long): " + latitude + ':' + longitude);
   }

  function locateCountry(position) {
    const latitude  = position.coords.latitude;
    const longitude = position.coords.longitude;

    // Reverse geocode to find the country
    fetch(`//nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${latitude}&lon=${longitude}`)
    .then(response => response.json())
    .then(data => {
      const country = '<b>' + data.address.country;
      const city    = data.address.city;
      $("#modal_error").html(modal_error_text + '<br>' + country);
    })
    .catch(error => {
      console.error('Error:', error);
    });
  }

  function geoFindMe() {

    function success(position) {
      const latitude = position.coords.latitude;
      const longitude = position.coords.longitude;

      locateCountry(position);
    }

    function error() {
      console.warn("Unable to retrieve the location");
    }

    if (!navigator.geolocation) {
      console.warn("Geolocation API is not supported by the browser");
    } else {
      navigator.geolocation.getCurrentPosition(success, error);
    }
  }

  $("#spinner").hide();
  $("#output").hide();

  const API_KEY         = "AIzaSyAtiLEW4oQiOJtGiPsdsGwMHi8O__7cqjU";
  const genAI           = new GoogleGenerativeAI(API_KEY);
  var genAIError        = false;
  var genAIErrorType    = '';
  var response          = '';
  const httpError400    = 'Location is not supported: ';
  const httpError500    = 'Service currently not available: ';
  var modal_error_text  = '';
  const defaultPrompt   = 'Please provide tips on how using the prompt for a chat bot';
  var result;

  import { GoogleGenerativeAI } from "//esm.run/@google/generative-ai";

  async function run() {
    let input = document.getElementById("name");

    // For text-only input, use the gemini-pro model
    const model = genAI.getGenerativeModel({ model: "gemini-pro"});

    var prompt = $('textarea#prompt').val();
    if (prompt.length == 0) {
      prompt = defaultPrompt;
      document.getElementById('prompt').value = prompt;
    }

    try {
        result = await model.generateContent(prompt);
    } catch (e) {
      var error = e.toString();
        if (error.includes("400")) {
          genAIErrorType = 400;
          modal_error_text = httpError400;
          console.warn(httpError400);
        } else if (error.includes("50")) {
          genAIErrorType = 500;
          modal_error_text = httpError500;
          console.warn(httpError500);
        }
        genAIError = true;
    } finally {
        if (!genAIError) {
          try {
              response = await result.response;
          } catch (e) {
              console.warn(e);
          } finally {
            const text = response.text();
            if (text.length > 0) {
               document.getElementById('md_result').innerHTML = marked.parse(text);
               $("#spinner").hide();
               $("#output").show();
             }
          }
        } else {
           geoFindMe();
           console.warn('Processing failed.');
           $('#errorModal').modal('show');
           $("#spinner").hide();
       }
    }
  } //END async run()

  var dependencies_met_page_ready = setInterval (function (options) {
  var pageState   = $('#no_flicker').css("display");
  var pageVisible = (pageState == 'block') ? true : false;

  if (j1.getState() === 'finished' && pageVisible) {
    const sendButton = document.getElementById('send');
    sendButton.addEventListener('click', (event) => {
      // Prevent default actions
      event.preventDefault();
      $("#spinner").show();
      run();
    });

    const resetButton = document.getElementById('reset');
    resetButton.addEventListener('click', (event) => {
      // Prevent default actions
      event.preventDefault();
      document.getElementById("prompt").value = "";
      document.getElementById("output").value = "";
      $("#spinner").hide();
      $("#output").hide();
    });

    clearInterval(dependencies_met_page_ready);
  }
}, 10);

</script>
++++
