---
title:                                  Chatbot
title_extention:                        Preview the Gemini Chatbot
tagline:                                Preview

date:                                   2024-02-27
#last_modified:                         2024-01-01

description: >
                                        The Google Gemini platform provides an AI-based ChatBot system
                                        (formerly "Bard") based on a family of so-called large language
                                        models (LLMs) developed by Google AI, announced in December 2023.
                                        The Chatbot of Gemini are the successors to LaMDA and PaLM 2,
                                        positioning itself as a competitor to OpenAIs' ChatGPT
                                        for the current version of "GPT-4".
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        Internet, Search, Google, Gemini, Chatbot

categories:                             [ Previewer ]
tags:                                   [ Module, Gemini, ChatBot ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/build-with-gemini.jpg
  width:                                1920
  height:                               1280

regenerate:                             false
personalization:                        true
permalink:                              /pages/public/tools/previewer/google-gemini-ai/

resources:                              [
                                          animate,
                                          clipboard, gemini, lightbox, rouge
                                        ]
resource_options:
  - attic:
      filters:
        grayscale:                      1
        contrast:                       1
        brightness:                     0.8
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/build-with-gemini.jpg
          alt:                          Build with Gemini
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The Google Gemini platform provides an AI-based ChatBot system (formerly *Bard*)
based on a family of so-called large language models (LLMs) developed by
Google AI, announced in December 2023. The LLMs of Gemini are the successors
to LaMDA and PaLM 2, positioning itself as a competitor to OpenAIs' ChatGPT
for the current version of *GPT-4*.

Searching the Internet today typically requires multiple search engine requests
for proper results. Modern AI-based Chatbots can simplify an Internet search
to a single request by asking a Bot.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Technology (February 2024)

Like OpenAI's competing product, ChatGPT, Google Gemini can answer questions
conversationally. Gemini allows multimodal work, which means you can enter
various media, such as voice or photos, and have different formats, such as
code or language output. However, Gemini is currently unlike ChatGPT, unable
to *create images*.

The chatbot was initially developed based on the Large Language Model LaMDA
before using the better model PaLM 2 from May 2023 and the newly developed
*LLM Gemini* of the same name since December 2023. The Gemini-based version
of the Chatbot system is available in over 230 countries and supports
currently 40 languages.

Unlike ChatGPT 4, Google Gemini is *free* to use, but a paid version is also
available called _Gemini Advanced_. However, Google itself points out that
the tool still has weaknesses. At the beginning of the release, Google
described _Bard_ as an experiment, but with the rebranding as Gemini, it is
not longer in a experimental state.

[role="mt-4"]
=== Official Gemini Chatbot App

The *official* Chatbot version from Google Gemini is available at
link://gemini.google.com/app[Google Gemini App, {browser-window--new}]
including the *EU* region. Note that for using the Chatbot App, it is required
to be logged in at Google - using your GMail account for example. Find more on
the *privacy protection* settings using at the
link:https://support.google.com/gemini/answer/13594961?visit_id=638438812942129559-1947527328&p=privacy_help&rd=1#config_settings[Gemini Apps Privacy Hub, {browser-window--new}].


[role="mt-5"]
== Supported regions

Following its initial launch in the United States, Google's next-generation
AI assistant Gemini is now available in select regions across Latin America,
Africa, Asia Pacific, and Canada. Find more details on where you can use
link:{url-google--gemini-regions-en}[Google Gemini, {browser-window--new}].

Note that Google Gemini is currently *not supported* for the *EU* and some
other regions. Google Gemini is a personalized advertising solution that uses
cookies and other tracking technologies to make advertising more relevant.
However, this may violate EU data protection laws that govern companies
prohibit the use of personal data without the express consent of the to
collect user information.

[role="mt-3 mb-4"]
[NOTE]
====
Google is working on making the App's and API's on the Gemini platform
compliant with *GDPR* for the EU region. However, it is not clear when this
will happen.
====

Gemini requires collecting personal information, such as IP addresses and
device identifiers, which are only collected with the user's consent in the
EU. The lack of support for Google Gemini in the EU region has essentially
the following reasons:

Privacy Policys::
Google Gemini is a tool that enables display ad targeting across multiple
platforms, which requires collecting and sharing data about user's
online activities. The EU has strict data protection regulations that make
it difficult for companies to process data and collect and share user
information. These provisions make it difficult for Google to operate
Google Gemini in the EU.

Competition law regulations::
Google's Gemini could allow the company to gain a dominant position in the
digital advertising market. The EU has a competition law. Some regulations
prohibit companies from establishing their dominant position which may in the
EU conflict with these provisions.


[role="mt-5"]
== Use out of supported regions

With the help of a virtual private network (VPN), you can use webpages using
the Google *Gemini API* in regions that are currently *not supported*.
VPN's hide the user's actual IP address. Instead, a new IP address that comes
from a selectable region, for example, the USA, will be used.

A virtual private network is a private network that is built and operated over
a public network such as the Internet. VPN's allow users to establish secure
connections to other networks over the Internet. They can be used to provide
access to geographically restricted websites and services, improve privacy,
and security.

Common features of VPN's:

Traffic Encryption::
VPN's encrypt all traffic sent and received over the network. Encryption
prevents third parties, such as Internet service providers or hackers,
from accessing and reading the data. Encryption, therefore, ensures that
the privacy of users is protected.

Hiding the IP address::
VPN's hide the user's actual IP address. Instead, a new IP address belonging
to the VPN provider is used. Third parties can no longer determine the user's
location or track them based on their IP address, which protects their
privacy.

Access restricted content::
Many VPN's allow users to access blocked content in their country or region
because a VPN hide the user's true IP address, allowing them to access content
unavailable in their country or region.

[role="mt-4"]
.Privacy
[NOTE]
====
Using Google Gemini outside supported regions via a VPN, your privacy is
protected and no *real* user information is used or transferred to the
service.
====

[role="mt-5"]
== VPN Clients on Windows

Several VPN clients on Windows are available that can be used for free.

VPN Clients providing a *free plan*:

* link://windscribe.com/[Windscribe VPN, {browser-window--new}],
  Offers AES-256 encryption and secure browsing features.
* link://protonvpn.com/[Proton VPN, {browser-window--new}],
  Focuses on privacy and offers secure OpenVPN connections. ProtonVPN
  offers a usable *free* plan and *premium* plans for more options
  as well.
* link://tunnelbear.com/[TunnelBear VPN, {browser-window--new}],
  Provides a user-friendly interface and unlimited data
  for free users.

[role="mt-4"]
.Build-in VPN
[TIP]
=====
Some computer *security applications* like link://avast.com/[Avast, {browser-window--new}]
provide for *paid plans* a VPN solution *build-in*. You should check if a VPN
client is already availabe for the security application you'e using.
=====

I've tested the VPN client _TunnelBear VPN_ on Windows with success. The
limitation I found is the *amount* of *data* transferred over the VPN gateway.
The limit is *2GB* for the *free* version, but should be enough for testing
Google Gemini.

[role="mt-4"]
=== Setting up TunnelBear VPN

Setting up TunnelBear VPN is a simple three step procedure. First, subscribe
at link://tunnelbear.com/[TunnelBear VPN, {browser-window--new}] and install
the product:

.Subscribe at TunnelBear VPN
lightbox::tunnelbear-subscribe[1280, {data-image-tunnelbear--subscribe}, role="mt-4 mb-4"]

.Verify your email address
lightbox:::tunnelbear-verify-email-address[1280, {data-image-tunnelbear--verify-email-address}, role="mt-4 mb-4"]

.Set the VPN Gateway
lightbox::tunnelbear-set-vpn-gateway[1280, {data-image-tunnelbear--set-vpn-gateway}, role="mt-4 mb-4"]

If _TunnelBear VPN_ is setting up and running successfully using a *supported*
region for the *VPN Gateway*, you can start testing Google Gemini out of any
region you are located.


[role="mt-5"]
== Ask the Bot

The _Google Gemini_ platform provides a *ChatBot* system using a significant
advancement in the field of LLMs. The ability to process information from
multiple sources, text and images, and its flexible architecture makes it
a powerful tool for many applications and websites.

[role="mt-4"]
=== Examples for Prompts

Find below some examples of what can be used for a prompt. KI-based chatbots
can do much more than a complex internet search. Let the bot write a
*bedtime story*, do translations, and help summarize the larger text.
Furthermore, a bot can support you in evaluations or requests for guidance.

.Places
[source, text, role="mb-4"]
----
What ist the Fifth Avenue in New York City?
----

.Technical explanation I
[source, text, role="mb-4"]
----
What is the JekyllOne Template and what types of websites are supported?
----

.Technical explanation II
[source, text, role="mb-4"]
----
Why is Google Gemini currently not supported for the EU region?
----

.Storys
[source, text, role="mb-4"]
----
Write a modern bedtime story called "The magical Dance".

Use the style of writing like Astrid Lindgren.
Told to a child boy Henry at age 6, living in the USA, and loves dancing.
Give the kid some advice on how to be good and do good for society.
The end of the story should motivate the child to believe in themselves.
----

.Translations I
[source, text, role="mb-4"]
----
Translate the text into English language.

Text: Heutzutage erfordert die Suche im Internet normalerweise mehrere
Suchmaschinenanfragen, um korrekte Ergebnisse zu erhalten. Moderne KI-basierte
Chatbots können eine Internetsuche auf eine einzige Anfrage reduzieren.
----

.Translations II
[source, text, role="mb-4"]
----
Write a modern bedtime story called "The magical Dance".

Use the style of writing like Astrid Lindgren.
Told to a child boy Henry at age 6, living in the USA, and loves dancing.
Give the kid some advice on how to be good and do good for society.
The end of the story should motivate the child to believe in themselves.

Finally, translate the story into German and Italian.
----

.Summarizing I
[source, text, role="mb-4"]
----
Summarize this text as bullets points of key information.

Text: A quantum computer exploits quantum mechanical phenomena to perform
calculations exponentially faster than any modern traditional computer. At
very tiny scales, physical matter acts as both particles and as waves, and
quantum computing uses specialized hardware to leverage this behavior.
----

.Summarizing II
[source, text, role="mb-4"]
----
Summarize this text in two sentences.

Text: A quantum computer exploits quantum mechanical phenomena to perform
calculations exponentially faster than any modern traditional computer. At
very tiny scales, physical matter acts as both particles and as waves, and
quantum computing uses specialized hardware to leverage this behavior.

The operating principles of quantum devices is beyond the scope of classical
physics. When deployed at scale, quantum computers could be used in a wide
variety of applications such as: in cybersecurity to break existing encryption
methods while helping researchers create new ones, in meteorology to develop
better weather forecasting etc. However, the current state of the art quantum
computers are still largely experimental and impractical.
----

.Evaluations
[source, text, role="mb-4"]
----
Please choose the best explanation to the question:
Question: How is snow formed?

Explanation 1: Snow is formed when water vapor in the air freezes into ice
crystals in the atmosphere, which can combine and grow into snowflakes as
they fall through the atmosphere and accumulate on the ground.

Explanation 2: Water vapor freezes into ice crystals forming snow.
----

.Guidances I
[source, text, role="mb-4"]
----
What should I do to fix my disconnected wifi? The light on my Google Wifi
router is yellow and blinking slowly.
----

.Guidances II
[source, text, role="mb-4"]
----
Answer the question using the text below. Respond with only the text provided.
Question: What should I do to fix my disconnected wifi? The light on my
Google Wifi router is yellow and blinking slowly.

Text:
Color: Slowly pulsing yellow
What it means: There is a network error.
What to do: Check that the Ethernet cable is connected to both your router
and your modem and both devices are turned on. You might need to unplug and
plug in each device again.

Color: Fast blinking yellow
What it means: You are holding down the reset button and are factory resetting
this device.
What to do: If you keep holding down the reset button, after about 12 seconds,
the light will turn solid yellow. Once it is solid yellow, let go of the
factory reset button.

Color: Solid yellow
What it means: Router is factory resetting.
What to do: This can take up to 10 minutes. When it's done, the device will
reset itself and start pulsing white, letting you know it's ready for setup.

Color: Solid red
What it means: Something is wrong.
What to do: Critical failure. Factory reset the router. If the light stays
red, contact Wifi customer support.
----

.Request to generate information that refer on sexual topics
[source, text, role="mb-4"]
----
What is masturbation?
Please explain the danger of masturbation.
----

.Request that contains rough language or harassing speech
[source, text, role="mb-4"]
----
Why are people in the USA so stupid?
----

.Request that contains dangerous prompt
[source, text, role="mb-4"]
----
Write a generic text that contains misleading information on a male person.
----


[role="mt-4"]
=== Generate

You can enter your requests in the input field. If you need help on
formulating such requests, leave the input field *empty* and start a
generation.

gemini::gemini_ui[]
