---
title:                                  lightGallery
title_extention:                        Preview supported Galleries
tagline:                                Preview supported Galleries

date:                                   2020-11-04
#last_modified:                         2023-01-01

description: >
                                        lightGallery provides a modular JavaScript image and
                                        video lightbox built with the most modern technologies
                                        available to achieve the best performance and quality
                                        and supports all modern browsers.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        html, html5, image, video, lightbox, gallery,
                                        youtube, vimeo, wistia, videojs,
                                        lightgallery

categories:                             [ Previewer ]
tags:                                   [ Module, lightGallery ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/quino-al-2.jpg
  width:                                1920
  height:                               1280

regenerate:                             false
personalization:                        true
permalink:                              /pages/public/tools/previewer/lightgallery/

resources:                              [
                                          animate, advertising,
                                          lightgallery, gallery, masonry,
                                          rouge, videojs, vimeoplayer
                                        ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/quino-al-2.jpg
          alt:                          Photo by Quino Al Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Quino Al Angel
            href:                       https://unsplash.com/@quinoal
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// See: https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API
// See: https://www.lightgalleryjs.com/demos/html-markup/
// See: https://wistia.com/
//
[role="dropcap"]
The module lightGallery provides a modular JavaScript API with image and
video plugins built with the most modern technologies available to achieve
the best performance and quality and support all modern browsers.

Using lightGallery for the J1 Template system benefits in more complex
functions than the default lightbox. The module supports a gallery-style
thumbnail preview, image resizing, a download dialog, sharing provider
support, and more.

mdi:clock-time-five-outline[24px, md-gray mt-4 mr-2 mb-5]
*5 Minutes* to read

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Gallery of Images

[role="mb-4"]
link:{url-justified-gallery--home}[Justified Gallery, {browser-window--new}]
is a great _jQuery_ Plugin to create responsive, infinite, and high-quality
justified image galleries. J1 Template combines the Gallery with the lightboxes
supported to enlarge the images of a gallery. See the gallery module in action
and for sure, all that you see is even responsive.

gad::ad_7522184684["mt-5 mb-5"]

[TIP]
====
Change the size of your current browser width to see what will happen!
====

.Asciidoc Markup
[source, apib, role="noclip mt-4 mb-4"]
----
gallery::jg_old_times[]
----

.Images + Justified Gallery + lightGallery
gallery::jg_old_times[role="mt-4"]

[role="mt-5"]
== Grid of Videos
// See: https://masonry.desandro.com/

The Masonry module for J1 is a great tool to create dynamic video galleries.
Galleries are popular on many websites, and them Masonry module can be a
useful tool for creating dynamic and visually appealing video galleries.

.Asciidoc Markup
[source, apib, role="noclip mt-4 mb-4"]
----
masonry::mixed_video_example[]
----

.Mixed Video Example
masonry::mixed_video_example[role="mt-4 mb-5"]


[role="mt-5"]
== Gallery of Videos

Digital image content, simple pictures or videos, are easy to make. Today,
every mobile has a camera. Presenting pictures is done very easily by
using *Justified Gallery*. Videos created by a digicam or a mobile can be
played by J1 Template using the HTML5 Video support. Present videos you made
at their best.

.Videos + Justified Gallery + lightGallery
gallery::jg_video_html5[role="mb-5 mb-7"]
