---
title:                                  VideoJS
title_extention:                        Custom Video Players
tagline:                                Custom Video Players

date:                                   2024-11-10
#last_modified:                         2024-01-01

description: >
                                        The J1 Template support playing video on web pages
                                        by HTML5 Video, the new standard of HTML to show
                                        videos on web pages.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        html, html5, video, support, flash player,
                                        quicktime, silverlight

categories:                             [ Previewer ]
tags:                                   [ Module, Video ]

image:
  path:                                 /assets/image/icon/videojs/videojs-poster.png
  width:                                1920
  height:                               1280

regenerate:                             false
personalization:                        true
permalink:                              /pages/public/tools/previewer/videojs/

resources:                              [ videojs ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/icon/videojs/videojs-poster.png
          alt:                          VideoJS Poster
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

// Attribute settings for section control
//
:ytp_fortnight:                         false
:ytp_example:                           false


//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The J1 Template support playing audio on web pages by HTML5 Video, the new
standard of HTML to show videos on webpages. Modern browsers support the
audio tag `<audio>` for the new HTML5 audio audio standard.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Plugin `hotkeys`

The *hotkeys* plugin for Video.js enables *keyboard hotkeys* when the
*player has focus*.

* `Space bar` toggles play|pause.
* `Right|Left Arrow keys` seek the video forwards and back.
* Up and Down Arrow keys increase and decrease the volume.
* `M key` toggles mute/unmute.
* `F key` toggles fullscreen off and on. Does not work in Internet Explorer,
  it seems to be a limitation where scripts cannot request fullscreen without
  a mouse click:
* Double-clicking with the mouse toggles fullscreen off and on.
* `Number keys` from *1-9* skip to a percentage of the video:
  1 is `10%` and 9 is `90%`.

[role="mb-5"]
[NOTE]
====
Clicking any of the control buttons such as Play/Pause, Fullscreen,  or Mute,
will remove focus on the player which appears to *break* the hotkeys.

This is for accessibility reasons so that people who do not use or know about
the hotkeys can still properly use the `Tab` key to highlight the control
buttons and press `space` to toggle them.
====

*To restore focus*, just click on the video, or an empty part of the
control bar at the bottom of the video player. *To override this behaviour*,
set the flag `alwaysCaptureHotkeys` to `true`. This will *fix* hotkeys. For
accessibility, the `Tab` key may be used in combination with the
`Enter`|`Return` key to navigate and activate control buttons.

[role="mt-4"]
=== Options

* `volumeStep` (decimal): The percentage to increase/decrease the volume
   level when using the Up and Down Arrow keys (default: `0.1`)
* `seekStep` (integer or function): The number of seconds to seek forward
   and backwards when using the Right and Left Arrow keys, or a function
   that generates an integer given the `KeyboardEvent` (default: `5`)
* `enableMute` (boolean): Enables the volume mute to be toggle by pressing
   the *M* key (default: `true`)
* `enableVolumeScroll` (boolean): Enables increasing/decreasing the volume
   by scrolling the mouse wheel (default: `true`)
* `enableHoverScroll` (boolean): Only changes volume when the mouse is
   hovering over the volume control elements. This works in connection with
   `enableVolumeScroll` (default: `false`)
* `enableFullscreen` (boolean): Enables toggling the video fullscreen by
   pressing the *F* key (default: `true`)
* `enableNumbers` (boolean): Enables seeking the video by pressing the number
   keys (default `true`)
* `enableModifiersForNumbers` (boolean): Enables the use of
   Ctrl|Alt|Cmd + Number keys for skipping around in the video, instead of
   switching browser tabs. This is enabled by default due to backwards
   compatibility https://github.com/ctd1500/videojs-hotkeys/pull/35[PR #35]
   (default: `true`)
* `alwaysCaptureHotkeys` (boolean): Forces the capture of hotkeys, even when
   control elements are focused.

The *Enter*|*Return* key may be used instead to activate the control
elements. (default: `false`) 

[role="mb-5"]
[NOTE]
====
This feature may break accessibility, and cause unexpected behavior.
====

* `enableInactiveFocus` (boolean): This reassigns focus to the player when
  the control bar fades out after a user has clicked a button on the
  control bar (default: `true`)
* `skipInitialFocus` (boolean): This stops focusing the player on initial
  Play under unique autoplay situations. More information in
  https://github.com/ctd1500/videojs-hotkeys/issues/44[Issue #44] (default: `false`)
* `captureDocumentHotkeys` (boolean): Capture document keydown events to also
  use hotkeys even if the player does not have focus. If you enable this option,
  **you must** configure `documentHotkeysFocusElementFilter` (default: `false`)
* `documentHotkeysFocusElementFilter` (function): Filter function to capture
  document hotkeys (if `captureDocumentHotkeys` is enabled) depending on the
  current focused element. For example, if you want to capture hotkeys when
  the player is not focused and avoid conflicts when the user is focusing a
  particular link: `documentHotkeysFocusElementFilter: e => e.tagName.toLowerCase() === 'body'` (default: `() => false`)
* `enableJogStyle` (boolean): Enables seeking the video in a broadcast-style
  jog by pressing the Up and Down Arrow keys.

[WARNING]
====
`seekStep` will also need to be changed to get a proper broadcast-style jog.
 This feature and the changes for seekStep are explained a bit more in
 [PR #12](https://github.com/ctd1500/videojs-hotkeys/pull/12)
 Defaults to `false`.

This isn't a feature for everyone, and enabling JogStyle will disable the
volume hotkeys.
====

////
[role="mt-4"]
== Built-in Player

All modern browsers universally support the video tag `<video>`. This tag
offers an out-of-the-box framework for decoding and displaying video content
without loading *external players*.

.MP4 Video, Peck Pocketed
video::/assets/video/html5/peck_pocketed.mp4[poster="/assets/video/poster/html5/peck_pocketed.jpg", opts="" role="mt-4 mb-5"]

++++
<div class="videoblock mb-5">
  <div class="title">MP4 Video, Peck Pocketed</div>
  <video controls
    src="/assets/video/gallery/html5/video1.mp4"
    poster="/assets/video/gallery/video1-poster.jpg">
    Your browser does not support the video tag.
  </video>
</div>
++++

////


[role="mt-5"]
== VideoJS

VideoJS is a *free-to-use* open-source JavaScript framework for building
custom video players for the web. Implementing VideoJS for the J1 Template
supports local video and several platforms, such as YouTube, Vimeo, Wistia,
or Dailymotion, for presenting videos *online*.

For *online sources*, VideoJS uses plugins, such as the so-called VJS
Playback Technology. With the help of *plugins*, it is possible to present
*different media* using the *same player*, the same look and feel for a
better user experience.

// [role="mt-4"]
// === Local Video

// VideoJS provides a flexible and customizable platform for displaying and
// controlling MPEG 4 video content on websites and web applications.

// .Rolling Wild 路 MP4 Video
// videojs::/assets/video//html5/rolling_wild.mp4[poster="/assets/video/poster/html5/rolling_wild.jpg", opts="" role="mt-4 mb-5"]

[role="mt-4"]
=== YouTube

YouTube is a popular online video-sharing platform that allows users to
upload, view, share, and comment on videos. The platform provides services
for people and organizations to publish various video content.

// .Fortnight (feat. Post Malone, Official Music Video) 路 Taylor Swift
// youtube::q3zqJs7JUCQ[poster="//img.youtube.com/vi/q3zqJs7JUCQ/maxresdefault.jpg" role="mt-4 mb-5"]

++++
<div class="gallery-title">Adele 路 The Final Carpool Karaoke</div>
<video
  id="videojs_youtube_james"
  class="video-js vjs-theme-uno"
  controls
  width="640" height="360"
  poster="//img.youtube.com/vi/nV8UZJNBY6Y/maxresdefault.jpg"
  data-setup='{
    "fluid" : true,
    "rel": 0,
    "techOrder": [
      "youtube", "html5"
    ],
    "sources": [{
      "type": "video/youtube",
      "src": "//youtube.com/watch?v=nV8UZJNBY6Y"
    }],
    "controlBar": {
      "pictureInPictureToggle": false,
      "skipButtons": {
        "backward": 15,
        "forward": 15
      },                
      "volumePanel": {
        "inline": false
      }
    }
  }'
>
</video>
++++

++++
<script id='bla'>
  $(function() {

    function addCaptionAfterImage(imageSrc) {
      const image = document.querySelector(`img[src="${imageSrc}"]`);

      if (image) {
        // create div|caption container
        const newDiv = document.createElement('div');
        newDiv.classList.add('caption');
        newDiv.textContent = 'Adele 路 The Final Carpool Karaoke';

        // insert div|caption container AFTER the image
        image.parentNode.insertBefore(newDiv, image.nextSibling);
      } else {
        console.error(`Kein Bild mit src="${imageSrc}" gefunden.`);
      }
    }

    var dependencies_met_page_ready = setInterval (function (options) {
      var pageState      = $('#content').css("display");
      var pageVisible    = (pageState == 'block') ? true : false;
      var j1CoreFinished = (j1.getState() === 'finished') ? true : false;

      if (j1CoreFinished && pageVisible) {
         var captionImage = '//img.youtube.com/vi/nV8UZJNBY6Y/maxresdefault.jpg';
            var dependencies_met_page_ready = setInterval (function (options) {
              var pageState      = $('#content').css("display");
              var pageVisible    = (pageState == 'block') ? true : false;
              var j1CoreFinished = (j1.getState() === 'finished') ? true : false;

              if (j1CoreFinished && pageVisible) {

                if (captionImage) {
                  addCaptionAfterImage(captionImage);
                }

                var appliedOnce = false;
                videojs("videojs_youtube_james").ready(function() {
                  var videojsPlayer = this;

                  // add playbackRates
                  videojsPlayer.playbackRates([0.5, 1, 1.5, 2]);

                  // add skipButtons plugin
                  videojsPlayer.skipButtons({
                    forward:  10,
                    backward: 10
                  });

                  // set start position of current video
                  // -----------------------------------------------------------
                  videojsPlayer.on("play", function() {
                    var startFromSecond = new Date('1970-01-01T' + "#{attributes['start']}" + 'Z').getTime() / 1000;
                    if (!appliedOnce) {
                      videojsPlayer.currentTime(startFromSecond);
                      appliedOnce = true;
                    }
                  });

                });

        // scroll to player top position
        // -------------------------------------------------------------
        var vjs_player = document.getElementById('videojs_youtube_james');

        vjs_player.addEventListener('click', function(event) {
          event.preventDefault();
          event.stopPropagation();

          var scrollOffset = (window.innerWidth >= 720) ? -130 : -110;

          // scroll player to top position
          const targetDiv         = document.getElementById('videojs_youtube_james');
          const targetDivPosition = targetDiv.offsetTop;
          window.scrollTo(0, targetDivPosition + scrollOffset);
        }); // END EventListener 'click'

        clearInterval(dependencies_met_page_ready);
      }
    }, 10);
  });
</script>
++++

////
[role="mt-5"]
== Wistia

Wistia is a marketing software and video hosting platform for business-to-business
marketers. Free or paid plans are available. While Wistia may not be the
*Big Man on Campus*, like Vimeo, still brings valuable functionality and
should be considered a viable video platform.

.Platform Intro
// wistia::29b0fbf547[poster="/assets/video/poster/wistia/wistia-black.jpg" role="mt-4 mb-4"]
wistia::29b0fbf547[poster="auto" role="mt-4 mb-4"]
// wistia::29b0fbf547[role="mt-4 mb-4"]


[role="mt-5"]
== Vimeo

Vimeo is an sharing platform that allows users to upload, share, and view
video content. It was founded in 2004 by a group of filmmakers and has
since grown into a popular platform for individuals and businesses to
showcase their videos.

.Forever 21 - Kick It Old School
vimeo::179528528[poster="/assets/video/poster/vimeo/kick_it_old_school.jpg" role="mt-4 mb-5"]
// vimeo::179528528[poster="auto" role="mt-4 mb-5"]
// vimeo::179528528[role="mt-4 mb-5"]

[role="mb-7"]
.Video controls
[CAUTION]
====
For the *VJS Vimeo Tech*, native vjs controls (controllbar) are currently
*NOT* supported. Instead, the controllbar of the Vimeo Player is shown.
====
////