//  Update Amplitude API manual #2
// Added an explicit section anchor for stable cross-references, as used
// by the sub-documents of the SwiperJS API manual.
[role="mt-5"]
[[amplitude-api--metadata]]
== Metadata

////
Update Amplitude API manual #2
--------------------------------------------------------------------------------
Reworded the section introduction in simple English for beginners.
Original paragraphs (deprecated, preserved for reference):

Meta data elements get their information filled in with meta data from the
active song object or on initialization from the keyed song in the array.
These can be any type of HTML element except when filling in cover_art_url,
station_art_url, or podcast_episode_cover_art_url.

These specific keys have to be on an img tag since they update the src
attribute of the tag. Every other attribute fills in the inner html of
the tag.
--------------------------------------------------------------------------------
////

Metadata elements are *display* elements: Amplitude fills them
automatically with information about the *active song* -- the song name,
the artist, the album, the cover image, and so on. When the song
changes, the elements are updated automatically.

You can use almost any HTML tag for a metadata element. There is one
exception: the image keys `cover_art_url`, `station_art_url`, and
`podcast_episode_cover_art_url` must be placed on an `<img>` tag,
because Amplitude updates the `src` attribute of the tag. All other
keys fill in the *inner HTML* (the text) of the element.

[role="mt-4"]
=== Image Metadata

When defining a song object there are 3 different keys you can define
image meta data with:

* cover_art_url
* station_art_url
* podcast_episode_cover_art_url

These URLs point to an image that will be substituted out for the active
song image.

[role="mt-4"]
=== Text Metadata

With text metadata describing a song, you can use whatever information
you like and place it in whatever element you like. This give much more
flexibility when using Amplitude in a variety of audio scenarios such
as for radio stations and podcasts. To add an element that contains a
piece of meta data regarding the now playing song simply add:

[source, html]
----
<span data-amplitude-song-info="{song_meta_index}"></span>
----

If it's an element for a playlist add the key for the playlist:

[source, html]
----
<span
  data-amplitude-song-info="{song_meta_index}"
  data-amplitude-playlist="{playlist_index}">
</span>
----

[role="mt-4"]
=== Autofill Meta Data

Sometimes when building a player, you don't know what every song is on
load and need to load songs dynamically. With Amplitude this is not a
problem. Amplitude will autofill the meta data for lists of songs if
you do a combination of the following on the element.

data-amplitude-song-info::
  Defines the information you want injected into the element.
  This is the key of the song object.
data-amplitude-song-index::
  Defines the index of the song in the songs array that you want
  to inject into the element.

This is super convenient when loading songs dynamically either server
side or loading after the page has loaded.

[role="mt-4"]
=== Playlist Meta Data

When you add a playlist, you can add all sorts of other metadata to the
playlist object, similar to who song objects work. Amplitude also
takes care of initializing this data on the screen if you have your meta
data element keyed up correctly. Let's say you have a playlist title
field represented by `title` in the playlist element that you want to
display on the screen. You'd add an element that has the following
attributes:

[source, html]
----
<span
  data-amplitude-playlist-info="title"
  data-amplitude-playlist="{playlist_key}">
</span>
----

Essentially you have to add an attribute with the key of the element and
the playlist key in a format like this:

[source, html]
----
<span
  data-amplitude-playlist-info="{info}"
  data-amplitude-playlist="{playlist_key}">
</span>
----

[role="mt-4"]
=== Metadata for Time

There are certain elements that contain time data about the active song.
You can add these elements to your document and they will auto fill with
the current status of the song. Like other elements, these can be either
for the overall player, scoped in a playlist or for a specific song.

There are three sets of time meta data:

* current time
* song duration
* time remaining

The song *duration* can only be set for the *active* song since the metadata
isn't preloaded for all of the songs. The time remaining is a count down for
how much time is left for a song.

[role="mt-4"]
==== Current Time

Current Time Metadata is used for the *overall player* referencing the
*global* playlist defined by the *songs* array configured for an Amplitude
instance.

.Current Time
[cols="3,3a,6a", subs=+macros, options="header", width="100%", role="rtable mt-3"]
|===
|Name |Value |Description

|`amplitude-current-time`
|Current Time
|
.Format
----
Current Time - Displays in MM:SS
----

.Example
[source, html]
----
<span class="amplitude-current-time"></span>
----

|`amplitude-current-hours`
|Current Hours
|
.Example
[source, html]
----
<span class="amplitude-current-hours"></span>
----

|`amplitude-current-minutes`
|Current Minutes
|
.Example
[source, html]
----
<span class="amplitude-current-minutes"></span>
----

|`amplitude-current-seconds`
|Current Seconds
|
.Example
[source, html]
----
<span class="amplitude-current-seconds"></span>
----

|===


[role="mt-4"]
==== Duration Time

Duration Time Metadata is used for the *overall player* referencing the
*global* playlist defined by the *songs* array configured for an Amplitude
instance.

.Duration Time
[cols="3,3a,6a", subs=+macros, options="header", width="100%", role="rtable mt-3"]
|===
|Name |Value |Description

|`amplitude-duration-time`
|Duration Time
|
.Format
----
Duration Time - Displays in MM:SS
----

.Example
[source, html]
----
<span class="amplitude-duration-time"></span>
----

|`amplitude-duration-hours`
|Duration Hours
|
.Example
[source, html]
----
<span class="amplitude-duration-hours"></span>
----

|`amplitude-duration-minutes`
|Duration Minutes
|
.Example
[source, html]
----
<span class="amplitude-duration-minutes"></span>
----

|`amplitude-duration-seconds`
|Duration Seconds
|
.Example
[source, html]
----
<span class="amplitude-duration-seconds"></span>
----

|===


[role="mt-4"]
==== Metadata for a Playlist

.Format
----
Current Time For Playlist - Displays in MM:SS
----

[source, html]
----
<span
  class="amplitude-current-time"
  data-amplitude-playlist="{playlist_key}">
</span>
----

Current Hours For Playlist

[source, html]
----
<span
  class="amplitude-current-hours"
  data-amplitude-playlist="{playlist_key}">
</span>
----

Current Minutes For Playlist

[source, html]
----
<span
  class="amplitude-current-minutes"
  data-amplitude-playlist="{playlist_key}">
</span>
----

Current Seconds For Playlist

[source, html]
----
<span
  class="amplitude-current-seconds"
  data-amplitude-playlist="{playlist_key}">
</span>
----


[role="mt-4"]
==== Metadata for a Song

.Format
----
Current Time For Song
----

[source, html]
----
<span
  class="amplitude-current-time"
  data-amplitude-song-index="{song_index}">
</span>
----

Current Hours For Song
[source, html]
----
<span
  class="amplitude-current-hours"
  data-amplitude-song-index="{song_index}">
</span>
----

Current Minutes For Song

[source, html]
----
<span
  class="amplitude-current-minutes"
  data-amplitude-song-index="{song_index}">
</span>
----

Current Seconds For Song

[source, html]
----
<span
  class="amplitude-current-seconds"
  data-amplitude-song-index="{song_index}">
</span>
----

[role="mt-4"]
==== Metadata for a Song in a Playlist

Current Time For Song In Playlist

[source, html]
----
<span
  class="amplitude-current-time"
  data-amplitude-playlist="{playlist_key}"
  data-amplitude-song-index="{song_index}">
</span>
----

Current Hours For Song In Playlist
[source, html]
----
<span
  class="amplitude-current-hours"
  data-amplitude-playlist="{playlist_key}"
  data-amplitude-song-index="{song_index}">
</span>
----

Current Minutes For Song In Playlist

[source, html]
----
<span
  class="amplitude-current-minutes"
  data-amplitude-playlist="{playlist_key}"
  data-amplitude-song-index="{song_index}">
</span>
----

Current Seconds For Song In Playlist

[source, html]
----
<span
  class="amplitude-current-seconds"
  data-amplitude-playlist="{playlist_key}"
  data-amplitude-song-index="{song_index}">
</span>
----

Duration Time For Playlist - Displays in MM:SS

[source, html]
----
<span
  class="amplitude-duration-time"
  data-amplitude-playlist="{playlist_key}">
</span>
----

Duration Hours For Playlist

[source, html]
----
<span
  class="amplitude-duration-hours"
  data-amplitude-playlist="{playlist_key}">
</span>
----

Duration Minutes For Playlist

[source, html]
----
<span
  class="amplitude-duration-minutes"
  data-amplitude-playlist="{playlist_key}">
</span>
----

Duration Seconds For Playlist

[source, html]
----
<span
  class="amplitude-duration-seconds"
  data-amplitude-playlist="{playlist_key}">
</span>
----

Duration Time For Song - Displays in MM:SS

[source, html]
----
<span
  class="amplitude-duration-time"
  data-amplitude-song-index="{song_index}">
</span>
----

Duration Hours For Song

[source, html]
----
<span
  class="amplitude-duration-hours"
  data-amplitude-song-index="{song_index}">
</span>
----

Duration Minutes For Song

[source, html]
----
<span
  class="amplitude-duration-minutes"
  data-amplitude-song-index="{song_index}">
</span>
----

Duration Seconds For Song

[source, html]
----
<span
  class="amplitude-duration-seconds"
  data-amplitude-song-index="{song_index}">
</span>
----

Main Time Remaining For Song

[source, html]
----
<span class="amplitude-time-remaining"></span>
----

Playlist Main Time Remaining For Song

[source, html]
----
<span
  class="amplitude-time-remaining"
  data-amplitude-playlist="{playlist_key}">
</span>
----

Song Time Remaining

[source, html]
----
<span
  class="amplitude-time-remaining"
  data-amplitude-song-index="{song_index}">
</span>
----

[role="mt-4"]
=== Song Container

This is a unique element. What this does is allow you to assign a
container to the visual representation of a song or a song in a
playlist. When that song is currently playing, the class
`amplitude-active-song-container` will be applied to the song container
element. This way you can style the element to show the active song.

For a single song container it would be:

[source, html]
----
<div class="amplitude-song-container" data-amplitude-song-index="{X}"></div>
----

For a playlist song container it would be:

[source, html]
----
<div
  class="amplitude-song-container"
  data-amplitude-playlist="{playlist_key}"
  data-amplitude-song-index="{song_index}">
</div>
----
