// Update Amplitude API manual #2
// Added an explicit section anchor for stable cross-references, as used
// by the sub-documents of the SwiperJS API manual.
[role="mt-5"]
[[amplitude-api--methods]]
== Methods

Amplitude exposes a number of *public methods* that you can call from
your own JavaScript code. Most pages do not need any of them: the CSS
classes (`amplitude-play`, `amplitude-pause`, ...) and data attributes
described above already cover normal use. You only need the methods
below when you want to:

* add or remove songs *after* the page has loaded,
* read the current player state for a custom display, or
* change a setting (volume increment, default album art, ...) on the
  fly.

All methods are called on the global `Amplitude` object, for example
`Amplitude.play()`.

[role="mt-4"]
=== Bind new Elements

The bind new elements function should be called whenever a new song
element is added to the page. This will bind all of the event handlers
for that element.

[source, js]
----
Amplitude.bindNewElements()
----

[role="mt-4"]
=== Add a Playlist

This method allows you to add a playlist to Amplitude. To do this, you
need a unique key for your playlist, the data describing your playlist
such as `title`, `author`, etc. and an array of song objects for your
playlist.

[source, js]
----
Amplitude.addPlaylist( key, data, songs );
----

The first argument is the `key`. Remember this is a JSON key and should
be formatted as such.

The second argument is all of the data describing the playlist such as
`name`, `title`, `author`, etc. in the form of a JSON object.

Finally, the third argument is an array of song objects. These are the
songs that will be added to the playlist.

[role="mt-4"]
=== Add a Song

Adds a song to the Amplitude player. You will need to write a method
yourself to add the visual side of things to fit your custom design, and
then call the bindNewElements() method to make sure it works.

This method returns the index of the song added to the player.

[source, js]
----
Amplitude.addSong( {song_object} );
----

[role="mt-4"]
=== Prepend a Song

Adds a song to the beginning of the Amplitude player. After
pre-pending the song, you will have to bindNewElements() method to make
sure that any visuals are updated as well.

This method returns the index of the song added to the player.

[source, js]
----
Amplitude.prependSong( {song_object} );
----

[role="mt-4"]
=== Add a Song to a Playlist

Adds a song to a specific playlist within Amplitude. Once the song is
added you will need to update the visual side of the player yourself.
After you update the visual side, run the `Amplitude.bindNewElements()`
method to make sure the functionality is there for the new element.

[source, js]
----
Amplitude.addSongToPlaylist( songObject, playlistKey )
----

[role="mt-4"]
=== Remove a Song

Removes a song from the global song array. You will have to remove the
containing element by yourself.

[source, js]
----
Amplitude.removeSong( indexOfSong )
----

[role="mt-4"]
=== Remove a Song From Playlist

Removes a song from a playlist. You will have to update the visual side
by yourself.

[source, js]
----
Amplitude.removeSongFromPlaylist( indexOfSongInPlaylist, playlistKey )
----

[role="mt-4"]
=== Play

This simply plays whatever song is active.

[source, js]
----
Amplitude.play()
----

[role="mt-4"]
=== Play a Song At Index

Plays whatever song is set in the config at the specified index.

[source, js]
----
Amplitude.playSongAtIndex( songIndex )
----

[role="mt-4"]
=== Play a Playlist Song At Index

Plays the song in a playlist at the specified index.

[source, js]
----
Amplitude.playPlaylistSongAtIndex( playlistIndex, playlistKey )
----

[role="mt-4"]
=== Play Now

In Amplitude 2.0 this was referred to as 'Dynamic Mode'. Now you can
just pass a song to Amplitude and it will automatically play. If there
are visual elements, then they will sync as well.

[source, js]
----
Amplitude.playNow( {song_object} );
----

[role="mt-4"]
=== Pause

This simply pauses whatever song is active.

[source, js]
----
Amplitude.pause()
----

[role="mt-4"]
=== Stop

This simply stops whatever song is active.

[source, js]
----
Amplitude.stop()
----

[role="mt-4"]
=== Next

Plays the next song either in the playlist or globally.

[source, js]
----
Amplitude.next( playlistKey = null )
----

[role="mt-4"]
=== Prev

Plays the previous song either in the playlist or globally.

[source, js]
----
Amplitude.prev( playlistKey = null )
----

[role="mt-4"]
=== Skip To

Allows the user to skip to a specific location in the song whether that
song is in a playlist or not.

[source, js]
----
Amplitude.skipTo( seconds, songIndex, playlist = null )
----

[role="mt-4"]
=== Register Visualization

The other way to register a visualization is through the public
`Amplitude.registerVisualization( visualization, preferences )` method.
The first parameter being the object included with the visualization
file and the second parameter being a JSON object containing any of the
parameters needed to overwrite defaults provided by the visualization.

[source, js]
----
  Amplitude.registerVisualization( visualization, preferences );
----


[role="mt-5"]
=== Setters

Setter methods change a value inside Amplitude *while the player is
running*. Use them when you need to react to something that happens
*after* `Amplitude.init()`, for example: a user changes the album art,
your back-end sends new song meta data, or a different playlist is
selected. Each setter takes one or two arguments and returns nothing.

[role="mt-4"]
==== Set Default Album Art

Sets the default album art for the player to the URL provided.

[source, js]
----
Amplitude.setDefaultAlbumArt( url )
----

[role="mt-4"]
==== Set Default Playlist Art

Sets the default playlist art.

[source, js]
----
Amplitude.setDefaultPlaylistArt( url )
----

[role="mt-4"]
==== Set Debug

To change the debug mode setting, you can call the setDebug method any
time and start to receive data about the state of the player or turn off
debugging.

[source, js]
----
Amplitude.setDebug( {bool} );
----

[role="mt-4"]
==== Set Delay

If you have multiple songs that your player is using you can change the
amount of time you have as a delay between the songs. When one song
ends, what is set will be the amount of time delayed before the next
song starts.

[source, js]
----
Amplitude.setDelay( milliseconds )
----

[role="mt-4"]
==== Set Global Visualization

You can set the global visualization through the public method like
this:

[source, js]
----
  Amplitude.setGlobalVisualization( visualizationKey );
----

[role="mt-4"]
==== Set Playlist Visualization

You can set the visualization through the public facing method like
this:

[source, js]
----
  Amplitude.setPlaylistVisualization( playlist_key, visualization_key );
----

[role="mt-4"]
==== Set Individual Song Visualization

You can set the visualization for an individual song like so:

[source, js]
----
  Amplitude.setSongVisualization( songIndex, visualizationKey );
----

[role="mt-4"]
==== Set Individual Song In Playlist Visualization

You can set the visualization for an individual song in a playlist
using:

[source, js]
----
Amplitude.setSongInPlaylistVisualization( playlistKey, songIndex, visualizationKey );
----

[role="mt-4"]
==== Set Shuffle

Sets the global shuffle state for Amplitude.

[source, js]
----
Amplitude.setShuffle( shuffleState )
----

[role="mt-4"]
==== Set Shuffle Playlist

Sets the shuffle state for a playlist.

[source, js]
----
Amplitude.setShufflePlaylist( playlistKey, shuffleState )
----

[role="mt-4"]
==== Set Repeat

Sets the global repeat status for Amplitude

[source, js]
----
Amplitude.setRepeat( repeatState )
----

[role="mt-4"]
==== Set Repeat Song

Sets the global state to determine if we should repeat the individual
song upon completion.

[source, js]
----
Amplitude.setRepeatSong( repeatSongState )
----

[role="mt-4"]
==== Set Repeat Playlist

Sets the repeat for the playlist.

[source, js]
----
Amplitude.setRepeatPlaylist( playlistKey, repeatState )
----

[role="mt-4"]
==== Set Song Played Percentage

This method allows you to set the percentage of the active song. The
method accepts a float between 0 and 100 for the percentage of the song
to be set to.

[source, js]
----
Amplitude.setSongPlayedPercentage( percentage )
----

[role="mt-4"]
==== Set Song Meta Data

You can set the meta data for any song in your song objects. This is
helpful if you are doing a live stream and have a call back that returns
the information of what song is currently playing.

[source, js]
----
Amplitude.setSongMetaData( index, metaData )
----

The first parameter `index` is the index of the song in the songs array
you are setting the meta data for. The `metaData` is an object that
contains meta data similar to a song object. The keys that get passed
will be updated on the song object at the index. The only key that can
not be updated is the `url`.

[role="mt-4"]
==== Set Playlist Meta Data

You can set the metadata for the playlist. Similar to the songs object,
you can do it for a playlist object.

[source, js]
----
Amplitude.setPlaylistMetaData( playlist, metaData )
----

The first argument `playlist` is the key of the playlist we are setting
the meta data for and the second object `metaData` is the object
containing all of the keys we are updating.

[role="mt-5"]
=== Getters

Getter methods *read* a value from Amplitude without changing anything.
They are most useful when you need to display the current state of the
player (the active song, the current volume, whether shuffle is on, ...)
in your own custom UI, or when you want to log information for
debugging. Each getter returns the value directly, so you can assign it
to a variable: `const state = Amplitude.getPlayerState();`

[role="mt-4"]
==== Get Analyser

Returns the Web Audio API Analyser. This allows for the user to bind to
the active audio through the web audio API.

[source, js]
----
Amplitude.getAnalyser()
----

[role="mt-4"]
==== Get Config

Returns the current Amplitude configuration.

[source, js]
----
Amplitude.getConfig();
----

[role="mt-4"]
==== Get Delay

Gets the current delay between songs in milliseconds.

[source, js]
----
Amplitude.getDelay();
----

[role="mt-4"]
==== Get Player State

Returns the current state of the player whether it's `playing`,
`paused`, or `stopped`.

[source, js]
----
Amplitude.getPlayerState()
----

[role="mt-4"]
==== Get Active Playlist

This method will return the key of the active playlist.

[source, js]
----
Amplitude.getActivePlaylist()
----

[role="mt-4"]
==== Get Playback Speed

Returns the current playback speed for the player.

[source, js]
----
Amplitude.getPlaybackSpeed()
----

[role="mt-4"]
==== Get Repeat

Returns the state of the global repeat status for the player.

[source, js]
----
Amplitude.getRepeat()
----

[role="mt-4"]
==== Get Repeat Playlist

Returns the state of the repeat status for the playlist.

[source, js]
----
Amplitude.getRepeatPlaylist( playlistKey )
----

[role="mt-4"]
==== Get Shuffle

Returns the current state of the global shuffle status for the player.

[source, js]
----
Amplitude.getShuffle()
----

[role="mt-4"]
==== Get Shuffle Playlist

Returns the state of the shuffle flag for a playlist.

[source, js]
----
Amplitude.getShufflePlaylist( playlistKey )
----

[role="mt-4"]
==== Get Default Album Art

Returns the default album art URL set in the player.

[source, js]
----
Amplitude.getDefaultAlbumArt()
----

// Removed a duplicated "Get Default Album Art" section that appeared
// twice in a row with the same code example. Only one entry is kept.

[role="mt-4"]
==== Get Default Playlist Art

Gets the default art for a playlist.

[source, js]
----
Amplitude.getDefaultPlaylistArt()
----

[role="mt-4"]
==== Get Active Song Metadata

Returns the active song's metadata as a JSON object.

[source, js]
----
Amplitude.getActiveSongMetadata();
----

[role="mt-4"]
==== Get Active Playlist Metadata

Gets the active playlist's metadata as a JSON object.

[source, js]
----
Amplitude.getActivePlaylistMetadata();
----

[role="mt-4"]
==== Get Active Index

This method returns the index of the active song in the songs array.

[source, js]
----
Amplitude.getActiveIndex()
----

[role="mt-4"]
==== Get Active Index State

This method returns the index of the active song in the songs array but
accounts for if shuffle has been enabled or not.

[source, js]
----
Amplitude.getActiveIndexState()
----

[role="mt-4"]
==== Get Audio

This returns the actual audio element. This is mainly used for writing
extensions but exposes the core of Amplitude. This returns the audio
element used by Amplitude.

[source, js]
----
Amplitude.getAudio()
----

[role="mt-4"]
==== Get Buffered

This method returns the buffered percentage of the now playing song.
This can be used to show how much of the song has been buffered and
ready to be played.

[source, js]
----
Amplitude.getBuffered()
----

[role="mt-4"]
==== Get songs

This method returns all of the songs defined in Amplitude. It can be
used for a variety of different functions. It's extremely helpful if you
are AJAX loading songs and want to see the contents of the song array.

[source, js]
----
Amplitude.getSongs()
----

[role="mt-4"]
==== Get Songs In Playlist

This method returns all of the songs in a playlist. Since the user
defines a playlist with a key and the indexes of the songs, this will
map the keys to the songs and return all of the songs in the playlist.

[source, js]
----
Amplitude.getSongsInPlaylist( playlistKey )
----

[role="mt-4"]
==== Get Songs State

This method returns the current order of the songs. It can be used for
determining what song is next. If shuffle is on, it will return the
shuffled list of songs.

[source, js]
----
Amplitude.getSongsState()
----

[role="mt-4"]
==== Get Songs State Playlist

This method returns the current order of the songs in a playlist. If
needed this can be used to determine the next song in a playlist. This
accounts for whether the playlist has been shuffled or not.

[source, js]
----
Amplitude.getSongsStatePlaylist( playlist )
----

[role="mt-4"]
==== Get Song Played Percentage

This method returns the percentage of the song played. When implementing
a 3rd party tracking element, you can set the percentage of the element
to the percentage played of the song.

[source, js]
----
Amplitude.getSongPlayedPercentage()
----

You can combine this method with the time_update callback and whenever
the time updates your method can call
Amplitude.getSongPlayedPercentage() and you can set your tracking
element correctly.

[role="mt-4"]
==== Get Song Played Seconds

This method returns the current seconds the user is into the song.

[source, js]
----
Amplitude.getSongPlayedSeconds()
----

[role="mt-4"]
==== Get Song Duration

Returns the duration of the current song.

[source, js]
----
Amplitude.getSongDuration()
----

[role="mt-4"]
==== Get Song At Index

Returns a song's metadata at a specific index.

[source, js]
----
Amplitude.getSongAtIndex( {index} );
----

[role="mt-4"]
==== Get Song At Playlist Index

Returns a song at a playlist's index.

[source, js]
----
Amplitude.getSongAtPlaylistIndex( {playlistIndex}, {index} );
----

[role="mt-4"]
==== Get Version

This method returns the version of Amplitude being used.

[source, js]
----
Amplitude.getVersion()
----
