---
title:                                  J1
tagline:                                about
date:                                   2022-01-01 00:00:00
description: >
                                        Things you should know about this site,
                                        the people and the software and/or
                                        services provided.

tags:                                   [ Overview ]
categories:                             [ Software, Platforms, Contributers ]

scrollbar:                              false

permalink:                              /pages/public/gist/
regenerate:                             false

resources:                              []
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/runner-1920x1200.jpg
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        false

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ifeval::[{badges-enabled} == true]
{badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
endif::[]

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

image:https://mybinder.org/badge_logo.svg[Binder, link="https://mybinder.org/v2/gist/jekyll-one/7818823efbfa538c35cc811da9e72296", window="_blank"]


== Github ODE Gist

// See: https://towardsdatascience.com/ordinal-differential-equation-ode-in-python-8dc1de21323b

Ordinary Differential Equation (ODE) can be used to describe a dynamic system.
To some extent, we are living in a dynamic system, the weather outside of the
window changes from dawn to dusk, the metabolism occurs in our body is also a
dynamic system because thousands of reactions and molecules got synthesized
and degraded as time goes.

.Ordinary Differential Equation (ODE) in Python
[source, prometheus, role="noclip"]
----
.Guard setup to live preview AsciiDoc output
gist::jekyll-one/7818823efbfa538c35cc811da9e72296[]
----

[.result]
====
.Ordinary Differential Equation (ODE) in Python
gist::jekyll-one/7818823efbfa538c35cc811da9e72296[]
====

More formally, if we define a set of variables, like the temperatures in a
day,and it changes with the independent variable (in a dynamic system, usually
it will be time t).
ODE offers us a way to mathematically depict the dynamic changes of defined
variables. The opposite system to that is called static system, thinking about
taking a photo of the outside, this snapshot doesn’t contain any dynamics,
in another word, it is static.

Solving Ordinary Differential Equations means determining how the variables
will change as time goes by, the solution, sometimes referred to as solution
curve (visually shown as below), provide informative prediction to the default
behavior of any dynamic systems.
