---
title:                                  Amplitude
title_extention:                        Custom Audio Players
tagline:                                Custom Audio Players

date:                                   2024-04-17
#last_modified:                         2024-01-01

description: >
                                        Amplitude is a JavaScript library to control the design of audio media
                                        elements on web pages. The concept allows designers to fully control the
                                        look and feel of audio players without deep scripting knowledge.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap, html, html5, audio,
                                        Amplitude

categories:                             [ Testpage ]
tags:                                   [ Audio. Amplitude ]

image:
  path:                                 /assets/images/icons/videojs/videojs-poster.png
  width:                                1920
  height:                               1280

regenerate:                             false
personalization:                        true
permalink:                              /pages/public/amplitude_tester/

resources:                              [ amplitude-js ]
resource_options:
  - toccer:
      collapseDepth:                    2
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/alexey-ruban.jpg
          alt:                          Photo by Alexey Ruban on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexey Ruban
            href:                       //unsplash.com/de/@intelligenciya
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Amplitude allows designers to fully control their audio players' look and
feel without understanding advanced scripting.

The audio tag `<audio>` in HTML5 is a great way to add audio to web pages.
However, the browser controls the audio playback interface, which can be very
limiting. Amplitude steps in and enables designers for the power to create
interfaces using themes to define the look and feel of the audio control
elements individually.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== J1 Audio Player
// See: https://521dimensions.com/open-source/amplitudejs/docs
// See: https://github.com/mediaelement/mediaelement-plugins
// See: https://github.com/serversideup/amplitudejs/

Amplitude is a JavaScript library to control the design of audio media
elements on web pages. The concept allows designers to fully control the
look and feel of audio players without deep scripting knowledge.

[NOTE]
====
Amplitude players are mobile-friendly. Touch events will be applied for
mobile devices instead of clicking on the appropriate elements.
====

The J1 Template implements a custom player based on the (default) theme Uno.
The color scheme used matches the look and feel of the template.

.Amy Winehouse · Back To Black
amplitude::back_to_black[role="mt-3 mb-5"]


[role="mt-5"]
== Player configuration

lorem:sentences[5]

[role="mt-4"]
=== Macro `amplitude::`

lorem:sentences[7]

[role="mt-4"]
=== Module settings

[role="mb-7"]
lorem:sentences[7]
