---
title:                                  Amplitude
title_extention:                        Custom Audio Player
tagline:                                Custom Audio Player

date:                                   2024-04-17
#last_modified:                         2024-01-01

description: >
                                        Amplitude is a JavaScript library to control the design of audio media
                                        elements on web pages. The concept allows designers to fully control the
                                        look and feel of audio players without deep scripting knowledge.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap, html, html5, audio,
                                        Amplitude

categories:                             [ Testpage ]
tags:                                   [ Audio. Amplitude ]

image:
  path:                                 /assets/images/icons/videojs/videojs-poster.png
  width:                                1920
  height:                               1280

regenerate:                             false
personalization:                        true
permalink:                              /pages/public/amplitude_tester/

resources:                              [ amplitude-js ]
resource_options:
  - toccer:
      collapseDepth:                    2
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/alexey-ruban.jpg
          alt:                          Photo by Alexey Ruban on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexey Ruban
            href:                       //unsplash.com/de/@intelligenciya
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// See: https://521dimensions.com/open-source/amplitudejs/docs
// See: https://github.com/mediaelement/mediaelement-plugins
// See: https://github.com/serversideup/amplitudejs/

[role="dropcap"]
Amplitude allows designers to fully control their audio players' look and
feel without understanding advanced scripting.

The audio tag `<audio>` in HTML5 is a great way to add audio to web pages.
However, the browser controls the audio playback interface, which can be very
limiting. Amplitude steps in and enables designers for the power to create
interfaces using themes to define the look and feel of the audio control
elements individually.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Single Song Player

Balla Balla ..

++++
<div id="audio-player-container" class="mb-5">
  <!-- Player -->
  <div id="single-song-player" class="single-song-player">
    <img data-amplitude-song-info="cover_art_url"/>

    <div class="bottom-container">

      <progress id="single-song-player-progress" class="amplitude-song-played-progress"></progress>

      <div class="time-container">
        <span class="current-time">
          <span class="amplitude-current-minutes"></span>:<span class="amplitude-current-seconds"></span>
        </span>
        <span class="duration">
          <span class="amplitude-duration-minutes"></span>:<span class="amplitude-duration-seconds"></span>
        </span>
      </div>

      <div class="single-song-player control-container">
        <div id="play-pause" class="amplitude-play-pause"></div>
        <div class="meta-container single-song-player">
          <span data-amplitude-song-info="name" class="song-name"></span>

          <span class="single-song-player-song-artist-album">
            <span data-amplitude-song-info="artist" data-amplitude-song-index="0">Amy Winehouse</span>
            <span data-amplitude-song-info="album" data-amplitude-song-index="0" style="margin-top: 5px; margin-bottom: 15px">Back To Black</span>
          </span>

          <div id="volume-container" class="single-song-player-volume-container">
            <img src="/assets/themes/j1/modules/amplitudejs/icons/volume.svg">
            <input type="range" class="single-song-player amplitude-volume-slider" step=".1">
          </div>


      </div>
    </div>

  </div>

</div>
++++


++++
<style>

/* Single Song-Player
 =============================================================================== */

/* 1. Base
------------------------------------------------------------------------------- */


/* 2. Components
------------------------------------------------------------------------------- */
.single-song-player-volume-container {
  display: flex;
  margin-left: -54px;
  padding-bottom: 12px;
  padding-top: 5px;
}

/* div#volume-container {
  padding-bottom: 26px;
  text-align: center;
} */

div#volume-container input[type=range]::-webkit-slider-thumb {
  box-shadow: 0px 0px 0px #000000, 0px 0px 0px #0d0d0d;
  border: 1px solid var(--ajs-theme-uno--blue);
  height: 15px;
  width: 15px;
  border-radius: 16px;
  background: var(--ajs-theme-uno--blue);
  cursor: pointer;
  -webkit-appearance: none;
  margin-top: -7.5px;
}

div#volume-container input[type=range]:focus::-webkit-slider-runnable-track {
  background: var(--ajs-theme-uno--gray-300);
}

div#volume-container input[type=range]::-moz-range-thumb {
  box-shadow: 0px 0px 0px #000000, 0px 0px 0px #0d0d0d;
  border: 1px solid var(--ajs-theme-uno--blue);
  height: 15px;
  width: 15px;
  border-radius: 16px;
  background: var(--ajs-theme-uno--blue);
  cursor: pointer;
}

div.single-song-player.meta-container {
   width: calc(60% + 60px) !important;
   padding-bottom: 16px;
}

div.single-song-player.control-container {
   margin-top: 5px;
   /* padding-bottom: 16px; */
}

input[type=range].single-song-player.amplitude-volume-slider {
  margin-top: 0px;
  /*  jadams
  webkit-appearance: none;
  width: calc(100% - 33px);
  float: left;
  margin-left: 20px;
  background: transparent;
  */
}

div.control-container div.amplitude-play-pause {
   width: 70px;
   height: 70px;
   cursor: pointer;
   float: left;
   margin-top: 5px;
   margin-left: 24px;
}

div.control-container div.amplitude-play-pause.amplitude-paused {
   background: url("/assets/themes/j1/modules/amplitudejs/icons/black/play.svg");
   background-size: cover;
}

div.control-container div.amplitude-play-pause.amplitude-playing {
   background: url("/assets/themes/j1/modules/amplitudejs/icons/black/pause.svg");
   background-size: cover;
}

div.control-container div.meta-container {
  float: left;
  text-align: center;
  color: white;
  margin-top: 5px;
  margin-left: 12px;
}

div.control-container div.meta-container span[data-amplitude-song-info="name"] {
   font-family: "Lato", sans-serif;
   font-size: 24px;
   color: #fff;
   display: block;
}

div.control-container div.meta-container span[data-amplitude-song-info="artist"] {
   font-family: "Lato", sans-serif;
   opacity: 0.5;
   font-size: 16px;
   color: #fff;
   letter-spacing: 0.5px;
   line-height: 16px;
   display: block;
}

div.control-container div.meta-container span[data-amplitude-song-info="album"] {
   font-family: "Lato", sans-serif;
   opacity: 0.5;
   font-size: 16px;
   color: #fff;
   letter-spacing: 0.5px;
   line-height: 16px;
   display: block;
}

div.control-container:after {
   content: "";
   display: table;
   clear: both;
}

/*   Small only
------------------------------------------------------------------------------- */
@media screen and (max-width: 39.9375em) {
  div.control-container div.amplitude-play-pause {
     background-size: cover;
     width: 64px;
     height: 64px;
  }

  div.control-container div.meta-container {
    width: calc(100% - 74px);
  }
}

/* Medium only
------------------------------------------------------------------------------- */

/* Large Only
------------------------------------------------------------------------------- */
div.time-container {
  font-family: "Lato", sans-serif;
  font-weight: bold;
  font-size: 12px;
  color: #fff;
  height: 18px;
}

div.time-container span.current-time {
   float: left;
   margin-left: 5px;
}

div.time-container span.duration {
   float: right;
   margin-right: 5px;
}

/* Small only
------------------------------------------------------------------------------- */

/* Medium only
------------------------------------------------------------------------------- */

/* Large Only
------------------------------------------------------------------------------- */
progress.amplitude-song-played-progress {
  background-color: var(--ajs-theme-uno--gray-700) !important;
  -webkit-appearance: none;
  appearance: none;
  width: 100%;
  height: 6px;
  display: block;
  cursor: pointer;
  border: none;
}

progress.amplitude-song-played-progress:not([value]) {
   background-color: var(--ajs-theme-uno--gray-800);
}

progress[value]::-webkit-progress-bar {
  background-color: var(--ajs-theme-uno--gray-800);
}

progress[value]::-moz-progress-bar {
  background-color: var(--ajs-theme-uno--blue);
}

progress[value]::-webkit-progress-value {
  background-color: var(--ajs-theme-uno--blue);
}

/* Small only
------------------------------------------------- ------------------------------ */

/* Medium only
------------------------------------------------------------------------------- */

/* Large Only
------------------------------------------------------------------------------- */

/* 3. Layout
------------------------------------------------------------------------------- */
div.bottom-container {
  background-color: var(--ajs-theme-uno--blue-gray-900);
}

/* Small only
------------------------------------------------------------------------------- */

/* Medium only
------------------------------------------------------------------------------- */

/* Large Only
------------------------------------------------------------------------------- */
div#single-song-player {
   /* width: 100%; */
   max-width: 475px;
   -webkit-font-smoothing: antialiased;
}

div#single-song-player img[data-amplitude-song-info="cover_art_url"] {
   width: 100%;
   /* border-top-right-radius: 10px;
   border-top-left-radius: 10px; */
}

/* Small only
------------------------------------------------------------------------------- */

/* Medium only
------------------------------------------------------------------------------- */

/* Large Only
------------------------------------------------------------------------------- */


/* 4. Pages
------------------------------------------------------------------------------- */

/* 5. Themes
------------------------------------------------------------------------------- */

/* 6. Utils
------------------------------------------------------------------------------- */

/* 7. Vendors
------------------------------------------------------------------------------- */

/* 8. Animations
 ------------------------------------------------------------------------------- */

</style>
++++


[role="mt-5"]
== Flat Player

Balla Balla ..

++++
<div id="flat-black-player-container">

  <div id="list-screen" class="slide-in-top">

    <div id="list-screen-header" class="hide-playlist">
      <img id="up-arrow" src="/assets/themes/j1/modules/amplitudejs/icons/up.svg"/>
      Hide Playlist
    </div>

    <div id="list" class="hide-scrollbar">

      <div class="song amplitude-song-container amplitude-play-pause" data-amplitude-song-index="0">
        <span class="song-number-now-playing">
        <span class="number">1</span>
        <img class="now-playing" src="/assets/themes/j1/modules/amplitudejs/icons/black/now-playing.svg"/>
        </span>
        <div class="song-meta-container">
          <span class="song-name" data-amplitude-song-info="name" data-amplitude-song-index="0"></span>
          <span class="song-artist-album">
            <span data-amplitude-song-info="artist" data-amplitude-song-index="0"></span>
            <span class="song-artist-album-delimiter">·</span>
            <span data-amplitude-song-info="album" data-amplitude-song-index="0"></span>
          </span>
        </div>
        <span class="song-duration">3:30<span>
      </div>
      <div class="song amplitude-song-container amplitude-play-pause" data-amplitude-song-index="1">
        <span class="song-number-now-playing">
        <span class="number">2</span>
        <img class="now-playing" src="/assets/themes/j1/modules/amplitudejs/icons/black/now-playing.svg"/>
        </span>
        <div class="song-meta-container">
          <span class="song-name" data-amplitude-song-info="name" data-amplitude-song-index="1"></span>
          <span class="song-artist-album">
            <span data-amplitude-song-info="artist" data-amplitude-song-index="1"></span>
            <span class="song-artist-album-delimiter">·</span>
            <span data-amplitude-song-info="album" data-amplitude-song-index="1"></span>
          </span>
        </div>
        <span class="song-duration">4:17<span>
      </div>
      <div class="song amplitude-song-container amplitude-play-pause" data-amplitude-song-index="2">
        <span class="song-number-now-playing">
        <span class="number">3</span>
        <img class="now-playing" src="/assets/themes/j1/modules/amplitudejs/icons/black/now-playing.svg"/>
        </span>
        <div class="song-meta-container">
          <span class="song-name" data-amplitude-song-info="name" data-amplitude-song-index="2"></span>
          <span class="song-artist-album">
            <span data-amplitude-song-info="artist" data-amplitude-song-index="2"></span>
            <span class="song-artist-album-delimiter">·</span>
            <span data-amplitude-song-info="album" data-amplitude-song-index="2"></span>
          </span>
        </div>
        <span class="song-duration">2:33<span>
      </div>

      <div id="list-screen-footer">
        <div id="list-screen-meta-container">
          <span data-amplitude-song-info="name" class="song-name"></span>
          <div class="song-artist-album">
            <span data-amplitude-song-info="artist" data-amplitude-song-index="0"></span>
            <span class="song-artist-album-delimiter">·</span>
            <span data-amplitude-song-info="album" data-amplitude-song-index="0"></span>
          </div>
        </div>
        <div class="list-controls">
          <div class="list-previous amplitude-prev"></div>
          <div class="list-play-pause amplitude-play-pause"></div>
          <div class="list-next amplitude-next"></div>
        </div>
      </div>

    </div>
  </div>

  <div id="player-screen" class="flat-player">

    <div class="player-header down-header">
      <img id="down" src="/assets/themes/j1/modules/amplitudejs/icons/down.svg"/>
      Show Playlist
    </div>

    <div id="player-top">
      <img data-amplitude-song-info="cover_art_url"/>
    </div>

    <div id="player-progress-bar-container">
      <progress id="flat-player-progress" class="amplitude-song-played-progress"></progress>
    </div>

    <div id="player-bottom">
      <div id="control-container" class="flat-control-container">
        <div id="shuffle-container">
          <div class="amplitude-shuffle amplitude-shuffle-off" id="shuffle"></div>
        </div>
        <div id="prev-container">
          <div class="amplitude-prev" id="previous"></div>
        </div>
        <div id="play-pause-container">
          <div class="amplitude-play-pause" id="play-pause"></div>
        </div>
        <div id="next-container">
          <div class="amplitude-next" id="next"></div>
        </div>
        <div id="repeat-container">
          <div class="amplitude-repeat" id="repeat"></div>
        </div>
      </div>

      <div id="volume-container" class="flat-player-volume-container">
        <img src="/assets/themes/j1/modules/amplitudejs/icons/volume.svg">
        <input type="range" class="single-song-player amplitude-volume-slider" step=".1">
      </div>

      <!-- div id="volume-container" class="flat-player-volume-container">
        <img src="/assets/themes/j1/modules/amplitudejs/icons/volume.svg"/>
        <input type="range" class="flat-player amplitude-volume-slider" step=".1"/>
      </div -->
    </div>

    <div id="player-middle">
      <div id="time-container">
        <span class="amplitude-current-time time-container"></span>
        <span class="amplitude-duration-time time-container"></span>
      </div>
      <div id="meta-container">
        <span data-amplitude-song-info="name" class="song-name" style="margin-bottom: 5px"></span>
        <!-- div class="song-artist-album" -->
        <div class="audio-artist-album">
          <span data-amplitude-song-info="artist"></span>
          <span data-amplitude-song-info="album"></span>
        </div>
      </div>
    </div>

  </div>

</div>
++++


[role="mt-5"]
== Expanded Player
// See: https://521dimensions.com/open-source/amplitudejs/docs
// See: https://github.com/mediaelement/mediaelement-plugins
// See: https://github.com/serversideup/amplitudejs/

Amplitude is a JavaScript library to control the design of audio media
elements on web pages. The concept allows designers to fully control the
look and feel of audio players without deep scripting knowledge.

[NOTE]
====
Amplitude players are mobile-friendly. Touch events will be applied for
mobile devices instead of clicking on the appropriate elements.
====

The J1 Template implements a custom player based on the (default) theme Uno.
The color scheme used matches the look and feel of the template.

.Amy Winehouse · Back To Black
amplitude::back_to_black[role="mt-3 mb-5"]


[role="mt-5"]
== Player configuration

lorem:sentences[5]

[role="mt-4"]
=== Macro `amplitude::`

lorem:sentences[7]

[role="mt-4"]
=== Module settings

[role="mb-7"]
lorem:sentences[7]


++++
<style>

/* Flat Player
 =============================================================================== */

/* 1. Base
------------------------------------------------------------------------------- */

/* 2. Components
------------------------------------------------------------------------------- */

.flat-player-volume-container {
  display: flex;
  margin-left: -5px;
  padding-bottom: 19px;
  padding-top: 10px;
}

.flat-player-volume-slider {
  width: calc(100% - 75px);
  float: left;
  margin-top: 16px;
  margin-left: -6px;
  background: transparent;
}

input[type=range].flat-player-volume-slider {
    -webkit-appearance: none;
}

div#list-screen {
  background-color: #141920;
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
  bottom: 0;
  z-index: 9999;
  display: none;
}

div#list-screen div#list-screen-header {
  background-color: #141920;
  padding: 15px;
  text-align: center;
  position: relative;
  color: white;
  font-family: "Lato", sans-serif;
  cursor: pointer;
}

div#list-screen div#list-screen-header img#up-arrow {
  position: absolute;
  top: 23px;
  left: 15px;
  cursor: pointer;
}

div#list-screen div#list-screen-header span.list-active-song-name {
  color: #fff;
  line-height: 25px;
  font-size: 16px;
  font-family: "Lato", sans-serif;
  letter-spacing: 0.5px;
}

div#list-screen div#list {
  overflow-y: scroll;
}

div#list-screen div#list div.song {
  padding: 15px;
  background-color: #242b33 !important;
  margin-bottom: 1px;
  cursor: pointer;
  line-height: 24px;
}

div#list-screen div#list div.song span.song-number-now-playing {
  display: inline-block;
  width: 24px;
  text-align: center;
}

div#list-screen div#list div.song span.song-number-now-playing span.number {
  opacity: 0.5;
  font-family: "Lato", sans-serif;
  font-size: 14px;
  color: #fff;
  letter-spacing: 0.5px;
}

div#list-screen div#list div.song span.song-number-now-playing img.now-playing {
  display: none;
}

div#list-screen div#list div.song.amplitude-active-song-container {
  background-color: #30363e !important;
}

div#list-screen div#list div.song.amplitude-active-song-container span.song-number-now-playing img.now-playing {
  display: inline-block;
}

div#list-screen div#list div.song.amplitude-active-song-container span.song-number-now-playing span.number {
  display: none;
}

div#list-screen div#list div.song div.song-meta-container {
  display: inline-block;
  margin-left: 8px;
  vertical-align: middle;
  width: calc(100% - 80px);
}

div#list-screen div#list div.song div.song-meta-container span.song-name {
  font-family: "Lato", sans-serif;
  font-size: 20px;
  line-height: 20px;
  color: var(--ajs-theme-uno--blue);
  letter-spacing: 0.47px;
  display: block;
}

div#list-screen div#list div.song div.song-meta-container span.song-artist-album {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  line-height: 28px;
  color: #fff;
  letter-spacing: 0.47px;
  display: block;
}

div#list-screen div#list div.song span.song-duration {
  display: inline-block;
  opacity: 0.5;
  font-family: "Lato", sans-serif;
  font-size: 18px;
  color: #fff;
  letter-spacing: 0.5px;
  width: 35px;
  text-align: center;
}

div#list-screen div#list div.song span.song-artist-album {
  color: #5277b0;
}

div#list-screen div#list-screen-footer {
  height: 80px;
  padding: 15px;
  background-color: var(--ajs-theme-uno--black);
}

div#list-screen div#list-screen-footer div#list-screen-meta-container {
  width: calc(100% - 123px);
  float: left;
}

div#list-screen div#list-screen-footer div#list-screen-meta-container span.song-name {
  font-family: "Lato", sans-serif;
  font-size: 22px;
  color: #fff;
  letter-spacing: 0.5px;
  line-height: 24px;
  margin-left: 38px;
}

div#list-screen div#list-screen-footer div#list-screen-meta-container div.song-artist-album {
  opacity: 0.5;
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #fff;
  letter-spacing: 0.5px;
  line-height: 16px;
  margin-left: 38px;
}

div#list-screen div#list-screen-footer div.list-controls {
  width: 90px;
  float: right;
  margin-top: 8px;
}

div#list-screen div#list-screen-footer div.list-controls div.list-previous {
  cursor: pointer;
  width: 15px;
  height: 17px;
  /* background-image: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/small-previous.svg"); */
  background-image:  url("/assets/themes/j1/modules/amplitudejs/icons/small/previous.svg");
  background-repeat: no-repeat;
  float: left;
  margin-right: 15px;
  margin-top: 4px;
}

div#list-screen div#list-screen-footer div.list-controls div.list-play-pause {
  cursor: pointer;
  width: 17px;
  height: 24px;
  background-repeat: no-repeat;
  float: left;
}

div#list-screen div#list-screen-footer div.list-controls div.list-play-pause.amplitude-playing {
  /* background-image: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/small-pause.svg"); */
  background-image:  url("/assets/themes/j1/modules/amplitudejs/icons/small/pause.svg");
}

div#list-screen div#list-screen-footer div.list-controls div.list-play-pause.amplitude-paused {
  /* background-image: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/small-play.svg"); */
  background-image:  url("/assets/themes/j1/modules/amplitudejs/icons/small/play.svg");
}

div#list-screen div#list-screen-footer div.list-controls div.list-next {
  cursor: pointer;
  width: 15px;
  height: 17px;
  /* background-image: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/small-next.svg"); */
  background-image:  url("/assets/themes/j1/modules/amplitudejs/icons/small/next.svg");
  background-repeat: no-repeat;
  float: left;
  margin-left: 15px;
  margin-top: 4px;
}

div.player-header {
  background-color: #141920;
  padding: 15px;
  text-align: center;
  /* height: 25px; */
  position: relative;
  /* margin-top: 40px; */
  cursor: pointer;
  color: white;
  font-family: "Lato", sans-serif;
}

div.player-header img#down {
  position: absolute;
  top: 23px;
  left: 15px;
  cursor: pointer;
}

div#player-top {
  position: relative;
}

div#player-top img[data-amplitude-song-info="cover_art_url"] {
  width: 100%;
  /* height: 370px; */
}

div#player-progress-bar-container {
  width: 100%;
  height: 6px;
  background-color: #000;
  position: relative;
  margin-top: -6px;
}

/*
div#player-progress-bar-container progress#song-played-progress {
  width: 100%;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  height: 4px;
  display: block;
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
  bottom: 0;
  z-index: 9;
  border: none;
  cursor: pointer;
  background: transparent;
}

div#player-progress-bar-container progress#song-played-progress[value]::-webkit-progress-bar {
  background: none;
}

div#player-progress-bar-container progress#song-played-progress[value]::-webkit-progress-value {
  background: white;
}

div#player-progress-bar-container progress#song-played-progress[value]::-moz-progress-bar {
  background: white;
}

div#player-progress-bar-container progress#song-buffered-progress {
  width: 100%;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  height: 4px;
  display: block;
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
  bottom: 0;
  z-index: 2;
  border: none;
  background: transparent;
}

div#player-progress-bar-container progress#song-buffered-progress[value]::-webkit-progress-bar {
  background: none;
}

div#player-progress-bar-container progress#song-buffered-progress[value]::-webkit-progress-value {
  background-color: rgba(255, 255, 255, 0.5);
  transition: width 0.1s ease;
}

div#player-progress-bar-container progress#song-buffered-progress[value]::-moz-progress-bar {
  background: rgba(255, 255, 255, 0.5);
}
*/

div#player-middle {
  background-color: #000;
  padding-left: 15px;
  padding-right: 15px;
  padding-top: 20px;
  padding-bottom: 40px;
  text-align: center;
  position: relative;
}

div#player-middle div#time-container {
  color: white;
  width: 100%;
  background-color: #000;
  font-size: 14px;
  font-weight: bold;
}

div#player-middle div#time-container span.amplitude-duration-time {
  position: absolute;
  top: 0px;
  right: 5px;
}

div#player-middle div#time-container span.amplitude-current-time {
  position: absolute;
  top: 0px;
  left: 5px;
}

div#player-middle span.song-name {
  font-family: "Lato", sans-serif;
  font-size: 24px;
  color: #fff;
  letter-spacing: 0.5px;
  line-height: 24px;
  display: block;
}

div#player-middle div.song-artist-album {
  opacity: 0.5;
  font-family: "Lato", sans-serif;
  font-size: 18px;
  color: #fff;
  letter-spacing: 0.5px;
  line-height: 18px;
  margin-top: 5px;
}

div#player-bottom {
  background-color: var(--ajs-theme-uno--blue-gray-900);
  padding-left: 25px;
  padding-right: 25px;
}

.flat-player {
  max-width: 475px;
}

.flat-control-container {
  margin-top: 0px !important;
}

div#player-bottom div#control-container {
  height: 60px;
  padding-top: 18px;
  padding-bottom: 40px;
}

div#player-bottom div#control-container div#shuffle-container {
  float: left;
  width: 20%;
  height: 60px;
  padding-top: 21px;
}

div#player-bottom div#control-container div#shuffle-container div#shuffle {
  width: 16px;
  height: 17px;
  cursor: pointer;
  margin: auto;
  opacity: 0.7;
}

div#player-bottom div#control-container div#shuffle-container div#shuffle.amplitude-shuffle-off {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/shuffle.svg");
}

div#player-bottom div#control-container div#shuffle-container div#shuffle.amplitude-shuffle-off:hover {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/shuffle-on.svg");
  opacity: 0.8;
}

div#player-bottom div#control-container div#shuffle-container div#shuffle.amplitude-shuffle-on {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/shuffle-on.svg");
  opacity: 1;
}

div#player-bottom div#control-container div#shuffle-container div#shuffle.amplitude-shuffle-on:hover {
  opacity: 1;
}

div#player-bottom div#control-container div#prev-container {
  width: 20%;
  float: left;
  height: 60px;
  padding-top: 18px;
}

div#player-bottom div#control-container div#prev-container div#previous {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/previous.svg");
  width: 24px;
  height: 24px;
  cursor: pointer;
  margin: auto;
}

div#player-bottom div#control-container div#prev-container div#previous:hover {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/previous-hover.svg");
}

div#player-bottom div#control-container div#play-pause-container {
  width: 20%;
  float: left;
  height: 60px;
}

div#player-bottom div#control-container div#play-pause-container div#play-pause {
  width: 60px;
  height: 60px;
  cursor: pointer;
  margin: auto;
}

div#player-bottom div#control-container div#play-pause-container div#play-pause.amplitude-playing {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/pause.svg");
}

div#player-bottom div#control-container div#play-pause-container div#play-pause.amplitude-paused {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/play.svg");
}

div#player-bottom div#control-container div#next-container {
  width: 20%;
  float: left;
  height: 60px;
  padding-top: 18px;
}

div#player-bottom div#control-container div#next-container div#next {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/next.svg");
  width: 24px;
  height: 24px;
  cursor: pointer;
  margin: auto;
}

div#player-bottom div#control-container div#next-container div#next:hover {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/next-hover.svg");
}

div#player-bottom div#control-container div#repeat-container {
  float: left;
  width: 20%;
  height: 60px;
  padding-top: 20px;
}

div#player-bottom div#control-container div#repeat-container div#repeat {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/repeat.svg");
  width: 18px;
  height: 20px;
  cursor: pointer;
  margin: auto;
  opacity: 0.7;
}

div#player-bottom div#control-container div#repeat-container div#repeat:hover {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/repeat-on.svg");
  opacity: 0.8;
}

div#player-bottom div#control-container div#repeat-container div#repeat.amplitude-repeat-on {
  background: url("https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/repeat-on.svg");
  opacity: 1;
}

div#player-bottom div#control-container div#repeat-container div#repeat.amplitude-repeat-on:hover {
  opacity: 1;
}

div#player-bottom div#control-container::after {
  content: "";
  display: table;
  clear: both;
}

/* div#player-bottom div#volume-container {
  padding-bottom: 26px;
  text-align: center;
} */

div#player-bottom div#volume-container img {
  display: block;
  float: left;
  /* margin-top: 15px; */
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player {
  width: calc(100% - 70px);
  -webkit-appearance: none;
  display: block;
  margin-left: 0px;
  margin-top: 24px;
  float: left;
}

input[type=range].amplitude-volume-slider.flat-player {
    -webkit-appearance: none;
    width: calc(100% - 33px);
    float: left;
    margin-top: 24px;
    margin-left: 5px;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player:focus {
  outline: none;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player::-webkit-slider-runnable-track {
  width: 75%;
  height: 2px;
  cursor: pointer;
  animate: 0.2s;
  background: #cfd8dc;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player::-webkit-slider-thumb {
  height: 18px;
  width: 18px;
  background-color: white;
  cursor: pointer;
  margin-top: -8px;
  -webkit-appearance: none;
  border-radius: 20px;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player:focus::-webkit-slider-runnable-track {
  background: #cfd8dc;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player::-moz-range-track {
  width: 100%;
  height: 1px;
  cursor: pointer;
  animate: 0.2s;
  background: #cfd8dc;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player::-moz-range-thumb {
  height: 18px;
  width: 18px;
  background-color: white;
  cursor: pointer;
  margin-top: -8px;
  -webkit-appearance: none;
  border-radius: 20px;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player::-ms-track {
  width: 100%;
  height: 2px;
  cursor: pointer;
  animate: 0.2s;
  background: #cfd8dc;
  border-width: 15px 0;
  color: transparent;
  border-color: #192029;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player::-ms-fill-lower {
  background: transparent;
  border-radius: 2.6px;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player::-ms-fill-upper {
  background: transparent;
  border-radius: 2.6px;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player::-ms-thumb {
  height: 18px;
  width: 18px;
  background-color: white;
  cursor: pointer;
  margin-top: 0px;
  border: 20px;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player:focus::-ms-fill-lower {
  background: #cfd8dc;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player::-ms-fill-upper {
  background: #cfd8dc;
}

div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player::-ms-tooltip {
  display: none;
}

div#player-bottom div#volume-container:after {
  content: "";
  display: table;
  clear: both;
}

@-moz-document url-prefix() {
  div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player {
    margin-top: 0px;
  }
}

@supports (-ms-ime-align: auto) {
  div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player {
    margin-top: -4px;
    height: 30px;
    background-color: #192029 !important;
  }
}

@media all and (-ms-high-contrast: none) {

  div#player-bottom div#volume-container *::-ms-backdrop,
  div#flat-black-player-container div#player-bottom div#volume-container input[type="range"].amplitude-volume-slider.flat-player {
    margin-top: -8px;
    background-color: #192029 !important;
    background: #192029 !important;
  }
}

/* 3. Layout
------------------------------------------------------------------------------- */
div#flat-black-player-container {
  position: relative;
  /*
  max-width: 400px;
  margin: auto;
  */
}

/* 4. Pages
 ------------------------------------------------------------------------------- */

/* 5. Themes
 ------------------------------------------------------------------------------- */

/* 6. Utils
 ------------------------------------------------------------------------------- */

/* 7. Vendors
 ------------------------------------------------------------------------------- */


/* 8. Animations
 ------------------------------------------------------------------------------- */
.slide-in-top {
  -webkit-animation: slide-in-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-in-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-3-25 18:39:54
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation slide-in-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-10px);
    transform: translateY(-10px);
    opacity: 0;
  }

  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}

@keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-10px);
    transform: translateY(-10px);
    opacity: 0;
  }

  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}

.slide-out-top {
  -webkit-animation: slide-out-top 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
  animation: slide-out-top 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-3-25 18:45:17
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation slide-out-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-out-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }

  100% {
    -webkit-transform: translateY(-10px);
    transform: translateY(-10px);
    opacity: 0;
  }
}

@keyframes slide-out-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }

  100% {
    -webkit-transform: translateY(-10px);
    transform: translateY(-10px);
    opacity: 0;
  }
}

</style>
++++
