---
title:                                  Amplitude
title_extention:                        Custom Audio Players
tagline:                                Custom Audio Players

date:                                   2024-04-17
#last_modified:                         2024-01-01

description: >
                                        Amplitude is a JavaScript library to control the design of audio media
                                        elements on web pages. The concept allows designers to fully control the
                                        look and feel of audio players without deep scripting knowledge.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap, html, html5, audio,
                                        Amplitude

categories:                             [ Testpage ]
tags:                                   [ Audio. Amplitude ]

image:
  path:                                 /assets/image/icons/videojs/videojs-poster.png
  width:                                1920
  height:                               1280

regenerate:                             false
personalization:                        true
permalink:                              /pages/public/amplitude_tester/

resources:                              [ amplitude-js ]
resource_options:
  - toccer:
      collapseDepth:                    2
  - attic:
      slides:
        - url:                          /assets/image/modules/attics/1920x1280/alexey-ruban.jpg
          alt:                          Photo by Alexey Ruban on Unsplash
          badge:
            type:                       unsplash
            author:                     Alexey Ruban
            href:                       //unsplash.com/de/@intelligenciya
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Amplitude allows designers to fully control their audio players' look and
feel without understanding advanced scripting.

The audio tag `<audio>` in HTML5 is a great way to add audio to web pages.
However, the browser controls the audio playback interface, which can be very
limiting. Amplitude steps in and enables designers for the power to create
interfaces using themes to define the look and feel of the audio control
elements individually.


// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Amplitude Player
// See: https://521dimensions.com/open-source/amplitudejs/docs
// See: https://github.com/mediaelement/mediaelement-plugins
// See: https://github.com/serversideup/amplitudejs/

Amplitude is a JavaScript library to control the design of audio media
elements on web pages. The concept allows designers to fully control the
look and feel of audio players without deep scripting knowledge.

[NOTE]
====
Amplitude is mobile-friendly. For mobile devices, it will apply a touch
start event listener instead of a click to the appropriate elements.
====

++++
<!-- Title -->
<div class="audioblock mt-5 mb-1">
  <div class="title">Example Player (Theme Uno)</div>
  <!-- Player Container -->
  <div id="audio-player-container" class="mb-7">

    <!-- Amplitude Player -->
    <div id="amplitude-player">
      <!-- Left Side Player -->
      <div id="amplitude-left">
        <img data-amplitude-song-info="cover_art_url" class="album-art"/>
        <div class="amplitude-visualization" id="large-visualization">
        </div>
        <div id="player-left-bottom">
          <div id="time-container">
            <span class="current-time">
            <span class="amplitude-current-minutes" ></span>:<span class="amplitude-current-seconds"></span>
            </span>
            <div id="progress-container">
              <div class="amplitude-wave-form">
              </div>
              <input type="range" class="amplitude-song-slider"/>
              <progress id="song-played-progress" class="amplitude-song-played-progress"></progress>
              <progress id="song-buffered-progress" class="amplitude-buffered-progress" value="0"></progress>
            </div>
            <span class="duration">
            <span class="amplitude-duration-minutes"></span>:<span class="amplitude-duration-seconds"></span>
            </span>
          </div>
          <div id="control-container">
            <div id="repeat-container">
              <div class="amplitude-repeat" id="repeat"></div>
              <div class="amplitude-shuffle amplitude-shuffle-off" id="shuffle"></div>
            </div>
            <div id="central-control-container">
              <div id="central-controls">
                <div class="amplitude-prev" id="previous"></div>
                <div class="amplitude-play-pause" id="play-pause"></div>
                <div class="amplitude-next" id="next"></div>
              </div>
            </div>
            <div id="volume-container">
              <div class="volume-controls">
                <div class="amplitude-mute amplitude-not-muted"></div>
                <input type="range" class="amplitude-volume-slider"/>
                <div class="ms-range-fix"></div>
              </div>
              <div class="amplitude-shuffle amplitude-shuffle-off" id="shuffle-right"></div>
            </div>
          </div>
          <div id="meta-container">
            <span data-amplitude-song-info="name" class="song-name"></span>
            <div class="song-artist-album">
              <span data-amplitude-song-info="artist"></span>
              <span data-amplitude-song-info="album"></span>
            </div>
          </div>
        </div>
      </div>
      <!-- End Left Side Player -->

      <!-- Right Side Player -->
      <div id="amplitude-right">
        <div class="song amplitude-song-container amplitude-play-pause" data-amplitude-song-index="0">
          <div class="song-now-playing-icon-container">
            <div class="play-button-container">
            </div>
            <img class="now-playing" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/now-playing.svg"/>
          </div>
          <div class="song-meta-data">
            <span class="song-title">Rehab</span>
            <span class="song-artist">Amy Winehouse</span>
          </div>
          <a href="#" class="bandcamp-link" target="_blank">
          <img class="bandcamp-grey" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/bandcamp-grey.svg"/>
          <img class="bandcamp-white" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/bandcamp-white.svg"/>
          </a>
          <span class="song-duration">3:34</span>
        </div>
        <div class="song amplitude-song-container amplitude-play-pause" data-amplitude-song-index="1">
          <div class="song-now-playing-icon-container">
            <div class="play-button-container">
            </div>
            <img class="now-playing" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/now-playing.svg"/>
          </div>
          <div class="song-meta-data">
            <span class="song-title">You Know I'm No Good</span>
            <span class="song-artist">Amy Winehouse</span>
          </div>
          <a href="#" class="bandcamp-link" target="_blank">
          <img class="bandcamp-grey" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/bandcamp-grey.svg"/>
          <img class="bandcamp-white" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/bandcamp-white.svg"/>
          </a>
          <span class="song-duration">4:17</span>
        </div>
        <div class="song amplitude-song-container amplitude-play-pause" data-amplitude-song-index="2">
          <div class="song-now-playing-icon-container">
            <div class="play-button-container">
            </div>
            <img class="now-playing" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/now-playing.svg"/>
          </div>
          <div class="song-meta-data">
            <span class="song-title">Me & Mr Jones</span>
            <span class="song-artist">Amy Winehouse</span>
          </div>
          <a href="#" class="bandcamp-link" target="_blank">
          <img class="bandcamp-grey" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/bandcamp-grey.svg"/>
          <img class="bandcamp-white" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/bandcamp-white.svg"/>
          </a>
          <span class="song-duration">2:33</span>
        </div>
        <div class="song amplitude-song-container amplitude-play-pause" data-amplitude-song-index="3">
          <div class="song-now-playing-icon-container">
            <div class="play-button-container">
            </div>
            <img class="now-playing" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/now-playing.svg"/>
          </div>
          <div class="song-meta-data">
            <span class="song-title">Just Friends</span>
            <span class="song-artist">Amy Winehouse</span>
          </div>
          <a href="#" class="bandcamp-link" target="_blank">
          <img class="bandcamp-grey" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/bandcamp-grey.svg"/>
          <img class="bandcamp-white" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/bandcamp-white.svg"/>
          </a>
          <span class="song-duration">3:30</span>
        </div>
        <div class="song amplitude-song-container amplitude-play-pause" data-amplitude-song-index="4">
          <div class="song-now-playing-icon-container">
            <div class="play-button-container">
            </div>
            <img class="now-playing" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/now-playing.svg"/>
          </div>
          <div class="song-meta-data">
            <span class="song-title">Back To Black</span>
            <span class="song-artist">Amy Winehouse</span>
          </div>
          <a href="#" class="bandcamp-link" target="_blank">
          <img class="bandcamp-grey" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/bandcamp-grey.svg"/>
          <img class="bandcamp-white" src="https://521dimensions.com/img/open-source/amplitudejs/blue-player/bandcamp-white.svg"/>
          </a>
          <span class="song-duration">4:01</span>
        </div>
      </div>
      <!-- End Right Side Player -->
    </div>
    <!-- End Amplitdue Player -->
  </div>
</div>
++++

++++
<script>
  // module initializer
  // ---------------------------------------------------------------------------
  var dependencies_met_page_ready = setInterval (function (options) {
  var pageState      = $('#no_flicker').css("display");
  var pageVisible    = (pageState == 'block') ? true : false;
  var j1CoreFinished = (j1.getState() === 'finished') ? true : false;

  if (j1CoreFinished && pageVisible) {
  	// when the bandcamp link is pressed, stop all propagation so
    // AmplitudeJS doesn't play the song.
    var bandcampLinks = document.getElementsByClassName('bandcamp-link');

    for (var i = 0; i < bandcampLinks.length; i++) {
    	bandcampLinks[i].addEventListener('click', function (event) {
    		event.stopPropagation();
    	});
    }

    // highlight selected song items (player|right)
    // -------------------------------------------------------------------------
    var songElements = document.getElementsByClassName('song');
    for (var i = 0; i < songElements.length; i++) {
    	// ensure that on mouseover, CSS styles don't get messed up for active songs.
    	songElements[i].addEventListener('mouseover', function() {
    		this.style.backgroundColor = '#00A0FF';
    		this.querySelectorAll('.song-meta-data .song-title')[0].style.color = '#FFFFFF';
    		this.querySelectorAll('.song-meta-data .song-artist')[0].style.color = '#FFFFFF';

    		if( !this.classList.contains('amplitude-active-song-container') ){
    			this.querySelectorAll('.play-button-container')[0].style.display = 'block';
    		}

    		this.querySelectorAll('img.bandcamp-grey')[0].style.display = 'none';
    		this.querySelectorAll('img.bandcamp-white')[0].style.display = 'block';
    		this.querySelectorAll('.song-duration')[0].style.color = '#FFFFFF';
    	});

  		// ensure that on mouseout, CSS styles don't get messed up for active songs.
    	songElements[i].addEventListener('mouseout', function() {
    		this.style.backgroundColor = '#FFFFFF';
    		this.querySelectorAll('.song-meta-data .song-title')[0].style.color = '#272726';
    		this.querySelectorAll('.song-meta-data .song-artist')[0].style.color = '#607D8B';
    		this.querySelectorAll('.play-button-container')[0].style.display = 'none';
    		this.querySelectorAll('img.bandcamp-grey')[0].style.display = 'block';
    		this.querySelectorAll('img.bandcamp-white')[0].style.display = 'none';
    		this.querySelectorAll('.song-duration')[0].style.color = '#607D8B';
    	});

  		// dhow and hide the play button container on the song when the song is clicked.
    	songElements[i].addEventListener('click', function () {
    		this.querySelectorAll('.play-button-container')[0].style.display = 'none';
    	});
    }


  	// initializes Amplitude
    // -------------------------------------------------------------------------
    Amplitude.init({
    	songs: [
    		{
    			"name": "Rehab",
    			"artist": "Amy Winehouse",
    			"album": "Back To Black",
    			"url": "/assets/audio/album/Back To Black/01. Rehab.mp3",
    			"cover_art_url": "/assets/audio/cover/Back_To_Black.jpg"
    		},
    		{
          "name": "You Know I'm No Good",
    			"artist": "Amy Winehouse",
    			"album": "Back To Black",
    			"url": "/assets/audio/album/Back To Black/02. You Know I'm No Good.mp3",
    			"cover_art_url": "/assets/audio/cover/Back_To_Black.jpg"
    		},
    		{
          "name": "Me & Mr Jone",
    			"artist": "Amy Winehouse",
    			"album": "Back To Black",
    			"url": "/assets/audio/album/Back To Black/03. Me & Mr Jones.mp3",
    			"cover_art_url": "/assets/audio/cover/Back_To_Black.jpg"
    		},
    		{
          "name": "Just Friends",
    			"artist": "Amy Winehouse",
    			"album": "Back To Black",
    			"url": "/assets/audio/album/Back To Black/04. Just Friends.mp3",
    			"cover_art_url": "/assets/audio/cover/Back_To_Black.jpg"
    		},
    		{
          "name": "Back To Black",
    			"artist": "Amy Winehouse",
    			"album": "Back To Black",
    			"url": "/assets/audio/album/Back To Black/05. Back To Black.mp3",
    			"cover_art_url": "/assets/audio/cover/Back_To_Black.jpg"
    		}
    	],

      callbacks: {
        'play': function() {
            document.getElementById('album-art').style.visibility = 'hidden';
            document.getElementById('large-visualization').style.visibility = 'visible';
        },
        'pause': function() {
            document.getElementById('album-art').style.visibility = 'visible';
            document.getElementById('large-visualization').style.visibility = 'hidden';
        }
      },

      waveforms: {
        sample_rate: 50
      }
    });

    clearInterval(dependencies_met_page_ready);
  } // END id page ready
}, 10); // ENF dependencies_met_page_ready
</script>
++++
