---
title:                                  TikTok
tagline:                                video examples
date:                                   2021-04-17 00:00:00
description: >
                                        Welcome to the preview page focussing on the image module. This page
                                        shows some valuable features of the J1 Theme to manage your image-based
                                        content using lightboxes, carousels (slider), and galleries.

categories:                             [ TikTok ]
tags:                                   [ Video, Desktop ]

comments:                               true
fab_menu_id:                            open_toc

personalization:                        true

permalink:                              /pages/public/tiktok/
regenerate:                             false

resources:                              [
                                          animate,
                                          lightgallery, gallery, rouge,
                                          tictokplayer
                                        ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/franck-1920x1280.jpg
          alt:                          Photo by Franck on Unsplash
          badge:
            type:                       unsplash
            author:                     Franck
            href:                       https://unsplash.com/@franckinjapan
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

lorem:sentences[5]

[role="mt-5"]
== Embedded Videos (iFrame)

lorem:sentences[3]

++++
<!-- See: https://forum.obsidian.md/t/how-do-i-embed-tiktok-videos/13532/13 -->
<!-- div style="max-width: 56vh;"><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 177.7778%; padding-top: 120px;"><iframe src="https://www.tiktok.com/embed/6992668750692584710" allow="fullscreen" style="position: absolute; top: 0px; left: 0px; height: 100%; width: 100%;"></iframe></div -->
<iframe
  id="tiktokFrame"
  class="tiktok-embed lggg-tiktok"
  loading="lazy"
  scrolling="no"
  width="300"
  height="575"
  src="//tiktok.com/embed/6901614235709869314"
  frameborder="0"
  allowfullscreen="false">
</iframe>

<iframe
  loading="lazy"
  scrolling="no"
  width="300"
  height="575"
  src="//tiktok.com/embed/6938375143181913349"
  frameborder="0"
  allowfullscreen="false">
</iframe>

<iframe
  loading="lazy"
  scrolling="no"
  width="300"
  height="575"
  src="//tiktok.com/embed/6919457437510569218"
  frameborder="0"
  allowfullscreen="false">
</iframe>

<!-- script async src="https://www.tiktok.com/embed.js"></script -->
<!-- script>
$(function() {
  var dependencies_met_page_ready = setInterval (function (options) {
    var pageState   = $('#no_flicker').css("display");
    var pageVisible = (pageState == 'block') ? true : false;

    if (j1.getState() === 'finished' && pageVisible) {
      var tiktokFrame = document.getElementById('tiktokFrame');
      tiktokFrame.setAttribute('allow', 'autoplay; encrypted-media');
      tiktokFrame.setAttribute('autoplay', 'false');
      clearInterval(dependencies_met_page_ready);
    }
  }, 10);
});
</script -->

<style>

/*
$grid-breakpoint-xl:                              1200px;
$grid-breakpoint-lg:                              992px;
$grid-breakpoint-lg-min:                          991px;
$grid-breakpoint-md:                              768px;
$grid-breakpoint-md-min:                          767px;
$grid-breakpoint-sm:                              576px;
$grid-breakpoint-xs:                              575px;
*/

.lg-tiktok {
  padding-left: 200px;
}

/* Desktop */
@media screen and (min-width: 991px) {
  .lg-tiktok {
    padding-left: 300px;
  }
}


/* iPad */
@media screen and (max-width: 1024px) {
  .lg-tiktok {
    padding-left: 40px;
  }
}

/* Mobile */
@media screen and (max-width: 575px) {
  .lg-tiktok {
    padding-left: 20px;
  }
 }

</style>
++++

[role="mt-4"]
lorem:sentences[5]

[source, html, role="noclip"]
----
<iframe
  loading="lazy"
  scrolling="no"
  width="300"
  height="575"
  src="//tiktok.com/embed/6919457437510569218"
  frameborder="0"
  allowfullscreen="false">
</iframe>
----

[role="mt-5"]
== Video Gallery

lorem:sentences[5]

.TikToc Videos
gallery::jg_video_online_tiktoc[role="mb-4"]

[role="mb-7"]
lorem:sentences[5]
