---
title:                                  TubeNinja
title_extention:                        Download Widget
tagline:                                Download Widget

date:                                   2023-01-01
#last_modified:                         2023-01-01

description: >
                                        Welcome to the info pages of J1 Template. A good decision
                                        to get on that page first. Certainly, there is no better
                                        place to learn what J1 Template can do and what pages are
                                        available to experience more.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap

categories:                             [ Info ]
tags:                                   [ Introduction ]

image:
  path:                                 /assets/image/module/attic/1920x1280/brigitta-schneiter.jpg
  width:                                1920
  height:                               1280

comments:                               false
regenerate:                             false
permalink:                              /pages/public/learn/tubeninja/

resources:                              [ rouge ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/module/attic/1920x1280/brigitta-schneiter.jpg
          alt:                          Photo by Brigitta Schneiter on Unsplash
          badge:
            type:                       unsplash
            author:                     Brigitta Schneiter
            href:                       //unsplash.com/de/@brisch27
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>


//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Do you have your own blog where you embed videos for your readers? Want to
allow your readers to quickly and easily download those videos?
Install TubeNinja's simple script on your page to automatically add download
links to the video embeds.

mdi:clock-time-five-outline[24px, md-gray mr-2]
*3 Minutes* to read


// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
// See: https://www.tubeninja.net/welcome
// See: https://www.tubeninja.net/download-widget
== Download

Welcome to TubeNinja - The best online video downloader. TubeNinja is an
online video download helper that allows you to save streaming audio or video.
It works on your computer or smartphone without any hassle. You don’t have
to install and sketchy apps or plugins.

We support over 80 streaming sites and you can even paste links to pages that
we are not supported. Our system will most likely find the files that you want
anyway. (It’s that good)

Now that sounds good, doesn’t it?

// https://ge.xhamster.desi/videos/cute-18-year-old-tiny-tit-step-sister-fucked-pov-xhZ3mSu
// https://ge.xhamster.desi/videos/redhead-babe-with-tiny-tits-gets-cremy-xhjlUDe
// https://ge.xhamster.desi/videos/waking-up-to-step-sister-sucking-my-cock-xhriw4L
// https://ge.xhamster.desi/videos/i-let-my-classmate-fuck-my-pussy-xhIYI6u
// https://ge.xhamster.desi/videos/stepsister-jerks-off-stepbrothers-cock-and-lets-him-cum-on-her-xhLSsCh

++++
<!-- form id="urlForm" action="//www.tubeninja.net" method="get" class="" -->
<!-- form id="urlForm" action="/welcome" method="get" class="" -->
<form id="urlForm" action="//www.tubeninja.net/welcome" method="get" class="">
    <div class="input-group input-group-lg">
        <input type="text" class="form-control" autofocus="" name="url" id="urlfield" placeholder="Paste a link or write a search term" value="" aria-label="Paste a link or write a search term">
        <div class="input-group-append">
            <button class="btn btn-success" type="submit" id="addressSearch" aria-label="Download">
                <i class="fa fa-fw fa-download" aria-hidden="true"></i>
                <span class="hidden-xs inline">Download</span>
            </button>
        </div>
    </div>
</form>

<div id="result"></div>
++++

++++
<script>
  window.tubeninja = (function () {
      Element.prototype.appendAfter = function (element) {
          element.parentNode.insertBefore(this, element.nextSibling);
      };
      String.prototype.contains = function (it) {
          return this.indexOf(it) !== -1;
      };
      var tubeninja = {
          text: 'Download',
          title: 'Download with TubeNinja',
          target: '_blank',
          btnClass: 'btn-tubeninja',
          init: function () {
              var els = document.getElementsByTagName('iframe');
              for (var i = 0; i < els.length; i++) {
                  var iframe = els[i];
                  if (iframe.src.contains('youtube.com') || iframe.src.contains('vimeo.com')) {
                      var dlbtn = document.createElement('a');
                      dlbtn.className = tubeninja.btnClass;
                      dlbtn.style = 'display:block;width:60px;';
                      dlbtn.textContent = tubeninja.text;
                      dlbtn.title = tubeninja.title;
                      dlbtn.target = tubeninja.target;
                      dlbtn.href = 'https://tubeninja.net/?url=' + iframe.src + '&utm_source=widget&utm_medium=widget';
                      dlbtn.rel = 'nofollow';
                      dlbtn.appendAfter(iframe);
                  }
              }
          }
      };
      document.addEventListener("DOMContentLoaded", function (event) {
          tubeninja.init();
      });
      return tubeninja;
  }());


  // $('#video').removeClass('d-none');
  // $.post('/get', {
  //     url: 'https://ge.xhamster.desi/videos/cute-18-year-old-tiny-tit-step-sister-fucked-pov-xhZ3mSu',
  //     'csrfmiddlewaretoken': 'fZ1OmUNuJ5fSjWxjAaCZz9Y0uT8HaLjMHLjtSsbsgmRTjnUIkkr3qDIjWtXQWC9Q'
  // }, function (response) {
  //     setTimeout(function () {
  //         $('#video').removeClass('text-center').replaceWith(response);
  //     }, 100)
  // });
  // getVideo = function (el, url) {
  //     var $el = $(el);
  //     $el.addClass('fetching');
  //     $el.removeAttr("href").removeAttr("onclick");
  //     var $parent = $el.parents('.row.movie');
  //     $.post('/get', data = {
  //         url: url,
  //         username: window.username,
  //         password: window.password,
  //         'csrfmiddlewaretoken': 'fZ1OmUNuJ5fSjWxjAaCZz9Y0uT8HaLjMHLjtSsbsgmRTjnUIkkr3qDIjWtXQWC9Q'
  //     }, function (response) {
  //         var $html = $('<div>').html($($.parseHTML($.trim(response), document, true)));
  //         $parent.replaceWith($html.find('.row.movie'));
  //     })
  // }


  var dependencies_met_page_ready = setInterval (function (options) {
    var pageState           = $('#no_flicker').css("display");
    var pageVisible         = (pageState == 'block') ? true : false;

    if (j1.getState() === 'finished' && pageVisible) {

      $(document).on('click', 'a.ts, a.share', function (e) {
          e.preventDefault();
          window.open($(this).attr('href'), '', "width=550,height=350");
      });
      $('#urlfield').on('paste', function () {
          setTimeout(function () {
              $('#urlForm').submit();
          }, 100);
      });

      clearInterval(dependencies_met_page_ready);
    }
  }, 10);
</script>
++++

++++
<style>

/* html {
    position: relative;
    min-height: 100%;
}

body {
    margin-bottom: 180px;
}

a, a:hover {
    text-decoration: none;
}

a, .btn-link {
    color: #337ab7;
}

a:hover, a:focus, .btn-link:hover, .btn-link:focus {
    color: #23527c;
} */


.jumbotron {
    background-position: center;
    background-size: cover;
    background-color: #676767;
    color: white;
    text-shadow: 0px 0px 20px rgba(0, 0, 0, 1);
    padding-bottom: 2em;
    padding-top: 2em;
    margin-bottom: 10px;
}

.jumbotron .container {
    min-height: 230px;
}

.jumbotron .h1, .jumbotron .main, .jumbotron .h2, .jumbotron .h3, .jumbotron h1, .jumbotron h2, .permtext, .navbar-brand {
    font-family: 'Permanent Marker', cursive;
    display: block;
    line-height: 1em;
}

.jumbotron span.h1 {
    font-size: 63px;
}

.jumbotron .main {
    margin-top: 20px;
    font-size: 30px;
    margin-bottom: 10px;
}

.jumbotron .h2 {
    margin-top: 0;
    margin-bottom: 1.5em;
}

.jumbotron form {
    margin: auto;
    width: 60%;
}

@media screen and (max-width: 992px) {
    .jumbotron form {
        width: 100%;
    }
}

.jumbotron .help-block {
    margin: 0;
    text-align: left;
}

.jumbotron .help-block .btn-link {
    font-family: 'Permanent Marker', cursive;
    color: white;
    color: rgba(255, 255, 255, 0.8);
    text-shadow: 0 0 20px rgba(0, 0, 0, 1);
}

/* .footer {
    height: 180px;
    margin-top: 1em;
    border-top: 1px solid lightgrey;
    position: absolute;
    padding-top: 0.5em;
    bottom: 0;
    width: 100%;
    background-color: #f5f5f5;
} */


.toc + .share {
    padding-right: 1em;
}

div.share:before {
    content: attr(title);
    position: absolute;
    margin-top: -1.2em;
    font-weight: bold;
}

div.share {
    display: flex;
    margin-bottom: 1.5em;
}

.share a {
    color: white;
    padding: 0.4em;
    font-size: 1.5em;
    display: inline-flex;
    flex-grow: 1;
    text-align: center;
    min-height: 2em;
    text-decoration: none;
    opacity: 0.8;
}

.share a:hover {
    opacity: 1;
}

.share a .fab, .share a .fas {
    margin: auto;
}

.reddit, .reddit:hover {
    background-color: #FF4006 !important;
}

.email, .email:hover {
    background-color: #4CAF50 !important;
}

ul.share-buttons {
    list-style: none;
    padding: 0;
    z-index: 9;
    float: right;
}

ul.share-buttons li {
    display: inline-block;
    margin-bottom: 0.5em;
}

a.social {
    min-width: 35px;
    min-height: 34px;
    display: inline-block;
    color: white;
    font-size: 1.5em;
    padding: 2px 4px;
    margin-left: 2px;
    border-radius: 3px;
}

a.ts .fa {
    width: 1.48em;
    color: white;
}

a.ts:hover {
    box-shadow: inset 0 0 1px rgba(0, 0, 0, 0.8);
    color: #e7e7e7 !important;
}

.stumble, .stumble:hover {
    background-color: #EB4823 !important;
}

.pin, .pin:hover {
    background-color: #cb2027 !important;
}

a.fb, a.fb:hover {
    background-color: #3b5998 !important;
}

.twitter, .twitter:hover {
    background-color: #00aced !important;
}

.vk, .vk:hover {
    background-color: #45668e !important;
}

.ts.linkedin, .ts.linkedin:hover {
    background-color: #007bb6 !important;
}

.okru, .okru:hover {
    background-color: #DF8832 !important;
}

.mix, .mix:hover {
    background-color: #fd8235 !important;
}

h5 a, h5 a:hover {
    color: black;
    text-decoration: none;
}

.agelimit {
    min-height: 200px;
}

.agelimit *, .age-prompt {
    display: none;
}

.agelimit div.age-prompt, .agelimit div.age-prompt * {
    margin: auto;
    display: inline-block;
}

.agelimit div.age-prompt .checkbox {
    margin-top: 10px;
}

.agelimit div.age-prompt input {
    margin-top: 4px;
    margin-left: -20px;
}

.agelimit div.age-prompt {
    margin-top: 2em;
    display: block;
}

.movie {
    padding: 1em 0;
    border: 1px solid rgba(0, 0, 0, 0.1);
    border-radius: .25rem;
    position: relative;
    margin-bottom: 2em;
}

a.playlist .fa-spin, a.playlist .fetching, a.playlist.fetching .fetch, a.playlist.fetching .fa-arrow-right {
    display: none;
}

a.playlist.fetching .fa-spin, a.playlist.fetching .fetching {
    display: inline-block;
}

.thumbnail {
    padding-bottom: 1em;
    padding-top: 1em;
    background-color: rgba(0, 0, 0, 0.1);
}

.thumbnail {
    margin: auto;
}

a.ts {
    padding: 2px 7px 2px 4px !important;
    text-align: right;
    color: white !important;
    font-size: 12px;
    line-height: 20px;
    margin-right: 15px;
    display: block;
    text-decoration: none;
    border-radius: 1px;
    box-shadow: 1px 1px 1px rgba(0, 0, 0, 0.8);
}

a.ts .fab {
    width: 1.48em;
    color: white;
}

a.ts:hover {
    box-shadow: inset 0 0 1px rgba(0, 0, 0, 0.8);
    color: #e7e7e7 !important;
}

nav .rotatedtext {
    display: inline-block;
    vertical-align: bottom;
    font-family: 'Permanent Marker', cursive;
    font-size: 87%;
    transform: rotate(-19deg);
    color: rgba(255, 255, 255, 0.8);
    margin-right: 0.5em;
}

@media screen and (max-width: 992px) {
    .bookmarkletitem {
        display: none;
    }

    .sm-inline, .sm-inline li {
        display: inline-block;
    }
}

ul.toc {
    background-color: #F5F5F5;
    border: 1px dashed orangered;
    padding: 1em;
}

.banner-img {
    display: block;
    max-width: 53.25rem;
    width: 100%;
    height: auto;
    margin: 0 auto;
}

.vdplus-ad {
    display: flex;
    width: 100%;
    align-items: center;
    background: linear-gradient(45deg, #ff825b 0%, #f57186 100%);
    border-radius: .25rem;
    padding: .75rem 1rem;
    margin-bottom: 1rem;
}

.vdplus-ad__text {
    color: #ffffff;
    margin: 0 15px 0 0;
}

.vdplus-ad__button {
    display: flex;
    background-color: rgba(29, 29, 31, 1);
    padding: 6px 12px;
    border-radius: 6.25rem;
    color: #ffffff;
    text-align: center;
}

.vdplus-ad__button:hover {
    color: #ffffff;
}

</style>
++++

////
++++
<script src="https://www.tubeninja.net/widget.js">
++++


++++
<video controls="" autoplay="" name="media"><source src="https://ip254454611.ahcdn.com/key=d+Ge6KfilELXWsH2TNK14w,s=,end=1716746400,limit=3/data=2604:a880:800:10::8f4:7001-dvp/state=ZlNKXeXK/reftag=0324070418/ssd5/21/4/311613004/023/250/401/2160p.h264.mp4" type="video/mp4">
</video>


<video controls="" autoplay="" name="media"><source src="https://ip255736194.ahcdn.com/key=6f6mypc0ksIcib-xj1+S-Q,s=,end=1716746400,limit=3/data=2604:a880:800:10::ba6:1-dvp/state=ZlNKXeXK/reftag=0324070418/ssd5/21/6/311124526/023/235/237/2160p.h264.mp4" type="video/mp4">
</video>


<video controls="" autoplay="" name="media"><source src="https://ip179686385.ahcdn.com/key=CYgvLlphhdDOybOR0V55og,s=,end=1716746400,limit=3/data=2604:a880:800:10::ee3:1001-dvp/state=ZlNKXeXK/reftag=0324070418/ssd2/21/7/290239647/022/465/397/2160p.h264.mp4" type="video/mp4">
</video>


<video controls="" autoplay="" name="media"><source src="https://ip254455630.ahcdn.com/key=W3w+K+q9MZRaHM3Ulro1ng,s=,end=1716746400,limit=3/data=2604:a880:800:10::8f4:7001-dvp/state=ZlNMXeXK/reftag=0324070418/ssd1/21/2/249966942/019/492/200/2160p.h264.mp4" type="video/mp4">
</video>
++++
////
