---
title:                                  Jekyll Paginate V2
tagline:                                Example 2 - Category pagination
date:                                   2022-01-01
#last_modified:                         2023-01-01
description: >
                                        J1 Template is a Bootstrap V5 website template for the static
                                        site generator Jekyll.
                                        Usage of the pagination gem on categories of a site

categories:                             [ Manual, Plugin ]
tags:                                   [ Paginator, Examples ]

permalink:                              /pages/manuals/paginator_v2/url-github--jekyll-paginate_v2_example_2/
regenerate:                             false

resources:                              [ lightbox ]
resource_options:
  - toccer:
      collapseDepth:                    3
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

This example website contains information about sports cars and has a
single main paginated front page that lists all entries in the system.
It also contains separate paginated category pages that list only subset
of cars on the site.

The site is generated using the jekyll built in new command
`jekyll new myblog` and it uses the
https://github.com/jekyll/minima[default `minima` theme].

After generating the pagination gem was installed using

----
  gem install jekyll-paginate-v2
----

== Structure

The blog has two types of posts that can be found under `&#x5F;posts/` and
the `cars/&#x5F;posts` folder.

NOTE: The `cars/&#x5F;posts` folder structure is handy as it automatically
assigns the category `cars` to all posts under it.

Users can then assign other categories to their posts by editing each
post's front-matter as they see fit.

This site uses the same `&#x5F;layouts/home.html` and `&#x5F;includes/header.html`
overrides as Example 01 does (please refer to that example project for
details).

The project also has additional pagination pages that only list subsets
of the car list `toyota/index.md`, `categories/porsche.md`,
`categories/byname.md`.

It is not advisable to have multiple pagination pages stored directly under the
main site root. It makes it easy to mis-configure resulting in overwritten
pagination pages unless developers remember to specify a unique
`pagination: permalink: ''` override for each pagination page.

=== Toyota/index.md

Simple category pagination page that only paginates cars having the category
`sports` assigned to them. The configuration is simple being only

[source, yaml]
----
  ---
  layout: home
  title: Toyota
  pagination:
    enabled: true
    category: sports
  ---
----

This configuration draws the paging permalink structure from the `&#x5F;config.yml`
file. Therefore the generated paging urls will be based on the folder name of
the pagination page with the site configuration permalink added to it, like so:

----
  Page 1: http://localhost:4000/toyota/
  Page 2: http://localhost:4000/toyota/page/2/
  Page N: http://localhost:4000/toyota/page/N/
----

=== Categories/porsche.md

This is a more complex category pagination including a permalink
override for both the main page url and the pagination pages. The
configuration for the page looks like this

[source, yaml]
----
  ---
  layout: home
  title: Only Porsche
  permalink: /porsches/
  pagination:
    enabled: true
    category: porsche
    permalink: /:num/
  ---
----

The paging will only list posts in the category `porsche`. The main
difference here is that the url structure generated will look different
because of the combined page and category permalink config in the main
front-matter.

----
  Page 1: http://localhost:4000/porsches/
  Page 2: http://localhost:4000/porsches/2/
  Page N: http://localhost:4000/porsches/N/
----

=== Categories/byname.md

This pagination page expands on the the first two examples by adding a
custom sorting for the category pagination. It displays all cars but by
alphabetical order by Car name.

This configuration is achieved with the following front-matter
configuration

[source, yaml]
----
  ---
  layout: home
  title: By Name
  permalink: /name/
  pagination:
    enabled: true
    category: cars
    permalink: /:num/
    sort_field: 'title'
    sort_reverse: false
  ---
----

The paging url structure will look similar to the example before

----
  Page 1: http://localhost:4000/name/
  Page 2: http://localhost:4000/name/2/
  Page N: http://localhost:4000/name/N/
----

== Setup Configuration

The gem is added to the `&#x5F;config.yml` file under

[source, yaml]
----
  gems:
    - jekyll-paginate-v2
----

as well as to the `Gemfile` into the main loop

[source, ruby]
----
  group :jekyll_plugins do
    gem "jekyll-paginate-v2"
    gem "jekyll-feed"
  end
----

At this point is is advisable to delete the `Gemfile.lock` file to clear
out any potential issues with gem caching and dependency issues (no
worries this file will be auto generated for you again).

Try building the site yourself using `jekyll build` or `jekyll serve`.
