---
title:                                  Jekyll Paginate V2
tagline:                                Example 3 - Collection and Tag pagination
date:                                   2022-01-01
#last_modified:                         2023-01-01
description: >
                                        J1 Template is a Bootstrap V5 website template for the static
                                        site generator Jekyll.
                                        Usage of the pagination gem to paginate by single,
                                        multiple or all collections at the same time.

categories:                             [ Manual, Plugin ]
tags:                                   [ Paginator, Examples ]

permalink:                              /pages/manuals/paginator_v2/url-github--jekyll-paginate_v2_example_3/
regenerate:                             false

resources:                              [ lightbox ]
resource_options:
  - toccer:
      collapseDepth:                    3
---

/// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

This example bookshop website uses collections to organize its books. The
site relies on pagination of its books by both: collections *and* tags. The
web shows how to paginate by single, multiple or all collections at the *same*
time.

For the links, the web uses the *pretty* permalink structure. To going somewhatIt
furter, it also demonstrates *advanced sorting features* such as *nested* fields.

The site is generated using the jekyll built in new command `jekyll new myblog`
and it uses the default https://github.com/jekyll/minima[minima] theme provided
by the Jekyll gem.

After generating the pagination gem was installed using

----
  gem install jekyll-paginate-v2
----

It could be argued that the bookstore should have just used categories here
and collections were better suited to separate things into 'books', 'DVDs',
'Games' etc.

== Structure

The site has three types of document collections `&#x5F;biography/`,
`&#x5F;fantasy/` and `&#x5F;romance/`. In addition to that, the bookstore
also has a blog; those posts are stored under `blog/&#x5F;posts`.

All books have multiple tags assigned to them.

Permalinks are configured to the `pretty` format site-wide. The pagination
logic handles this configuration smart and constructs the correct sub url
structure automatically.

Pagination pages are:

* biography/biograpy.md
* biography/biograpy-musicians.md
* romance/romance-historical.md
* tags/contemporary.md
* tags/fantasy.md
* tags/sci-fi.md
* index.md
* byisbn.md

Most pages are self explanatory and most sort books by the nested
attribute `rank`.

=== Page: byisbn.md

Demonstrates how to have multiple pagination pages defined in the root
of the site without their pagination pages clashing. Uses permalinks to
achieve this.

=== Page: Under tags/

Demonstrate how to paginate across multiple collections by using the
`collections: all` front matter configuration

== Setup Configuration

The gem is added to the `&#x5F;config.yml` file under

[source, yaml]
----
  gems:
    - jekyll-paginate-v2
----

as well as to the `Gemfile` into the main loop

[source, ruby]
----
  group :jekyll_plugins do
    gem "jekyll-paginate-v2"
    gem "jekyll-feed"
  end
----

At this point is is advisable to delete the `Gemfile.lock` file to clear
out any potential issues with gem caching and dependency issues (no
worries this file will be auto generated for you again).

Try building the site yourself using `jekyll build` or `jekyll serve`.
