---
title:                                  Jekyll Paginate V2
tagline:                                Example 1 - A typical Blog
date:                                   2022-01-01
#last_modified:                         2023-01-01
description: >
                                        J1 Template is a Bootstrap V5 website template for the static
                                        site generator Jekyll.
                                        Usage of the pagination Ruby GEM on a simple blog site

categories:                             [ Manual, Plugin ]
tags:                                   [ Paginator, Examples ]

permalink:                              /pages/manuals/paginator_v2/url-github--jekyll-paginate_v2_example_1/
regenerate:                             false

resources:                              [ lightbox ]
resource_options:
  - toccer:
      collapseDepth:                    3
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

This example site shows how the pagination gem can be used on a simple
blog site. The site is generated using the jekyll built in new command
`jekyll new myblog` and it uses the https://github.com/jekyll/minima[default `minima` theme].

After generating the pagination gem was installed using

----
gem install jekyll-paginate-v2
----

== Structure

The blog has only one type of posts, blog posts. No category pagination
is performed. To implement the pagination for the minima theme the
`&#x5F;layouts/home.html` needed to be modified to call the pagination logic.

The `&#x5F;includes/header.html` was also overridden to omit listing the
auto-generated pagination sites at the top of the header part.


== Setup configuration

The gem is added to the `&#x5F;config.yml` file under

[source, yaml]
----
  gems:
    - jekyll-paginate-v2
----

as well as to the `Gemfile` into the main loop

[source, ruby]
----
  group :jekyll_plugins do
    gem "jekyll-paginate-v2"
    gem "jekyll-feed"
  end
----

At this point is is advisable to delete the `Gemfile.lock` file to clear
out any potential issues with gem caching and dependency issues (no
worries this file will be auto generated for you again).


== Configuring the pagination

Add the pagination configuration to `&#x5F;config.yml`

[source, yaml]
----
  # Pagination Settings
  pagination:
    enabled: true
    per_page: 3
    permalink: '/page/:num/'
    title_suffix: ' - page :num'
    limit: 0
    sort_field: 'date'
    sort_reverse: true
----

Due to the way the entries in the blog utilize multiple categories it is
also good to explicitly state the permalink format to avoid excessive
nesting of the post pages. So place the following line into the
`&#x5F;config.yml` file as well

[source, yaml]
----
  # Produces a cleaner folder structure when using categories
  permalink: /:year/:month/:title.html
----

== Completing the setup

Now the pagination simply needs to be enabled in the `index.html` file.

[source, yaml]
----
  ---
  layout: home
  pagination:
    enabled: true
  ---
----

That is it, no further configuration is needed!

Try building the site yourself using `jekyll build` or `jekyll serve`.

== Testing backwards compatability

In the `&#x5F;config.yml` file remove or comment out the new `pagination:`
configuration and paste/uncomment the following configuration instead.

[source, yaml]
----
  # Old jekyll-paginate pagination logic
  paginate: 3
  paginate_path: "/legacy/page:num/"
----

Now run `jekyll serve` again and the gem will generate the pagination
according to the old jekyll-paginate rules and behavior.

CAUTION: You must disable the new pagination configuration for the old one to
work. You cannot run both configurations at the same time.
