---
title:                                  Biography
tagline:                                Today's People in the Book Shelf
date:                                   2020-11-03 00:00:00 +100
description: >
                                        Today's People in the Book Shelf

categories:                             [ Collection, Template ]
tags:                                   [ Books ]

permalink:                              /pages/public/collections/bookshelf/biography/
regenerate:                             false

fab_menu_id:                            open_toc

resources:                              [ animate ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/giammarco-boscaro-1920x1280.jpg
          alt:                          Photo by Giammarco on Unsplash
          badge:
            type:                       unsplash
            author:                     Giammarco
            href:                       https://unsplash.com/@giamboscaro
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

{% comment %} Liquid procedures
-------------------------------------------------------------------------------- {% endcomment %}
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}
{% capture create_collection_article_preview %}themes/{{site.template.name}}/procedures/collections/create_collection_article_preview.proc{% endcapture %}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
== Biography

Find popular titles of Autobiographies written by today's people in the
bookshelf *Biography*. Read memoirs from Rock Star’s to people well known
from political and public life.

++++
<div class="row mb-4">
  <div class="col-md-12 col-xs-12">
    {% include {{create_collection_article_preview}} collection=site.biography %}
  </div>
</div>
++++
