---
title:                                  Slick sliders
tagline:                                Preview
date:                                   2023-03-02 00:00:00
description: >
                                        The last carousel you'll ever need. Slick is a responsive carousel
                                        jQuery plugin that supports multiple breakpoints, CSS3 transitions,
                                        touch events/swiping & much more.

categories:                             [ Testpages ]
tags:                                   [ Example ]

comments:                               false
fab_menu_id:                            page_ctrl

permalink:                              /pages/public/previewer/slick/
regenerate:                             true

resources:                              [ clipboard, rouge, slick ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       https://unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// https://github.com/EdwardBalaj/Simple-DeepL-API-Integration

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="dropcap"]
The last carousel you'll ever need. Slick is a responsive carousel
jQuery plugin that supports multiple breakpoints, CSS3 transitions,
touch events/swiping & much more!

== Responsive Display

lorem:sentences[5]

++++
<div class="slider responsive mt-4 mb-6">
  <div>
    <h3 class="slide-item">1</h3>
  </div>
  <div>
    <h3 class="slide-item">2</h3>
  </div>
  <div>
    <h3 class="slide-item">3</h3>
  </div>
  <div>
    <h3 class="slide-item">4</h3>
  </div>
  <div>
    <h3 class="slide-item">5</h3>
  </div>
  <div>
    <h3 class="slide-item">6</h3>
  </div>
  <div>
    <h3 class="slide-item">7</h3>
  </div>
  <div>
    <h3 class="slide-item">8</h3>
  </div>
</div>
++++

[source, js, role="noclip"]
----
var slick_arrows = true;

$('.responsive').slick({
  arrows:                             slick_arrows,
  dots:                               true,
  infinite:                           false,
  speed:                              300,
  slidesToShow:                       4,
  slidesToScroll:                     4,
  responsive: [
    {
      breakpoint:                     1024,
      settings: {
        arrows:                       false,
        slidesToShow:                 3,
        slidesToScroll:               3
      }
    },
    {
      breakpoint:                     600,
      settings: {
        dots:                         false,
        arrows:                       false,
        slidesToShow:                 2,
        slidesToScroll:               2
      }
    },
    {
      breakpoint:                     480,
      settings: {
        dots:                         false,
        arrows:                       false,
        slidesToShow:                 1,
        slidesToScroll:               1
      }
    }
  ]
});
----

[role="mt-5"]
== Features

* Fully responsive. Scales with its container.
* Separate settings per breakpoint.
* Uses CSS3 when available. Fully functional when not.
* Swipe enabled. Or disabled, if you prefer.
* Desktop mouse dragging.
* Infinite looping.
* Fully accessible with arrow key navigation.
* Add, remove, filter & unfilter slides.
* Autoplay, dots, arrows, callbacks, and more.

++++
<script>
$(function() {
  var slick_arrows = true;

  if (slick_arrows) {
    $('.responsive').addClass('slick-arrows');
  }

  $('.responsive').slick({
    arrows:                             slick_arrows,
    dots:                               true,
    infinite:                           false,
    speed:                              300,
    slidesToShow:                       4,
    slidesToScroll:                     4,
    responsive: [
      {
        breakpoint:                     1024,
        settings: {
          arrows:                       false,
          slidesToShow:                 3,
          slidesToScroll:               3
        }
      },
      {
        breakpoint:                     600,
        settings: {
          dots:                         false,
          arrows:                       false,
          slidesToShow:                 2,
          slidesToScroll:               2
        }
      },
      {
        breakpoint:                     480,
        settings: {
          dots:                         false,
          arrows:                       false,
          slidesToShow:                 1,
          slidesToScroll:               1
        }
      }
    ]
  });
});
</script>
++++
