== Waves

Block elements like footers, banners, and panels are typically rectangular
in geometry. To make block elements appear less angular, shapes can be used
to surround them.

.Intro Panel using top and bottom shapes
lightbox::blocks--intro-panel-waves[ 1280, {data-images-blocks--intro-panel-waves} ]

.Wave Configuration for the Intro Panel
[source, yaml]
----
wave:
  top:
    enabled:                      false
    height:                       3
    style:                        wave-1
    color:                        "#dcdcdc"
    background_color:             "#f5f5f5"
    transform:                    false
  bottom:
    enabled:                      false
    height:                       3
    style:                        wave-4
    color:                        "#dcdcdc"
    background_color:             "#f5f5f5"
    transform:                    rotate
----

NOTE: Waves can enclose block elements by placing a shape on the top and
(or) at the bottom.

.Wave Properties
[cols="^2,^4a,^6a", options="header", width="100%", role="rtable mt-3"]
|===
|Propertiy |Values |Description

|`enabled`
|`true`\|`false`
|Enables (show) or disables (hide) a shape.  +
*Default*: No default.

|`height`
|Value out of `1 .. 9`
|Scales the height of a shape. +
*Default*: 3

|`style`
|`wave-1`\|`wave-2`\|`wave-3`\|`wave-4`
|Select a specific wave (shape). +
*Default*: `wave-1`

|`color`
|RGB value
|(Foreground-)Color of the wave element. +
*Default*: `#dcdcdc`

|`background_color`
|RGB value
|Background color of the wave element. +
*Default*: `#f5f5f5`

|`transform`
|`rotate`\|`flip-x`\|`flip-y`
|Transform a wave element. To use a wave at the bottom, the default style
may needed to be tranformed by rotating or flipping. +
*Default*: No default.

|===

=== Shapes

For wave elements, four different shapes are available. Using different sizes
or transformations like *rotate* and *flip*, multiple variations of shapes can
be created.

[cols="^2,^2a,^8a", subs=+macros, options="header", width="100%", role="rtable mt-3"]
|===
|Wave |Height |Example

|`wave-1`
|5
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-20) scale(1,1.5)" class="mt-5">
  <path fill="#212121" fill-opacity="1"
    d="m 0,71.532704 h 71.111114 c 71.111116,0 213.333326,0 355.555566,-18.948546 C 568.88891,33.279773 711.11114,-4.0835522 853.33336,0.36446289 995.55556,4.8124779 1137.7778,52.851042 1208.8889,76.2476 L 1280,100 v 0 h -71.1111 c -71.1111,0 -213.33334,0 -355.55554,0 -142.22222,0 -284.44445,0 -426.66668,0 -142.22224,0 -284.44445,0 -355.555566,0 H 0 Z">
  </path>
</svg>
++++

|`wave-2`
|5
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-20) scale(1,1.5)" class="mt-5">
  <path fill="#212121" fill-opacity="1"
    d="M 0,13.637791 106.66667,8.8698767 C 213.33334,3.7421199 426.66668,-5.2539441 640.00003,4.0120013 853.33333,13.637791 1066.6667,42.425196 1173.3334,56.8189 L 1280,71.212604 V 100 h -106.6666 c -106.6667,0 -320.00007,0 -533.33337,0 -213.33335,0 -426.66669,0 -533.33336,0 H 0 Z">
  </path>
</svg>
++++

|`wave-3`
|5
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-20) scale(1,1.5)" class="mt-5">
  <path fill="#212121" fill-opacity="1"
    d="m 0,0 106.66667,11.111108 c 106.66666,11.111113 320,33.333338 533.33333,46.284725 213.33333,13.09028 426.6667,16.5625 533.3333,18.541667 L 1280,77.777779 V 100 h -106.6667 c -106.6666,0 -319.99997,0 -533.3333,0 -213.33333,0 -426.66667,0 -533.33333,0 H 0 Z">
  </path>
</svg>
++++

|`wave-4`
|5
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-20) scale(1,1.5)" class="mt-5">
  <path fill="#212121" fill-opacity="1"
    d="m 1280,55.555554 -106.6667,7.395833 C 1066.6667,70.486113 853.33333,85.069446 640,75.9375 426.66667,66.666667 213.3333,33.333333 106.6667,16.666667 L 0,0 v 100 h 106.6667 c 106.6666,0 319.99997,0 533.3333,0 213.33333,0 426.6667,0 533.3333,0 H 1280 Z">
  </path>
</svg>
++++

|===

=== Sizes

Waves are scalable in height. Find below some examples of scaled shapes.

[cols="^2,^2a,^8a", subs=+macros, options="header", width="100%", role="rtable mt-3"]
|===
|Wave |Height |Example

|`wave-1`
|1
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-4) scale(1,1.1)" class="mt-5">
  <path fill="#212121" fill-opacity="1" d="m 0,71.532704 h 71.111114 c 71.111116,0 213.333326,0 355.555566,-18.948546 C 568.88891,33.279773 711.11114,-4.0835522 853.33336,0.36446289 995.55556,4.8124779 1137.7778,52.851042 1208.8889,76.2476 L 1280,100 v 0 h -71.1111 c -71.1111,0 -213.33334,0 -355.55554,0 -142.22222,0 -284.44445,0 -426.66668,0 -142.22224,0 -284.44445,0 -355.555566,0 H 0 Z"></path>
</svg>
++++

|`wave-1`
|3
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-12) scale(1,1.3)" class="mt-5">
  <path fill="#212121" fill-opacity="1" d="m 0,71.532704 h 71.111114 c 71.111116,0 213.333326,0 355.555566,-18.948546 C 568.88891,33.279773 711.11114,-4.0835522 853.33336,0.36446289 995.55556,4.8124779 1137.7778,52.851042 1208.8889,76.2476 L 1280,100 v 0 h -71.1111 c -71.1111,0 -213.33334,0 -355.55554,0 -142.22222,0 -284.44445,0 -426.66668,0 -142.22224,0 -284.44445,0 -355.555566,0 H 0 Z"></path>
</svg>
++++

|`wave-1`
|5
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-20) scale(1,1.5)" class="mt-5">
  <path fill="#212121" fill-opacity="1" d="m 0,71.532704 h 71.111114 c 71.111116,0 213.333326,0 355.555566,-18.948546 C 568.88891,33.279773 711.11114,-4.0835522 853.33336,0.36446289 995.55556,4.8124779 1137.7778,52.851042 1208.8889,76.2476 L 1280,100 v 0 h -71.1111 c -71.1111,0 -213.33334,0 -355.55554,0 -142.22222,0 -284.44445,0 -426.66668,0 -142.22224,0 -284.44445,0 -355.555566,0 H 0 Z"></path>
</svg>
++++

|`wave-1`
|9
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-36) scale(1,1.9)" class="mt-6">
  <path fill="#212121" fill-opacity="1" d="m 0,71.532704 h 71.111114 c 71.111116,0 213.333326,0 355.555566,-18.948546 C 568.88891,33.279773 711.11114,-4.0835522 853.33336,0.36446289 995.55556,4.8124779 1137.7778,52.851042 1208.8889,76.2476 L 1280,100 v 0 h -71.1111 c -71.1111,0 -213.33334,0 -355.55554,0 -142.22222,0 -284.44445,0 -426.66668,0 -142.22224,0 -284.44445,0 -355.555566,0 H 0 Z"></path>
</svg>
++++

|===

=== Rotate and Flip

To place a wave at the *bottom* of a block element, the default shape may
needed to be transformed by rotating or flipping.

[cols="^2,^2a,^8a", subs=+macros, options="header", width="100%", role="rtable mt-3"]
|===
|Wave |Transform |Example

|`wave-1`
|none
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-20) scale(1,1.5)" class="mt-5">
  <path fill="#212121" fill-opacity="1"
    d="m 0,71.532704 h 71.111114 c 71.111116,0 213.333326,0 355.555566,-18.948546 C 568.88891,33.279773 711.11114,-4.0835522 853.33336,0.36446289 995.55556,4.8124779 1137.7778,52.851042 1208.8889,76.2476 L 1280,100 v 0 h -71.1111 c -71.1111,0 -213.33334,0 -355.55554,0 -142.22222,0 -284.44445,0 -426.66668,0 -142.22224,0 -284.44445,0 -355.555566,0 H 0 Z">
  </path>
</svg>
++++

|`wave-1`
|rotate
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-20) scale(1,1.5) rotate(180)" class="mt-5">
  <path fill="#212121" fill-opacity="1"
    d="m 0,71.532704 h 71.111114 c 71.111116,0 213.333326,0 355.555566,-18.948546 C 568.88891,33.279773 711.11114,-4.0835522 853.33336,0.36446289 995.55556,4.8124779 1137.7778,52.851042 1208.8889,76.2476 L 1280,100 v 0 h -71.1111 c -71.1111,0 -213.33334,0 -355.55554,0 -142.22222,0 -284.44445,0 -426.66668,0 -142.22224,0 -284.44445,0 -355.555566,0 H 0 Z">
  </path>
  </svg>
++++

|`wave-1`
|flip-x
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-20) scale(1,1.5) scale(1,-1)" class="mt-5">
  <path fill="#212121" fill-opacity="1"
    d="m 0,71.532704 h 71.111114 c 71.111116,0 213.333326,0 355.555566,-18.948546 C 568.88891,33.279773 711.11114,-4.0835522 853.33336,0.36446289 995.55556,4.8124779 1137.7778,52.851042 1208.8889,76.2476 L 1280,100 v 0 h -71.1111 c -71.1111,0 -213.33334,0 -355.55554,0 -142.22222,0 -284.44445,0 -426.66668,0 -142.22224,0 -284.44445,0 -355.555566,0 H 0 Z">
  </path>
  </svg>
++++

|`wave-1`
|flip-y
|
++++
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 100" transform="translate(0,-20) scale(1,1.5) scale(-1,1)" class="mt-5">
  <path fill="#212121" fill-opacity="1"
    d="m 0,71.532704 h 71.111114 c 71.111116,0 213.333326,0 355.555566,-18.948546 C 568.88891,33.279773 711.11114,-4.0835522 853.33336,0.36446289 995.55556,4.8124779 1137.7778,52.851042 1208.8889,76.2476 L 1280,100 v 0 h -71.1111 c -71.1111,0 -213.33334,0 -355.55554,0 -142.22222,0 -284.44445,0 -426.66668,0 -142.22224,0 -284.44445,0 -355.555566,0 H 0 Z">
  </path>
</svg>
++++

|===
