---
title:                                  Tester
tagline:                                master slider pro
date:                                   2020-11-03 00:00:00
description: >
                                        Welcome to the preview page focussing on the image module. This page
                                        shows some valuable features of the J1 Theme to manage your image-based
                                        content using lightboxes, carousels (slider), and galleries.

categories:                             [ Testpages ]
tags:                                   [ Example ]

comments:                               false
fab_menu_id:                            open_toc

permalink:                              /pages/public/learn/masterslider-pro/
regenerate:                             false

resources:                              [ lightbox, lightGallery, mastersliderpro, rouge ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/image/page/tour/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       //unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Slider 1 - Simple + SliderControls

lorem:sentences[3]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00001[role="mt-3 mb-5"]


== Slider 2 -  Full Width + Lightbox + MSScrollParallax

lorem:sentences[3]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00002[role="mt-3 mb-5"]


== Slider 3 - SlideInfo (boxed) + MSScrollParallax

lorem:sentences[3]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00003[role="mt-3 mb-5"]


== Slider 4 - ThumbImage (right|vertical)

lorem:sentences[2]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00004[role="mt-3 mb-5"]


== Slider 5 - ThumbImage (bottom|horizontal)

lorem:sentences[2]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00005[role="mt-3 mb-5"]


== Slider 6 - ThumbInfo (bottom|horizontal)

lorem:sentences[2]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00006[role="mt-3 mb-5"]


== Slider 7 - ThumbInfo (right|vertical)

lorem:sentences[2]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00007[role="mt-3 mb-5"]


== Slider 8 - Blog articles + PartialView

lorem:sentences[3]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00008[role="mt-3 mb-5"]


== Slider 9 - SlideInfo (below) + PartialView

lorem:sentences[3]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00009[role="mt-3 mb-5"]



++++
<style>



</style>
++++
