---
title:                                  Gem Cheatsheet
tagline:                                Commands for daily use
date:                                   2023-05-19 00:00:00 +100
description: >
                                        Welcome to the info pages of J1 Theme. A good decision
                                        to get on that page first. Certainly, there is no better
                                        place to learn what J1 Theme can do and what pages are
                                        available to experience more.
keywords: >
                                        Jekyll, Theme, JekyllOne, Info, Manual, Cheatsheet, Ruby, Gem

categories:                             [ Manual ]
tags:                                   [ Cheatsheet, Gem ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/recha-oktaviani.jpg
  width:                                1920
  height:                               1280
  alt:                                  Photo by Recha Oktaviani on Unsplash

regenerate:                             false
permalink:                              /pages/public/learn/cheatsheet/gem/

resources:                              [ animate, comments, clipboard, rouge ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/recha-oktaviani.jpg
          alt:                          Photo by Recha Oktaviani on Unsplash
          badge:
            type:                       unsplash
            author:                     Recha Oktaviani
            href:                       https://unsplash.com/de/@rechaoktaviani
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Welcome to the info pages of J1 Theme. A good decision to get on that page
first. Certainly, there is no better place to learn what J1 Theme can do
and what pages are available to experience more.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
== Update Rubygems

[source, sh]
----
gem install rubygems-update
update_rubygems
gem update --system
----

== Install a Ruby Gem

Add this line to your application's Gemfile:

[source, sh]
----
gem 'j1_template', '~> 2023.3.0'
----

and install the locally created RubGem as:

[source, sh]
----
gem install --local j1-template --no-document
----

== Userized Installation

When you use the **--user-install option**, RubyGems will install the gems
to a directory inside your home directory, someth
ing like `~/.gem/ruby/3.1.0`
for Ruby version `3.1.x`. The commands provided by the gems you have installed
will end up in ~/.gem/ruby/3.1.0/bin.

[source, sh]
----
gem install j1-template --user-install --no-document
----

For the programs installed userized, you need to add `~/.gem/ruby/3.1.0/bin`
to your **PATH** environment variable.

=== Install a Gem in specific version

[source, sh]
----
gem install j1-template -v 2023.3.0 --user-install --no-document
----

You can also use version comparators like >= or ~>

[source, sh]
----
gem install j1-template -v "~> 2023.3.0" --user-install --no-document
----

=== Install a Gem from different source

[source, sh]
----
gem install j1-template -v 2023.3.0 --source 'https://gem.fury.io/jekyll-one-org/' --user-install --no-document
----

### Clean up old Gem versions on GEM_PATH

To clean up old versions of installed gems use below command

[source, sh]
----
gem cleanup <GEMNAME …>
----

The cleanup command removes old versions of gems from GEM_HOME that are not
required to meet a dependency. If a gem is installed elsewhere in GEM_PATH
the cleanup command won’t delete it.

If no gems are named all gems in GEM_HOME are cleaned.
