---
title:                                  J1 Template Cheatsheet
tagline:                                Commands for daily use
date:                                   2023-05-19 00:00:00 +100
description: >
                                        RubyGems is a package manager for the Ruby programming language. It provides
                                        a convenient way to distribute and manage software packages, called gems,
                                        written in Ruby. With RubyGems, developers can easily install, uninstall, and
                                        manage Ruby libraries and applications.
keywords: >
                                        Jekyll, Theme, JekyllOne, Info, Manual, Cheatsheet, J1, Template

categories:                             [ Manual ]
tags:                                   [ Cheatsheet, JekyllOne, Template ]

image:
  path:                                 /assets/images/modules/attics/1920x1280/recha-oktaviani.jpg
  width:                                1920
  height:                               1280
  alt:                                  Photo by Recha Oktaviani on Unsplash

regenerate:                             false
permalink:                              /pages/public/learn/cheatsheet/j1/

resources:                              [ animate, clipboard, rouge ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/images/modules/attics/1920x1280/recha-oktaviani.jpg
          alt:                          Photo by Recha Oktaviani on Unsplash
          badge:
            type:                       unsplash
            author:                     Recha Oktaviani
            href:                       https://unsplash.com/de/@rechaoktaviani
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
RubyGems is a package manager for the Ruby programming language. It provides
a convenient way to distribute and manage software packages, called GEMs,
written in Ruby. With RubyGems, developers can easily install, uninstall, and
manage Ruby libraries and applications. It simplifies obtaining and managing
the dependencies needed for a Ruby project by automatically resolving and
installing the GEMs required.

RubyGems also provides a centralized *repository*, the RubyGems website
at https://rubygems.org/[rubygems.org, {browser-window--new}], where developers
can publish their *GEMs* for others to use. The website serves as a searchable
catalog of available GEMs, allowing developers to discover and download GEMs
for their projects.

TIP: In addition to the default RubyGems repository, developers can
configure their GEM sources or specify alternative sources when installing
GEMs. This flexibility allows private GEM repositories or custom sources to
be used as needed.

RubyGems comes pre-installed with a Ruby installation. It provides
a command-line interface, the `gem` command, for performing various
operations, such as installing GEMS, listing installed libraries,
updating GEMs, and managing library sources.

Here are *common* commands you can use with the `j1` command:

* *install*     -- Installs a GEM from the default RubyGems repository
* *uninstall*   -- Uninstalls a GEM
* *update*      -- Updates installed GEMs to their latest versions
* *search*      -- Searches for GEMs matching a specific term
* *list*        -- Lists all installed GEMs
* *info*        -- Provides information about a specific GEM
* *cleanup*     -- Removes old versions of installed GEMs, keeping only the latest version

The following examples give your a good overview of the most *common*
commands managin Ruby GEMs for daily use. All examples are focussing the *J1*
template to make it easier for users using the template system. Anyway, all
commands can be used for *any* Ruby Appication by simply replacing the *name*
of the GEM as you need.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Update Rubygems

[source, sh]
----
gem install rubygems-update
update_rubygems
gem update --system
----

[role="mt-5"]
== Install commands

bla ...
