== Manage Collections

Not everything is a post or a page. Maybe you want to document the various
methods in your open source project, members of a team, or talks at a
conference.

Collections allow you to define a new type of document that behave like Pages
or Posts do normally, but also have their own unique properties and namespace.

=== Step 1: Enable your collection

To enable a collection you need to instruct Jekyll to read in your collection
folders. Add the following to your site's `_config.yml` file, replacing
`my_collection` with the name of your collection:

[source, yaml]
--------------
collections:
- my_collection
--------------

You can optionally specify metadata for your collection in the configuration:

[source, yaml]
--------------
collections:
  my_collection:
    foo: bar
--------------

Default attributes can also be set for a collection:

[source, yaml]
--------------
defaults:
  - scope:
      path: ""
      type: my_collection
    values:
      layout: page
--------------

=== Step 2: Add your content

Create a corresponding folder (e.g. `/_my_collection`) and add
documents to. The YAML Front Matter is read in as data if it exists, and
everything after it is stuck in the Document's `content` attribute. If no
YAML Front Matter is provided, Jekyll will *not generate* the file in your
collection.

[NOTE]
====
Be sure to name of your collection directories are correctly

The folder *must* be named *identically* to the collection as defined in
your site configuration `_config.yml` file, with the addition of the
preceding `_` character (underscore).
====

=== Step 3: Create independent files

Optionally you can render your collection's documents into independent files.
If you'd like Jekyll to create a public-facing, rendered version of each
document in your collection, set the `output` key to `true` in your collection
metadata with your site configuration `_config.yml`:

[source, yaml]
--------------
collections:
  my_collection:
    output: true
--------------

This will produce a file for each document in the collection. For example, if
you have `my_collection/some_subdir/some_doc.md`, it will be rendered
using Liquid and the Markdown converter of your choice and written out
to `/my_collection/some_subdir/some_doc.html`.

As for posts with Permalinks, the document URL can be customized by setting
`permalink` metadata for the collection:

[source, yaml]
--------------
collections:
  my_collection:
    output:         true
    permalink:      /awesome/:path/
--------------

For example, if you have `_my_collection/some_subdir/some_doc.md`,
it will be written out to `<dest>/awesome/some_subdir/some_doc/index.html`.

[NOTE]
====
Don't forget to add a (YAML) front matter for processing.

Files in collections that do not have front matter are treated as `static files`
and simply copied to their output location without any processing.
====


=== Collections placed in one subdirectory

See: {jekyll-talk-collections-subdir}[How all collections inside one subdirectory works]

I think there’s an error in the official docs … from the souce code it looks
like collections_dir is a top-level key instead of being nested within
collections object …

from the souce code it looks like collections_dir is a top-level key instead
of being nested within collections object…


So, if your Gemfile is pointed towards the jekyll repo master, then change
your config file to following and try again …

[source, yaml]
--------------
collections_dir:    mycollections

collections:
  collection1:
    output:         true
    permalink:      /:name
  collection2:
    output:         true
    permalink:      /:name
  collection3:
    output: true
    permalink:      /:name
--------------

[NOTE]
====
Notice for Jekyll version `3.7.2` and above. From {jekyll-home-news}[Jekyll News section]:

Another regression reported was related to our “Custom collections directory”
feature introduced in 3.7.0.

Users setting collection_dir to a certain directory would have altered paths
to their posts still at the root of their site’s source. This roughly
translated to 404 errors on URLs to their posts.

Props to @localheinz for bringing this regression to our notice. We decided to
resolve this by having Jekyll *ignore posts and drafts* at the *root* of the
site’s source directory if the user customizes the `collection_dir` setting.

Ergo, if you set a custom location for your collections, please *ensure* you
move all of your collections into that directory. This includes *posts and
drafts* as well. Your links generated by `{% post_url %}` or `{% link %}` will
adapt automatically.
====


=== Liquid Variables

Each collection is accessible via the `site` Liquid variable. For example, if
you want to access the `albums` collection found in `_albums`, you'd use
`site.albums`. Each collection is itself an array of documents
(e.g. `site.albums` is an array of documents, much like `site.pages` and
`site.posts`). See below for how to access attributes of those documents.

==== Collection specific variables

The collections are also available under `site.collections`, with the metadata
you specified in your `_config.yml` (if present) and the following
information:

[width="100%", cols="6,6", options="header", role="table-responsive mt-3"]
|=======================================================================
|Variable     |Description
|`label`      |The name of your collection, e.g. `my_collection`.

|`docs`       |An array of link:#documents[documents].

|`files`      |An array of static files in the collection.

|`relative_directory` |The path to the collection's source directory,
relative to the site source.

|`directory`  |The full path to the collections's source directory.

|`output`     |Whether the collection's documents will be output as
individual files.
|=======================================================================


==== Document specific variables

In addition to any YAML Front Matter provided in the document's corresponding
file, each document has the following attributes:

[width="100%", cols="6,6", options="header", role="table-responsive mt-3"]
|=======================================================================
|Variable     |Description
|`content`    |The (unrendered) content of the document. If no YAML Front
Matter is provided, Jekyll will not generate the file in your
collection. If YAML Front Matter is used, then this is all the contents
of the file after the terminating `---` of the front matter.

|`output`     |The rendered output of the document, based on the `content`.

|`path`       |The full path to the document's source file.

|`relative_path` |The path to the document's source file relative to the
site source.

|`url`        |The URL of the rendered collection. The file is only written to
the destination when the collection to which it belongs has
`output: true` in the site's configuration.

|`collection` |The name of the document's collection.

|`date`       |The date of the document's collection.
|=======================================================================

=== Collection Variables

Attributes from the YAML front matter can be accessed as data anywhere in the
site. Using the above example for configuring a collection as `site.albums`,
one might have front matter in an individual file structured as follows (which
must use a supported markup format, and cannot be saved with a `.yaml`
extension):

[source, yaml]
----
title: "Josquin: Missa De beata virgine and Missa Ave maris stella"
artist: "The Tallis Scholars"
director: "Peter Phillips"
works:
  - title: "Missa De beata virgine"
    composer: "Josquin des Prez"
    tracks:
      - title: "Kyrie"
        duration: "4:25"
      - title: "Gloria"
        duration: "9:53"
      - title: "Credo"
        duration: "9:09"
      - title: "Sanctus & Benedictus"
        duration: "7:47"
      - title: "Agnus Dei I, II & III"
        duration: "6:49"
----

Every album in the collection could be listed on a single page with a template:

[source, liquid]
----
{% for album in site.albums %}
  <h2>{{ album.title }}</h2>
  <p>Performed by {{ album.artist }}{% if album.director %}, directed by {{ album.director }}{% endif %}</p>
  {% for work in album.works %}
    <h3>{{ work.title }}</h3>
    <p>Composed by {{ work.composer }}</p>
    <ul>
    {% for track in work.tracks %}
      <li>{{ track.title }} ({{ track.duration }})</li>
    {% endfor %}
    </ul>
  {% endfor %}
{% endfor %}
----
