
[role="mt-5"]
== Parameters

The SwiperJS API offers a rich collection of parameters that allow to
configure almost every aspect of a slider. Parameters are passed as the
second argument during initialization.

.Initialization example
[source, js]
----
const mySwiper = new Swiper('.my-swiper-container', {
  speed: 400,
  spaceBetween: 100,
});
----

Find in this section a list of all available parameters ordered
alphabetically.

[role="mt-4"]
=== a11y (Accessibility)

Once the a11y (Accessibility) module is activated, Swiper automatically
adds ARIA attributes and semantic roles to the DOM. Specifically, important
ARIA attributes such as aria-live, aria-label, and role are automatically
added to the slider and its controls so that screen reader users can understand
the purpose of the slider and navigate between the slides.

Object with a11y parameters or boolean `true` to enable with default
settings.

[source, js]
----
const mySwiper = new Swiper('.my-swiper-container', {
  a11y: {
    prevSlideMessage: 'Previous slide',
    nextSlideMessage: 'Next slide',
  },
});
----

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`a11y`
|boolean \| A11yOptions
|none

|===


[role="mt-4"]
=== allowSlideNext

When set to `false` to disable swiping to next slide direction (to right or bottom).

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`allowSlideNext`
|boolean
|true

|===

[role="mt-4"]
=== allowSlidePrev

When set to `false` to disable swiping to previous slide direction (to left or top).

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`allowSlidePrev`
|boolean
|true

|===

[role="mt-4"]
=== allowTouchMove

When set to `false`, then the only way to switch the slide is use of external API
functions like slidePrev or slideNext.

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`allowTouchMove`
|boolean
|true

|===

[role="mt-4"]
=== autoHeight

When set to `true` and slider wrapper will adapt its height to the height
of the currently active slide.

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`autoHeight`
|boolean
|false

|===


[role="mt-4"]
=== autoplay

Object with autoplay parameters or boolean `true` to enable with default
settings.

[source, js]
----
const swiper = new Swiper('.swiper', {
 autoplay: {
   delay: 5000,
 },
});
----

[role="mt-4"]
=== breakpoints

Allows to set different parameter for different responsive breakpoints
(screen sizes). Not all parameters can be changed in breakpoints, only
those which do not require different layout and logic, like
`slidesPerView`, `slidesPerGroup`, `spaceBetween`, `grid.rows`.

[CAUTION]
====
Parameters like `loop` and `effect` won't work.
====

[source, js]
----
const swiper = new Swiper('.swiper', {
  // Default parameters
  slidesPerView: 1,
  spaceBetween: 10,
  // Responsive breakpoints
  breakpoints: {
    // when window width is >= 320px
    320: {
      slidesPerView: 2,
      spaceBetween: 20
    },
    // when window width is >= 480px
    480: {
      slidesPerView: 3,
      spaceBetween: 30
    },
    // when window width is >= 640px
    640: {
      slidesPerView: 4,
      spaceBetween: 40
    }
  }
})
----

[source, js]
----
const swiper = new Swiper('.swiper', {
  slidesPerView: 1,
  spaceBetween: 10,
  // using "ratio" endpoints
  breakpoints: {
    '@0.75': {
      slidesPerView: 2,
      spaceBetween: 20,
    },
    '@1.00': {
      slidesPerView: 3,
      spaceBetween: 40,
    },
    '@1.50': {
      slidesPerView: 4,
      spaceBetween: 50,
    },
  }
});
----

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`breakpoints`
|object
|none

|===

[role="mt-4"]
=== breakpointsBase (beta)

Base for breakpoints. Can be `window` or `container`. If set to `window`
(by default) then breakpoint keys mean window width. If set to `container`
then breakpoint keys treated as swiper container width.

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`breakpointsBase`
|'container' \| CSSSelector \| 'window'
|window

|===

[role="mt-4"]
=== cardsEffect

Object with Cards-effect parameters

[source, js]
----
const swiper = new Swiper('.swiper', {
  effect: 'cards',
  cardsEffect: {
    // ...
  },
});
----

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`cardsEffect`
|CardsEffectOptions
|none

|===

[role="mt-4"]
=== centerInsufficientSlides

When enabled it center slides if the amount of slides less than
`slidesPerView`.

[CAUTION]
====
Not intended to be used `loop` mode and `grid.rows`.
====

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`centerInsufficientSlides`
|boolean
|false

|===

[role="mt-4"]
=== centeredSlides

When set to `true`, then active slide will be centered, not always on the left side.

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`centeredSlides`
|boolean
|false

|===

[role="mt-4"]
=== centeredSlidesBounds

When set to `true`, then active slide will be centered without adding gaps at
the beginning and end of slider. Required `centeredSlides: true`.

[CAUTION]
====
Not intended to be used with `loop` or `pagination`.
====

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`centeredSlidesBounds`
|boolean
|false

|===

[role="mt-4"]
=== containerModifierClass

The beginning (prepended) of the modifier CSS class that can be added to
swiper container depending on different parameters.

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`containerModifierClass`
|string
|'swiper-'

|===

[role="mt-4"]
=== controller

Object with controller parameters or boolean `true` to enable with
default settings

[source, js]
----
const swiper = new Swiper('.swiper', {
  controller: {
    inverse: true,
  },
});
----

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`controller`
|ControllerOptions \| boolean
|none \| true

|===

[role="mt-4"]
=== coverflowEffect

Object with Coverflow-effect parameters.

[source, js]
----
const swiper = new Swiper('.swiper', {
  effect: 'coverflow',
  coverflowEffect: {
    rotate: 30,
    slideShadows: false,
  },
});
----

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`coverflowEffect`
|CoverflowEffectOptions
|none

|===

[role="mt-4"]
=== createElements

When enabled Swiper will automatically wrap slides with swiper-wrapper
element, and will create required elements for navigation, pagination
and scrollbar they are enabled (with their respective params object or
with boolean `true`).

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`createElements`
|boolean
|false

|===

[role="mt-4"]
=== creativeEffect

Object with Creative-effect parameters.

[source, js]
----
const swiper = new Swiper('.swiper', {
  effect: 'creative',
  creativeEffect: {
    prev: {
      // will set `translateZ(-400px)` on previous slides
      translate: [0, 0, -400],
    },
    next: {
      // will set `translateX(100%)` on next slides
      translate: ['100%', 0, 0],
    },
  },
});
----

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`creativeEffect`
|CreativeEffectOptions
|none

|===

[role="mt-4"]
=== cssMode

When enabled it will use modern CSS Scroll Snap API. It doesn't support
all of Swiper's features, but potentially should bring a much better
performance in simple configurations.

This is what is not supported when it is enabled:

* Cube effect
* `speed` parameter may not have no effect
* All transition start/end related events (use `slideChange` instead)
* `slidesPerGroup` has limited support
* `simulateTouch` doesn't have effect and "dragging" with mouse doesn't work
* `resistance` doesn't have any effect
* `allowSlidePrev/Next`
* `swipeHandler`

In case if you use it with other effects, especially 3D effects, it is
required to wrap slide's content with <div className="swiper-slide-transform">`
element. And if you use any custom styles on slides (like background colors,
border radius, border, etc.), they should be set on `swiper-slide-transform`
element instead.

[source, html]
----
<div class="swiper">
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      <!-- wrap slide content with transform element -->
      <div class="swiper-slide-transform">
        ... slide content ...
      </div>
    </div>
    ...
  </div>
</div>
<script>
const swiper = new Swiper('.swiper', {
   effect: 'flip',
   cssMode: true,
 });
</script>
----

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`cssMode`
|boolean
|false

|===

[role="mt-4"]
=== cubeEffect

Object with Cube-effect parameters.

[source, js]
----
const swiper = new Swiper('.swiper', {
  effect: 'cube',
  cubeEffect: {
    slideShadows: false,
  },
});
----

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`cubeEffect`
|CubeEffectOptions
|false

|===

[role="mt-4"]
=== direction

Can be `horizontal` or `vertical` (for vertical slider).

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`direction`
'horizontal' \| 'vertical'
|horizontal

|===

[role="mt-4"]
=== edgeSwipeDetection

Enable to release Swiper events for swipe-back work in app. When set to
`prevent` then it will prevent system swipe-back navigation instead.

[CAUTION]
=====
This feature works only with "touch" events (and not pointer events),
so it will work on iOS/Android devices and won't work on Windows devices
with pointer events.
=====

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`edgeSwipeDetection`
|string \| boolean
|false

|===

[role="mt-4"]
=== edgeSwipeThreshold

Area (in px) from left edge of the screen to release touch events for
swipe-back in app.

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`edgeSwipeThreshold`
|number
|20

|===

[role="mt-4"]
=== effect

Transition effect. Can be on of `slide`, `fade`, `cube`, `coverflow`,
`flip`, `creative` or `cards`

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`effect`
|Transition effect
|slide

|===

[role="mt-4"]
=== enabled

Whether Swiper initially enabled. When Swiper is disabled, it will hide
all navigation elements and won't respond to any events and interactions.

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`enabled`
|boolean
|true

|===

[role="mt-4"]
=== eventsPrefix

Event name prefix for all DOM events emitted by Swiper Element
(web component).


[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`eventsPrefix`
|string
|'swiper'

|===

[role="mt-4"]
=== fadeEffect

Object with Fade-effect parameters.

[source, js]
----
const swiper = new Swiper('.swiper', {
  effect: 'fade',
  fadeEffect: {
    crossFade: true
  },
});
----

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`fadeEffect`
|FadeEffectOptions
|none

|===

[role="mt-4"]
=== flipEffect

Object with Flip-effect parameters.

[source, js]
----
const swiper = new Swiper('.swiper', {
  effect: 'flip',
  flipEffect: {
    slideShadows: false,
  },
});
----

[cols="3a,2a,1a", options="header", width="100%", role="table-responsive mt-4"]
|===
|Name |Type |Default

|`flipEffect`
|FlipEffectOptions
|none

|===




[cols="3a,2a,1a,6a", options="header", width="100%", role="table-striped table-responsive mt-4"]
|===
|Name |Type |Default |Description

|link:#param-focusableElements[focusableElements] |string |'input,
select, option, textarea, button, video, label' |CSS selector for
focusable elements. Swiping will be disabled on such elements if they
are "focused"

|link:#param-followFinger[followFinger] |boolean |true |If disabled,
then slider will be animated only when you release it, it will not move
while you hold your finger on it

|link:#param-freeMode[freeMode] |boolean \| FreeModeOptions | a|
Enables free mode functionality. Object with free mode parameters or
boolean `true` to enable with default settings.

[source, js]
----
const swiper = new Swiper('.swiper', {
  freeMode: true,
});

const swiper = new Swiper('.swiper', {
  freeMode: {
    enabled: true,
    sticky: true,
  },
});
----

|link:#param-grabCursor[grabCursor] |boolean |false |This option may a
little improve desktop usability. If `true`, user will see the "grab"
cursor when hover on Swiper

|link:#param-grid[grid] |GridOptions | a|
Object with grid parameters to enable "multirow" slider.

[source, js]
----
const swiper = new Swiper('.swiper', {
  grid: {
    rows: 2,
  },
});
----

|link:#param-hashNavigation[hashNavigation] |boolean \|
HashNavigationOptions | a|
Enables hash url navigation to for slides. Object with hash navigation
parameters or boolean `true` to enable with default settings

[source, js]
----
const swiper = new Swiper('.swiper', {
  hashNavigation: {
    replaceState: true,
  },
});
----

|link:#param-height[height] |number \| null |null a|
Swiper height (in px). Parameter allows to force Swiper height. Useful
only if you initialize Swiper when it is hidden and in SSR and Test
environments for correct Swiper initialization

____
Setting this parameter will make Swiper not responsive
____

|link:#param-history[history] |boolean \| HistoryOptions | a|
Enables history push state where every slide will have its own url. In
this parameter you have to specify main slides url like `"slides"` and
specify every slide url using `data-history` attribute.

Object with history navigation parameters or boolean `true` to enable
with default settings

[source, js]
----
const swiper = new Swiper('.swiper', {
  history: {
    replaceState: true,
  },
});
----

[source, html]
----
<!-- will produce "slides/slide1" url in browser history -->
<div class="swiper-slide" data-history="slide1"></div>
----

|link:#param-init[init] |boolean |true |Whether Swiper should be
initialised automatically when you create an instance. If disabled, then
you need to init it manually by calling `swiper.init()`

|link:#param-initialSlide[initialSlide] |number |0 |Index number of
initial slide.

|link:#param-injectStyles[injectStyles] |string[] | |Inject text styles
to the shadow DOM. Only for usage with Swiper Element

|link:#param-injectStylesUrls[injectStylesUrls] |string[] | |Inject
styles `<link>`s to the shadow DOM. Only for usage with Swiper Element

|link:#param-keyboard[keyboard] |boolean \| KeyboardOptions | a|
Enables navigation through slides using keyboard. Object with keyboard
parameters or boolean `true` to enable with default settings

[source, js]
----
const swiper = new Swiper('.swiper', {
  keyboard: {
    enabled: true,
    onlyInViewport: false,
  },
});
----

|link:#param-lazyPreloadPrevNext[lazyPreloadPrevNext] |number |0 |Number
of next and previous slides to preload. Only applicable if using lazy
loading.

|link:#param-lazyPreloaderClass[lazyPreloaderClass] |string
|'swiper-lazy-preloader' |CSS class name of lazy preloader

|link:#param-longSwipes[longSwipes] |boolean |true |Set to `false` if
you want to disable long swipes

|link:#param-longSwipesMs[longSwipesMs] |number |300 |Minimal duration
(in ms) to trigger swipe to next/previous slide during long swipes

|link:#param-longSwipesRatio[longSwipesRatio] |number |0.5 |Ratio to
trigger swipe to next/previous slide during long swipes

|link:#param-loop[loop] |boolean |false a|
Set to `true` to enable continuous loop mode

Because of nature of how the loop mode works (it will rearrange slides),
total number of slides must be:

* more than or equal to `slidesPerView` + `slidesPerGroup` (and
`+ 1` in case of `centeredSlides`)
* even to `slidesPerGroup` (or use `loopAddBlankSlides` parameter)
* even to `grid.rows` (or use `loopAddBlankSlides` parameter)

|link:#param-loopAddBlankSlides[loopAddBlankSlides] |boolean |true
|Automatically adds blank slides if you use Grid or `slidesPerGroup`
and the total amount of slides is not even to `slidesPerGroup` or to
`grid.rows`

|link:#param-loopAdditionalSlides[loopAdditionalSlides] |number |0
|Allows to increase amount of looped slides

|link:#param-loopPreventsSliding[loopPreventsSliding] |boolean |true |If
enabled then slideNext/Prev will do nothing while slider is animating in
loop mode

|link:#param-maxBackfaceHiddenSlides[maxBackfaceHiddenSlides] |number
|10 a|
If total number of slides less than specified here value, then Swiper
will enable `backface-visibility: hidden` on slide elements to reduce
visual "flicker" in Safari.

____
It is not recommended to enable it on large amount of slides as it will
reduce performance
____

|link:#param-modules[modules] |SwiperModule[] | a|
Array with Swiper modules

[source, js]
----
import Swiper from 'swiper';
import { Navigation, Pagination } from 'swiper/modules';

const swiper = new Swiper('.swiper', {
   modules: [ Navigation, Pagination ],
 });
----

|link:#param-mousewheel[mousewheel] |boolean \| MousewheelOptions | a|
Enables navigation through slides using mouse wheel. Object with
mousewheel parameters or boolean `true` to enable with default
settings

[source, js]
----
const swiper = new Swiper('.swiper', {
  mousewheel: {
    invert: true,
  },
});
----

|link:#param-navigation[navigation] |boolean \| NavigationOptions | a|
Object with navigation parameters or boolean `true` to enable with
default settings.

[source, js]
----
const swiper = new Swiper('.swiper', {
  navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  },
});
----

|link:#param-nested[nested] |boolean |false |Set to `true` on Swiper
for correct touch events interception. Use only on swipers that use same
direction as the parent one

|link:#param-noSwiping[noSwiping] |boolean |true |Enable/disable swiping
on elements matched to class specified in `noSwipingClass`

|link:#param-noSwipingClass[noSwipingClass] |string |'swiper-no-swiping'
|Specify `noSwiping`s element css class

|link:#param-noSwipingSelector[noSwipingSelector] |string | |Can be used
instead of `noSwipingClass` to specify elements to disable swiping on.
For example `input` will disable swiping on all inputs

|link:#param-normalizeSlideIndex[normalizeSlideIndex] |boolean |true
|Normalize slide index.

|link:#param-observeParents[observeParents] |boolean |false |Set to
`true` if you also need to watch Mutations for Swiper parent elements

|link:#param-observeSlideChildren[observeSlideChildren] |boolean |false
|Set to `true` if you also need to watch Mutations for Swiper slide
children elements

|link:#param-observer[observer] |boolean |false |Set to `true` to
enable Mutation Observer on Swiper and its elements. In this case Swiper
will be updated (reinitialized) each time if you change its style (like
hide/show) or modify its child elements (like adding/removing slides)

|link:#param-on[on] |object | |Register event handlers

|link:#param-onAny[onAny] |function(handler) | a|
Add event listener that will be fired on all events

[source, js]
----
const swiper = new Swiper('.swiper', {
   onAny(eventName, ...args) {
     console.log('Event: ', eventName);
     console.log('Event data: ', args);
   }
 });
----

|link:#param-oneWayMovement[oneWayMovement] |boolean |false |When
enabled, will swipe slides only forward (one-way) regardless of swipe
direction

|link:#param-pagination[pagination] |boolean \| PaginationOptions | a|
Object with pagination parameters or boolean `true` to enable with
default settings.

[source, js]
----
const swiper = new Swiper('.swiper', {
  pagination: {
    el: '.swiper-pagination',
    type: 'bullets',
  },
});
----

|link:#param-parallax[parallax] |boolean \| ParallaxOptions | a|
Object with parallax parameters or boolean `true` to enable with
default settings.

[source, js]
----
const swiper = new Swiper('.swiper', {
  parallax: true,
});
----

|link:#param-passiveListeners[passiveListeners] |boolean |true |Passive
event listeners will be used by default where possible to improve
scrolling performance on mobile devices. But if you need to use
`e.preventDefault` and you have conflict with it, then you should
disable this parameter

|link:#param-preventClicks[preventClicks] |boolean |true |Set to
`true` to prevent accidental unwanted clicks on links during swiping

|link:#param-preventClicksPropagation[preventClicksPropagation] |boolean
|true |Set to `true` to stop clicks event propagation on links during
swiping

|link:#param-preventInteractionOnTransition[preventInteractionOnTransition]
|boolean |false |When enabled it won't allow to change slides by swiping
or navigation/pagination buttons during transition

|link:#param-resistance[resistance] |boolean |true |Set to `false` if
you want to disable resistant bounds

|link:#param-resistanceRatio[resistanceRatio] |number |0.85 |This option
allows you to control resistance ratio

|link:#param-resizeObserver[resizeObserver] |boolean |true |When enabled
it will use ResizeObserver (if supported by browser) on swiper container
to detect container resize (instead of watching for window resize)

|link:#param-rewind[rewind] |boolean |false a|
Set to `true` to enable "rewind" mode. When enabled, clicking "next"
navigation button (or calling `.slideNext()`) when on last slide will
slide back to the first slide. Clicking "prev" navigation button (or
calling `.slidePrev()`) when on first slide will slide forward to the
last slide.

____
Should not be used together with `loop` mode
____

|link:#param-roundLengths[roundLengths] |boolean |false |Set to `true`
to round values of slides width and height to prevent blurry texts on
usual resolution screens (if you have such)

|link:#param-runCallbacksOnInit[runCallbacksOnInit] |boolean |true |Fire
Transition/SlideChange/Start/End events on swiper initialization. Such
events will be fired on initialization in case of your initialSlide is
not 0, or you use loop mode

|link:#param-scrollbar[scrollbar] |boolean \| ScrollbarOptions | a|
Object with scrollbar parameters or boolean `true` to enable with
default settings.

[source, js]
----
const swiper = new Swiper('.swiper', {
  scrollbar: {
    el: '.swiper-scrollbar',
    draggable: true,
  },
});
----

|link:#param-setWrapperSize[setWrapperSize] |boolean |false |Enabled
this option and plugin will set width/height on swiper wrapper equal to
total size of all slides. Mostly should be used as compatibility
fallback option for browser that don't support flexbox layout well

|link:#param-shortSwipes[shortSwipes] |boolean |true |Set to `false`
if you want to disable short swipes

|link:#param-simulateTouch[simulateTouch] |boolean |true |If `true`,
Swiper will accept mouse events like touch events (click and drag to
change slides)

|link:#param-slideActiveClass[slideActiveClass] |string
|'swiper-slide-active' a|
CSS class name of currently active slide

____
By changing classes you will also need to change Swiper's CSS to reflect
changed classes
____

____
Not supported in Swiper React/Vue components
____

|link:#param-slideBlankClass[slideBlankClass] |string
|'swiper-slide-blank' a|
CSS class name of the blank slide added by the loop mode (when
`loopAddBlankSlides` is enabled)

____
Not supported in Swiper React/Vue
____

|link:#param-slideClass[slideClass] |string |'swiper-slide' a|
CSS class name of slide

____
By changing classes you will also need to change Swiper's CSS to reflect
changed classes
____

____
Not supported in Swiper React/Vue components
____

|link:#param-slideFullyVisibleClass[slideFullyVisibleClass] |string
|'swiper-slide-fully-visible' a|
CSS class name of fully (when whole slide is in the viewport) visible
slide

____
Not supported in Swiper React/Vue
____

|link:#param-slideNextClass[slideNextClass] |string |'swiper-slide-next'
a|
CSS class name of slide which is right after currently active slide

____
By changing classes you will also need to change Swiper's CSS to reflect
changed classes
____

____
Not supported in Swiper React/Vue
____

|link:#param-slidePrevClass[slidePrevClass] |string |'swiper-slide-prev'
a|
CSS class name of slide which is right before currently active slide

____
By changing classes you will also need to change Swiper's CSS to reflect
changed classes
____

____
Not supported in Swiper React/Vue
____

|link:#param-slideToClickedSlide[slideToClickedSlide] |boolean |false
|Set to `true` and click on any slide will produce transition to this
slide

|link:#param-slideVisibleClass[slideVisibleClass] |string
|'swiper-slide-visible' a|
CSS class name of currently/partially visible slide

____
By changing classes you will also need to change Swiper's CSS to reflect
changed classes
____

____
Not supported in Swiper React/Vue
____

|link:#param-slidesOffsetAfter[slidesOffsetAfter] |number |0 |Add (in
px) additional slide offset in the end of the container (after all
slides)

|link:#param-slidesOffsetBefore[slidesOffsetBefore] |number |0 |Add (in
px) additional slide offset in the beginning of the container (before
all slides)

|link:#param-slidesPerGroup[slidesPerGroup] |number |1 |Set numbers of
slides to define and enable group sliding. Useful to use with
slidesPerView > 1

|link:#param-slidesPerGroupAuto[slidesPerGroupAuto] |boolean |false
|This param intended to be used only with `slidesPerView: 'auto` and
`slidesPerGroup: 1`. When enabled, it will skip all slides in view on
`.slideNext()` & `.slidePrev()` methods calls, on Navigation
"buttons" clicks and in autoplay.

|link:#param-slidesPerGroupSkip[slidesPerGroupSkip] |number |0 a|
The parameter works in the following way: If `slidesPerGroupSkip`
equals `0` (default), no slides are excluded from grouping, and the
resulting behaviour is the same as without this change.

If `slidesPerGroupSkip` is equal or greater than `1` the first X
slides are treated as single groups, whereas all following slides are
grouped by the `slidesPerGroup` value.

|link:#param-slidesPerView[slidesPerView] |number \| 'auto' |1 a|
Number of slides per view (slides visible at the same time on slider's
container).

____
`slidesPerView: 'auto` is currently not compatible with multirow
mode, when `grid.rows` > 1
____

|link:#param-snapToSlideEdge[snapToSlideEdge] |boolean |false |When
enabled, the swiper will always snap to slide edges rather than
arbitrary positions. This prevents partial slides from appearing
misaligned at the end of the swiper. Only applies when `slidesPerView`
is fractional or `auto`, and is ignored in `loop` and
`centeredSlides` modes.

|link:#param-spaceBetween[spaceBetween] |string \| number |'0' a|
Distance between slides in px.

____
If you use "margin" css property to the elements which go into Swiper in
which you pass "spaceBetween" into, navigation might not work properly.
____

|link:#param-speed[speed] |number |300 |Duration of transition between
slides (in ms)

|link:#param-swipeHandler[swipeHandler] |HTMLElement \| CSSSelector \|
null |null |String with CSS selector or HTML element of the container
with pagination that will work as only available handler for swiping

|link:#param-swiperElementNodeName[swiperElementNodeName] |string
|'SWIPER-CONTAINER' |The name of the swiper element node name; used for
detecting web component rendering

|link:#param-threshold[threshold] |number |5 |Threshold value in px. If
"touch distance" will be lower than this value then swiper will not move

|link:#param-thumbs[thumbs] |ThumbsOptions | a|
Object with thumbs component parameters

[source, js]
----
const swiper = new Swiper('.swiper', {
  ...
  thumbs: {
    swiper: thumbsSwiper
  }
});
----

|link:#param-touchAngle[touchAngle] |number |45 |Allowable angle (in
degrees) to trigger touch move

|link:#param-touchEventsTarget[touchEventsTarget] |'container' \|
'wrapper' |wrapper |Target element to listen touch events on. Can be
`container` (to listen for touch events on swiper) or
`wrapper`(to listen for touch events on swiper-wrapper)

|link:#param-touchMoveStopPropagation[touchMoveStopPropagation] |boolean
|false |If enabled, then propagation of "touchmove" will be stopped

|link:#param-touchRatio[touchRatio] |number |1 |Touch ratio

|link:#param-touchReleaseOnEdges[touchReleaseOnEdges] |boolean |false
|Enable to release touch events on slider edge position (beginning, end)
to allow for further page scrolling. This feature works only with
"touch" events (and not pointer events), so it will work on iOS/Android
devices and won't work on Windows devices with pointer events. Also
`threshold` parameter must be set to `0`

|link:#param-touchStartForcePreventDefault[touchStartForcePreventDefault]
|boolean |false |Force to always prevent default for `touchstart`
(`pointerdown`) event

|link:#param-touchStartPreventDefault[touchStartPreventDefault] |boolean
|true |If disabled, `pointerdown` event won't be prevented

|link:#param-uniqueNavElements[uniqueNavElements] |boolean |true |If
enabled (by default) and navigation elements' parameters passed as a
string (like `".pagination"`) then Swiper will look for such elements
through child elements first. Applies for pagination, prev/next buttons
and scrollbar elements

|link:#param-updateOnWindowResize[updateOnWindowResize] |boolean |true
|Swiper will recalculate slides position on window resize
(orientationchange)

|link:#param-url[url] |string \| null |'null' |Required for active slide
detection when rendered on server-side and enabled history

|link:#param-userAgent[userAgent] |string \| null |'null' |userAgent
string. Required for browser/device detection when rendered on
server-side

|link:#param-virtual[virtual] |boolean \| VirtualOptions | a|
Enables virtual slides functionality. Object with virtual slides
parameters or boolean `true` to enable with default settings.

[source, js]
----
const swiper = new Swiper('.swiper', {
  virtual: {
    slides: ['Slide 1', 'Slide 2', 'Slide 3', 'Slide 4', 'Slide 5'],
  },
});
----

|link:#param-virtualTranslate[virtualTranslate] |boolean |false |Enabled
this option and swiper will be operated as usual except it will not
move, real translate values on wrapper will not be set. Useful when you
may need to create custom slide transition

|link:#param-watchOverflow[watchOverflow] |boolean |true |When enabled
Swiper will be disabled and hide navigation buttons on case there are
not enough slides for sliding.

|link:#param-watchSlidesProgress[watchSlidesProgress] |boolean |false
|Enable this feature to calculate each slides progress and visibility
(slides in viewport will have additional visible class)

|link:#param-width[width] |number \| null |null a|
Swiper width (in px). Parameter allows to force Swiper width. Useful
only if you initialize Swiper when it is hidden and in SSR and Test
environments for correct Swiper initialization

____
Setting this parameter will make Swiper not responsive
____

|link:#param-wrapperClass[wrapperClass] |string |'swiper-wrapper' a|
CSS class name of slides' wrapper

____
By changing classes you will also need to change Swiper's CSS to reflect
changed classes
____

____
Not supported in Swiper React/Vue
____

|link:#param-zoom[zoom] |boolean \| ZoomOptions | a|
Enables zooming functionality. Object with zoom parameters or boolean
`true` to enable with default settings

[source, js]
----
const swiper = new Swiper('.swiper', {
  zoom: {
    maxRatio: 5,
  },
});
----

|===

