== Audio and Video

=== Contents

* link:#audio-macro-syntax[Audio macro syntax]
* link:#video-macro-syntax[Video macro syntax]
* link:#vimeo-and-youtube-videos[Vimeo and YouTube videos]
* link:#audio-and-video-attributes-and-options[Audio and video
attributes and options]

=== link:#audio-macro-syntax[]Audio macro syntax

The block audio macro enables you to embed audio streams into your
documentation. You can embed self-hosted audio files that are supported
by the browser.

The audio formats AsciiDoc supports is dictated by the output format,
such as the formats supported by the browser when generating HTML. While
this was once a precarious ordeal, HTML 5 has brought sanity to audio
support in the browser by adding a dedicated
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio[`<audio>`]
element and by introducing several standard audio formats. Those formats
are now widely supported across browsers and systems.

For a canonical list of supported web audio formats and their
interaction with modern browsers, see the
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility[Mozilla
Developer Supported Media Formats] documentation.

Example 1. Basic audio file include

[source,highlightjs,highlight]
----
audio::ocean-waves.wav[]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

You can control the audio settings using additional attributes on the
macro. For instance, you can offset the start time of playback using the
`start` attribute and enable autoplay using the `autoplay` option.

Example 2. Set attributes for local audio playback

[source,highlightjs,highlight]
----
audio::ocean-waves.wav[start=60,opts=autoplay]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

You can include a caption above the audio using the title attribute.

Example 3. Add a caption to the audio

[source,highlightjs,highlight]
----
.Take a zen moment
audio::ocean-waves.wav[]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

=== link:#video-macro-syntax[]Video macro syntax

The block video macro enables you to embed videos into your
documentation. You can embed self-hosted videos or videos shared on
popular video hosting sites such as Vimeo and YouTube.

The video formats AsciiDoc supports is dictated by the output format,
such as the formats supported by the browser when generating HTML. While
this was once a precarious ordeal, HTML 5 has brought sanity to video
support in the browser by adding a dedicated
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video[`<video>`]
element and by introducing several standard video formats. Those formats
are now widely supported across browsers and systems.

For a canonical list of supported web video formats and their
interaction with modern browsers, see the
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility[Mozilla
Developer Supported Media Formats] documentation.

A recommendation for serving video to browsers

Where appropriate, we recommend using a video hosting service like Vimeo
or YouTube to serve videos in online documentation. These services
specialize in streaming optimized video to the browser, with the lowest
latency possible given hardware, software, and network capabilities of
the device viewing the video.

Vimeo even offers a white label mode so users aren’t made aware that the
video is being served through its service.

See link:#vimeo-and-youtube-videos[Vimeo and YouTube videos] for details
about how to serve videos from these services.

Example 4. Basic video file include

[source,highlightjs,highlight]
----
video::video-file.mp4[]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

You can control the video settings using additional attributes on the
macro. For instance, you can offset the start time of playback using the
`start` attribute and enable autoplay using the `autoplay` option.

Example 5. Set attributes for local video playback

[source,highlightjs,highlight]
----
video::video-file.mp4[width=640,start=60,opts=autoplay]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

You can include a caption on the video using the title attribute.

Example 6. Add a caption to a video

[source,highlightjs,highlight]
----
.A walkthrough of the product
video::video-file.mp4[]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

==== link:#vimeo-and-youtube-videos[]Vimeo and YouTube videos

The video macro supports embedding videos from external video hosting
services like Vimeo and YouTube. The AsciiDoc processor, specifically
the converter, automatically generates the correct code to embed the
video in the HTML output.

To use this feature, put the video ID in the macro target and the name
of the hosting service in the first positional attribute.

Example 7. Embed a Vimeo video

[source,highlightjs,highlight]
----
video::67480300[vimeo]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

Example 8. Embed a YouTube video

[source,highlightjs,highlight]
----
video::RvRhUHTV_8k[youtube]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

When embedding a YouTube video, you can specify a playlist to associate
with the video using the `list` attribute. The playlist must be
specified by its ID.

Example 9. Embed a YouTube video with a playlist

[source,highlightjs,highlight]
----
video::RvRhUHTV_8k[youtube,list=PLDitloyBcHOm49bxNhvGgg0f9NRZ5lSaP]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

Instead of using the `list` attribute, you can specify the ID of the
playlist after the video ID in the target, separated by a slash.

Example 10. Embed a YouTube video with a playlist in the target

[source,highlightjs,highlight]
----
video::RvRhUHTV_8k/PLDitloyBcHOm49bxNhvGgg0f9NRZ5lSaP[youtube]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

Alternatively, you can create a dynamic, unnamed playlist by listing
several additional video IDs in the `playlist` attribute.

Example 11. Embed a YouTube video with a dynamic playlist

[source,highlightjs,highlight]
----
video::RvRhUHTV_8k[youtube,playlist="_SvwdK_HibQ,SGqg_ZzThDU"]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

Instead of using the `playlist` attribute, you can create a dynamic,
unnamed playlist by listing several video IDs in the target separated by
a comma.

Example 12. Embed a YouTube video with a dynamic playlist in the target

[source,highlightjs,highlight]
----
video::RvRhUHTV_8k,_SvwdK_HibQ,SGqg_ZzThDU[youtube]
----

[.source-lang]#asciidoc#

image:../../../../_/img/octicons-16.svg#view-clippy[copy
icon][.copy-toast]##Copied!##

=== link:#audio-and-video-attributes-and-options[]Audio and video attributes and options

.Audio attributes and values
[cols=",,,",options="header",]
|===
|Attribute |Value(s) |Example Syntax |Notes
|`title` |User defined text |`.Ocean waves` |

|`start` |User-defined playback start time in seconds. |`start=30` |

|`end` |User-defined playback end time in seconds. |`end=90` |

|`options` (`opts`) |`autoplay`, `loop`, `controls`, `nocontrols`
|`opts="autoplay,loop"` |The controls value is enabled by default
|===

.Video attributes and values
[cols=",,,",options="header",]
|===
|Attribute |Value(s) |Example Syntax |Notes
|`title` |User defined text |`.An ocean sunset` |

|`poster` |A URL to an image to show until the user plays or seeks.
|`poster=sunset.jpg` |Can be specified as the first positional (unnamed)
attribute. Also used to specify the service when referring to a video
hosted on Vimeo (`vimeo`) or YouTube (`youtube`).

|`width` |User-defined size in pixels. |`width=640` |Can be specified as
the second positional (unnamed) attribute.

|`height` |User-defined size in pixels. |`height=480` |Can be specified
as the third positional (unnamed) attribute.

|`start` |User-defined playback start time in seconds. |`start=30` |

|`end` |User-defined playback end time in seconds. |`end=90` |

|`theme` |The YouTube theme to use for the frame. |`theme=light` |Valid
values are `dark` (the default) and `light`.

|`lang` |The language used in the YouTube frame. |`lang=fr` |A BCP 47
language tag (typically a two-letter language code, like `en`).

|`list` |The ID of a playlist to associate with a YouTube video.
|`list=PLabc123` |Only applies to YouTube videos.

|`playlist` |Additional video IDs to create a dynamic YouTube playlist.
|`playlist="video-abc,video-xyz"` |IDs must be separated by commas.
Therefore, the value must be enclosed in double quotes. Only applies to
YouTube videos.

|`options` (`opts`) |`autoplay`, `loop`, `modest`, `nocontrols`,
`nofullscreen`, `muted` |`opts="autoplay,loop"` |The controls are
enabled by default. The `modest` option enables modest branding for a
YouTube video.
|===

[.prev]#link:../image-ref/[Images Reference]#
[.next]#link:../icons/[Icons]#
