== The plugin `asciidoctor`

The plugin link:{url-jekyll-plugin--asciidoctor}[Asciidoctor, {browser-window--new}]
is the core engine to convert Asciidoc-based text data into HTML code. The
engine is implicitely called by the integration library `jekyll-asciidoc`.
To interprete and compile Asciidoc Markups, the plugin calls the *Converter*
API of `jekyll-asciidoc`.

NOTE: The core engine of Asciidoctor is completely *silent* from the
prospective of _Jekyll_. All the integration work is handled by the plugin
`jekyll-asciidoc`. Read the next section how Asciidoc integration is managed
for _Jekyll_.


== The plugin `jekyll-asciidoc`

The plugin link:{url-jekyll-plugin--jekyll-asciidoc}[Jekyll-Asciidoc, {browser-window--new}]
is the integration library for _Jekyll_. All the managing of Asciidoc code is
done by this integration library The plugin consists of three *extensions*
to be used by _Jekyll_ to manage **Asciidoc**-based content sources:

include::../tables/jekyll-asciidoc-api.asciidoc[]

NOTE: The extensions are automatically registered if the Gem
*jekyll-asciidoc* is loaded.
