== Building and previewing your site

Because _Asciidoctor_ is fully integrated into J1 Theme, the _Jekyll_
commands for building and previewing a website remain *unchanged*. Find a
brief list for typical Jekyll_ commands below.

You can build your site into the `_site` directory using:

[source, sh]
----
jekyll build
----

If you're using Bundler, prefix each command with `bundle exec`:

[source, sh]
----
bundle exec jekyll build
----

You can preview your site at \http://localhost:4000 using:

[source, sh]
----
jekyll serve
----

Since Jekyll 2.4.0, the `serve` command monitors the file system and rebuilds
the site whenever a change is detected by default (i.e., watch mode).
You can enable watch mode explicitly using the `--watch` flag:

[source, sh]
----
jekyll serve --watch
----

To disable watch mode explicitly, use the `--no-watch` flag instead.
You can also use the `--watch` flag with the `build` command:

[source, sh]
----
jekyll build --watch
----

If you only want Jekyll to build files which have changed, and not the whole
site, add the `--incremental` flag:

[source, sh]
----
jekyll serve --incremental
----

or

[source, sh]
----
jekyll build --watch --incremental
----

To see a report of all the files that are processed, add the `--verbose` flag:

[source, sh]
----
jekyll build --verbose
----

IMPORTANT: If you add the `--safe` flag, third-party plugins such as this
one are disabled by default* To reenable the plugin, you must add the name
of the gem to the whitelist* See <<Running in Safe Mode>> for details.
