---
title:                                  Audio
title_extention:                        Playing HTML5 Audio using J1 Template
tagline:                                Playing Video

date:                                   2020-11-04
#last_modified:                         2023-01-01

description: >
                                        The J1 Template support playing video on web pages
                                        by HTML5 Video, the new standard of HTML to show
                                        videos on web pages.
keywords: >
                                        open source, free, template, jekyll, jekyllone, web,
                                        sites, static, jamstack, bootstrap,
                                        html, html5, video, support, flash player,
                                        quicktime, silverlight

categories:                             [ Roundtrip ]
tags:                                   [ Module, Video ]

image:
  path:                                 /assets/image/icon/videojs/videojs-poster.png
  width:                                1920
  height:                               1280

regenerate:                             false
personalization:                        true
permalink:                              /pages/public/audio_tester/

resources:                              [
                                          animate,
                                          lightGallery, justifiedGallery,
                                          video_js
                                        ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/icon/videojs/videojs-poster.png
          alt:                          VideoJS Poster
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
The J1 Template support playing audio on web pages by HTML5 Video, the new
standard of HTML to show videos on webpages. Modern browsers support the
audio tag `<audio>` for the new HTML5 audio audio standard.

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== HTML5 Audio

HTML5 Video opens the doors to your way of presenting video content. All
modern browsers support the video tag `<video>` for the HTML5. Browsers have
a built-in multimedia framework already for decoding and displaying video
content. No need to use such proprietary software components anymore!

audio:://cdn.julephosting.de/podcasts/554-pinkelpause/97348-new-episode.mp3[start="00:05:49" role="mt-4 mb-5"]

/////
++++
<div class="gallery-title">Playing Audio</div>
<audio
  id="554-pinkelpause"
  controls
  style="display: none;">
   <source src="//cdn.julephosting.de/podcasts/554-pinkelpause/97348-new-episode.mp3" type="audio/mpeg" />
</audio>

<script>
  $(function() {
    var dependencies_met_page_ready = setInterval (function (options) {
      var pageState   = $('#no_flicker').css("display");
      var pageVisible = (pageState == 'block') ? true : false;

      if (j1.getState() === 'finished' && pageVisible) {
        var ts = "00:05:49";
        var startFromSecond = new Date('1970-01-01T' + ts + 'Z').getTime() / 1000;
        const audio = document.getElementById("554-pinkelpause");
        //add the time in seconds
        audio.currentTime = startFromSecond;
        audio.style.display = 'block';
        clearInterval(dependencies_met_page_ready);
      }
    }, 10);
  });
</script>
++++
/////
