---
title:                                  Tester
tagline:                                master slider pro
date:                                   2020-11-03 00:00:00
description: >
                                        Welcome to the preview page focussing on the image module. This page
                                        shows some valuable features of the J1 Theme to manage your image-based
                                        content using lightboxes, carousels (slider), and galleries.

categories:                             [ Testpages ]
tags:                                   [ Example ]

comments:                               false
fab_menu_id:                            open_toc

permalink:                              /pages/public/learn/masterslider-pro/
regenerate:                             false

resources:                              [ animate, mastersliderpro ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/image/pages/roundtrip/images-1920x1280-bw.jpg
          alt:                          Photo by Ricardo Gomez Angel on Unsplash
          badge:
            type:                       unsplash
            author:                     Ricardo Gomez Angel
            href:                       //unsplash.com/@ripato/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Slider 1 - Simple Boxed

lorem:sentences[5]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00001[role="mt-3 mb-5"]


== Slider 2 - Full Width

lorem:sentences[5]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00002[role="mt-3 mb-5"]


== Slider 3 - SlideInfo (Boxed|Animated)

lorem:sentences[5]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00003[role="mt-3 mb-5"]

== Slider 4 - ThumbView (position right|vertical)

lorem:sentences[5]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00004[role="mt-3 mb-5"]


== Slider 5 - ThumbView  (position bottom|horizontal)

lorem:sentences[5]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00005[role="mt-3 mb-5"]


== Slider 6 - Blog articles (PartialView)

lorem:sentences[5]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00006[role="mt-3 mb-5"]


== Slider 7 - PartialView/MS-Info (info position below)

lorem:sentences[5]

// add placeholder for dynamic load (AJAX)
//
masterslider::ms_00007[role="mt-3 mb-5"]

////
++++
<script>
  $(document).ready(function() {
    var dependencies_met_data_loaded = setInterval(function() {
      if (j1.getState() == 'finished') {
        // var settings = $.extend({}, {"layout": "page", "fab_menu_id": "page_ctrl", "scrollbar": "false", "toc": "true", "comments": "false", "scrollDynamicPagesTopOnChange": ""});
        // j1.adapter.masterslider.init(settings);
        j1.adapter.masterslider.init();
        clearInterval(dependencies_met_data_loaded);
      } // END dependencies_met_j1_finished
    }, 25);
  });

  masterslider_1.setup();
</script>
++++
////
